"""
AWS PERSONALIZE CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:25Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class BatchInferenceJobMode:
    BATCH_INFERENCE = "BATCH_INFERENCE"
    THEME_GENERATION = "THEME_GENERATION"


class Domain:
    ECOMMERCE = "ECOMMERCE"
    VIDEO_ON_DEMAND = "VIDEO_ON_DEMAND"


class ImportMode:
    FULL = "FULL"
    INCREMENTAL = "INCREMENTAL"


class IngestionMode:
    BULK = "BULK"
    PUT = "PUT"
    ALL = "ALL"


class ObjectiveSensitivity:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    OFF = "OFF"


class RankingInfluenceType:
    POPULARITY = "POPULARITY"
    FRESHNESS = "FRESHNESS"


class RecipeProvider:
    SERVICE = "SERVICE"


class TrainingMode:
    FULL = "FULL"
    UPDATE = "UPDATE"
    AUTOTRAIN = "AUTOTRAIN"


class TrainingType:
    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"


# PropertyType submodules
from . import Dataset as _Dataset
from . import Solution as _Solution


# Resources
# ============================================================


@dataclass
class Dataset(CloudFormationResource):
    """Dataset resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-personalize-dataset.html

    CloudFormation type: AWS::Personalize::Dataset
    """

    _resource_type: ClassVar[str] = "AWS::Personalize::Dataset"

    dataset_group_arn: str | None = None
    dataset_type: str | None = None
    name: str | None = None
    schema_arn: str | None = None
    dataset_import_job: _Dataset.DatasetImportJob | None = None

    # GetAtt attributes
    DATASETARN: ClassVar[str] = "DatasetArn"


@dataclass
class DatasetGroup(CloudFormationResource):
    """DatasetGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-personalize-datasetgroup.html

    CloudFormation type: AWS::Personalize::DatasetGroup
    """

    _resource_type: ClassVar[str] = "AWS::Personalize::DatasetGroup"

    name: str | None = None
    domain: str | None = None
    kms_key_arn: str | None = None
    role_arn: str | None = None

    # GetAtt attributes
    DATASETGROUPARN: ClassVar[str] = "DatasetGroupArn"


@dataclass
class Schema(CloudFormationResource):
    """Schema resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-personalize-schema.html

    CloudFormation type: AWS::Personalize::Schema
    """

    _resource_type: ClassVar[str] = "AWS::Personalize::Schema"

    name: str | None = None
    schema: str | None = None
    domain: str | None = None

    # GetAtt attributes
    SCHEMAARN: ClassVar[str] = "SchemaArn"


@dataclass
class Solution(CloudFormationResource):
    """Solution resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-personalize-solution.html

    CloudFormation type: AWS::Personalize::Solution
    """

    _resource_type: ClassVar[str] = "AWS::Personalize::Solution"
    _property_mappings: ClassVar[dict[str, str]] = {
        "perform_auto_ml": "PerformAutoML",
        "perform_hpo": "PerformHPO",
    }

    dataset_group_arn: str | None = None
    name: str | None = None
    event_type: str | None = None
    perform_auto_ml: bool | None = None
    perform_hpo: bool | None = None
    recipe_arn: str | None = None
    solution_config: _Solution.SolutionConfig | None = None

    # GetAtt attributes
    SOLUTIONARN: ClassVar[str] = "SolutionArn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Dataset.DataSource = PropertyTypeDescriptor(_Dataset.DataSource, "DataSource")
Dataset.DatasetImportJob = PropertyTypeDescriptor(
    _Dataset.DatasetImportJob, "DatasetImportJob"
)
Solution.AlgorithmHyperParameterRanges = PropertyTypeDescriptor(
    _Solution.AlgorithmHyperParameterRanges, "AlgorithmHyperParameterRanges"
)
Solution.AutoMLConfig = PropertyTypeDescriptor(_Solution.AutoMLConfig, "AutoMLConfig")
Solution.CategoricalHyperParameterRange = PropertyTypeDescriptor(
    _Solution.CategoricalHyperParameterRange, "CategoricalHyperParameterRange"
)
Solution.ContinuousHyperParameterRange = PropertyTypeDescriptor(
    _Solution.ContinuousHyperParameterRange, "ContinuousHyperParameterRange"
)
Solution.HpoConfig = PropertyTypeDescriptor(_Solution.HpoConfig, "HpoConfig")
Solution.HpoObjective = PropertyTypeDescriptor(_Solution.HpoObjective, "HpoObjective")
Solution.HpoResourceConfig = PropertyTypeDescriptor(
    _Solution.HpoResourceConfig, "HpoResourceConfig"
)
Solution.IntegerHyperParameterRange = PropertyTypeDescriptor(
    _Solution.IntegerHyperParameterRange, "IntegerHyperParameterRange"
)
Solution.SolutionConfig = PropertyTypeDescriptor(
    _Solution.SolutionConfig, "SolutionConfig"
)
