"""
AWS IOTANALYTICS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:21Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# Constants
# ============================================================


class ChannelStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"


class ComputeType:
    ACU_1 = "ACU_1"
    ACU_2 = "ACU_2"


class DatasetActionType:
    QUERY = "QUERY"
    CONTAINER = "CONTAINER"


class DatasetContentState:
    CREATING = "CREATING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class DatasetStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"


class DatastoreStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"


class FileFormatType:
    JSON = "JSON"
    PARQUET = "PARQUET"


class LoggingLevel:
    ERROR = "ERROR"


class ReprocessingStatus:
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


# PropertyType submodules
from . import Channel as _Channel
from . import Dataset as _Dataset
from . import Datastore as _Datastore
from . import Pipeline as _Pipeline


# Resources
# ============================================================


@dataclass
class Channel(CloudFormationResource):
    """Channel resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotanalytics-channel.html

    CloudFormation type: AWS::IoTAnalytics::Channel
    """

    _resource_type: ClassVar[str] = "AWS::IoTAnalytics::Channel"

    channel_name: str | None = None
    channel_storage: _Channel.ChannelStorage | None = None
    retention_period: _Channel.RetentionPeriod | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class Dataset(CloudFormationResource):
    """Dataset resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotanalytics-dataset.html

    CloudFormation type: AWS::IoTAnalytics::Dataset
    """

    _resource_type: ClassVar[str] = "AWS::IoTAnalytics::Dataset"

    actions: list[_Dataset.Action] = field(default_factory=list)
    content_delivery_rules: list[_Dataset.DatasetContentDeliveryRule] = field(
        default_factory=list
    )
    dataset_name: str | None = None
    late_data_rules: list[_Dataset.LateDataRule] = field(default_factory=list)
    retention_period: _Dataset.RetentionPeriod | None = None
    tags: list[Tag] = field(default_factory=list)
    triggers: list[_Dataset.Trigger] = field(default_factory=list)
    versioning_configuration: _Dataset.VersioningConfiguration | None = None

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class Datastore(CloudFormationResource):
    """Datastore resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotanalytics-datastore.html

    CloudFormation type: AWS::IoTAnalytics::Datastore
    """

    _resource_type: ClassVar[str] = "AWS::IoTAnalytics::Datastore"

    datastore_name: str | None = None
    datastore_partitions: _Datastore.DatastorePartitions | None = None
    datastore_storage: _Datastore.DatastoreStorage | None = None
    file_format_configuration: _Datastore.FileFormatConfiguration | None = None
    retention_period: _Datastore.RetentionPeriod | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class Pipeline(CloudFormationResource):
    """Pipeline resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotanalytics-pipeline.html

    CloudFormation type: AWS::IoTAnalytics::Pipeline
    """

    _resource_type: ClassVar[str] = "AWS::IoTAnalytics::Pipeline"

    pipeline_activities: list[_Pipeline.Activity] = field(default_factory=list)
    pipeline_name: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Channel.ChannelStorage = _Channel.ChannelStorage
Channel.CustomerManagedS3 = _Channel.CustomerManagedS3
Channel.RetentionPeriod = _Channel.RetentionPeriod
Dataset.Action = _Dataset.Action
Dataset.ContainerAction = _Dataset.ContainerAction
Dataset.DatasetContentDeliveryRule = _Dataset.DatasetContentDeliveryRule
Dataset.DatasetContentDeliveryRuleDestination = (
    _Dataset.DatasetContentDeliveryRuleDestination
)
Dataset.DatasetContentVersionValue = _Dataset.DatasetContentVersionValue
Dataset.DeltaTime = _Dataset.DeltaTime
Dataset.DeltaTimeSessionWindowConfiguration = (
    _Dataset.DeltaTimeSessionWindowConfiguration
)
Dataset.Filter = _Dataset.Filter
Dataset.GlueConfiguration = _Dataset.GlueConfiguration
Dataset.IotEventsDestinationConfiguration = _Dataset.IotEventsDestinationConfiguration
Dataset.LateDataRule = _Dataset.LateDataRule
Dataset.LateDataRuleConfiguration = _Dataset.LateDataRuleConfiguration
Dataset.OutputFileUriValue = _Dataset.OutputFileUriValue
Dataset.QueryAction = _Dataset.QueryAction
Dataset.ResourceConfiguration = _Dataset.ResourceConfiguration
Dataset.RetentionPeriod = _Dataset.RetentionPeriod
Dataset.S3DestinationConfiguration = _Dataset.S3DestinationConfiguration
Dataset.Schedule = _Dataset.Schedule
Dataset.Trigger = _Dataset.Trigger
Dataset.TriggeringDataset = _Dataset.TriggeringDataset
Dataset.Variable = _Dataset.Variable
Dataset.VersioningConfiguration = _Dataset.VersioningConfiguration
Datastore.Column = _Datastore.Column
Datastore.CustomerManagedS3 = _Datastore.CustomerManagedS3
Datastore.CustomerManagedS3Storage = _Datastore.CustomerManagedS3Storage
Datastore.DatastorePartition = _Datastore.DatastorePartition
Datastore.DatastorePartitions = _Datastore.DatastorePartitions
Datastore.DatastoreStorage = _Datastore.DatastoreStorage
Datastore.FileFormatConfiguration = _Datastore.FileFormatConfiguration
Datastore.IotSiteWiseMultiLayerStorage = _Datastore.IotSiteWiseMultiLayerStorage
Datastore.ParquetConfiguration = _Datastore.ParquetConfiguration
Datastore.Partition = _Datastore.Partition
Datastore.RetentionPeriod = _Datastore.RetentionPeriod
Datastore.SchemaDefinition = _Datastore.SchemaDefinition
Datastore.TimestampPartition = _Datastore.TimestampPartition
Pipeline.Activity = _Pipeline.Activity
Pipeline.AddAttributes = _Pipeline.AddAttributes
Pipeline.Channel = _Pipeline.Channel
Pipeline.Datastore = _Pipeline.Datastore
Pipeline.DeviceRegistryEnrich = _Pipeline.DeviceRegistryEnrich
Pipeline.DeviceShadowEnrich = _Pipeline.DeviceShadowEnrich
Pipeline.Filter = _Pipeline.Filter
Pipeline.Lambda = _Pipeline.Lambda
Pipeline.Math = _Pipeline.Math
Pipeline.RemoveAttributes = _Pipeline.RemoveAttributes
Pipeline.SelectAttributes = _Pipeline.SelectAttributes
