"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    Tag,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    Attr,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    RefIntrinsic,
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
    # Condition operator constants
    BOOL,
    STRING_EQUALS,
    STRING_NOT_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_LIKE,
    STRING_NOT_LIKE,
    NUMERIC_EQUALS,
    NUMERIC_NOT_EQUALS,
    NUMERIC_LESS_THAN,
    NUMERIC_LESS_THAN_EQUALS,
    NUMERIC_GREATER_THAN,
    NUMERIC_GREATER_THAN_EQUALS,
    DATE_EQUALS,
    DATE_NOT_EQUALS,
    DATE_LESS_THAN,
    DATE_LESS_THAN_EQUALS,
    DATE_GREATER_THAN,
    DATE_GREATER_THAN_EQUALS,
    IP_ADDRESS,
    NOT_IP_ADDRESS,
    ARN_EQUALS,
    ARN_NOT_EQUALS,
    ARN_LIKE,
    ARN_NOT_LIKE,
    NULL,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    serverless,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .compute import DirectorySettingsLambdaFunction as DirectorySettingsLambdaFunction
from .compute import DirectorySettingsLambdaFunctionCapacityProviderVpcConfig as DirectorySettingsLambdaFunctionCapacityProviderVpcConfig
from .compute import DirectorySettingsLambdaFunctionContent as DirectorySettingsLambdaFunctionContent
from .compute import DirectorySettingsLambdaFunctionEnvironment as DirectorySettingsLambdaFunctionEnvironment
from .main import DirectorySettingsResource as DirectorySettingsResource
from .messaging import DirectoryMonitoringTopic as DirectoryMonitoringTopic
from .messaging import DirectoryMonitoringTopicSubscription as DirectoryMonitoringTopicSubscription
from .monitoring import DirectorySettingsLambdaLogsLogGroup as DirectorySettingsLambdaLogsLogGroup
from .outputs import DirectoryAliasUrlOutput as DirectoryAliasUrlOutput
from .params import CreateDirectoryAlias as CreateDirectoryAlias
from .params import CreateDirectoryConsoleDelegatedAccessRoles as CreateDirectoryConsoleDelegatedAccessRoles
from .params import DirectoryAlias as DirectoryAlias
from .params import DirectoryConsoleDelegatedAccessRolesConditionCondition as DirectoryConsoleDelegatedAccessRolesConditionCondition
from .params import DirectoryID as DirectoryID
from .params import DirectoryMonitoringEmail as DirectoryMonitoringEmail
from .params import DirectoryMonitoringSNSTopicKMSKey as DirectoryMonitoringSNSTopicKMSKey
from .params import DirectoryMonitoringSNSTopicKMSKeyConditionCondition as DirectoryMonitoringSNSTopicKMSKeyConditionCondition
from .params import EnableDirectorySSO as EnableDirectorySSO
from .params import LambdaFunctionName as LambdaFunctionName
from .params import LambdaLogLevel as LambdaLogLevel
from .params import LambdaLogsCloudWatchKMSKey as LambdaLogsCloudWatchKMSKey
from .params import LambdaLogsCloudWatchKMSKeyConditionCondition as LambdaLogsCloudWatchKMSKeyConditionCondition
from .params import LambdaLogsLogGroupRetention as LambdaLogsLogGroupRetention
from .params import LambdaS3BucketName as LambdaS3BucketName
from .params import LambdaZipFileName as LambdaZipFileName
from .params import SecurityGroups as SecurityGroups
from .params import Subnets as Subnets
from .security import DirectoryConsoleDelegatedAccessEC2ReadOnlyRole as DirectoryConsoleDelegatedAccessEC2ReadOnlyRole
from .security import DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAllowStatement0 as DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAllowStatement0
from .security import DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAssumeRolePolicyDocument as DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAssumeRolePolicyDocument
from .security import DirectoryConsoleDelegatedAccessSecurityAuditRole as DirectoryConsoleDelegatedAccessSecurityAuditRole
from .security import DirectoryConsoleDelegatedAccessSecurityAuditRoleAllowStatement0 as DirectoryConsoleDelegatedAccessSecurityAuditRoleAllowStatement0
from .security import DirectoryConsoleDelegatedAccessSecurityAuditRoleAssumeRolePolicyDocument as DirectoryConsoleDelegatedAccessSecurityAuditRoleAssumeRolePolicyDocument
from .security import DirectorySettingsLambdaRole as DirectorySettingsLambdaRole
from .security import DirectorySettingsLambdaRoleAllowStatement0 as DirectorySettingsLambdaRoleAllowStatement0
from .security import DirectorySettingsLambdaRoleAllowStatement0_1 as DirectorySettingsLambdaRoleAllowStatement0_1
from .security import DirectorySettingsLambdaRoleAllowStatement0_2 as DirectorySettingsLambdaRoleAllowStatement0_2
from .security import DirectorySettingsLambdaRoleAllowStatement1 as DirectorySettingsLambdaRoleAllowStatement1
from .security import DirectorySettingsLambdaRoleAllowStatement1_1 as DirectorySettingsLambdaRoleAllowStatement1_1
from .security import DirectorySettingsLambdaRoleAllowStatement2 as DirectorySettingsLambdaRoleAllowStatement2
from .security import DirectorySettingsLambdaRoleAssumeRolePolicyDocument as DirectorySettingsLambdaRoleAssumeRolePolicyDocument
from .security import DirectorySettingsLambdaRolePolicies0PolicyDocument as DirectorySettingsLambdaRolePolicies0PolicyDocument
from .security import DirectorySettingsLambdaRolePolicies1PolicyDocument as DirectorySettingsLambdaRolePolicies1PolicyDocument
from .security import DirectorySettingsLambdaRolePolicy as DirectorySettingsLambdaRolePolicy
from .security import DirectorySettingsLambdaRolePolicy1 as DirectorySettingsLambdaRolePolicy1

__all__: list[str] = ['AMI_ID', 'ARN', 'ARN_EQUALS', 'ARN_LIKE', 'ARN_NOT_EQUALS', 'ARN_NOT_LIKE', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'Attr', 'BOOL', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'CreateDirectoryAlias', 'CreateDirectoryConsoleDelegatedAccessRoles', 'DATE_EQUALS', 'DATE_GREATER_THAN', 'DATE_GREATER_THAN_EQUALS', 'DATE_LESS_THAN', 'DATE_LESS_THAN_EQUALS', 'DATE_NOT_EQUALS', 'DenyStatement', 'DirectoryAlias', 'DirectoryAliasUrlOutput', 'DirectoryConsoleDelegatedAccessEC2ReadOnlyRole', 'DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAllowStatement0', 'DirectoryConsoleDelegatedAccessEC2ReadOnlyRoleAssumeRolePolicyDocument', 'DirectoryConsoleDelegatedAccessRolesConditionCondition', 'DirectoryConsoleDelegatedAccessSecurityAuditRole', 'DirectoryConsoleDelegatedAccessSecurityAuditRoleAllowStatement0', 'DirectoryConsoleDelegatedAccessSecurityAuditRoleAssumeRolePolicyDocument', 'DirectoryID', 'DirectoryMonitoringEmail', 'DirectoryMonitoringSNSTopicKMSKey', 'DirectoryMonitoringSNSTopicKMSKeyConditionCondition', 'DirectoryMonitoringTopic', 'DirectoryMonitoringTopicSubscription', 'DirectorySettingsLambdaFunction', 'DirectorySettingsLambdaFunctionCapacityProviderVpcConfig', 'DirectorySettingsLambdaFunctionContent', 'DirectorySettingsLambdaFunctionEnvironment', 'DirectorySettingsLambdaLogsLogGroup', 'DirectorySettingsLambdaRole', 'DirectorySettingsLambdaRoleAllowStatement0', 'DirectorySettingsLambdaRoleAllowStatement0_1', 'DirectorySettingsLambdaRoleAllowStatement0_2', 'DirectorySettingsLambdaRoleAllowStatement1', 'DirectorySettingsLambdaRoleAllowStatement1_1', 'DirectorySettingsLambdaRoleAllowStatement2', 'DirectorySettingsLambdaRoleAssumeRolePolicyDocument', 'DirectorySettingsLambdaRolePolicies0PolicyDocument', 'DirectorySettingsLambdaRolePolicies1PolicyDocument', 'DirectorySettingsLambdaRolePolicy', 'DirectorySettingsLambdaRolePolicy1', 'DirectorySettingsResource', 'EnableDirectorySSO', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'IP_ADDRESS', 'If', 'ImportValue', 'Join', 'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'LambdaFunctionName', 'LambdaLogLevel', 'LambdaLogsCloudWatchKMSKey', 'LambdaLogsCloudWatchKMSKeyConditionCondition', 'LambdaLogsLogGroupRetention', 'LambdaS3BucketName', 'LambdaZipFileName', 'Mapping', 'NOT_IP_ADDRESS', 'NULL', 'NUMBER', 'NUMERIC_EQUALS', 'NUMERIC_GREATER_THAN', 'NUMERIC_GREATER_THAN_EQUALS', 'NUMERIC_LESS_THAN', 'NUMERIC_LESS_THAN_EQUALS', 'NUMERIC_NOT_EQUALS', 'Not', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType', 'Ref', 'RefDict', 'RefIntrinsic', 'RefList', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'STRING_EQUALS', 'STRING_EQUALS_IGNORE_CASE', 'STRING_LIKE', 'STRING_NOT_EQUALS', 'STRING_NOT_EQUALS_IGNORE_CASE', 'STRING_NOT_LIKE', 'SUBNET_ID', 'SecurityGroups', 'Select', 'Split', 'Sub', 'Subnets', 'Tag', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'serverless', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
