"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    Tag,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    Attr,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    RefIntrinsic,
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
    # Condition operator constants
    BOOL,
    STRING_EQUALS,
    STRING_NOT_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_LIKE,
    STRING_NOT_LIKE,
    NUMERIC_EQUALS,
    NUMERIC_NOT_EQUALS,
    NUMERIC_LESS_THAN,
    NUMERIC_LESS_THAN_EQUALS,
    NUMERIC_GREATER_THAN,
    NUMERIC_GREATER_THAN_EQUALS,
    DATE_EQUALS,
    DATE_NOT_EQUALS,
    DATE_LESS_THAN,
    DATE_LESS_THAN_EQUALS,
    DATE_GREATER_THAN,
    DATE_GREATER_THAN_EQUALS,
    IP_ADDRESS,
    NOT_IP_ADDRESS,
    ARN_EQUALS,
    ARN_NOT_EQUALS,
    ARN_LIKE,
    ARN_NOT_LIKE,
    NULL,
    # Loader
    setup_resources,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .database import AuroraCluster as AuroraCluster
from .database import AuroraDB as AuroraDB
from .database import AuroraDBSubnetGroup as AuroraDBSubnetGroup
from .database import AuroraDBTagFormat as AuroraDBTagFormat
from .main import AuroraSourceEndpoint as AuroraSourceEndpoint
from .main import DMSReplicationInstance as DMSReplicationInstance
from .main import DMSReplicationSubnetGroup as DMSReplicationSubnetGroup
from .main import DMSReplicationTask as DMSReplicationTask
from .main import S3TargetEndpoint as S3TargetEndpoint
from .main import S3TargetEndpointRedshiftSettings as S3TargetEndpointRedshiftSettings
from .network import AttachGateway as AttachGateway
from .network import AuroraSecurityGroup as AuroraSecurityGroup
from .network import AuroraSecurityGroupEgress as AuroraSecurityGroupEgress
from .network import AuroraSecurityGroupEgress1 as AuroraSecurityGroupEgress1
from .network import DBSubnet1 as DBSubnet1
from .network import DBSubnet1AssociationParameter as DBSubnet1AssociationParameter
from .network import DBSubnet2 as DBSubnet2
from .network import DBSubnet2AssociationParameter as DBSubnet2AssociationParameter
from .network import DMSSecurityGroup as DMSSecurityGroup
from .network import InternetGateway as InternetGateway
from .network import InternetGatewayAssociationParameter as InternetGatewayAssociationParameter
from .network import Route as Route
from .network import RouteTable as RouteTable
from .network import RouteTableAssociationParameter as RouteTableAssociationParameter
from .network import SubnetRouteTableAssociation as SubnetRouteTableAssociation
from .network import SubnetRouteTableAssociation1 as SubnetRouteTableAssociation1
from .network import VPC as VPC
from .network import VPCAssociationParameter as VPCAssociationParameter
from .network import VPCAssociationParameter1 as VPCAssociationParameter1
from .outputs import AuroraEndpointOutput as AuroraEndpointOutput
from .outputs import RegionNameOutput as RegionNameOutput
from .outputs import S3BucketNameOutput as S3BucketNameOutput
from .outputs import StackNameOutput as StackNameOutput
from .params import ClientIP as ClientIP
from .params import ExistsDMSCloudwatchRole as ExistsDMSCloudwatchRole
from .params import ExistsDMSVPCRole as ExistsDMSVPCRole
from .params import NotExistsDMSCloudwatchRoleCondition as NotExistsDMSCloudwatchRoleCondition
from .params import NotExistsDMSVPCRoleCondition as NotExistsDMSVPCRoleCondition
from .params import SnapshotIdentifier as SnapshotIdentifier
from .security import DMSCloudwatchRole as DMSCloudwatchRole
from .security import DMSCloudwatchRoleAllowStatement0 as DMSCloudwatchRoleAllowStatement0
from .security import DMSCloudwatchRoleAssumeRolePolicyDocument as DMSCloudwatchRoleAssumeRolePolicyDocument
from .security import DMSVpcRole as DMSVpcRole
from .security import DMSVpcRoleAllowStatement0 as DMSVpcRoleAllowStatement0
from .security import DMSVpcRoleAssumeRolePolicyDocument as DMSVpcRoleAssumeRolePolicyDocument
from .security import S3TargetDMSRole as S3TargetDMSRole
from .security import S3TargetDMSRoleAllowStatement0 as S3TargetDMSRoleAllowStatement0
from .security import S3TargetDMSRoleAllowStatement0_1 as S3TargetDMSRoleAllowStatement0_1
from .security import S3TargetDMSRoleAllowStatement1 as S3TargetDMSRoleAllowStatement1
from .security import S3TargetDMSRoleAssumeRolePolicyDocument as S3TargetDMSRoleAssumeRolePolicyDocument
from .security import S3TargetDMSRolePolicies0PolicyDocument as S3TargetDMSRolePolicies0PolicyDocument
from .security import S3TargetDMSRolePolicy as S3TargetDMSRolePolicy
from .storage import S3Bucket as S3Bucket
from .storage import S3BucketBucketEncryption as S3BucketBucketEncryption
from .storage import S3BucketPublicAccessBlockConfiguration as S3BucketPublicAccessBlockConfiguration
from .storage import S3BucketServerSideEncryptionByDefault as S3BucketServerSideEncryptionByDefault
from .storage import S3BucketServerSideEncryptionRule as S3BucketServerSideEncryptionRule

__all__: list[str] = ['AMI_ID', 'ARN', 'ARN_EQUALS', 'ARN_LIKE', 'ARN_NOT_EQUALS', 'ARN_NOT_LIKE', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'AttachGateway', 'Attr', 'AuroraCluster', 'AuroraDB', 'AuroraDBSubnetGroup', 'AuroraDBTagFormat', 'AuroraEndpointOutput', 'AuroraSecurityGroup', 'AuroraSecurityGroupEgress', 'AuroraSecurityGroupEgress1', 'AuroraSourceEndpoint', 'BOOL', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'ClientIP', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'DATE_EQUALS', 'DATE_GREATER_THAN', 'DATE_GREATER_THAN_EQUALS', 'DATE_LESS_THAN', 'DATE_LESS_THAN_EQUALS', 'DATE_NOT_EQUALS', 'DBSubnet1', 'DBSubnet1AssociationParameter', 'DBSubnet2', 'DBSubnet2AssociationParameter', 'DMSCloudwatchRole', 'DMSCloudwatchRoleAllowStatement0', 'DMSCloudwatchRoleAssumeRolePolicyDocument', 'DMSReplicationInstance', 'DMSReplicationSubnetGroup', 'DMSReplicationTask', 'DMSSecurityGroup', 'DMSVpcRole', 'DMSVpcRoleAllowStatement0', 'DMSVpcRoleAssumeRolePolicyDocument', 'DenyStatement', 'Equals', 'ExistsDMSCloudwatchRole', 'ExistsDMSVPCRole', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'IP_ADDRESS', 'If', 'ImportValue', 'InternetGateway', 'InternetGatewayAssociationParameter', 'Join', 'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NOT_IP_ADDRESS', 'NULL', 'NUMBER', 'NUMERIC_EQUALS', 'NUMERIC_GREATER_THAN', 'NUMERIC_GREATER_THAN_EQUALS', 'NUMERIC_LESS_THAN', 'NUMERIC_LESS_THAN_EQUALS', 'NUMERIC_NOT_EQUALS', 'Not', 'NotExistsDMSCloudwatchRoleCondition', 'NotExistsDMSVPCRoleCondition', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType', 'Ref', 'RefDict', 'RefIntrinsic', 'RefList', 'RegionNameOutput', 'Route', 'RouteTable', 'RouteTableAssociationParameter', 'S3Bucket', 'S3BucketBucketEncryption', 'S3BucketNameOutput', 'S3BucketPublicAccessBlockConfiguration', 'S3BucketServerSideEncryptionByDefault', 'S3BucketServerSideEncryptionRule', 'S3TargetDMSRole', 'S3TargetDMSRoleAllowStatement0', 'S3TargetDMSRoleAllowStatement0_1', 'S3TargetDMSRoleAllowStatement1', 'S3TargetDMSRoleAssumeRolePolicyDocument', 'S3TargetDMSRolePolicies0PolicyDocument', 'S3TargetDMSRolePolicy', 'S3TargetEndpoint', 'S3TargetEndpointRedshiftSettings', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'STRING_EQUALS', 'STRING_EQUALS_IGNORE_CASE', 'STRING_LIKE', 'STRING_NOT_EQUALS', 'STRING_NOT_EQUALS_IGNORE_CASE', 'STRING_NOT_LIKE', 'SUBNET_ID', 'Select', 'SnapshotIdentifier', 'Split', 'StackNameOutput', 'Sub', 'SubnetRouteTableAssociation', 'SubnetRouteTableAssociation1', 'Tag', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC', 'VPCAssociationParameter', 'VPCAssociationParameter1', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
