"""
AWS ARCZONALSHIFT CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:16Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# PropertyType submodules
from . import ZonalAutoshiftConfiguration as _ZonalAutoshiftConfiguration


# Resources
# ============================================================


@dataclass
class AutoshiftObserverNotificationStatus(CloudFormationResource):
    """AutoshiftObserverNotificationStatus resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-arczonalshift-autoshiftobservernotificationstatus.html

    CloudFormation type: AWS::ARCZonalShift::AutoshiftObserverNotificationStatus
    """

    _resource_type: ClassVar[str] = (
        "AWS::ARCZonalShift::AutoshiftObserverNotificationStatus"
    )

    status: str | None = None

    # GetAtt attributes
    ACCOUNTID: ClassVar[str] = "AccountId"
    REGION: ClassVar[str] = "Region"


@dataclass
class ZonalAutoshiftConfiguration(CloudFormationResource):
    """ZonalAutoshiftConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-arczonalshift-zonalautoshiftconfiguration.html

    CloudFormation type: AWS::ARCZonalShift::ZonalAutoshiftConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::ARCZonalShift::ZonalAutoshiftConfiguration"

    resource_identifier: str | None = None
    practice_run_configuration: (
        _ZonalAutoshiftConfiguration.PracticeRunConfiguration | None
    ) = None
    zonal_autoshift_status: str | None = None


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
ZonalAutoshiftConfiguration.ControlCondition = (
    _ZonalAutoshiftConfiguration.ControlCondition
)
ZonalAutoshiftConfiguration.PracticeRunConfiguration = (
    _ZonalAutoshiftConfiguration.PracticeRunConfiguration
)
