"""
AWS INSPECTORV2 CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:22Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# PropertyType submodules
from . import CisScanConfiguration as _CisScanConfiguration
from . import CodeSecurityIntegration as _CodeSecurityIntegration
from . import CodeSecurityScanConfiguration as _CodeSecurityScanConfiguration
from . import Filter as _Filter


# Resources
# ============================================================


@dataclass
class CisScanConfiguration(CloudFormationResource):
    """CisScanConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-cisscanconfiguration.html

    CloudFormation type: AWS::InspectorV2::CisScanConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::InspectorV2::CisScanConfiguration"

    scan_name: str | None = None
    schedule: _CisScanConfiguration.Schedule | None = None
    security_level: str | None = None
    targets: _CisScanConfiguration.CisTargets | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class CodeSecurityIntegration(CloudFormationResource):
    """CodeSecurityIntegration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-codesecurityintegration.html

    CloudFormation type: AWS::InspectorV2::CodeSecurityIntegration
    """

    _resource_type: ClassVar[str] = "AWS::InspectorV2::CodeSecurityIntegration"

    create_integration_details: _CodeSecurityIntegration.CreateDetails | None = None
    name: str | None = None
    tags: dict[str, String] = field(default_factory=dict)
    type_: str | None = None
    update_integration_details: _CodeSecurityIntegration.UpdateDetails | None = None

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    AUTHORIZATIONURL: ClassVar[str] = "AuthorizationUrl"
    LASTUPDATEDAT: ClassVar[str] = "LastUpdatedAt"
    STATUSREASON: ClassVar[str] = "StatusReason"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    ARN: ClassVar[str] = "Arn"


@dataclass
class CodeSecurityScanConfiguration(CloudFormationResource):
    """CodeSecurityScanConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-codesecurityscanconfiguration.html

    CloudFormation type: AWS::InspectorV2::CodeSecurityScanConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::InspectorV2::CodeSecurityScanConfiguration"

    configuration: (
        _CodeSecurityScanConfiguration.CodeSecurityScanConfiguration | None
    ) = None
    level: str | None = None
    name: str | None = None
    scope_settings: _CodeSecurityScanConfiguration.ScopeSettings | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class Filter(CloudFormationResource):
    """Filter resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-filter.html

    CloudFormation type: AWS::InspectorV2::Filter
    """

    _resource_type: ClassVar[str] = "AWS::InspectorV2::Filter"

    filter_action: str | None = None
    filter_criteria: _Filter.FilterCriteria | None = None
    name: str | None = None
    description: str | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
CisScanConfiguration.CisTargets = PropertyTypeDescriptor(
    _CisScanConfiguration.CisTargets, "CisTargets"
)
CisScanConfiguration.DailySchedule = PropertyTypeDescriptor(
    _CisScanConfiguration.DailySchedule, "DailySchedule"
)
CisScanConfiguration.MonthlySchedule = PropertyTypeDescriptor(
    _CisScanConfiguration.MonthlySchedule, "MonthlySchedule"
)
CisScanConfiguration.Schedule = PropertyTypeDescriptor(
    _CisScanConfiguration.Schedule, "Schedule"
)
CisScanConfiguration.Time = PropertyTypeDescriptor(_CisScanConfiguration.Time, "Time")
CisScanConfiguration.WeeklySchedule = PropertyTypeDescriptor(
    _CisScanConfiguration.WeeklySchedule, "WeeklySchedule"
)
CodeSecurityIntegration.CreateDetails = PropertyTypeDescriptor(
    _CodeSecurityIntegration.CreateDetails, "CreateDetails"
)
CodeSecurityIntegration.CreateGitLabSelfManagedIntegrationDetail = (
    PropertyTypeDescriptor(
        _CodeSecurityIntegration.CreateGitLabSelfManagedIntegrationDetail,
        "CreateGitLabSelfManagedIntegrationDetail",
    )
)
CodeSecurityIntegration.UpdateDetails = PropertyTypeDescriptor(
    _CodeSecurityIntegration.UpdateDetails, "UpdateDetails"
)
CodeSecurityIntegration.UpdateGitHubIntegrationDetail = PropertyTypeDescriptor(
    _CodeSecurityIntegration.UpdateGitHubIntegrationDetail,
    "UpdateGitHubIntegrationDetail",
)
CodeSecurityIntegration.UpdateGitLabSelfManagedIntegrationDetail = (
    PropertyTypeDescriptor(
        _CodeSecurityIntegration.UpdateGitLabSelfManagedIntegrationDetail,
        "UpdateGitLabSelfManagedIntegrationDetail",
    )
)
CodeSecurityScanConfiguration.CodeSecurityScanConfiguration = PropertyTypeDescriptor(
    _CodeSecurityScanConfiguration.CodeSecurityScanConfiguration,
    "CodeSecurityScanConfiguration",
)
CodeSecurityScanConfiguration.ContinuousIntegrationScanConfiguration = (
    PropertyTypeDescriptor(
        _CodeSecurityScanConfiguration.ContinuousIntegrationScanConfiguration,
        "ContinuousIntegrationScanConfiguration",
    )
)
CodeSecurityScanConfiguration.PeriodicScanConfiguration = PropertyTypeDescriptor(
    _CodeSecurityScanConfiguration.PeriodicScanConfiguration,
    "PeriodicScanConfiguration",
)
CodeSecurityScanConfiguration.ScopeSettings = PropertyTypeDescriptor(
    _CodeSecurityScanConfiguration.ScopeSettings, "ScopeSettings"
)
Filter.DateFilter = PropertyTypeDescriptor(_Filter.DateFilter, "DateFilter")
Filter.FilterCriteria = PropertyTypeDescriptor(_Filter.FilterCriteria, "FilterCriteria")
Filter.MapFilter = PropertyTypeDescriptor(_Filter.MapFilter, "MapFilter")
Filter.NumberFilter = PropertyTypeDescriptor(_Filter.NumberFilter, "NumberFilter")
Filter.PackageFilter = PropertyTypeDescriptor(_Filter.PackageFilter, "PackageFilter")
Filter.PortRangeFilter = PropertyTypeDescriptor(
    _Filter.PortRangeFilter, "PortRangeFilter"
)
Filter.StringFilter = PropertyTypeDescriptor(_Filter.StringFilter, "StringFilter")
