"""
AWS S3VECTORS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:24Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class DataType:
    FLOAT32 = "float32"


class DistanceMetric:
    EUCLIDEAN = "euclidean"
    COSINE = "cosine"


class SseType:
    AES256 = "AES256"
    AWSKMS = "aws:kms"


# PropertyType submodules
from . import Index as _Index
from . import VectorBucket as _VectorBucket


# Resources
# ============================================================


@dataclass
class Index(CloudFormationResource):
    """Index resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-index.html

    CloudFormation type: AWS::S3Vectors::Index
    """

    _resource_type: ClassVar[str] = "AWS::S3Vectors::Index"

    data_type: DslValue[str] | None = None
    dimension: DslValue[int] | None = None
    distance_metric: DslValue[str] | None = None
    encryption_configuration: DslValue[_Index.EncryptionConfiguration] | None = None
    index_name: DslValue[str] | None = None
    metadata_configuration: DslValue[_Index.MetadataConfiguration] | None = None
    vector_bucket_arn: DslValue[str] | None = None
    vector_bucket_name: DslValue[str] | None = None

    # GetAtt attributes
    INDEXARN: ClassVar[str] = "IndexArn"
    CREATIONTIME: ClassVar[str] = "CreationTime"

    # PropertyType descriptors for nested GetAtt support
    EncryptionConfiguration = PropertyTypeDescriptor(
        _Index.EncryptionConfiguration, "EncryptionConfiguration"
    )
    MetadataConfiguration = PropertyTypeDescriptor(
        _Index.MetadataConfiguration, "MetadataConfiguration"
    )


@dataclass
class VectorBucket(CloudFormationResource):
    """VectorBucket resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-vectorbucket.html

    CloudFormation type: AWS::S3Vectors::VectorBucket
    """

    _resource_type: ClassVar[str] = "AWS::S3Vectors::VectorBucket"

    encryption_configuration: DslValue[_VectorBucket.EncryptionConfiguration] | None = (
        None
    )
    vector_bucket_name: DslValue[str] | None = None

    # GetAtt attributes
    VECTORBUCKETARN: ClassVar[str] = "VectorBucketArn"
    CREATIONTIME: ClassVar[str] = "CreationTime"

    # PropertyType descriptors for nested GetAtt support
    EncryptionConfiguration = PropertyTypeDescriptor(
        _VectorBucket.EncryptionConfiguration, "EncryptionConfiguration"
    )


@dataclass
class VectorBucketPolicy(CloudFormationResource):
    """VectorBucketPolicy resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-vectorbucketpolicy.html

    CloudFormation type: AWS::S3Vectors::VectorBucketPolicy
    """

    _resource_type: ClassVar[str] = "AWS::S3Vectors::VectorBucketPolicy"

    policy: DslValue[dict[str, Any]] | None = None
    vector_bucket_arn: DslValue[str] | None = None
    vector_bucket_name: DslValue[str] | None = None
