"""
AWS ACCESSANALYZER CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:18Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class AccessCheckPolicyType:
    IDENTITY_POLICY = "IDENTITY_POLICY"
    RESOURCE_POLICY = "RESOURCE_POLICY"


class AccessCheckResourceType:
    AWSDYNAMODBTABLE = "AWS::DynamoDB::Table"
    AWSDYNAMODBSTREAM = "AWS::DynamoDB::Stream"
    AWSEFSFILESYSTEM = "AWS::EFS::FileSystem"
    AWSOPENSEARCHSERVICEDOMAIN = "AWS::OpenSearchService::Domain"
    AWSKINESISSTREAM = "AWS::Kinesis::Stream"
    AWSKINESISSTREAMCONSUMER = "AWS::Kinesis::StreamConsumer"
    AWSKMSKEY = "AWS::KMS::Key"
    AWSLAMBDAFUNCTION = "AWS::Lambda::Function"
    AWSS3BUCKET = "AWS::S3::Bucket"
    AWSS3ACCESSPOINT = "AWS::S3::AccessPoint"
    AWSS3EXPRESSDIRECTORYBUCKET = "AWS::S3Express::DirectoryBucket"
    AWSS3GLACIER = "AWS::S3::Glacier"
    AWSS3OUTPOSTSBUCKET = "AWS::S3Outposts::Bucket"
    AWSS3OUTPOSTSACCESSPOINT = "AWS::S3Outposts::AccessPoint"
    AWSSECRETSMANAGERSECRET = "AWS::SecretsManager::Secret"
    AWSSNSTOPIC = "AWS::SNS::Topic"
    AWSSQSQUEUE = "AWS::SQS::Queue"
    AWSIAMASSUMEROLEPOLICYDOCUMENT = "AWS::IAM::AssumeRolePolicyDocument"
    AWSS3TABLESTABLEBUCKET = "AWS::S3Tables::TableBucket"
    AWSAPIGATEWAYRESTAPI = "AWS::ApiGateway::RestApi"
    AWSCODEARTIFACTDOMAIN = "AWS::CodeArtifact::Domain"
    AWSBACKUPBACKUPVAULT = "AWS::Backup::BackupVault"
    AWSCLOUDTRAILDASHBOARD = "AWS::CloudTrail::Dashboard"
    AWSCLOUDTRAILEVENTDATASTORE = "AWS::CloudTrail::EventDataStore"
    AWSS3TABLESTABLE = "AWS::S3Tables::Table"
    AWSS3EXPRESSACCESSPOINT = "AWS::S3Express::AccessPoint"


class AccessPreviewStatus:
    COMPLETED = "COMPLETED"
    CREATING = "CREATING"
    FAILED = "FAILED"


class AccessPreviewStatusReasonCode:
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"


class AclPermission:
    READ = "READ"
    WRITE = "WRITE"
    READ_ACP = "READ_ACP"
    WRITE_ACP = "WRITE_ACP"
    FULL_CONTROL = "FULL_CONTROL"


class AnalyzerStatus:
    ACTIVE = "ACTIVE"
    CREATING = "CREATING"
    DISABLED = "DISABLED"
    FAILED = "FAILED"


class CheckAccessNotGrantedResult:
    PASS = "PASS"
    FAIL = "FAIL"


class CheckNoNewAccessResult:
    PASS = "PASS"
    FAIL = "FAIL"


class CheckNoPublicAccessResult:
    PASS = "PASS"
    FAIL = "FAIL"


class FindingChangeType:
    CHANGED = "CHANGED"
    NEW = "NEW"
    UNCHANGED = "UNCHANGED"


class FindingSourceType:
    POLICY = "POLICY"
    BUCKET_ACL = "BUCKET_ACL"
    S3_ACCESS_POINT = "S3_ACCESS_POINT"
    S3_ACCESS_POINT_ACCOUNT = "S3_ACCESS_POINT_ACCOUNT"


class FindingStatus:
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    RESOLVED = "RESOLVED"


class FindingStatusUpdate:
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class FindingType:
    EXTERNALACCESS = "ExternalAccess"
    UNUSEDIAMROLE = "UnusedIAMRole"
    UNUSEDIAMUSERACCESSKEY = "UnusedIAMUserAccessKey"
    UNUSEDIAMUSERPASSWORD = "UnusedIAMUserPassword"
    UNUSEDPERMISSION = "UnusedPermission"
    INTERNALACCESS = "InternalAccess"


class InternalAccessType:
    INTRA_ACCOUNT = "INTRA_ACCOUNT"
    INTRA_ORG = "INTRA_ORG"


class JobErrorCode:
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR"
    SERVICE_QUOTA_EXCEEDED_ERROR = "SERVICE_QUOTA_EXCEEDED_ERROR"
    SERVICE_ERROR = "SERVICE_ERROR"


class JobStatus:
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class KmsGrantOperation:
    CREATEGRANT = "CreateGrant"
    DECRYPT = "Decrypt"
    DESCRIBEKEY = "DescribeKey"
    ENCRYPT = "Encrypt"
    GENERATEDATAKEY = "GenerateDataKey"
    GENERATEDATAKEYPAIR = "GenerateDataKeyPair"
    GENERATEDATAKEYPAIRWITHOUTPLAINTEXT = "GenerateDataKeyPairWithoutPlaintext"
    GENERATEDATAKEYWITHOUTPLAINTEXT = "GenerateDataKeyWithoutPlaintext"
    GETPUBLICKEY = "GetPublicKey"
    REENCRYPTFROM = "ReEncryptFrom"
    REENCRYPTTO = "ReEncryptTo"
    RETIREGRANT = "RetireGrant"
    SIGN = "Sign"
    VERIFY = "Verify"


class Locale:
    DE = "DE"
    EN = "EN"
    ES = "ES"
    FR = "FR"
    IT = "IT"
    JA = "JA"
    KO = "KO"
    PT_BR = "PT_BR"
    ZH_CN = "ZH_CN"
    ZH_TW = "ZH_TW"


class OrderBy:
    ASC = "ASC"
    DESC = "DESC"


class PolicyType:
    IDENTITY_POLICY = "IDENTITY_POLICY"
    RESOURCE_POLICY = "RESOURCE_POLICY"
    SERVICE_CONTROL_POLICY = "SERVICE_CONTROL_POLICY"
    RESOURCE_CONTROL_POLICY = "RESOURCE_CONTROL_POLICY"


class PrincipalType:
    IAM_ROLE = "IAM_ROLE"
    IAM_USER = "IAM_USER"


class ReasonCode:
    AWS_SERVICE_ACCESS_DISABLED = "AWS_SERVICE_ACCESS_DISABLED"
    DELEGATED_ADMINISTRATOR_DEREGISTERED = "DELEGATED_ADMINISTRATOR_DEREGISTERED"
    ORGANIZATION_DELETED = "ORGANIZATION_DELETED"
    SERVICE_LINKED_ROLE_CREATION_FAILED = "SERVICE_LINKED_ROLE_CREATION_FAILED"


class RecommendationType:
    UNUSEDPERMISSIONRECOMMENDATION = "UnusedPermissionRecommendation"


class RecommendedRemediationAction:
    CREATE_POLICY = "CREATE_POLICY"
    DETACH_POLICY = "DETACH_POLICY"


class ResourceControlPolicyRestriction:
    APPLICABLE = "APPLICABLE"
    FAILED_TO_EVALUATE_RCP = "FAILED_TO_EVALUATE_RCP"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    APPLIED = "APPLIED"


class ResourceType:
    AWSS3BUCKET = "AWS::S3::Bucket"
    AWSIAMROLE = "AWS::IAM::Role"
    AWSSQSQUEUE = "AWS::SQS::Queue"
    AWSLAMBDAFUNCTION = "AWS::Lambda::Function"
    AWSLAMBDALAYERVERSION = "AWS::Lambda::LayerVersion"
    AWSKMSKEY = "AWS::KMS::Key"
    AWSSECRETSMANAGERSECRET = "AWS::SecretsManager::Secret"
    AWSEFSFILESYSTEM = "AWS::EFS::FileSystem"
    AWSEC2SNAPSHOT = "AWS::EC2::Snapshot"
    AWSECRREPOSITORY = "AWS::ECR::Repository"
    AWSRDSDBSNAPSHOT = "AWS::RDS::DBSnapshot"
    AWSRDSDBCLUSTERSNAPSHOT = "AWS::RDS::DBClusterSnapshot"
    AWSSNSTOPIC = "AWS::SNS::Topic"
    AWSS3EXPRESSDIRECTORYBUCKET = "AWS::S3Express::DirectoryBucket"
    AWSDYNAMODBTABLE = "AWS::DynamoDB::Table"
    AWSDYNAMODBSTREAM = "AWS::DynamoDB::Stream"
    AWSIAMUSER = "AWS::IAM::User"


class ServiceControlPolicyRestriction:
    APPLICABLE = "APPLICABLE"
    FAILED_TO_EVALUATE_SCP = "FAILED_TO_EVALUATE_SCP"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    APPLIED = "APPLIED"


class Status:
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    IN_PROGRESS = "IN_PROGRESS"


class Type:
    ACCOUNT = "ACCOUNT"
    ORGANIZATION = "ORGANIZATION"
    ACCOUNT_UNUSED_ACCESS = "ACCOUNT_UNUSED_ACCESS"
    ORGANIZATION_UNUSED_ACCESS = "ORGANIZATION_UNUSED_ACCESS"
    ACCOUNT_INTERNAL_ACCESS = "ACCOUNT_INTERNAL_ACCESS"
    ORGANIZATION_INTERNAL_ACCESS = "ORGANIZATION_INTERNAL_ACCESS"


class ValidatePolicyFindingType:
    ERROR = "ERROR"
    SECURITY_WARNING = "SECURITY_WARNING"
    SUGGESTION = "SUGGESTION"
    WARNING = "WARNING"


class ValidatePolicyResourceType:
    AWSS3BUCKET = "AWS::S3::Bucket"
    AWSS3ACCESSPOINT = "AWS::S3::AccessPoint"
    AWSS3MULTIREGIONACCESSPOINT = "AWS::S3::MultiRegionAccessPoint"
    AWSS3OBJECTLAMBDAACCESSPOINT = "AWS::S3ObjectLambda::AccessPoint"
    AWSIAMASSUMEROLEPOLICYDOCUMENT = "AWS::IAM::AssumeRolePolicyDocument"
    AWSDYNAMODBTABLE = "AWS::DynamoDB::Table"


class ValidationExceptionReason:
    UNKNOWNOPERATION = "unknownOperation"
    CANNOTPARSE = "cannotParse"
    FIELDVALIDATIONFAILED = "fieldValidationFailed"
    OTHER = "other"
    NOTSUPPORTED = "notSupported"


# PropertyType submodules
from . import Analyzer as _Analyzer


# Resources
# ============================================================


@dataclass
class Analyzer(CloudFormationResource):
    """Analyzer resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-accessanalyzer-analyzer.html

    CloudFormation type: AWS::AccessAnalyzer::Analyzer
    """

    _resource_type: ClassVar[str] = "AWS::AccessAnalyzer::Analyzer"

    type_: str | None = None
    analyzer_configuration: _Analyzer.AnalyzerConfiguration | None = None
    analyzer_name: str | None = None
    archive_rules: list[_Analyzer.ArchiveRule] = field(default_factory=list)
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Analyzer.AnalysisRule = PropertyTypeDescriptor(_Analyzer.AnalysisRule, "AnalysisRule")
Analyzer.AnalysisRuleCriteria = PropertyTypeDescriptor(
    _Analyzer.AnalysisRuleCriteria, "AnalysisRuleCriteria"
)
Analyzer.AnalyzerConfiguration = PropertyTypeDescriptor(
    _Analyzer.AnalyzerConfiguration, "AnalyzerConfiguration"
)
Analyzer.ArchiveRule = PropertyTypeDescriptor(_Analyzer.ArchiveRule, "ArchiveRule")
Analyzer.Filter = PropertyTypeDescriptor(_Analyzer.Filter, "Filter")
Analyzer.InternalAccessAnalysisRule = PropertyTypeDescriptor(
    _Analyzer.InternalAccessAnalysisRule, "InternalAccessAnalysisRule"
)
Analyzer.InternalAccessAnalysisRuleCriteria = PropertyTypeDescriptor(
    _Analyzer.InternalAccessAnalysisRuleCriteria, "InternalAccessAnalysisRuleCriteria"
)
Analyzer.InternalAccessConfiguration = PropertyTypeDescriptor(
    _Analyzer.InternalAccessConfiguration, "InternalAccessConfiguration"
)
Analyzer.UnusedAccessConfiguration = PropertyTypeDescriptor(
    _Analyzer.UnusedAccessConfiguration, "UnusedAccessConfiguration"
)
