"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    serverless,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .database import ProcessedDataTable as ProcessedDataTable
from .database import ProcessedDataTableAttributeDefinition as ProcessedDataTableAttributeDefinition
from .database import ProcessedDataTableKeySchema as ProcessedDataTableKeySchema
from .database import ProcessedDataTableTimeToLiveSpecification as ProcessedDataTableTimeToLiveSpecification
from .main import CountFunction as CountFunction
from .main import CountFunctionEnvironment as CountFunctionEnvironment
from .main import CountTable as CountTable
from .main import Firehose as Firehose
from .main import FirehoseAmazonOpenSearchServerlessBufferingHints as FirehoseAmazonOpenSearchServerlessBufferingHints
from .main import FirehoseAmazonOpenSearchServerlessBufferingHints1 as FirehoseAmazonOpenSearchServerlessBufferingHints1
from .main import FirehoseExtendedS3DestinationConfiguration as FirehoseExtendedS3DestinationConfiguration
from .main import FirehoseProcessingConfiguration as FirehoseProcessingConfiguration
from .main import FirehoseProcessor as FirehoseProcessor
from .main import FirehoseProcessorParameter as FirehoseProcessorParameter
from .main import FirehoseS3DestinationConfiguration as FirehoseS3DestinationConfiguration
from .main import KinesisAnalyticsApp as KinesisAnalyticsApp
from .main import KinesisAnalyticsAppDestinationSchema as KinesisAnalyticsAppDestinationSchema
from .main import KinesisAnalyticsAppInput as KinesisAnalyticsAppInput
from .main import KinesisAnalyticsAppInputSchema as KinesisAnalyticsAppInputSchema
from .main import KinesisAnalyticsAppRecordColumn as KinesisAnalyticsAppRecordColumn
from .main import KinesisAnalyticsAppRecordColumn1 as KinesisAnalyticsAppRecordColumn1
from .main import KinesisAnalyticsAppRecordColumn2 as KinesisAnalyticsAppRecordColumn2
from .main import KinesisAnalyticsAppRecordColumn3 as KinesisAnalyticsAppRecordColumn3
from .main import KinesisAnalyticsOutput as KinesisAnalyticsOutput
from .main import KinesisAnalyticsOutputDestinationSchema as KinesisAnalyticsOutputDestinationSchema
from .main import KinesisAnalyticsOutputOutput as KinesisAnalyticsOutputOutput
from .main import ProcessFunction as ProcessFunction
from .main import ProcessFunctionEnvironment as ProcessFunctionEnvironment
from .security import FirehoseAccessRole as FirehoseAccessRole
from .security import FirehoseAccessRoleAllowStatement0 as FirehoseAccessRoleAllowStatement0
from .security import FirehoseAccessRoleAssumeRolePolicyDocument as FirehoseAccessRoleAssumeRolePolicyDocument
from .security import FirehoseAccessRolePolicy as FirehoseAccessRolePolicy
from .security import FirehoseAccessRolePolicy1 as FirehoseAccessRolePolicy1
from .security import KinesisAnalyticsAccessRole as KinesisAnalyticsAccessRole
from .security import KinesisAnalyticsAccessRoleAllowStatement0 as KinesisAnalyticsAccessRoleAllowStatement0
from .security import KinesisAnalyticsAccessRoleAssumeRolePolicyDocument as KinesisAnalyticsAccessRoleAssumeRolePolicyDocument
from .security import KinesisAnalyticsAccessRolePolicy as KinesisAnalyticsAccessRolePolicy
from .security import KinesisAnalyticsAccessRolePolicy1 as KinesisAnalyticsAccessRolePolicy1
from .storage import ProcessedDataBucket as ProcessedDataBucket
from .storage import RawDataBucket as RawDataBucket

__all__: list[str] = ['AMI_ID', 'ARN', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'CountFunction', 'CountFunctionEnvironment', 'CountTable', 'DenyStatement', 'Equals', 'FindInMap', 'Firehose', 'FirehoseAccessRole', 'FirehoseAccessRoleAllowStatement0', 'FirehoseAccessRoleAssumeRolePolicyDocument', 'FirehoseAccessRolePolicy', 'FirehoseAccessRolePolicy1', 'FirehoseAmazonOpenSearchServerlessBufferingHints', 'FirehoseAmazonOpenSearchServerlessBufferingHints1', 'FirehoseExtendedS3DestinationConfiguration', 'FirehoseProcessingConfiguration', 'FirehoseProcessor', 'FirehoseProcessorParameter', 'FirehoseS3DestinationConfiguration', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'If', 'ImportValue', 'Join', 'KEY_PAIR', 'KinesisAnalyticsAccessRole', 'KinesisAnalyticsAccessRoleAllowStatement0', 'KinesisAnalyticsAccessRoleAssumeRolePolicyDocument', 'KinesisAnalyticsAccessRolePolicy', 'KinesisAnalyticsAccessRolePolicy1', 'KinesisAnalyticsApp', 'KinesisAnalyticsAppDestinationSchema', 'KinesisAnalyticsAppInput', 'KinesisAnalyticsAppInputSchema', 'KinesisAnalyticsAppRecordColumn', 'KinesisAnalyticsAppRecordColumn1', 'KinesisAnalyticsAppRecordColumn2', 'KinesisAnalyticsAppRecordColumn3', 'KinesisAnalyticsOutput', 'KinesisAnalyticsOutputDestinationSchema', 'KinesisAnalyticsOutputOutput', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NUMBER', 'Not', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'ProcessFunction', 'ProcessFunctionEnvironment', 'ProcessedDataBucket', 'ProcessedDataTable', 'ProcessedDataTableAttributeDefinition', 'ProcessedDataTableKeySchema', 'ProcessedDataTableTimeToLiveSpecification', 'PropertyType', 'RawDataBucket', 'Ref', 'RefDict', 'RefList', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'SUBNET_ID', 'Select', 'Split', 'Sub', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'serverless', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
