"""AWS CloudFormation Sample Template Sample template EIP_With_Association: This template shows how to associate an Elastic IP address with an Amazon EC2 instance - you can use this same technique to ...

Generated by wetwire-aws import."""

from wetwire_aws.loader import setup_params, setup_resources

setup_params(globals())

from .params import *  # noqa: F403, F401

setup_resources(__file__, __name__, globals())

