"""
AWS LOOKOUTVISION CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:23Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Resources
# ============================================================


@dataclass
class Project(CloudFormationResource):
    """Project resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lookoutvision-project.html

    CloudFormation type: AWS::LookoutVision::Project
    """

    _resource_type: ClassVar[str] = "AWS::LookoutVision::Project"

    project_name: DslValue[str] | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"
