"""
AWS FSX CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:21Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class ActiveDirectoryErrorType:
    DOMAIN_NOT_FOUND = "DOMAIN_NOT_FOUND"
    INCOMPATIBLE_DOMAIN_MODE = "INCOMPATIBLE_DOMAIN_MODE"
    WRONG_VPC = "WRONG_VPC"
    INVALID_NETWORK_TYPE = "INVALID_NETWORK_TYPE"
    INVALID_DOMAIN_STAGE = "INVALID_DOMAIN_STAGE"


class AdministrativeActionType:
    FILE_SYSTEM_UPDATE = "FILE_SYSTEM_UPDATE"
    STORAGE_OPTIMIZATION = "STORAGE_OPTIMIZATION"
    FILE_SYSTEM_ALIAS_ASSOCIATION = "FILE_SYSTEM_ALIAS_ASSOCIATION"
    FILE_SYSTEM_ALIAS_DISASSOCIATION = "FILE_SYSTEM_ALIAS_DISASSOCIATION"
    VOLUME_UPDATE = "VOLUME_UPDATE"
    SNAPSHOT_UPDATE = "SNAPSHOT_UPDATE"
    RELEASE_NFS_V3_LOCKS = "RELEASE_NFS_V3_LOCKS"
    VOLUME_RESTORE = "VOLUME_RESTORE"
    THROUGHPUT_OPTIMIZATION = "THROUGHPUT_OPTIMIZATION"
    IOPS_OPTIMIZATION = "IOPS_OPTIMIZATION"
    STORAGE_TYPE_OPTIMIZATION = "STORAGE_TYPE_OPTIMIZATION"
    MISCONFIGURED_STATE_RECOVERY = "MISCONFIGURED_STATE_RECOVERY"
    VOLUME_UPDATE_WITH_SNAPSHOT = "VOLUME_UPDATE_WITH_SNAPSHOT"
    VOLUME_INITIALIZE_WITH_SNAPSHOT = "VOLUME_INITIALIZE_WITH_SNAPSHOT"
    DOWNLOAD_DATA_FROM_BACKUP = "DOWNLOAD_DATA_FROM_BACKUP"


class AliasLifecycle:
    AVAILABLE = "AVAILABLE"
    CREATING = "CREATING"
    DELETING = "DELETING"
    CREATE_FAILED = "CREATE_FAILED"
    DELETE_FAILED = "DELETE_FAILED"


class AutoImportPolicyType:
    NONE = "NONE"
    NEW = "NEW"
    NEW_CHANGED = "NEW_CHANGED"
    NEW_CHANGED_DELETED = "NEW_CHANGED_DELETED"


class AutocommitPeriodType:
    MINUTES = "MINUTES"
    HOURS = "HOURS"
    DAYS = "DAYS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"
    NONE = "NONE"


class BackupLifecycle:
    AVAILABLE = "AVAILABLE"
    CREATING = "CREATING"
    TRANSFERRING = "TRANSFERRING"
    DELETED = "DELETED"
    FAILED = "FAILED"
    PENDING = "PENDING"
    COPYING = "COPYING"


class BackupType:
    AUTOMATIC = "AUTOMATIC"
    USER_INITIATED = "USER_INITIATED"
    AWS_BACKUP = "AWS_BACKUP"


class DataCompressionType:
    NONE = "NONE"
    LZ4 = "LZ4"


class DataRepositoryLifecycle:
    CREATING = "CREATING"
    AVAILABLE = "AVAILABLE"
    MISCONFIGURED = "MISCONFIGURED"
    UPDATING = "UPDATING"
    DELETING = "DELETING"
    FAILED = "FAILED"


class DataRepositoryTaskFilterName:
    FILE_SYSTEM_ID = "file-system-id"
    TASK_LIFECYCLE = "task-lifecycle"
    DATA_REPOSITORY_ASSOCIATION_ID = "data-repository-association-id"
    FILE_CACHE_ID = "file-cache-id"


class DataRepositoryTaskLifecycle:
    PENDING = "PENDING"
    EXECUTING = "EXECUTING"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    CANCELED = "CANCELED"
    CANCELING = "CANCELING"


class DataRepositoryTaskType:
    EXPORT_TO_REPOSITORY = "EXPORT_TO_REPOSITORY"
    IMPORT_METADATA_FROM_REPOSITORY = "IMPORT_METADATA_FROM_REPOSITORY"
    RELEASE_DATA_FROM_FILESYSTEM = "RELEASE_DATA_FROM_FILESYSTEM"
    AUTO_RELEASE_DATA = "AUTO_RELEASE_DATA"


class DeleteFileSystemOpenZFSOption:
    DELETE_CHILD_VOLUMES_AND_SNAPSHOTS = "DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"


class DeleteOpenZFSVolumeOption:
    DELETE_CHILD_VOLUMES_AND_SNAPSHOTS = "DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"


class DiskIopsConfigurationMode:
    AUTOMATIC = "AUTOMATIC"
    USER_PROVISIONED = "USER_PROVISIONED"


class DriveCacheType:
    NONE = "NONE"
    READ = "READ"


class EventType:
    NEW = "NEW"
    CHANGED = "CHANGED"
    DELETED = "DELETED"


class FileCacheLifecycle:
    AVAILABLE = "AVAILABLE"
    CREATING = "CREATING"
    DELETING = "DELETING"
    UPDATING = "UPDATING"
    FAILED = "FAILED"


class FileCacheLustreDeploymentType:
    CACHE_1 = "CACHE_1"


class FileCacheType:
    LUSTRE = "LUSTRE"


class FileSystemLifecycle:
    AVAILABLE = "AVAILABLE"
    CREATING = "CREATING"
    FAILED = "FAILED"
    DELETING = "DELETING"
    MISCONFIGURED = "MISCONFIGURED"
    UPDATING = "UPDATING"
    MISCONFIGURED_UNAVAILABLE = "MISCONFIGURED_UNAVAILABLE"


class FileSystemMaintenanceOperation:
    PATCHING = "PATCHING"
    BACKING_UP = "BACKING_UP"


class FileSystemType:
    WINDOWS = "WINDOWS"
    LUSTRE = "LUSTRE"
    ONTAP = "ONTAP"
    OPENZFS = "OPENZFS"


class FilterName:
    FILE_SYSTEM_ID = "file-system-id"
    BACKUP_TYPE = "backup-type"
    FILE_SYSTEM_TYPE = "file-system-type"
    VOLUME_ID = "volume-id"
    DATA_REPOSITORY_TYPE = "data-repository-type"
    FILE_CACHE_ID = "file-cache-id"
    FILE_CACHE_TYPE = "file-cache-type"


class FlexCacheEndpointType:
    NONE = "NONE"
    ORIGIN = "ORIGIN"
    CACHE = "CACHE"


class InputOntapVolumeType:
    RW = "RW"
    DP = "DP"


class LustreAccessAuditLogLevel:
    DISABLED = "DISABLED"
    WARN_ONLY = "WARN_ONLY"
    ERROR_ONLY = "ERROR_ONLY"
    WARN_ERROR = "WARN_ERROR"


class LustreDeploymentType:
    SCRATCH_1 = "SCRATCH_1"
    SCRATCH_2 = "SCRATCH_2"
    PERSISTENT_1 = "PERSISTENT_1"
    PERSISTENT_2 = "PERSISTENT_2"


class LustreReadCacheSizingMode:
    NO_CACHE = "NO_CACHE"
    USER_PROVISIONED = "USER_PROVISIONED"
    PROPORTIONAL_TO_THROUGHPUT_CAPACITY = "PROPORTIONAL_TO_THROUGHPUT_CAPACITY"


class MetadataConfigurationMode:
    AUTOMATIC = "AUTOMATIC"
    USER_PROVISIONED = "USER_PROVISIONED"


class NetworkType:
    IPV4 = "IPV4"
    DUAL = "DUAL"


class NfsVersion:
    NFS3 = "NFS3"


class OntapDeploymentType:
    MULTI_AZ_1 = "MULTI_AZ_1"
    SINGLE_AZ_1 = "SINGLE_AZ_1"
    SINGLE_AZ_2 = "SINGLE_AZ_2"
    MULTI_AZ_2 = "MULTI_AZ_2"


class OntapFileSystemUserType:
    UNIX = "UNIX"
    WINDOWS = "WINDOWS"


class OntapVolumeType:
    RW = "RW"
    DP = "DP"
    LS = "LS"


class OpenZFSCopyStrategy:
    CLONE = "CLONE"
    FULL_COPY = "FULL_COPY"
    INCREMENTAL_COPY = "INCREMENTAL_COPY"


class OpenZFSDataCompressionType:
    NONE = "NONE"
    ZSTD = "ZSTD"
    LZ4 = "LZ4"


class OpenZFSDeploymentType:
    SINGLE_AZ_1 = "SINGLE_AZ_1"
    SINGLE_AZ_2 = "SINGLE_AZ_2"
    SINGLE_AZ_HA_1 = "SINGLE_AZ_HA_1"
    SINGLE_AZ_HA_2 = "SINGLE_AZ_HA_2"
    MULTI_AZ_1 = "MULTI_AZ_1"


class OpenZFSFileSystemUserType:
    POSIX = "POSIX"


class OpenZFSQuotaType:
    USER = "USER"
    GROUP = "GROUP"


class OpenZFSReadCacheSizingMode:
    NO_CACHE = "NO_CACHE"
    USER_PROVISIONED = "USER_PROVISIONED"
    PROPORTIONAL_TO_THROUGHPUT_CAPACITY = "PROPORTIONAL_TO_THROUGHPUT_CAPACITY"


class PrivilegedDelete:
    DISABLED = "DISABLED"
    ENABLED = "ENABLED"
    PERMANENTLY_DISABLED = "PERMANENTLY_DISABLED"


class ReportFormat:
    REPORT_CSV_20191124 = "REPORT_CSV_20191124"


class ReportScope:
    FAILED_FILES_ONLY = "FAILED_FILES_ONLY"


class ResourceType:
    FILE_SYSTEM = "FILE_SYSTEM"
    VOLUME = "VOLUME"


class RestoreOpenZFSVolumeOption:
    DELETE_INTERMEDIATE_SNAPSHOTS = "DELETE_INTERMEDIATE_SNAPSHOTS"
    DELETE_CLONED_VOLUMES = "DELETE_CLONED_VOLUMES"


class RetentionPeriodType:
    SECONDS = "SECONDS"
    MINUTES = "MINUTES"
    HOURS = "HOURS"
    DAYS = "DAYS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"
    INFINITE = "INFINITE"
    UNSPECIFIED = "UNSPECIFIED"


class S3AccessPointAttachmentLifecycle:
    AVAILABLE = "AVAILABLE"
    CREATING = "CREATING"
    DELETING = "DELETING"
    UPDATING = "UPDATING"
    FAILED = "FAILED"
    MISCONFIGURED = "MISCONFIGURED"


class S3AccessPointAttachmentType:
    OPENZFS = "OPENZFS"
    ONTAP = "ONTAP"


class S3AccessPointAttachmentsFilterName:
    FILE_SYSTEM_ID = "file-system-id"
    VOLUME_ID = "volume-id"
    TYPE = "type"


class SecurityStyle:
    UNIX = "UNIX"
    NTFS = "NTFS"
    MIXED = "MIXED"


class ServiceLimit:
    FILE_SYSTEM_COUNT = "FILE_SYSTEM_COUNT"
    TOTAL_THROUGHPUT_CAPACITY = "TOTAL_THROUGHPUT_CAPACITY"
    TOTAL_STORAGE = "TOTAL_STORAGE"
    TOTAL_USER_INITIATED_BACKUPS = "TOTAL_USER_INITIATED_BACKUPS"
    TOTAL_USER_TAGS = "TOTAL_USER_TAGS"
    TOTAL_IN_PROGRESS_COPY_BACKUPS = "TOTAL_IN_PROGRESS_COPY_BACKUPS"
    STORAGE_VIRTUAL_MACHINES_PER_FILE_SYSTEM = (
        "STORAGE_VIRTUAL_MACHINES_PER_FILE_SYSTEM"
    )
    VOLUMES_PER_FILE_SYSTEM = "VOLUMES_PER_FILE_SYSTEM"
    TOTAL_SSD_IOPS = "TOTAL_SSD_IOPS"
    FILE_CACHE_COUNT = "FILE_CACHE_COUNT"


class SnaplockType:
    COMPLIANCE = "COMPLIANCE"
    ENTERPRISE = "ENTERPRISE"


class SnapshotFilterName:
    FILE_SYSTEM_ID = "file-system-id"
    VOLUME_ID = "volume-id"


class SnapshotLifecycle:
    PENDING = "PENDING"
    CREATING = "CREATING"
    DELETING = "DELETING"
    AVAILABLE = "AVAILABLE"


class Status:
    FAILED = "FAILED"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    UPDATED_OPTIMIZING = "UPDATED_OPTIMIZING"
    OPTIMIZING = "OPTIMIZING"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"


class StorageType:
    SSD = "SSD"
    HDD = "HDD"
    INTELLIGENT_TIERING = "INTELLIGENT_TIERING"


class StorageVirtualMachineFilterName:
    FILE_SYSTEM_ID = "file-system-id"


class StorageVirtualMachineLifecycle:
    CREATED = "CREATED"
    CREATING = "CREATING"
    DELETING = "DELETING"
    FAILED = "FAILED"
    MISCONFIGURED = "MISCONFIGURED"
    PENDING = "PENDING"


class StorageVirtualMachineRootVolumeSecurityStyle:
    UNIX = "UNIX"
    NTFS = "NTFS"
    MIXED = "MIXED"


class StorageVirtualMachineSubtype:
    DEFAULT = "DEFAULT"
    DP_DESTINATION = "DP_DESTINATION"
    SYNC_DESTINATION = "SYNC_DESTINATION"
    SYNC_SOURCE = "SYNC_SOURCE"


class TieringPolicyName:
    SNAPSHOT_ONLY = "SNAPSHOT_ONLY"
    AUTO = "AUTO"
    ALL = "ALL"
    NONE = "NONE"


class Unit:
    DAYS = "DAYS"


class UpdateOpenZFSVolumeOption:
    DELETE_INTERMEDIATE_SNAPSHOTS = "DELETE_INTERMEDIATE_SNAPSHOTS"
    DELETE_CLONED_VOLUMES = "DELETE_CLONED_VOLUMES"
    DELETE_INTERMEDIATE_DATA = "DELETE_INTERMEDIATE_DATA"


class VolumeFilterName:
    FILE_SYSTEM_ID = "file-system-id"
    STORAGE_VIRTUAL_MACHINE_ID = "storage-virtual-machine-id"


class VolumeLifecycle:
    CREATING = "CREATING"
    CREATED = "CREATED"
    DELETING = "DELETING"
    FAILED = "FAILED"
    MISCONFIGURED = "MISCONFIGURED"
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"


class VolumeStyle:
    FLEXVOL = "FLEXVOL"
    FLEXGROUP = "FLEXGROUP"


class VolumeType:
    ONTAP = "ONTAP"
    OPENZFS = "OPENZFS"


class WindowsAccessAuditLogLevel:
    DISABLED = "DISABLED"
    SUCCESS_ONLY = "SUCCESS_ONLY"
    FAILURE_ONLY = "FAILURE_ONLY"
    SUCCESS_AND_FAILURE = "SUCCESS_AND_FAILURE"


class WindowsDeploymentType:
    MULTI_AZ_1 = "MULTI_AZ_1"
    SINGLE_AZ_1 = "SINGLE_AZ_1"
    SINGLE_AZ_2 = "SINGLE_AZ_2"


# PropertyType submodules
from . import DataRepositoryAssociation as _DataRepositoryAssociation
from . import FileSystem as _FileSystem
from . import S3AccessPointAttachment as _S3AccessPointAttachment
from . import StorageVirtualMachine as _StorageVirtualMachine
from . import Volume as _Volume


# Resources
# ============================================================


@dataclass
class DataRepositoryAssociation(CloudFormationResource):
    """DataRepositoryAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-datarepositoryassociation.html

    CloudFormation type: AWS::FSx::DataRepositoryAssociation
    """

    _resource_type: ClassVar[str] = "AWS::FSx::DataRepositoryAssociation"

    data_repository_path: str | None = None
    file_system_id: str | None = None
    file_system_path: str | None = None
    batch_import_meta_data_on_create: bool | None = None
    imported_file_chunk_size: int | None = None
    s3: _DataRepositoryAssociation.S3 | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceARN"
    ASSOCIATIONID: ClassVar[str] = "AssociationId"


@dataclass
class FileSystem(CloudFormationResource):
    """FileSystem resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html

    CloudFormation type: AWS::FSx::FileSystem
    """

    _resource_type: ClassVar[str] = "AWS::FSx::FileSystem"
    _property_mappings: ClassVar[dict[str, str]] = {
        "open_zfs_configuration": "OpenZFSConfiguration",
    }

    file_system_type: str | None = None
    subnet_ids: list[String] = field(default_factory=list)
    backup_id: str | None = None
    file_system_type_version: str | None = None
    kms_key_id: str | None = None
    lustre_configuration: _FileSystem.LustreConfiguration | None = None
    network_type: str | None = None
    ontap_configuration: _FileSystem.OntapConfiguration | None = None
    open_zfs_configuration: _FileSystem.OpenZFSConfiguration | None = None
    security_group_ids: list[String] = field(default_factory=list)
    storage_capacity: int | None = None
    storage_type: str | None = None
    tags: list[Tag] = field(default_factory=list)
    windows_configuration: _FileSystem.WindowsConfiguration | None = None

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceARN"
    ROOTVOLUMEID: ClassVar[str] = "RootVolumeId"
    DNSNAME: ClassVar[str] = "DNSName"
    LUSTREMOUNTNAME: ClassVar[str] = "LustreMountName"


@dataclass
class S3AccessPointAttachment(CloudFormationResource):
    """S3AccessPointAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-s3accesspointattachment.html

    CloudFormation type: AWS::FSx::S3AccessPointAttachment
    """

    _resource_type: ClassVar[str] = "AWS::FSx::S3AccessPointAttachment"
    _property_mappings: ClassVar[dict[str, str]] = {
        "open_zfs_configuration": "OpenZFSConfiguration",
    }

    name: str | None = None
    type_: str | None = None
    ontap_configuration: (
        _S3AccessPointAttachment.S3AccessPointOntapConfiguration | None
    ) = None
    open_zfs_configuration: (
        _S3AccessPointAttachment.S3AccessPointOpenZFSConfiguration | None
    ) = None
    s3_access_point: _S3AccessPointAttachment.S3AccessPoint | None = None

    # GetAtt attributes
    S3ACCESSPOINT_ALIAS: ClassVar[str] = "S3AccessPoint.Alias"
    S3ACCESSPOINT_RESOURCEARN: ClassVar[str] = "S3AccessPoint.ResourceARN"


@dataclass
class Snapshot(CloudFormationResource):
    """Snapshot resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-snapshot.html

    CloudFormation type: AWS::FSx::Snapshot
    """

    _resource_type: ClassVar[str] = "AWS::FSx::Snapshot"

    name: str | None = None
    volume_id: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceARN"


@dataclass
class StorageVirtualMachine(CloudFormationResource):
    """StorageVirtualMachine resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-storagevirtualmachine.html

    CloudFormation type: AWS::FSx::StorageVirtualMachine
    """

    _resource_type: ClassVar[str] = "AWS::FSx::StorageVirtualMachine"

    file_system_id: str | None = None
    name: str | None = None
    active_directory_configuration: (
        _StorageVirtualMachine.ActiveDirectoryConfiguration | None
    ) = None
    root_volume_security_style: str | None = None
    svm_admin_password: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceARN"
    STORAGEVIRTUALMACHINEID: ClassVar[str] = "StorageVirtualMachineId"
    UUID: ClassVar[str] = "UUID"


@dataclass
class Volume(CloudFormationResource):
    """Volume resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-volume.html

    CloudFormation type: AWS::FSx::Volume
    """

    _resource_type: ClassVar[str] = "AWS::FSx::Volume"
    _property_mappings: ClassVar[dict[str, str]] = {
        "open_zfs_configuration": "OpenZFSConfiguration",
    }

    name: str | None = None
    backup_id: str | None = None
    ontap_configuration: _Volume.OntapConfiguration | None = None
    open_zfs_configuration: _Volume.OpenZFSConfiguration | None = None
    tags: list[Tag] = field(default_factory=list)
    volume_type: str | None = None

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceARN"
    VOLUMEID: ClassVar[str] = "VolumeId"
    UUID: ClassVar[str] = "UUID"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
DataRepositoryAssociation.AutoExportPolicy = PropertyTypeDescriptor(
    _DataRepositoryAssociation.AutoExportPolicy, "AutoExportPolicy"
)
DataRepositoryAssociation.AutoImportPolicy = PropertyTypeDescriptor(
    _DataRepositoryAssociation.AutoImportPolicy, "AutoImportPolicy"
)
DataRepositoryAssociation.S3 = PropertyTypeDescriptor(
    _DataRepositoryAssociation.S3, "S3"
)
FileSystem.AuditLogConfiguration = PropertyTypeDescriptor(
    _FileSystem.AuditLogConfiguration, "AuditLogConfiguration"
)
FileSystem.ClientConfigurations = PropertyTypeDescriptor(
    _FileSystem.ClientConfigurations, "ClientConfigurations"
)
FileSystem.DataReadCacheConfiguration = PropertyTypeDescriptor(
    _FileSystem.DataReadCacheConfiguration, "DataReadCacheConfiguration"
)
FileSystem.DiskIopsConfiguration = PropertyTypeDescriptor(
    _FileSystem.DiskIopsConfiguration, "DiskIopsConfiguration"
)
FileSystem.LustreConfiguration = PropertyTypeDescriptor(
    _FileSystem.LustreConfiguration, "LustreConfiguration"
)
FileSystem.MetadataConfiguration = PropertyTypeDescriptor(
    _FileSystem.MetadataConfiguration, "MetadataConfiguration"
)
FileSystem.NfsExports = PropertyTypeDescriptor(_FileSystem.NfsExports, "NfsExports")
FileSystem.OntapConfiguration = PropertyTypeDescriptor(
    _FileSystem.OntapConfiguration, "OntapConfiguration"
)
FileSystem.OpenZFSConfiguration = PropertyTypeDescriptor(
    _FileSystem.OpenZFSConfiguration, "OpenZFSConfiguration"
)
FileSystem.ReadCacheConfiguration = PropertyTypeDescriptor(
    _FileSystem.ReadCacheConfiguration, "ReadCacheConfiguration"
)
FileSystem.RootVolumeConfiguration = PropertyTypeDescriptor(
    _FileSystem.RootVolumeConfiguration, "RootVolumeConfiguration"
)
FileSystem.SelfManagedActiveDirectoryConfiguration = PropertyTypeDescriptor(
    _FileSystem.SelfManagedActiveDirectoryConfiguration,
    "SelfManagedActiveDirectoryConfiguration",
)
FileSystem.UserAndGroupQuotas = PropertyTypeDescriptor(
    _FileSystem.UserAndGroupQuotas, "UserAndGroupQuotas"
)
FileSystem.WindowsConfiguration = PropertyTypeDescriptor(
    _FileSystem.WindowsConfiguration, "WindowsConfiguration"
)
S3AccessPointAttachment.FileSystemGID = PropertyTypeDescriptor(
    _S3AccessPointAttachment.FileSystemGID, "FileSystemGID"
)
S3AccessPointAttachment.OntapFileSystemIdentity = PropertyTypeDescriptor(
    _S3AccessPointAttachment.OntapFileSystemIdentity, "OntapFileSystemIdentity"
)
S3AccessPointAttachment.OntapUnixFileSystemUser = PropertyTypeDescriptor(
    _S3AccessPointAttachment.OntapUnixFileSystemUser, "OntapUnixFileSystemUser"
)
S3AccessPointAttachment.OntapWindowsFileSystemUser = PropertyTypeDescriptor(
    _S3AccessPointAttachment.OntapWindowsFileSystemUser, "OntapWindowsFileSystemUser"
)
S3AccessPointAttachment.OpenZFSFileSystemIdentity = PropertyTypeDescriptor(
    _S3AccessPointAttachment.OpenZFSFileSystemIdentity, "OpenZFSFileSystemIdentity"
)
S3AccessPointAttachment.OpenZFSPosixFileSystemUser = PropertyTypeDescriptor(
    _S3AccessPointAttachment.OpenZFSPosixFileSystemUser, "OpenZFSPosixFileSystemUser"
)
S3AccessPointAttachment.S3AccessPoint = PropertyTypeDescriptor(
    _S3AccessPointAttachment.S3AccessPoint, "S3AccessPoint"
)
S3AccessPointAttachment.S3AccessPointOntapConfiguration = PropertyTypeDescriptor(
    _S3AccessPointAttachment.S3AccessPointOntapConfiguration,
    "S3AccessPointOntapConfiguration",
)
S3AccessPointAttachment.S3AccessPointOpenZFSConfiguration = PropertyTypeDescriptor(
    _S3AccessPointAttachment.S3AccessPointOpenZFSConfiguration,
    "S3AccessPointOpenZFSConfiguration",
)
S3AccessPointAttachment.S3AccessPointVpcConfiguration = PropertyTypeDescriptor(
    _S3AccessPointAttachment.S3AccessPointVpcConfiguration,
    "S3AccessPointVpcConfiguration",
)
StorageVirtualMachine.ActiveDirectoryConfiguration = PropertyTypeDescriptor(
    _StorageVirtualMachine.ActiveDirectoryConfiguration, "ActiveDirectoryConfiguration"
)
StorageVirtualMachine.SelfManagedActiveDirectoryConfiguration = PropertyTypeDescriptor(
    _StorageVirtualMachine.SelfManagedActiveDirectoryConfiguration,
    "SelfManagedActiveDirectoryConfiguration",
)
Volume.AggregateConfiguration = PropertyTypeDescriptor(
    _Volume.AggregateConfiguration, "AggregateConfiguration"
)
Volume.AutocommitPeriod = PropertyTypeDescriptor(
    _Volume.AutocommitPeriod, "AutocommitPeriod"
)
Volume.ClientConfigurations = PropertyTypeDescriptor(
    _Volume.ClientConfigurations, "ClientConfigurations"
)
Volume.NfsExports = PropertyTypeDescriptor(_Volume.NfsExports, "NfsExports")
Volume.OntapConfiguration = PropertyTypeDescriptor(
    _Volume.OntapConfiguration, "OntapConfiguration"
)
Volume.OpenZFSConfiguration = PropertyTypeDescriptor(
    _Volume.OpenZFSConfiguration, "OpenZFSConfiguration"
)
Volume.OriginSnapshot = PropertyTypeDescriptor(_Volume.OriginSnapshot, "OriginSnapshot")
Volume.RetentionPeriod = PropertyTypeDescriptor(
    _Volume.RetentionPeriod, "RetentionPeriod"
)
Volume.SnaplockConfiguration = PropertyTypeDescriptor(
    _Volume.SnaplockConfiguration, "SnaplockConfiguration"
)
Volume.SnaplockRetentionPeriod = PropertyTypeDescriptor(
    _Volume.SnaplockRetentionPeriod, "SnaplockRetentionPeriod"
)
Volume.TieringPolicy = PropertyTypeDescriptor(_Volume.TieringPolicy, "TieringPolicy")
Volume.UserAndGroupQuotas = PropertyTypeDescriptor(
    _Volume.UserAndGroupQuotas, "UserAndGroupQuotas"
)
