"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    Tag,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    Attr,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    RefIntrinsic,
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
    # Condition operator constants
    BOOL,
    STRING_EQUALS,
    STRING_NOT_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_LIKE,
    STRING_NOT_LIKE,
    NUMERIC_EQUALS,
    NUMERIC_NOT_EQUALS,
    NUMERIC_LESS_THAN,
    NUMERIC_LESS_THAN_EQUALS,
    NUMERIC_GREATER_THAN,
    NUMERIC_GREATER_THAN_EQUALS,
    DATE_EQUALS,
    DATE_NOT_EQUALS,
    DATE_LESS_THAN,
    DATE_LESS_THAN_EQUALS,
    DATE_GREATER_THAN,
    DATE_GREATER_THAN_EQUALS,
    IP_ADDRESS,
    NOT_IP_ADDRESS,
    ARN_EQUALS,
    ARN_NOT_EQUALS,
    ARN_LIKE,
    ARN_NOT_LIKE,
    NULL,
    # Loader
    setup_resources,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .compute import DomainMember1WithInlineSsmAssociation as DomainMember1WithInlineSsmAssociation
from .compute import DomainMember1WithInlineSsmAssociationAssociationParameter as DomainMember1WithInlineSsmAssociationAssociationParameter
from .compute import DomainMember1WithInlineSsmAssociationAssociationParameter1 as DomainMember1WithInlineSsmAssociationAssociationParameter1
from .compute import DomainMember1WithInlineSsmAssociationAssociationParameter2 as DomainMember1WithInlineSsmAssociationAssociationParameter2
from .compute import DomainMember1WithInlineSsmAssociationBlockDeviceMapping as DomainMember1WithInlineSsmAssociationBlockDeviceMapping
from .compute import DomainMember1WithInlineSsmAssociationEbs as DomainMember1WithInlineSsmAssociationEbs
from .compute import DomainMember1WithInlineSsmAssociationSsmAssociation as DomainMember1WithInlineSsmAssociationSsmAssociation
from .compute import DomainMember2WithSsmAssociationInstance as DomainMember2WithSsmAssociationInstance
from .compute import DomainMember2WithSsmAssociationInstanceAssociationParameter as DomainMember2WithSsmAssociationInstanceAssociationParameter
from .compute import DomainMember2WithSsmAssociationInstanceBlockDeviceMapping as DomainMember2WithSsmAssociationInstanceBlockDeviceMapping
from .compute import DomainMember2WithSsmAssociationInstanceEbs as DomainMember2WithSsmAssociationInstanceEbs
from .compute import DomainMember3WithSsmAssociationTag as DomainMember3WithSsmAssociationTag
from .compute import DomainMember3WithSsmAssociationTagAssociationParameter as DomainMember3WithSsmAssociationTagAssociationParameter
from .compute import DomainMember3WithSsmAssociationTagAssociationParameter1 as DomainMember3WithSsmAssociationTagAssociationParameter1
from .compute import DomainMember3WithSsmAssociationTagBlockDeviceMapping as DomainMember3WithSsmAssociationTagBlockDeviceMapping
from .compute import DomainMember3WithSsmAssociationTagEbs as DomainMember3WithSsmAssociationTagEbs
from .compute import DomainMember4LinuxWithSsmAssociationInstance as DomainMember4LinuxWithSsmAssociationInstance
from .compute import DomainMember4LinuxWithSsmAssociationInstanceAssociationParameter as DomainMember4LinuxWithSsmAssociationInstanceAssociationParameter
from .compute import DomainMember4LinuxWithSsmAssociationInstanceBlockDeviceMapping as DomainMember4LinuxWithSsmAssociationInstanceBlockDeviceMapping
from .compute import DomainMember4LinuxWithSsmAssociationInstanceEbs as DomainMember4LinuxWithSsmAssociationInstanceEbs
from .params import AMAZONLINUX2 as AMAZONLINUX2
from .params import DirectoryID as DirectoryID
from .params import DirectoryName as DirectoryName
from .params import DomainDNSServer1 as DomainDNSServer1
from .params import DomainDNSServer1ConditionCondition as DomainDNSServer1ConditionCondition
from .params import DomainDNSServer2 as DomainDNSServer2
from .params import DomainDNSServer2ConditionCondition as DomainDNSServer2ConditionCondition
from .params import DomainDNSServer3 as DomainDNSServer3
from .params import DomainDNSServer3ConditionCondition as DomainDNSServer3ConditionCondition
from .params import DomainDNSServer4 as DomainDNSServer4
from .params import DomainDNSServer4ConditionCondition as DomainDNSServer4ConditionCondition
from .params import DomainDNSServersConditionCondition as DomainDNSServersConditionCondition
from .params import DomainMember1NetBIOSName as DomainMember1NetBIOSName
from .params import DomainMember2NetBIOSName as DomainMember2NetBIOSName
from .params import DomainMember3NetBIOSName as DomainMember3NetBIOSName
from .params import DomainMember4NetBIOSName as DomainMember4NetBIOSName
from .params import DomainMembersInstanceType as DomainMembersInstanceType
from .params import DomainMembersLinuxInstanceProfile as DomainMembersLinuxInstanceProfile
from .params import DomainMembersSGID as DomainMembersSGID
from .params import DomainMembersWindowsInstanceProfile as DomainMembersWindowsInstanceProfile
from .params import EBSKMSKey as EBSKMSKey
from .params import EBSKMSKeyConditionCondition as EBSKMSKeyConditionCondition
from .params import KeyPairName as KeyPairName
from .params import PrivateSubnet1ID as PrivateSubnet1ID
from .params import PrivateSubnet2ID as PrivateSubnet2ID
from .params import SSMLogsBucketConditionCondition as SSMLogsBucketConditionCondition
from .params import SSMLogsBucketName as SSMLogsBucketName
from .params import WINFULLBASE as WINFULLBASE
from .security import JoinDomainAssociationInstances as JoinDomainAssociationInstances
from .security import JoinDomainAssociationInstancesInstanceAssociationOutputLocation as JoinDomainAssociationInstancesInstanceAssociationOutputLocation
from .security import JoinDomainAssociationInstancesSsmParameter as JoinDomainAssociationInstancesSsmParameter
from .security import JoinDomainAssociationTags as JoinDomainAssociationTags
from .security import JoinDomainAssociationTagsInstanceAssociationOutputLocation as JoinDomainAssociationTagsInstanceAssociationOutputLocation
from .security import JoinDomainAssociationTagsSsmParameter as JoinDomainAssociationTagsSsmParameter

__all__: list[str] = ['AMAZONLINUX2', 'AMI_ID', 'ARN', 'ARN_EQUALS', 'ARN_LIKE', 'ARN_NOT_EQUALS', 'ARN_NOT_LIKE', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'Attr', 'BOOL', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'DATE_EQUALS', 'DATE_GREATER_THAN', 'DATE_GREATER_THAN_EQUALS', 'DATE_LESS_THAN', 'DATE_LESS_THAN_EQUALS', 'DATE_NOT_EQUALS', 'DenyStatement', 'DirectoryID', 'DirectoryName', 'DomainDNSServer1', 'DomainDNSServer1ConditionCondition', 'DomainDNSServer2', 'DomainDNSServer2ConditionCondition', 'DomainDNSServer3', 'DomainDNSServer3ConditionCondition', 'DomainDNSServer4', 'DomainDNSServer4ConditionCondition', 'DomainDNSServersConditionCondition', 'DomainMember1NetBIOSName', 'DomainMember1WithInlineSsmAssociation', 'DomainMember1WithInlineSsmAssociationAssociationParameter', 'DomainMember1WithInlineSsmAssociationAssociationParameter1', 'DomainMember1WithInlineSsmAssociationAssociationParameter2', 'DomainMember1WithInlineSsmAssociationBlockDeviceMapping', 'DomainMember1WithInlineSsmAssociationEbs', 'DomainMember1WithInlineSsmAssociationSsmAssociation', 'DomainMember2NetBIOSName', 'DomainMember2WithSsmAssociationInstance', 'DomainMember2WithSsmAssociationInstanceAssociationParameter', 'DomainMember2WithSsmAssociationInstanceBlockDeviceMapping', 'DomainMember2WithSsmAssociationInstanceEbs', 'DomainMember3NetBIOSName', 'DomainMember3WithSsmAssociationTag', 'DomainMember3WithSsmAssociationTagAssociationParameter', 'DomainMember3WithSsmAssociationTagAssociationParameter1', 'DomainMember3WithSsmAssociationTagBlockDeviceMapping', 'DomainMember3WithSsmAssociationTagEbs', 'DomainMember4LinuxWithSsmAssociationInstance', 'DomainMember4LinuxWithSsmAssociationInstanceAssociationParameter', 'DomainMember4LinuxWithSsmAssociationInstanceBlockDeviceMapping', 'DomainMember4LinuxWithSsmAssociationInstanceEbs', 'DomainMember4NetBIOSName', 'DomainMembersInstanceType', 'DomainMembersLinuxInstanceProfile', 'DomainMembersSGID', 'DomainMembersWindowsInstanceProfile', 'EBSKMSKey', 'EBSKMSKeyConditionCondition', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'IP_ADDRESS', 'If', 'ImportValue', 'Join', 'JoinDomainAssociationInstances', 'JoinDomainAssociationInstancesInstanceAssociationOutputLocation', 'JoinDomainAssociationInstancesSsmParameter', 'JoinDomainAssociationTags', 'JoinDomainAssociationTagsInstanceAssociationOutputLocation', 'JoinDomainAssociationTagsSsmParameter', 'KEY_PAIR', 'KeyPairName', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NOT_IP_ADDRESS', 'NULL', 'NUMBER', 'NUMERIC_EQUALS', 'NUMERIC_GREATER_THAN', 'NUMERIC_GREATER_THAN_EQUALS', 'NUMERIC_LESS_THAN', 'NUMERIC_LESS_THAN_EQUALS', 'NUMERIC_NOT_EQUALS', 'Not', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PrivateSubnet1ID', 'PrivateSubnet2ID', 'PropertyType', 'Ref', 'RefDict', 'RefIntrinsic', 'RefList', 'SECURITY_GROUP_ID', 'SSMLogsBucketConditionCondition', 'SSMLogsBucketName', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'STRING_EQUALS', 'STRING_EQUALS_IGNORE_CASE', 'STRING_LIKE', 'STRING_NOT_EQUALS', 'STRING_NOT_EQUALS_IGNORE_CASE', 'STRING_NOT_LIKE', 'SUBNET_ID', 'Select', 'Split', 'Sub', 'Tag', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC_ID', 'WINFULLBASE', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
