"""
AWS VOICEID CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:26Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# PropertyType submodules
from . import Domain as _Domain


# Resources
# ============================================================


@dataclass
class Domain(CloudFormationResource):
    """Domain resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-voiceid-domain.html

    CloudFormation type: AWS::VoiceID::Domain
    """

    _resource_type: ClassVar[str] = "AWS::VoiceID::Domain"

    name: str | None = None
    server_side_encryption_configuration: (
        _Domain.ServerSideEncryptionConfiguration | None
    ) = None
    description: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    DOMAINID: ClassVar[str] = "DomainId"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Domain.ServerSideEncryptionConfiguration = _Domain.ServerSideEncryptionConfiguration
