"""
AWS CLOUDFORMATION CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class AccountFilterType:
    NONE = "NONE"
    INTERSECTION = "INTERSECTION"
    DIFFERENCE = "DIFFERENCE"
    UNION = "UNION"


class AccountGateStatus:
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AfterValueFrom:
    TEMPLATE = "TEMPLATE"


class AnnotationSeverityLevel:
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnnotationStatus:
    PASSED = "PASSED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AttributeChangeType:
    ADD = "Add"
    REMOVE = "Remove"
    MODIFY = "Modify"
    SYNCWITHACTUAL = "SyncWithActual"


class BeaconStackOperationStatus:
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class BeforeValueFrom:
    PREVIOUS_DEPLOYMENT_STATE = "PREVIOUS_DEPLOYMENT_STATE"
    ACTUAL_STATE = "ACTUAL_STATE"


class CallAs:
    SELF = "SELF"
    DELEGATED_ADMIN = "DELEGATED_ADMIN"


class Capability:
    CAPABILITY_IAM = "CAPABILITY_IAM"
    CAPABILITY_NAMED_IAM = "CAPABILITY_NAMED_IAM"
    CAPABILITY_AUTO_EXPAND = "CAPABILITY_AUTO_EXPAND"


class Category:
    REGISTERED = "REGISTERED"
    ACTIVATED = "ACTIVATED"
    THIRD_PARTY = "THIRD_PARTY"
    AWS_TYPES = "AWS_TYPES"


class ChangeAction:
    ADD = "Add"
    MODIFY = "Modify"
    REMOVE = "Remove"
    IMPORT = "Import"
    DYNAMIC = "Dynamic"
    SYNCWITHACTUAL = "SyncWithActual"


class ChangeSetHooksStatus:
    PLANNING = "PLANNING"
    PLANNED = "PLANNED"
    UNAVAILABLE = "UNAVAILABLE"


class ChangeSetStatus:
    CREATE_PENDING = "CREATE_PENDING"
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_COMPLETE = "CREATE_COMPLETE"
    DELETE_PENDING = "DELETE_PENDING"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    DELETE_FAILED = "DELETE_FAILED"
    FAILED = "FAILED"


class ChangeSetType:
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    IMPORT = "IMPORT"


class ChangeSource:
    RESOURCEREFERENCE = "ResourceReference"
    PARAMETERREFERENCE = "ParameterReference"
    RESOURCEATTRIBUTE = "ResourceAttribute"
    DIRECTMODIFICATION = "DirectModification"
    AUTOMATIC = "Automatic"
    NOMODIFICATION = "NoModification"


class ChangeType:
    RESOURCE = "Resource"


class ConcurrencyMode:
    STRICT_FAILURE_TOLERANCE = "STRICT_FAILURE_TOLERANCE"
    SOFT_FAILURE_TOLERANCE = "SOFT_FAILURE_TOLERANCE"


class DeletionMode:
    STANDARD = "STANDARD"
    FORCE_DELETE_STACK = "FORCE_DELETE_STACK"


class DeploymentMode:
    REVERT_DRIFT = "REVERT_DRIFT"


class DeprecatedStatus:
    LIVE = "LIVE"
    DEPRECATED = "DEPRECATED"


class DetailedStatus:
    CONFIGURATION_COMPLETE = "CONFIGURATION_COMPLETE"
    VALIDATION_FAILED = "VALIDATION_FAILED"


class DifferenceType:
    ADD = "ADD"
    REMOVE = "REMOVE"
    NOT_EQUAL = "NOT_EQUAL"


class DriftIgnoredReason:
    MANAGED_BY_AWS = "MANAGED_BY_AWS"
    WRITE_ONLY_PROPERTY = "WRITE_ONLY_PROPERTY"


class EvaluationType:
    STATIC = "Static"
    DYNAMIC = "Dynamic"


class EventType:
    STACK_EVENT = "STACK_EVENT"
    PROGRESS_EVENT = "PROGRESS_EVENT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PROVISIONING_ERROR = "PROVISIONING_ERROR"
    HOOK_INVOCATION_ERROR = "HOOK_INVOCATION_ERROR"


class ExecutionStatus:
    UNAVAILABLE = "UNAVAILABLE"
    AVAILABLE = "AVAILABLE"
    EXECUTE_IN_PROGRESS = "EXECUTE_IN_PROGRESS"
    EXECUTE_COMPLETE = "EXECUTE_COMPLETE"
    EXECUTE_FAILED = "EXECUTE_FAILED"
    OBSOLETE = "OBSOLETE"


class GeneratedTemplateDeletionPolicy:
    DELETE = "DELETE"
    RETAIN = "RETAIN"


class GeneratedTemplateResourceStatus:
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETE = "COMPLETE"


class GeneratedTemplateStatus:
    CREATE_PENDING = "CREATE_PENDING"
    UPDATE_PENDING = "UPDATE_PENDING"
    DELETE_PENDING = "DELETE_PENDING"
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETE = "COMPLETE"


class GeneratedTemplateUpdateReplacePolicy:
    DELETE = "DELETE"
    RETAIN = "RETAIN"


class HandlerErrorCode:
    NOTUPDATABLE = "NotUpdatable"
    INVALIDREQUEST = "InvalidRequest"
    ACCESSDENIED = "AccessDenied"
    INVALIDCREDENTIALS = "InvalidCredentials"
    ALREADYEXISTS = "AlreadyExists"
    NOTFOUND = "NotFound"
    RESOURCECONFLICT = "ResourceConflict"
    THROTTLING = "Throttling"
    SERVICELIMITEXCEEDED = "ServiceLimitExceeded"
    NOTSTABILIZED = "NotStabilized"
    GENERALSERVICEEXCEPTION = "GeneralServiceException"
    SERVICEINTERNALERROR = "ServiceInternalError"
    NETWORKFAILURE = "NetworkFailure"
    INTERNALFAILURE = "InternalFailure"
    INVALIDTYPECONFIGURATION = "InvalidTypeConfiguration"
    HANDLERINTERNALFAILURE = "HandlerInternalFailure"
    NONCOMPLIANT = "NonCompliant"
    UNKNOWN = "Unknown"
    UNSUPPORTEDTARGET = "UnsupportedTarget"


class HookFailureMode:
    FAIL = "FAIL"
    WARN = "WARN"


class HookInvocationPoint:
    PRE_PROVISION = "PRE_PROVISION"


class HookStatus:
    HOOK_IN_PROGRESS = "HOOK_IN_PROGRESS"
    HOOK_COMPLETE_SUCCEEDED = "HOOK_COMPLETE_SUCCEEDED"
    HOOK_COMPLETE_FAILED = "HOOK_COMPLETE_FAILED"
    HOOK_FAILED = "HOOK_FAILED"


class HookTargetAction:
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    IMPORT = "IMPORT"


class HookTargetType:
    RESOURCE = "RESOURCE"


class IdentityProvider:
    AWS_MARKETPLACE = "AWS_Marketplace"
    GITHUB = "GitHub"
    BITBUCKET = "Bitbucket"


class ListHookResultsTargetType:
    CHANGE_SET = "CHANGE_SET"
    STACK = "STACK"
    RESOURCE = "RESOURCE"
    CLOUD_CONTROL = "CLOUD_CONTROL"


class OnFailure:
    DO_NOTHING = "DO_NOTHING"
    ROLLBACK = "ROLLBACK"
    DELETE = "DELETE"


class OnStackFailure:
    DO_NOTHING = "DO_NOTHING"
    ROLLBACK = "ROLLBACK"
    DELETE = "DELETE"


class OperationResultFilterName:
    OPERATION_RESULT_STATUS = "OPERATION_RESULT_STATUS"


class OperationStatus:
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class OperationType:
    CREATE_STACK = "CREATE_STACK"
    UPDATE_STACK = "UPDATE_STACK"
    DELETE_STACK = "DELETE_STACK"
    CONTINUE_ROLLBACK = "CONTINUE_ROLLBACK"
    ROLLBACK = "ROLLBACK"
    CREATE_CHANGESET = "CREATE_CHANGESET"


class OrganizationStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    DISABLED_PERMANENTLY = "DISABLED_PERMANENTLY"


class PermissionModels:
    SERVICE_MANAGED = "SERVICE_MANAGED"
    SELF_MANAGED = "SELF_MANAGED"


class PolicyAction:
    DELETE = "Delete"
    RETAIN = "Retain"
    SNAPSHOT = "Snapshot"
    REPLACEANDDELETE = "ReplaceAndDelete"
    REPLACEANDRETAIN = "ReplaceAndRetain"
    REPLACEANDSNAPSHOT = "ReplaceAndSnapshot"


class ProvisioningType:
    NON_PROVISIONABLE = "NON_PROVISIONABLE"
    IMMUTABLE = "IMMUTABLE"
    FULLY_MUTABLE = "FULLY_MUTABLE"


class PublisherStatus:
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"


class RegionConcurrencyType:
    SEQUENTIAL = "SEQUENTIAL"
    PARALLEL = "PARALLEL"


class RegistrationStatus:
    COMPLETE = "COMPLETE"
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"


class RegistryType:
    RESOURCE = "RESOURCE"
    MODULE = "MODULE"
    HOOK = "HOOK"


class Replacement:
    TRUE = "True"
    FALSE = "False"
    CONDITIONAL = "Conditional"


class RequiresRecreation:
    NEVER = "Never"
    CONDITIONALLY = "Conditionally"
    ALWAYS = "Always"


class ResourceAttribute:
    PROPERTIES = "Properties"
    METADATA = "Metadata"
    CREATIONPOLICY = "CreationPolicy"
    UPDATEPOLICY = "UpdatePolicy"
    DELETIONPOLICY = "DeletionPolicy"
    UPDATEREPLACEPOLICY = "UpdateReplacePolicy"
    TAGS = "Tags"


class ResourceScanStatus:
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETE = "COMPLETE"
    EXPIRED = "EXPIRED"


class ResourceSignalStatus:
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class ResourceStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    CREATE_COMPLETE = "CREATE_COMPLETE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    DELETE_SKIPPED = "DELETE_SKIPPED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_FAILED = "UPDATE_FAILED"
    UPDATE_COMPLETE = "UPDATE_COMPLETE"
    IMPORT_FAILED = "IMPORT_FAILED"
    IMPORT_COMPLETE = "IMPORT_COMPLETE"
    IMPORT_IN_PROGRESS = "IMPORT_IN_PROGRESS"
    IMPORT_ROLLBACK_IN_PROGRESS = "IMPORT_ROLLBACK_IN_PROGRESS"
    IMPORT_ROLLBACK_FAILED = "IMPORT_ROLLBACK_FAILED"
    IMPORT_ROLLBACK_COMPLETE = "IMPORT_ROLLBACK_COMPLETE"
    EXPORT_FAILED = "EXPORT_FAILED"
    EXPORT_COMPLETE = "EXPORT_COMPLETE"
    EXPORT_IN_PROGRESS = "EXPORT_IN_PROGRESS"
    EXPORT_ROLLBACK_IN_PROGRESS = "EXPORT_ROLLBACK_IN_PROGRESS"
    EXPORT_ROLLBACK_FAILED = "EXPORT_ROLLBACK_FAILED"
    EXPORT_ROLLBACK_COMPLETE = "EXPORT_ROLLBACK_COMPLETE"
    UPDATE_ROLLBACK_IN_PROGRESS = "UPDATE_ROLLBACK_IN_PROGRESS"
    UPDATE_ROLLBACK_COMPLETE = "UPDATE_ROLLBACK_COMPLETE"
    UPDATE_ROLLBACK_FAILED = "UPDATE_ROLLBACK_FAILED"
    ROLLBACK_IN_PROGRESS = "ROLLBACK_IN_PROGRESS"
    ROLLBACK_COMPLETE = "ROLLBACK_COMPLETE"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"


class ScanType:
    FULL = "FULL"
    PARTIAL = "PARTIAL"


class StackDriftDetectionStatus:
    DETECTION_IN_PROGRESS = "DETECTION_IN_PROGRESS"
    DETECTION_FAILED = "DETECTION_FAILED"
    DETECTION_COMPLETE = "DETECTION_COMPLETE"


class StackDriftStatus:
    DRIFTED = "DRIFTED"
    IN_SYNC = "IN_SYNC"
    UNKNOWN = "UNKNOWN"
    NOT_CHECKED = "NOT_CHECKED"


class StackInstanceDetailedStatus:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INOPERABLE = "INOPERABLE"
    SKIPPED_SUSPENDED_ACCOUNT = "SKIPPED_SUSPENDED_ACCOUNT"
    FAILED_IMPORT = "FAILED_IMPORT"


class StackInstanceFilterName:
    DETAILED_STATUS = "DETAILED_STATUS"
    LAST_OPERATION_ID = "LAST_OPERATION_ID"
    DRIFT_STATUS = "DRIFT_STATUS"


class StackInstanceStatus:
    CURRENT = "CURRENT"
    OUTDATED = "OUTDATED"
    INOPERABLE = "INOPERABLE"


class StackRefactorActionEntity:
    RESOURCE = "RESOURCE"
    STACK = "STACK"


class StackRefactorActionType:
    MOVE = "MOVE"
    CREATE = "CREATE"


class StackRefactorDetection:
    AUTO = "AUTO"
    MANUAL = "MANUAL"


class StackRefactorExecutionStatus:
    UNAVAILABLE = "UNAVAILABLE"
    AVAILABLE = "AVAILABLE"
    OBSOLETE = "OBSOLETE"
    EXECUTE_IN_PROGRESS = "EXECUTE_IN_PROGRESS"
    EXECUTE_COMPLETE = "EXECUTE_COMPLETE"
    EXECUTE_FAILED = "EXECUTE_FAILED"
    ROLLBACK_IN_PROGRESS = "ROLLBACK_IN_PROGRESS"
    ROLLBACK_COMPLETE = "ROLLBACK_COMPLETE"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"


class StackRefactorStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_COMPLETE = "CREATE_COMPLETE"
    CREATE_FAILED = "CREATE_FAILED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    DELETE_FAILED = "DELETE_FAILED"


class StackResourceDriftStatus:
    IN_SYNC = "IN_SYNC"
    MODIFIED = "MODIFIED"
    DELETED = "DELETED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"


class StackSetDriftDetectionStatus:
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    IN_PROGRESS = "IN_PROGRESS"
    STOPPED = "STOPPED"


class StackSetDriftStatus:
    DRIFTED = "DRIFTED"
    IN_SYNC = "IN_SYNC"
    NOT_CHECKED = "NOT_CHECKED"


class StackSetOperationAction:
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    DETECT_DRIFT = "DETECT_DRIFT"


class StackSetOperationResultStatus:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StackSetOperationStatus:
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    QUEUED = "QUEUED"


class StackSetStatus:
    ACTIVE = "ACTIVE"
    DELETED = "DELETED"


class StackStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    CREATE_COMPLETE = "CREATE_COMPLETE"
    ROLLBACK_IN_PROGRESS = "ROLLBACK_IN_PROGRESS"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    ROLLBACK_COMPLETE = "ROLLBACK_COMPLETE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS = "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS"
    UPDATE_COMPLETE = "UPDATE_COMPLETE"
    UPDATE_FAILED = "UPDATE_FAILED"
    UPDATE_ROLLBACK_IN_PROGRESS = "UPDATE_ROLLBACK_IN_PROGRESS"
    UPDATE_ROLLBACK_FAILED = "UPDATE_ROLLBACK_FAILED"
    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS = (
        "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"
    )
    UPDATE_ROLLBACK_COMPLETE = "UPDATE_ROLLBACK_COMPLETE"
    REVIEW_IN_PROGRESS = "REVIEW_IN_PROGRESS"
    IMPORT_IN_PROGRESS = "IMPORT_IN_PROGRESS"
    IMPORT_COMPLETE = "IMPORT_COMPLETE"
    IMPORT_ROLLBACK_IN_PROGRESS = "IMPORT_ROLLBACK_IN_PROGRESS"
    IMPORT_ROLLBACK_FAILED = "IMPORT_ROLLBACK_FAILED"
    IMPORT_ROLLBACK_COMPLETE = "IMPORT_ROLLBACK_COMPLETE"


class TemplateFormat:
    JSON = "JSON"
    YAML = "YAML"


class TemplateStage:
    ORIGINAL = "Original"
    PROCESSED = "Processed"


class ThirdPartyType:
    RESOURCE = "RESOURCE"
    MODULE = "MODULE"
    HOOK = "HOOK"


class TypeTestsStatus:
    PASSED = "PASSED"
    FAILED = "FAILED"
    IN_PROGRESS = "IN_PROGRESS"
    NOT_TESTED = "NOT_TESTED"


class ValidationStatus:
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class VersionBump:
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class Visibility:
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"


class WarningType:
    MUTUALLY_EXCLUSIVE_PROPERTIES = "MUTUALLY_EXCLUSIVE_PROPERTIES"
    UNSUPPORTED_PROPERTIES = "UNSUPPORTED_PROPERTIES"
    MUTUALLY_EXCLUSIVE_TYPES = "MUTUALLY_EXCLUSIVE_TYPES"
    EXCLUDED_PROPERTIES = "EXCLUDED_PROPERTIES"
    EXCLUDED_RESOURCES = "EXCLUDED_RESOURCES"


# PropertyType submodules
from . import GuardHook as _GuardHook
from . import HookVersion as _HookVersion
from . import LambdaHook as _LambdaHook
from . import ResourceVersion as _ResourceVersion
from . import StackSet as _StackSet
from . import TypeActivation as _TypeActivation


# Resources
# ============================================================


@dataclass
class CustomResource(CloudFormationResource):
    """CustomResource resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html

    CloudFormation type: AWS::CloudFormation::CustomResource
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::CustomResource"

    service_token: str | None = None
    service_timeout: int | None = None


@dataclass
class GuardHook(CloudFormationResource):
    """GuardHook resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-guardhook.html

    CloudFormation type: AWS::CloudFormation::GuardHook
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::GuardHook"

    alias: str | None = None
    execution_role: str | None = None
    failure_mode: str | None = None
    hook_status: str | None = None
    rule_location: _GuardHook.S3Location | None = None
    target_operations: list[String] = field(default_factory=list)
    log_bucket: str | None = None
    options: _GuardHook.Options | None = None
    stack_filters: _GuardHook.StackFilters | None = None
    target_filters: _GuardHook.TargetFilters | None = None

    # GetAtt attributes
    HOOKARN: ClassVar[str] = "HookArn"


@dataclass
class HookDefaultVersion(CloudFormationResource):
    """HookDefaultVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-hookdefaultversion.html

    CloudFormation type: AWS::CloudFormation::HookDefaultVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::HookDefaultVersion"

    type_name: str | None = None
    type_version_arn: str | None = None
    version_id: str | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class HookTypeConfig(CloudFormationResource):
    """HookTypeConfig resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-hooktypeconfig.html

    CloudFormation type: AWS::CloudFormation::HookTypeConfig
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::HookTypeConfig"

    configuration: str | None = None
    configuration_alias: str | None = None
    type_arn: str | None = None
    type_name: str | None = None

    # GetAtt attributes
    CONFIGURATIONARN: ClassVar[str] = "ConfigurationArn"


@dataclass
class HookVersion(CloudFormationResource):
    """HookVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-hookversion.html

    CloudFormation type: AWS::CloudFormation::HookVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::HookVersion"

    schema_handler_package: str | None = None
    type_name: str | None = None
    execution_role_arn: str | None = None
    logging_config: _HookVersion.LoggingConfig | None = None

    # GetAtt attributes
    VERSIONID: ClassVar[str] = "VersionId"
    ISDEFAULTVERSION: ClassVar[str] = "IsDefaultVersion"
    VISIBILITY: ClassVar[str] = "Visibility"
    ARN: ClassVar[str] = "Arn"
    TYPEARN: ClassVar[str] = "TypeArn"


@dataclass
class LambdaHook(CloudFormationResource):
    """LambdaHook resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-lambdahook.html

    CloudFormation type: AWS::CloudFormation::LambdaHook
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::LambdaHook"

    alias: str | None = None
    execution_role: str | None = None
    failure_mode: str | None = None
    hook_status: str | None = None
    lambda_function: str | None = None
    target_operations: list[String] = field(default_factory=list)
    stack_filters: _LambdaHook.StackFilters | None = None
    target_filters: _LambdaHook.TargetFilters | None = None

    # GetAtt attributes
    HOOKARN: ClassVar[str] = "HookArn"


@dataclass
class Macro(CloudFormationResource):
    """Macro resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-macro.html

    CloudFormation type: AWS::CloudFormation::Macro
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::Macro"
    _property_mappings: ClassVar[dict[str, str]] = {
        "log_role_arn": "LogRoleARN",
    }

    function_name: str | None = None
    name: str | None = None
    description: str | None = None
    log_group_name: str | None = None
    log_role_arn: str | None = None


@dataclass
class ModuleDefaultVersion(CloudFormationResource):
    """ModuleDefaultVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-moduledefaultversion.html

    CloudFormation type: AWS::CloudFormation::ModuleDefaultVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::ModuleDefaultVersion"

    arn: str | None = None
    module_name: str | None = None
    version_id: str | None = None


@dataclass
class ModuleVersion(CloudFormationResource):
    """ModuleVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-moduleversion.html

    CloudFormation type: AWS::CloudFormation::ModuleVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::ModuleVersion"

    module_name: str | None = None
    module_package: str | None = None

    # GetAtt attributes
    TIMECREATED: ClassVar[str] = "TimeCreated"
    VERSIONID: ClassVar[str] = "VersionId"
    DESCRIPTION: ClassVar[str] = "Description"
    SCHEMA: ClassVar[str] = "Schema"
    ISDEFAULTVERSION: ClassVar[str] = "IsDefaultVersion"
    VISIBILITY: ClassVar[str] = "Visibility"
    ARN: ClassVar[str] = "Arn"
    DOCUMENTATIONURL: ClassVar[str] = "DocumentationUrl"


@dataclass
class PublicTypeVersion(CloudFormationResource):
    """PublicTypeVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-publictypeversion.html

    CloudFormation type: AWS::CloudFormation::PublicTypeVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::PublicTypeVersion"

    arn: str | None = None
    log_delivery_bucket: str | None = None
    public_version_number: str | None = None
    type_: str | None = None
    type_name: str | None = None

    # GetAtt attributes
    PUBLICTYPEARN: ClassVar[str] = "PublicTypeArn"
    PUBLISHERID: ClassVar[str] = "PublisherId"
    TYPEVERSIONARN: ClassVar[str] = "TypeVersionArn"


@dataclass
class Publisher(CloudFormationResource):
    """Publisher resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-publisher.html

    CloudFormation type: AWS::CloudFormation::Publisher
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::Publisher"

    accept_terms_and_conditions: bool | None = None
    connection_arn: str | None = None

    # GetAtt attributes
    PUBLISHERID: ClassVar[str] = "PublisherId"
    IDENTITYPROVIDER: ClassVar[str] = "IdentityProvider"
    PUBLISHERPROFILE: ClassVar[str] = "PublisherProfile"
    PUBLISHERSTATUS: ClassVar[str] = "PublisherStatus"


@dataclass
class ResourceDefaultVersion(CloudFormationResource):
    """ResourceDefaultVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourcedefaultversion.html

    CloudFormation type: AWS::CloudFormation::ResourceDefaultVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::ResourceDefaultVersion"

    type_name: str | None = None
    type_version_arn: str | None = None
    version_id: str | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class ResourceVersion(CloudFormationResource):
    """ResourceVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourceversion.html

    CloudFormation type: AWS::CloudFormation::ResourceVersion
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::ResourceVersion"

    schema_handler_package: str | None = None
    type_name: str | None = None
    execution_role_arn: str | None = None
    logging_config: _ResourceVersion.LoggingConfig | None = None

    # GetAtt attributes
    VERSIONID: ClassVar[str] = "VersionId"
    PROVISIONINGTYPE: ClassVar[str] = "ProvisioningType"
    ISDEFAULTVERSION: ClassVar[str] = "IsDefaultVersion"
    VISIBILITY: ClassVar[str] = "Visibility"
    ARN: ClassVar[str] = "Arn"
    TYPEARN: ClassVar[str] = "TypeArn"


@dataclass
class Stack(CloudFormationResource):
    """Stack resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

    CloudFormation type: AWS::CloudFormation::Stack
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::Stack"
    _property_mappings: ClassVar[dict[str, str]] = {
        "notification_ar_ns": "NotificationARNs",
        "template_url": "TemplateURL",
    }

    template_url: str | None = None
    notification_ar_ns: list[String] = field(default_factory=list)
    parameters: dict[str, String] = field(default_factory=dict)
    tags: list[Tag] = field(default_factory=list)
    timeout_in_minutes: int | None = None


@dataclass
class StackSet(CloudFormationResource):
    """StackSet resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html

    CloudFormation type: AWS::CloudFormation::StackSet
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::StackSet"
    _property_mappings: ClassVar[dict[str, str]] = {
        "administration_role_arn": "AdministrationRoleARN",
        "template_url": "TemplateURL",
    }

    permission_model: str | None = None
    stack_set_name: str | None = None
    administration_role_arn: str | None = None
    auto_deployment: _StackSet.AutoDeployment | None = None
    call_as: str | None = None
    capabilities: list[String] = field(default_factory=list)
    description: str | None = None
    execution_role_name: str | None = None
    managed_execution: _StackSet.ManagedExecution | None = None
    operation_preferences: _StackSet.OperationPreferences | None = None
    parameters: list[_StackSet.Parameter] = field(default_factory=list)
    stack_instances_group: list[_StackSet.StackInstances] = field(default_factory=list)
    tags: list[Tag] = field(default_factory=list)
    template_body: str | None = None
    template_url: str | None = None

    # GetAtt attributes
    STACKSETID: ClassVar[str] = "StackSetId"


@dataclass
class TypeActivation(CloudFormationResource):
    """TypeActivation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html

    CloudFormation type: AWS::CloudFormation::TypeActivation
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::TypeActivation"

    auto_update: bool | None = None
    execution_role_arn: str | None = None
    logging_config: _TypeActivation.LoggingConfig | None = None
    major_version: str | None = None
    public_type_arn: str | None = None
    publisher_id: str | None = None
    type_: str | None = None
    type_name: str | None = None
    type_name_alias: str | None = None
    version_bump: str | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class WaitCondition(CloudFormationResource):
    """WaitCondition resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html

    CloudFormation type: AWS::CloudFormation::WaitCondition
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::WaitCondition"

    count: int | None = None
    handle: str | None = None
    timeout: str | None = None

    # GetAtt attributes
    DATA: ClassVar[str] = "Data"


@dataclass
class WaitConditionHandle(CloudFormationResource):
    """WaitConditionHandle resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitconditionhandle.html

    CloudFormation type: AWS::CloudFormation::WaitConditionHandle
    """

    _resource_type: ClassVar[str] = "AWS::CloudFormation::WaitConditionHandle"

    pass


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
GuardHook.HookTarget = PropertyTypeDescriptor(_GuardHook.HookTarget, "HookTarget")
GuardHook.Options = PropertyTypeDescriptor(_GuardHook.Options, "Options")
GuardHook.S3Location = PropertyTypeDescriptor(_GuardHook.S3Location, "S3Location")
GuardHook.StackFilters = PropertyTypeDescriptor(_GuardHook.StackFilters, "StackFilters")
GuardHook.StackNames = PropertyTypeDescriptor(_GuardHook.StackNames, "StackNames")
GuardHook.StackRoles = PropertyTypeDescriptor(_GuardHook.StackRoles, "StackRoles")
GuardHook.TargetFilters = PropertyTypeDescriptor(
    _GuardHook.TargetFilters, "TargetFilters"
)
HookVersion.LoggingConfig = PropertyTypeDescriptor(
    _HookVersion.LoggingConfig, "LoggingConfig"
)
LambdaHook.HookTarget = PropertyTypeDescriptor(_LambdaHook.HookTarget, "HookTarget")
LambdaHook.StackFilters = PropertyTypeDescriptor(
    _LambdaHook.StackFilters, "StackFilters"
)
LambdaHook.StackNames = PropertyTypeDescriptor(_LambdaHook.StackNames, "StackNames")
LambdaHook.StackRoles = PropertyTypeDescriptor(_LambdaHook.StackRoles, "StackRoles")
LambdaHook.TargetFilters = PropertyTypeDescriptor(
    _LambdaHook.TargetFilters, "TargetFilters"
)
ResourceVersion.LoggingConfig = PropertyTypeDescriptor(
    _ResourceVersion.LoggingConfig, "LoggingConfig"
)
StackSet.AutoDeployment = PropertyTypeDescriptor(
    _StackSet.AutoDeployment, "AutoDeployment"
)
StackSet.DeploymentTargets = PropertyTypeDescriptor(
    _StackSet.DeploymentTargets, "DeploymentTargets"
)
StackSet.ManagedExecution = PropertyTypeDescriptor(
    _StackSet.ManagedExecution, "ManagedExecution"
)
StackSet.OperationPreferences = PropertyTypeDescriptor(
    _StackSet.OperationPreferences, "OperationPreferences"
)
StackSet.Parameter = PropertyTypeDescriptor(_StackSet.Parameter, "Parameter")
StackSet.StackInstances = PropertyTypeDescriptor(
    _StackSet.StackInstances, "StackInstances"
)
TypeActivation.LoggingConfig = PropertyTypeDescriptor(
    _TypeActivation.LoggingConfig, "LoggingConfig"
)
