"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    Tag,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    Attr,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    RefIntrinsic,
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
    # Condition operator constants
    BOOL,
    STRING_EQUALS,
    STRING_NOT_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_LIKE,
    STRING_NOT_LIKE,
    NUMERIC_EQUALS,
    NUMERIC_NOT_EQUALS,
    NUMERIC_LESS_THAN,
    NUMERIC_LESS_THAN_EQUALS,
    NUMERIC_GREATER_THAN,
    NUMERIC_GREATER_THAN_EQUALS,
    DATE_EQUALS,
    DATE_NOT_EQUALS,
    DATE_LESS_THAN,
    DATE_LESS_THAN_EQUALS,
    DATE_GREATER_THAN,
    DATE_GREATER_THAN_EQUALS,
    IP_ADDRESS,
    NOT_IP_ADDRESS,
    ARN_EQUALS,
    ARN_NOT_EQUALS,
    ARN_LIKE,
    ARN_NOT_LIKE,
    NULL,
    # Loader
    setup_resources,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .params import AppName as AppName
from .security import ObjectStorageReplicationPolicy as ObjectStorageReplicationPolicy
from .security import ObjectStorageReplicationPolicyAllowStatement0 as ObjectStorageReplicationPolicyAllowStatement0
from .security import ObjectStorageReplicationPolicyAllowStatement1 as ObjectStorageReplicationPolicyAllowStatement1
from .security import ObjectStorageReplicationPolicyAllowStatement2 as ObjectStorageReplicationPolicyAllowStatement2
from .security import ObjectStorageReplicationPolicyPolicyDocument as ObjectStorageReplicationPolicyPolicyDocument
from .security import ObjectStorageReplicationRole as ObjectStorageReplicationRole
from .security import ObjectStorageReplicationRoleAllowStatement0 as ObjectStorageReplicationRoleAllowStatement0
from .security import ObjectStorageReplicationRoleAssumeRolePolicyDocument as ObjectStorageReplicationRoleAssumeRolePolicyDocument
from .storage import ObjectStorageBucket as ObjectStorageBucket
from .storage import ObjectStorageBucketBucketEncryption as ObjectStorageBucketBucketEncryption
from .storage import ObjectStorageBucketDeleteMarkerReplication as ObjectStorageBucketDeleteMarkerReplication
from .storage import ObjectStorageBucketLoggingConfiguration as ObjectStorageBucketLoggingConfiguration
from .storage import ObjectStorageBucketPolicyPolicy as ObjectStorageBucketPolicyPolicy
from .storage import ObjectStorageBucketPolicyPolicyAllowStatement1 as ObjectStorageBucketPolicyPolicyAllowStatement1
from .storage import ObjectStorageBucketPolicyPolicyDenyStatement0 as ObjectStorageBucketPolicyPolicyDenyStatement0
from .storage import ObjectStorageBucketPolicyPolicyPolicyDocument as ObjectStorageBucketPolicyPolicyPolicyDocument
from .storage import ObjectStorageBucketPublicAccessBlockConfiguration as ObjectStorageBucketPublicAccessBlockConfiguration
from .storage import ObjectStorageBucketReplicationConfiguration as ObjectStorageBucketReplicationConfiguration
from .storage import ObjectStorageBucketReplicationDestination as ObjectStorageBucketReplicationDestination
from .storage import ObjectStorageBucketReplicationRule as ObjectStorageBucketReplicationRule
from .storage import ObjectStorageBucketServerSideEncryptionByDefault as ObjectStorageBucketServerSideEncryptionByDefault
from .storage import ObjectStorageBucketServerSideEncryptionRule as ObjectStorageBucketServerSideEncryptionRule
from .storage import ObjectStorageLogBucket as ObjectStorageLogBucket
from .storage import ObjectStorageLogBucketBucketEncryption as ObjectStorageLogBucketBucketEncryption
from .storage import ObjectStorageLogBucketDefaultRetention as ObjectStorageLogBucketDefaultRetention
from .storage import ObjectStorageLogBucketDeleteMarkerReplication as ObjectStorageLogBucketDeleteMarkerReplication
from .storage import ObjectStorageLogBucketObjectLockConfiguration as ObjectStorageLogBucketObjectLockConfiguration
from .storage import ObjectStorageLogBucketObjectLockRule as ObjectStorageLogBucketObjectLockRule
from .storage import ObjectStorageLogBucketPolicyPolicy as ObjectStorageLogBucketPolicyPolicy
from .storage import ObjectStorageLogBucketPolicyPolicyAllowStatement1 as ObjectStorageLogBucketPolicyPolicyAllowStatement1
from .storage import ObjectStorageLogBucketPolicyPolicyDenyStatement0 as ObjectStorageLogBucketPolicyPolicyDenyStatement0
from .storage import ObjectStorageLogBucketPolicyPolicyPolicyDocument as ObjectStorageLogBucketPolicyPolicyPolicyDocument
from .storage import ObjectStorageLogBucketPublicAccessBlockConfiguration as ObjectStorageLogBucketPublicAccessBlockConfiguration
from .storage import ObjectStorageLogBucketServerSideEncryptionByDefault as ObjectStorageLogBucketServerSideEncryptionByDefault
from .storage import ObjectStorageLogBucketServerSideEncryptionRule as ObjectStorageLogBucketServerSideEncryptionRule
from .storage import ObjectStorageReplicaBucket as ObjectStorageReplicaBucket
from .storage import ObjectStorageReplicaBucketBucketEncryption as ObjectStorageReplicaBucketBucketEncryption
from .storage import ObjectStorageReplicaBucketDeleteMarkerReplication as ObjectStorageReplicaBucketDeleteMarkerReplication
from .storage import ObjectStorageReplicaBucketPolicyPolicy as ObjectStorageReplicaBucketPolicyPolicy
from .storage import ObjectStorageReplicaBucketPolicyPolicyAllowStatement1 as ObjectStorageReplicaBucketPolicyPolicyAllowStatement1
from .storage import ObjectStorageReplicaBucketPolicyPolicyDenyStatement0 as ObjectStorageReplicaBucketPolicyPolicyDenyStatement0
from .storage import ObjectStorageReplicaBucketPolicyPolicyPolicyDocument as ObjectStorageReplicaBucketPolicyPolicyPolicyDocument
from .storage import ObjectStorageReplicaBucketPublicAccessBlockConfiguration as ObjectStorageReplicaBucketPublicAccessBlockConfiguration
from .storage import ObjectStorageReplicaBucketServerSideEncryptionByDefault as ObjectStorageReplicaBucketServerSideEncryptionByDefault
from .storage import ObjectStorageReplicaBucketServerSideEncryptionRule as ObjectStorageReplicaBucketServerSideEncryptionRule

__all__: list[str] = ['AMI_ID', 'ARN', 'ARN_EQUALS', 'ARN_LIKE', 'ARN_NOT_EQUALS', 'ARN_NOT_LIKE', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'AppName', 'Attr', 'BOOL', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'DATE_EQUALS', 'DATE_GREATER_THAN', 'DATE_GREATER_THAN_EQUALS', 'DATE_LESS_THAN', 'DATE_LESS_THAN_EQUALS', 'DATE_NOT_EQUALS', 'DenyStatement', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'IP_ADDRESS', 'If', 'ImportValue', 'Join', 'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NOT_IP_ADDRESS', 'NULL', 'NUMBER', 'NUMERIC_EQUALS', 'NUMERIC_GREATER_THAN', 'NUMERIC_GREATER_THAN_EQUALS', 'NUMERIC_LESS_THAN', 'NUMERIC_LESS_THAN_EQUALS', 'NUMERIC_NOT_EQUALS', 'Not', 'ObjectStorageBucket', 'ObjectStorageBucketBucketEncryption', 'ObjectStorageBucketDeleteMarkerReplication', 'ObjectStorageBucketLoggingConfiguration', 'ObjectStorageBucketPolicyPolicy', 'ObjectStorageBucketPolicyPolicyAllowStatement1', 'ObjectStorageBucketPolicyPolicyDenyStatement0', 'ObjectStorageBucketPolicyPolicyPolicyDocument', 'ObjectStorageBucketPublicAccessBlockConfiguration', 'ObjectStorageBucketReplicationConfiguration', 'ObjectStorageBucketReplicationDestination', 'ObjectStorageBucketReplicationRule', 'ObjectStorageBucketServerSideEncryptionByDefault', 'ObjectStorageBucketServerSideEncryptionRule', 'ObjectStorageLogBucket', 'ObjectStorageLogBucketBucketEncryption', 'ObjectStorageLogBucketDefaultRetention', 'ObjectStorageLogBucketDeleteMarkerReplication', 'ObjectStorageLogBucketObjectLockConfiguration', 'ObjectStorageLogBucketObjectLockRule', 'ObjectStorageLogBucketPolicyPolicy', 'ObjectStorageLogBucketPolicyPolicyAllowStatement1', 'ObjectStorageLogBucketPolicyPolicyDenyStatement0', 'ObjectStorageLogBucketPolicyPolicyPolicyDocument', 'ObjectStorageLogBucketPublicAccessBlockConfiguration', 'ObjectStorageLogBucketServerSideEncryptionByDefault', 'ObjectStorageLogBucketServerSideEncryptionRule', 'ObjectStorageReplicaBucket', 'ObjectStorageReplicaBucketBucketEncryption', 'ObjectStorageReplicaBucketDeleteMarkerReplication', 'ObjectStorageReplicaBucketPolicyPolicy', 'ObjectStorageReplicaBucketPolicyPolicyAllowStatement1', 'ObjectStorageReplicaBucketPolicyPolicyDenyStatement0', 'ObjectStorageReplicaBucketPolicyPolicyPolicyDocument', 'ObjectStorageReplicaBucketPublicAccessBlockConfiguration', 'ObjectStorageReplicaBucketServerSideEncryptionByDefault', 'ObjectStorageReplicaBucketServerSideEncryptionRule', 'ObjectStorageReplicationPolicy', 'ObjectStorageReplicationPolicyAllowStatement0', 'ObjectStorageReplicationPolicyAllowStatement1', 'ObjectStorageReplicationPolicyAllowStatement2', 'ObjectStorageReplicationPolicyPolicyDocument', 'ObjectStorageReplicationRole', 'ObjectStorageReplicationRoleAllowStatement0', 'ObjectStorageReplicationRoleAssumeRolePolicyDocument', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType', 'Ref', 'RefDict', 'RefIntrinsic', 'RefList', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'STRING_EQUALS', 'STRING_EQUALS_IGNORE_CASE', 'STRING_LIKE', 'STRING_NOT_EQUALS', 'STRING_NOT_EQUALS_IGNORE_CASE', 'STRING_NOT_LIKE', 'SUBNET_ID', 'Select', 'Split', 'Sub', 'Tag', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
