"""
AWS SHIELD CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:26Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class ApplicationLayerAutomaticResponseStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AttackLayer:
    NETWORK = "NETWORK"
    APPLICATION = "APPLICATION"


class AttackPropertyIdentifier:
    DESTINATION_URL = "DESTINATION_URL"
    REFERRER = "REFERRER"
    SOURCE_ASN = "SOURCE_ASN"
    SOURCE_COUNTRY = "SOURCE_COUNTRY"
    SOURCE_IP_ADDRESS = "SOURCE_IP_ADDRESS"
    SOURCE_USER_AGENT = "SOURCE_USER_AGENT"
    WORDPRESS_PINGBACK_REFLECTOR = "WORDPRESS_PINGBACK_REFLECTOR"
    WORDPRESS_PINGBACK_SOURCE = "WORDPRESS_PINGBACK_SOURCE"


class AutoRenew:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ProactiveEngagementStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    PENDING = "PENDING"


class ProtectedResourceType:
    CLOUDFRONT_DISTRIBUTION = "CLOUDFRONT_DISTRIBUTION"
    ROUTE_53_HOSTED_ZONE = "ROUTE_53_HOSTED_ZONE"
    ELASTIC_IP_ALLOCATION = "ELASTIC_IP_ALLOCATION"
    CLASSIC_LOAD_BALANCER = "CLASSIC_LOAD_BALANCER"
    APPLICATION_LOAD_BALANCER = "APPLICATION_LOAD_BALANCER"
    GLOBAL_ACCELERATOR = "GLOBAL_ACCELERATOR"


class ProtectionGroupAggregation:
    SUM = "SUM"
    MEAN = "MEAN"
    MAX = "MAX"


class ProtectionGroupPattern:
    ALL = "ALL"
    ARBITRARY = "ARBITRARY"
    BY_RESOURCE_TYPE = "BY_RESOURCE_TYPE"


class SubResourceType:
    IP = "IP"
    URL = "URL"


class SubscriptionState:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class Unit:
    BITS = "BITS"
    BYTES = "BYTES"
    PACKETS = "PACKETS"
    REQUESTS = "REQUESTS"


class ValidationExceptionReason:
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED"
    OTHER = "OTHER"


# PropertyType submodules
from . import ProactiveEngagement as _ProactiveEngagement
from . import Protection as _Protection


# Resources
# ============================================================


@dataclass
class DRTAccess(CloudFormationResource):
    """DRTAccess resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shield-drtaccess.html

    CloudFormation type: AWS::Shield::DRTAccess
    """

    _resource_type: ClassVar[str] = "AWS::Shield::DRTAccess"

    role_arn: str | None = None
    log_bucket_list: list[String] = field(default_factory=list)

    # GetAtt attributes
    ACCOUNTID: ClassVar[str] = "AccountId"


@dataclass
class ProactiveEngagement(CloudFormationResource):
    """ProactiveEngagement resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shield-proactiveengagement.html

    CloudFormation type: AWS::Shield::ProactiveEngagement
    """

    _resource_type: ClassVar[str] = "AWS::Shield::ProactiveEngagement"

    emergency_contact_list: list[_ProactiveEngagement.EmergencyContact] = field(
        default_factory=list
    )
    proactive_engagement_status: str | None = None

    # GetAtt attributes
    ACCOUNTID: ClassVar[str] = "AccountId"


@dataclass
class Protection(CloudFormationResource):
    """Protection resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shield-protection.html

    CloudFormation type: AWS::Shield::Protection
    """

    _resource_type: ClassVar[str] = "AWS::Shield::Protection"

    name: str | None = None
    resource_arn: str | None = None
    application_layer_automatic_response_configuration: (
        _Protection.ApplicationLayerAutomaticResponseConfiguration | None
    ) = None
    health_check_arns: list[String] = field(default_factory=list)
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    PROTECTIONARN: ClassVar[str] = "ProtectionArn"
    PROTECTIONID: ClassVar[str] = "ProtectionId"


@dataclass
class ProtectionGroup(CloudFormationResource):
    """ProtectionGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-shield-protectiongroup.html

    CloudFormation type: AWS::Shield::ProtectionGroup
    """

    _resource_type: ClassVar[str] = "AWS::Shield::ProtectionGroup"

    aggregation: str | None = None
    pattern: str | None = None
    protection_group_id: str | None = None
    members: list[String] = field(default_factory=list)
    resource_type: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    PROTECTIONGROUPARN: ClassVar[str] = "ProtectionGroupArn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
ProactiveEngagement.EmergencyContact = PropertyTypeDescriptor(
    _ProactiveEngagement.EmergencyContact, "EmergencyContact"
)
Protection.Action = PropertyTypeDescriptor(_Protection.Action, "Action")
Protection.ApplicationLayerAutomaticResponseConfiguration = PropertyTypeDescriptor(
    _Protection.ApplicationLayerAutomaticResponseConfiguration,
    "ApplicationLayerAutomaticResponseConfiguration",
)
