"""
AWS WISDOM CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:25Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class AssistantStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    ACTIVE = "ACTIVE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETED = "DELETED"


class AssistantType:
    AGENT = "AGENT"


class AssociationType:
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"


class ContentStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    ACTIVE = "ACTIVE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETED = "DELETED"
    UPDATE_FAILED = "UPDATE_FAILED"


class ExternalSource:
    AMAZON_CONNECT = "AMAZON_CONNECT"


class FilterField:
    NAME = "NAME"


class FilterOperator:
    EQUALS = "EQUALS"


class ImportJobStatus:
    START_IN_PROGRESS = "START_IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETE = "COMPLETE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETED = "DELETED"


class ImportJobType:
    QUICK_RESPONSES = "QUICK_RESPONSES"


class KnowledgeBaseStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    ACTIVE = "ACTIVE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETED = "DELETED"


class KnowledgeBaseType:
    EXTERNAL = "EXTERNAL"
    CUSTOM = "CUSTOM"
    QUICK_RESPONSES = "QUICK_RESPONSES"


class Order:
    ASC = "ASC"
    DESC = "DESC"


class Priority:
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class QuickResponseFilterOperator:
    EQUALS = "EQUALS"
    PREFIX = "PREFIX"


class QuickResponseQueryOperator:
    CONTAINS = "CONTAINS"
    CONTAINS_AND_PREFIX = "CONTAINS_AND_PREFIX"


class QuickResponseStatus:
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    CREATED = "CREATED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETED = "DELETED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_FAILED = "UPDATE_FAILED"


class RecommendationSourceType:
    ISSUE_DETECTION = "ISSUE_DETECTION"
    RULE_EVALUATION = "RULE_EVALUATION"
    OTHER = "OTHER"


class RecommendationTriggerType:
    QUERY = "QUERY"


class RecommendationType:
    KNOWLEDGE_CONTENT = "KNOWLEDGE_CONTENT"


class RelevanceLevel:
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


# PropertyType submodules
from . import AIAgent as _AIAgent
from . import AIGuardrail as _AIGuardrail
from . import AIPrompt as _AIPrompt
from . import Assistant as _Assistant
from . import AssistantAssociation as _AssistantAssociation
from . import KnowledgeBase as _KnowledgeBase
from . import MessageTemplate as _MessageTemplate
from . import QuickResponse as _QuickResponse


# Resources
# ============================================================


@dataclass
class AIAgent(CloudFormationResource):
    """AIAgent resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aiagent.html

    CloudFormation type: AWS::Wisdom::AIAgent
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIAgent"

    assistant_id: DslValue[str] | None = None
    configuration: DslValue[_AIAgent.AIAgentConfiguration] | None = None
    type_: DslValue[str] | None = None
    description: DslValue[str] | None = None
    name: DslValue[str] | None = None
    tags: dict[str, DslValue[str]] = field(default_factory=dict)

    # GetAtt attributes
    AIAGENTARN: ClassVar[str] = "AIAgentArn"
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    AIAGENTID: ClassVar[str] = "AIAgentId"
    MODIFIEDTIMESECONDS: ClassVar[str] = "ModifiedTimeSeconds"

    # PropertyType descriptors for nested GetAtt support
    AIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.AIAgentConfiguration, "AIAgentConfiguration"
    )
    AnswerRecommendationAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.AnswerRecommendationAIAgentConfiguration,
        "AnswerRecommendationAIAgentConfiguration",
    )
    AssociationConfiguration = PropertyTypeDescriptor(
        _AIAgent.AssociationConfiguration, "AssociationConfiguration"
    )
    AssociationConfigurationData = PropertyTypeDescriptor(
        _AIAgent.AssociationConfigurationData, "AssociationConfigurationData"
    )
    EmailGenerativeAnswerAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.EmailGenerativeAnswerAIAgentConfiguration,
        "EmailGenerativeAnswerAIAgentConfiguration",
    )
    EmailOverviewAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.EmailOverviewAIAgentConfiguration, "EmailOverviewAIAgentConfiguration"
    )
    EmailResponseAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.EmailResponseAIAgentConfiguration, "EmailResponseAIAgentConfiguration"
    )
    KnowledgeBaseAssociationConfigurationData = PropertyTypeDescriptor(
        _AIAgent.KnowledgeBaseAssociationConfigurationData,
        "KnowledgeBaseAssociationConfigurationData",
    )
    ManualSearchAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.ManualSearchAIAgentConfiguration, "ManualSearchAIAgentConfiguration"
    )
    OrCondition = PropertyTypeDescriptor(_AIAgent.OrCondition, "OrCondition")
    SelfServiceAIAgentConfiguration = PropertyTypeDescriptor(
        _AIAgent.SelfServiceAIAgentConfiguration, "SelfServiceAIAgentConfiguration"
    )
    TagCondition = PropertyTypeDescriptor(_AIAgent.TagCondition, "TagCondition")
    TagFilter = PropertyTypeDescriptor(_AIAgent.TagFilter, "TagFilter")


@dataclass
class AIAgentVersion(CloudFormationResource):
    """AIAgentVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aiagentversion.html

    CloudFormation type: AWS::Wisdom::AIAgentVersion
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIAgentVersion"
    _property_mappings: ClassVar[dict[str, str]] = {
        "ai_agent_id": "AIAgentId",
    }

    ai_agent_id: DslValue[str] | None = None
    assistant_id: DslValue[str] | None = None
    modified_time_seconds: DslValue[float] | None = None

    # GetAtt attributes
    AIAGENTARN: ClassVar[str] = "AIAgentArn"
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    AIAGENTVERSIONID: ClassVar[str] = "AIAgentVersionId"
    VERSIONNUMBER: ClassVar[str] = "VersionNumber"


@dataclass
class AIGuardrail(CloudFormationResource):
    """AIGuardrail resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aiguardrail.html

    CloudFormation type: AWS::Wisdom::AIGuardrail
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIGuardrail"

    assistant_id: DslValue[str] | None = None
    blocked_input_messaging: DslValue[str] | None = None
    blocked_outputs_messaging: DslValue[str] | None = None
    content_policy_config: (
        DslValue[_AIGuardrail.AIGuardrailContentPolicyConfig] | None
    ) = None
    contextual_grounding_policy_config: (
        DslValue[_AIGuardrail.AIGuardrailContextualGroundingPolicyConfig] | None
    ) = None
    description: DslValue[str] | None = None
    name: DslValue[str] | None = None
    sensitive_information_policy_config: (
        DslValue[_AIGuardrail.AIGuardrailSensitiveInformationPolicyConfig] | None
    ) = None
    tags: dict[str, DslValue[str]] = field(default_factory=dict)
    topic_policy_config: DslValue[_AIGuardrail.AIGuardrailTopicPolicyConfig] | None = (
        None
    )
    word_policy_config: DslValue[_AIGuardrail.AIGuardrailWordPolicyConfig] | None = None

    # GetAtt attributes
    AIGUARDRAILID: ClassVar[str] = "AIGuardrailId"
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    AIGUARDRAILARN: ClassVar[str] = "AIGuardrailArn"

    # PropertyType descriptors for nested GetAtt support
    AIGuardrailContentPolicyConfig = PropertyTypeDescriptor(
        _AIGuardrail.AIGuardrailContentPolicyConfig, "AIGuardrailContentPolicyConfig"
    )
    AIGuardrailContextualGroundingPolicyConfig = PropertyTypeDescriptor(
        _AIGuardrail.AIGuardrailContextualGroundingPolicyConfig,
        "AIGuardrailContextualGroundingPolicyConfig",
    )
    AIGuardrailSensitiveInformationPolicyConfig = PropertyTypeDescriptor(
        _AIGuardrail.AIGuardrailSensitiveInformationPolicyConfig,
        "AIGuardrailSensitiveInformationPolicyConfig",
    )
    AIGuardrailTopicPolicyConfig = PropertyTypeDescriptor(
        _AIGuardrail.AIGuardrailTopicPolicyConfig, "AIGuardrailTopicPolicyConfig"
    )
    AIGuardrailWordPolicyConfig = PropertyTypeDescriptor(
        _AIGuardrail.AIGuardrailWordPolicyConfig, "AIGuardrailWordPolicyConfig"
    )
    GuardrailContentFilterConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailContentFilterConfig, "GuardrailContentFilterConfig"
    )
    GuardrailContextualGroundingFilterConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailContextualGroundingFilterConfig,
        "GuardrailContextualGroundingFilterConfig",
    )
    GuardrailManagedWordsConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailManagedWordsConfig, "GuardrailManagedWordsConfig"
    )
    GuardrailPiiEntityConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailPiiEntityConfig, "GuardrailPiiEntityConfig"
    )
    GuardrailRegexConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailRegexConfig, "GuardrailRegexConfig"
    )
    GuardrailTopicConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailTopicConfig, "GuardrailTopicConfig"
    )
    GuardrailWordConfig = PropertyTypeDescriptor(
        _AIGuardrail.GuardrailWordConfig, "GuardrailWordConfig"
    )


@dataclass
class AIGuardrailVersion(CloudFormationResource):
    """AIGuardrailVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aiguardrailversion.html

    CloudFormation type: AWS::Wisdom::AIGuardrailVersion
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIGuardrailVersion"
    _property_mappings: ClassVar[dict[str, str]] = {
        "ai_guardrail_id": "AIGuardrailId",
    }

    ai_guardrail_id: DslValue[str] | None = None
    assistant_id: DslValue[str] | None = None
    modified_time_seconds: DslValue[float] | None = None

    # GetAtt attributes
    AIGUARDRAILVERSIONID: ClassVar[str] = "AIGuardrailVersionId"
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    AIGUARDRAILARN: ClassVar[str] = "AIGuardrailArn"
    VERSIONNUMBER: ClassVar[str] = "VersionNumber"


@dataclass
class AIPrompt(CloudFormationResource):
    """AIPrompt resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aiprompt.html

    CloudFormation type: AWS::Wisdom::AIPrompt
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIPrompt"

    api_format: DslValue[str] | None = None
    model_id: DslValue[str] | None = None
    template_configuration: DslValue[_AIPrompt.AIPromptTemplateConfiguration] | None = (
        None
    )
    template_type: DslValue[str] | None = None
    type_: DslValue[str] | None = None
    assistant_id: DslValue[str] | None = None
    description: DslValue[str] | None = None
    name: DslValue[str] | None = None
    tags: dict[str, DslValue[str]] = field(default_factory=dict)

    # GetAtt attributes
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    MODIFIEDTIMESECONDS: ClassVar[str] = "ModifiedTimeSeconds"
    AIPROMPTID: ClassVar[str] = "AIPromptId"
    AIPROMPTARN: ClassVar[str] = "AIPromptArn"

    # PropertyType descriptors for nested GetAtt support
    AIPromptTemplateConfiguration = PropertyTypeDescriptor(
        _AIPrompt.AIPromptTemplateConfiguration, "AIPromptTemplateConfiguration"
    )
    TextFullAIPromptEditTemplateConfiguration = PropertyTypeDescriptor(
        _AIPrompt.TextFullAIPromptEditTemplateConfiguration,
        "TextFullAIPromptEditTemplateConfiguration",
    )


@dataclass
class AIPromptVersion(CloudFormationResource):
    """AIPromptVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-aipromptversion.html

    CloudFormation type: AWS::Wisdom::AIPromptVersion
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AIPromptVersion"
    _property_mappings: ClassVar[dict[str, str]] = {
        "ai_prompt_id": "AIPromptId",
    }

    ai_prompt_id: DslValue[str] | None = None
    assistant_id: DslValue[str] | None = None
    modified_time_seconds: DslValue[float] | None = None

    # GetAtt attributes
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    AIPROMPTVERSIONID: ClassVar[str] = "AIPromptVersionId"
    AIPROMPTARN: ClassVar[str] = "AIPromptArn"
    VERSIONNUMBER: ClassVar[str] = "VersionNumber"


@dataclass
class Assistant(CloudFormationResource):
    """Assistant resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-assistant.html

    CloudFormation type: AWS::Wisdom::Assistant
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::Assistant"

    name: DslValue[str] | None = None
    type_: DslValue[str] | None = None
    description: DslValue[str] | None = None
    server_side_encryption_configuration: (
        DslValue[_Assistant.ServerSideEncryptionConfiguration] | None
    ) = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    ASSISTANTID: ClassVar[str] = "AssistantId"

    # PropertyType descriptors for nested GetAtt support
    ServerSideEncryptionConfiguration = PropertyTypeDescriptor(
        _Assistant.ServerSideEncryptionConfiguration,
        "ServerSideEncryptionConfiguration",
    )


@dataclass
class AssistantAssociation(CloudFormationResource):
    """AssistantAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-assistantassociation.html

    CloudFormation type: AWS::Wisdom::AssistantAssociation
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::AssistantAssociation"

    assistant_id: DslValue[str] | None = None
    association: DslValue[_AssistantAssociation.AssociationData] | None = None
    association_type: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ASSISTANTASSOCIATIONARN: ClassVar[str] = "AssistantAssociationArn"
    ASSISTANTARN: ClassVar[str] = "AssistantArn"
    ASSISTANTASSOCIATIONID: ClassVar[str] = "AssistantAssociationId"

    # PropertyType descriptors for nested GetAtt support
    AssociationData = PropertyTypeDescriptor(
        _AssistantAssociation.AssociationData, "AssociationData"
    )
    ExternalBedrockKnowledgeBaseConfig = PropertyTypeDescriptor(
        _AssistantAssociation.ExternalBedrockKnowledgeBaseConfig,
        "ExternalBedrockKnowledgeBaseConfig",
    )


@dataclass
class KnowledgeBase(CloudFormationResource):
    """KnowledgeBase resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-knowledgebase.html

    CloudFormation type: AWS::Wisdom::KnowledgeBase
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::KnowledgeBase"

    knowledge_base_type: DslValue[str] | None = None
    name: DslValue[str] | None = None
    description: DslValue[str] | None = None
    rendering_configuration: DslValue[_KnowledgeBase.RenderingConfiguration] | None = (
        None
    )
    server_side_encryption_configuration: (
        DslValue[_KnowledgeBase.ServerSideEncryptionConfiguration] | None
    ) = None
    source_configuration: DslValue[_KnowledgeBase.SourceConfiguration] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    vector_ingestion_configuration: (
        DslValue[_KnowledgeBase.VectorIngestionConfiguration] | None
    ) = None

    # GetAtt attributes
    KNOWLEDGEBASEARN: ClassVar[str] = "KnowledgeBaseArn"
    KNOWLEDGEBASEID: ClassVar[str] = "KnowledgeBaseId"

    # PropertyType descriptors for nested GetAtt support
    AppIntegrationsConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.AppIntegrationsConfiguration, "AppIntegrationsConfiguration"
    )
    BedrockFoundationModelConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.BedrockFoundationModelConfiguration,
        "BedrockFoundationModelConfiguration",
    )
    ChunkingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.ChunkingConfiguration, "ChunkingConfiguration"
    )
    CrawlerLimits = PropertyTypeDescriptor(
        _KnowledgeBase.CrawlerLimits, "CrawlerLimits"
    )
    FixedSizeChunkingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.FixedSizeChunkingConfiguration, "FixedSizeChunkingConfiguration"
    )
    HierarchicalChunkingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.HierarchicalChunkingConfiguration,
        "HierarchicalChunkingConfiguration",
    )
    HierarchicalChunkingLevelConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.HierarchicalChunkingLevelConfiguration,
        "HierarchicalChunkingLevelConfiguration",
    )
    ManagedSourceConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.ManagedSourceConfiguration, "ManagedSourceConfiguration"
    )
    ParsingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.ParsingConfiguration, "ParsingConfiguration"
    )
    ParsingPrompt = PropertyTypeDescriptor(
        _KnowledgeBase.ParsingPrompt, "ParsingPrompt"
    )
    RenderingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.RenderingConfiguration, "RenderingConfiguration"
    )
    SeedUrl = PropertyTypeDescriptor(_KnowledgeBase.SeedUrl, "SeedUrl")
    SemanticChunkingConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.SemanticChunkingConfiguration, "SemanticChunkingConfiguration"
    )
    ServerSideEncryptionConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.ServerSideEncryptionConfiguration,
        "ServerSideEncryptionConfiguration",
    )
    SourceConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.SourceConfiguration, "SourceConfiguration"
    )
    UrlConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.UrlConfiguration, "UrlConfiguration"
    )
    VectorIngestionConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.VectorIngestionConfiguration, "VectorIngestionConfiguration"
    )
    WebCrawlerConfiguration = PropertyTypeDescriptor(
        _KnowledgeBase.WebCrawlerConfiguration, "WebCrawlerConfiguration"
    )


@dataclass
class MessageTemplate(CloudFormationResource):
    """MessageTemplate resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-messagetemplate.html

    CloudFormation type: AWS::Wisdom::MessageTemplate
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::MessageTemplate"

    channel_subtype: DslValue[str] | None = None
    content: DslValue[_MessageTemplate.Content] | None = None
    knowledge_base_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    default_attributes: DslValue[_MessageTemplate.MessageTemplateAttributes] | None = (
        None
    )
    description: DslValue[str] | None = None
    grouping_configuration: DslValue[_MessageTemplate.GroupingConfiguration] | None = (
        None
    )
    language: DslValue[str] | None = None
    message_template_attachments: list[
        DslValue[_MessageTemplate.MessageTemplateAttachment]
    ] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    MESSAGETEMPLATEARN: ClassVar[str] = "MessageTemplateArn"
    MESSAGETEMPLATECONTENTSHA256: ClassVar[str] = "MessageTemplateContentSha256"
    MESSAGETEMPLATEID: ClassVar[str] = "MessageTemplateId"

    # PropertyType descriptors for nested GetAtt support
    AgentAttributes = PropertyTypeDescriptor(
        _MessageTemplate.AgentAttributes, "AgentAttributes"
    )
    Content = PropertyTypeDescriptor(_MessageTemplate.Content, "Content")
    CustomerProfileAttributes = PropertyTypeDescriptor(
        _MessageTemplate.CustomerProfileAttributes, "CustomerProfileAttributes"
    )
    EmailMessageTemplateContent = PropertyTypeDescriptor(
        _MessageTemplate.EmailMessageTemplateContent, "EmailMessageTemplateContent"
    )
    EmailMessageTemplateContentBody = PropertyTypeDescriptor(
        _MessageTemplate.EmailMessageTemplateContentBody,
        "EmailMessageTemplateContentBody",
    )
    EmailMessageTemplateHeader = PropertyTypeDescriptor(
        _MessageTemplate.EmailMessageTemplateHeader, "EmailMessageTemplateHeader"
    )
    GroupingConfiguration = PropertyTypeDescriptor(
        _MessageTemplate.GroupingConfiguration, "GroupingConfiguration"
    )
    MessageTemplateAttachment = PropertyTypeDescriptor(
        _MessageTemplate.MessageTemplateAttachment, "MessageTemplateAttachment"
    )
    MessageTemplateAttributes = PropertyTypeDescriptor(
        _MessageTemplate.MessageTemplateAttributes, "MessageTemplateAttributes"
    )
    MessageTemplateBodyContentProvider = PropertyTypeDescriptor(
        _MessageTemplate.MessageTemplateBodyContentProvider,
        "MessageTemplateBodyContentProvider",
    )
    SmsMessageTemplateContent = PropertyTypeDescriptor(
        _MessageTemplate.SmsMessageTemplateContent, "SmsMessageTemplateContent"
    )
    SmsMessageTemplateContentBody = PropertyTypeDescriptor(
        _MessageTemplate.SmsMessageTemplateContentBody, "SmsMessageTemplateContentBody"
    )
    SystemAttributes = PropertyTypeDescriptor(
        _MessageTemplate.SystemAttributes, "SystemAttributes"
    )
    SystemEndpointAttributes = PropertyTypeDescriptor(
        _MessageTemplate.SystemEndpointAttributes, "SystemEndpointAttributes"
    )


@dataclass
class MessageTemplateVersion(CloudFormationResource):
    """MessageTemplateVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-messagetemplateversion.html

    CloudFormation type: AWS::Wisdom::MessageTemplateVersion
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::MessageTemplateVersion"

    message_template_arn: DslValue[str] | None = None
    message_template_content_sha256: DslValue[str] | None = None

    # GetAtt attributes
    MESSAGETEMPLATEVERSIONARN: ClassVar[str] = "MessageTemplateVersionArn"
    MESSAGETEMPLATEVERSIONNUMBER: ClassVar[str] = "MessageTemplateVersionNumber"


@dataclass
class QuickResponse(CloudFormationResource):
    """QuickResponse resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wisdom-quickresponse.html

    CloudFormation type: AWS::Wisdom::QuickResponse
    """

    _resource_type: ClassVar[str] = "AWS::Wisdom::QuickResponse"

    content: DslValue[_QuickResponse.QuickResponseContentProvider] | None = None
    knowledge_base_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    channels: list[DslValue[str]] = field(default_factory=list)
    content_type: DslValue[str] | None = None
    description: DslValue[str] | None = None
    grouping_configuration: DslValue[_QuickResponse.GroupingConfiguration] | None = None
    is_active: DslValue[bool] | None = None
    language: DslValue[str] | None = None
    shortcut_key: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    CONTENTS: ClassVar[str] = "Contents"
    QUICKRESPONSEARN: ClassVar[str] = "QuickResponseArn"
    CONTENTS_MARKDOWN_CONTENT: ClassVar[str] = "Contents.Markdown.Content"
    CONTENTS_PLAINTEXT_CONTENT: ClassVar[str] = "Contents.PlainText.Content"
    CONTENTS_PLAINTEXT: ClassVar[str] = "Contents.PlainText"
    CONTENTS_MARKDOWN: ClassVar[str] = "Contents.Markdown"
    QUICKRESPONSEID: ClassVar[str] = "QuickResponseId"

    # PropertyType descriptors for nested GetAtt support
    GroupingConfiguration = PropertyTypeDescriptor(
        _QuickResponse.GroupingConfiguration, "GroupingConfiguration"
    )
    QuickResponseContentProvider = PropertyTypeDescriptor(
        _QuickResponse.QuickResponseContentProvider, "QuickResponseContentProvider"
    )
    QuickResponseContents = PropertyTypeDescriptor(
        _QuickResponse.QuickResponseContents, "QuickResponseContents"
    )
