"""
AWS CONNECT CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class AccessType:
    ALLOW = "ALLOW"


class ActionType:
    CREATE_TASK = "CREATE_TASK"
    ASSIGN_CONTACT_CATEGORY = "ASSIGN_CONTACT_CATEGORY"
    GENERATE_EVENTBRIDGE_EVENT = "GENERATE_EVENTBRIDGE_EVENT"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"
    CREATE_CASE = "CREATE_CASE"
    UPDATE_CASE = "UPDATE_CASE"
    ASSIGN_SLA = "ASSIGN_SLA"
    END_ASSOCIATED_TASKS = "END_ASSOCIATED_TASKS"
    SUBMIT_AUTO_EVALUATION = "SUBMIT_AUTO_EVALUATION"


class AgentAvailabilityTimer:
    TIME_SINCE_LAST_ACTIVITY = "TIME_SINCE_LAST_ACTIVITY"
    TIME_SINCE_LAST_INBOUND = "TIME_SINCE_LAST_INBOUND"


class AgentStatusState:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AgentStatusType:
    ROUTABLE = "ROUTABLE"
    CUSTOM = "CUSTOM"
    OFFLINE = "OFFLINE"


class AiUseCase:
    AGENTASSISTANCE = "AgentAssistance"
    SELFSERVICE = "SelfService"


class AllowedUserAction:
    CALL = "CALL"
    DISCARD = "DISCARD"


class AnsweringMachineDetectionStatus:
    ANSWERED = "ANSWERED"
    UNDETECTED = "UNDETECTED"
    ERROR = "ERROR"
    HUMAN_ANSWERED = "HUMAN_ANSWERED"
    SIT_TONE_DETECTED = "SIT_TONE_DETECTED"
    SIT_TONE_BUSY = "SIT_TONE_BUSY"
    SIT_TONE_INVALID_NUMBER = "SIT_TONE_INVALID_NUMBER"
    FAX_MACHINE_DETECTED = "FAX_MACHINE_DETECTED"
    VOICEMAIL_BEEP = "VOICEMAIL_BEEP"
    VOICEMAIL_NO_BEEP = "VOICEMAIL_NO_BEEP"
    AMD_UNRESOLVED = "AMD_UNRESOLVED"
    AMD_UNANSWERED = "AMD_UNANSWERED"
    AMD_ERROR = "AMD_ERROR"
    AMD_NOT_APPLICABLE = "AMD_NOT_APPLICABLE"


class ApplicationType:
    MCP = "MCP"
    THIRD_PARTY_APPLICATION = "THIRD_PARTY_APPLICATION"


class ArtifactStatus:
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    IN_PROGRESS = "IN_PROGRESS"


class AttachedFileInvalidRequestExceptionReason:
    INVALID_FILE_SIZE = "INVALID_FILE_SIZE"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    INVALID_FILE_NAME = "INVALID_FILE_NAME"


class AttachedFileServiceQuotaExceededExceptionReason:
    TOTAL_FILE_SIZE_EXCEEDED = "TOTAL_FILE_SIZE_EXCEEDED"
    TOTAL_FILE_COUNT_EXCEEDED = "TOTAL_FILE_COUNT_EXCEEDED"


class AutoEvaluationStatus:
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"


class BehaviorType:
    ROUTE_CURRENT_CHANNEL_ONLY = "ROUTE_CURRENT_CHANNEL_ONLY"
    ROUTE_ANY_CHANNEL = "ROUTE_ANY_CHANNEL"


class BooleanComparisonType:
    IS_TRUE = "IS_TRUE"
    IS_FALSE = "IS_FALSE"


class Channel:
    VOICE = "VOICE"
    CHAT = "CHAT"
    TASK = "TASK"
    EMAIL = "EMAIL"


class ChatEventType:
    DISCONNECT = "DISCONNECT"
    MESSAGE = "MESSAGE"
    EVENT = "EVENT"


class Comparison:
    LT = "LT"


class ContactFlowModuleState:
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ContactFlowModuleStatus:
    PUBLISHED = "PUBLISHED"
    SAVED = "SAVED"


class ContactFlowState:
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ContactFlowStatus:
    PUBLISHED = "PUBLISHED"
    SAVED = "SAVED"


class ContactFlowType:
    CONTACT_FLOW = "CONTACT_FLOW"
    CUSTOMER_QUEUE = "CUSTOMER_QUEUE"
    CUSTOMER_HOLD = "CUSTOMER_HOLD"
    CUSTOMER_WHISPER = "CUSTOMER_WHISPER"
    AGENT_HOLD = "AGENT_HOLD"
    AGENT_WHISPER = "AGENT_WHISPER"
    OUTBOUND_WHISPER = "OUTBOUND_WHISPER"
    AGENT_TRANSFER = "AGENT_TRANSFER"
    QUEUE_TRANSFER = "QUEUE_TRANSFER"
    CAMPAIGN = "CAMPAIGN"


class ContactInitiationMethod:
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"
    TRANSFER = "TRANSFER"
    QUEUE_TRANSFER = "QUEUE_TRANSFER"
    CALLBACK = "CALLBACK"
    API = "API"
    DISCONNECT = "DISCONNECT"
    MONITOR = "MONITOR"
    EXTERNAL_OUTBOUND = "EXTERNAL_OUTBOUND"
    WEBRTC_API = "WEBRTC_API"
    AGENT_REPLY = "AGENT_REPLY"
    FLOW = "FLOW"


class ContactInteractionType:
    AGENT = "AGENT"
    AUTOMATED = "AUTOMATED"


class ContactMediaProcessingFailureMode:
    DELIVER_UNPROCESSED_MESSAGE = "DELIVER_UNPROCESSED_MESSAGE"
    DO_NOT_DELIVER_UNPROCESSED_MESSAGE = "DO_NOT_DELIVER_UNPROCESSED_MESSAGE"


class ContactMetricName:
    POSITION_IN_QUEUE = "POSITION_IN_QUEUE"


class ContactParticipantRole:
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"
    CUSTOM_BOT = "CUSTOM_BOT"


class ContactRecordingType:
    AGENT = "AGENT"
    IVR = "IVR"
    SCREEN = "SCREEN"


class ContactState:
    INCOMING = "INCOMING"
    PENDING = "PENDING"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    CONNECTED_ONHOLD = "CONNECTED_ONHOLD"
    MISSED = "MISSED"
    ERROR = "ERROR"
    ENDED = "ENDED"
    REJECTED = "REJECTED"


class CurrentMetricName:
    AGENTS_ONLINE = "AGENTS_ONLINE"
    AGENTS_AVAILABLE = "AGENTS_AVAILABLE"
    AGENTS_ON_CALL = "AGENTS_ON_CALL"
    AGENTS_NON_PRODUCTIVE = "AGENTS_NON_PRODUCTIVE"
    AGENTS_AFTER_CONTACT_WORK = "AGENTS_AFTER_CONTACT_WORK"
    AGENTS_ERROR = "AGENTS_ERROR"
    AGENTS_STAFFED = "AGENTS_STAFFED"
    CONTACTS_IN_QUEUE = "CONTACTS_IN_QUEUE"
    OLDEST_CONTACT_AGE = "OLDEST_CONTACT_AGE"
    CONTACTS_SCHEDULED = "CONTACTS_SCHEDULED"
    AGENTS_ON_CONTACT = "AGENTS_ON_CONTACT"
    SLOTS_ACTIVE = "SLOTS_ACTIVE"
    SLOTS_AVAILABLE = "SLOTS_AVAILABLE"


class DataTableAttributeValueType:
    TEXT = "TEXT"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    TEXT_LIST = "TEXT_LIST"
    NUMBER_LIST = "NUMBER_LIST"


class DataTableLockLevel:
    NONE = "NONE"
    DATA_TABLE = "DATA_TABLE"
    PRIMARY_VALUE = "PRIMARY_VALUE"
    ATTRIBUTE = "ATTRIBUTE"
    VALUE = "VALUE"


class DataTableStatus:
    PUBLISHED = "PUBLISHED"


class DateComparisonType:
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO"
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO"
    EQUAL_TO = "EQUAL_TO"


class DateTimeComparisonType:
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"
    GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO"
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO"
    EQUAL_TO = "EQUAL_TO"
    RANGE = "RANGE"


class DecimalComparisonType:
    GREATER_OR_EQUAL = "GREATER_OR_EQUAL"
    GREATER = "GREATER"
    LESSER_OR_EQUAL = "LESSER_OR_EQUAL"
    LESSER = "LESSER"
    EQUAL = "EQUAL"
    NOT_EQUAL = "NOT_EQUAL"
    RANGE = "RANGE"


class DeviceType:
    GCM = "GCM"
    APNS = "APNS"
    APNS_SANDBOX = "APNS_SANDBOX"


class DirectoryType:
    SAML = "SAML"
    CONNECT_MANAGED = "CONNECT_MANAGED"
    EXISTING_DIRECTORY = "EXISTING_DIRECTORY"


class DisconnectOnCustomerExitParticipantType:
    AGENT = "AGENT"


class EmailHeaderType:
    REFERENCES = "REFERENCES"
    MESSAGE_ID = "MESSAGE_ID"
    IN_REPLY_TO = "IN_REPLY_TO"
    X_SES_SPAM_VERDICT = "X_SES_SPAM_VERDICT"
    X_SES_VIRUS_VERDICT = "X_SES_VIRUS_VERDICT"


class EncryptionType:
    KMS = "KMS"


class EndpointType:
    TELEPHONE_NUMBER = "TELEPHONE_NUMBER"
    VOIP = "VOIP"
    CONTACT_FLOW = "CONTACT_FLOW"
    CONNECT_PHONENUMBER_ARN = "CONNECT_PHONENUMBER_ARN"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"


class EntityType:
    USER = "USER"
    AI_AGENT = "AI_AGENT"


class EvaluationFormItemEnablementAction:
    DISABLE = "DISABLE"
    ENABLE = "ENABLE"


class EvaluationFormItemEnablementOperator:
    OR = "OR"
    AND = "AND"


class EvaluationFormItemEnablementSourceType:
    QUESTION_REF_ID = "QUESTION_REF_ID"


class EvaluationFormItemEnablementSourceValueType:
    OPTION_REF_ID = "OPTION_REF_ID"


class EvaluationFormItemSourceValuesComparator:
    IN = "IN"
    NOT_IN = "NOT_IN"
    ALL_IN = "ALL_IN"
    EXACT = "EXACT"


class EvaluationFormLanguageCode:
    DE_DE = "de-DE"
    EN_US = "en-US"
    ES_ES = "es-ES"
    FR_FR = "fr-FR"
    IT_IT = "it-IT"
    PT_BR = "pt-BR"


class EvaluationFormMultiSelectQuestionDisplayMode:
    DROPDOWN = "DROPDOWN"
    CHECKBOX = "CHECKBOX"


class EvaluationFormQuestionAutomationAnswerSourceType:
    CONTACT_LENS_DATA = "CONTACT_LENS_DATA"
    GEN_AI = "GEN_AI"


class EvaluationFormQuestionType:
    TEXT = "TEXT"
    SINGLESELECT = "SINGLESELECT"
    NUMERIC = "NUMERIC"
    MULTISELECT = "MULTISELECT"
    DATETIME = "DATETIME"


class EvaluationFormScoringMode:
    QUESTION_ONLY = "QUESTION_ONLY"
    SECTION_ONLY = "SECTION_ONLY"


class EvaluationFormScoringStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class EvaluationFormSingleSelectQuestionDisplayMode:
    DROPDOWN = "DROPDOWN"
    RADIO = "RADIO"


class EvaluationFormVersionStatus:
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"


class EvaluationQuestionAnswerAnalysisType:
    CONTACT_LENS_DATA = "CONTACT_LENS_DATA"
    GEN_AI = "GEN_AI"


class EvaluationStatus:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"


class EvaluationSuggestedAnswerStatus:
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"


class EvaluationTranscriptType:
    RAW = "RAW"
    REDACTED = "REDACTED"


class EvaluationType:
    STANDARD = "STANDARD"
    CALIBRATION = "CALIBRATION"


class EventSourceName:
    ONPOSTCALLANALYSISAVAILABLE = "OnPostCallAnalysisAvailable"
    ONREALTIMECALLANALYSISAVAILABLE = "OnRealTimeCallAnalysisAvailable"
    ONREALTIMECHATANALYSISAVAILABLE = "OnRealTimeChatAnalysisAvailable"
    ONPOSTCHATANALYSISAVAILABLE = "OnPostChatAnalysisAvailable"
    ONZENDESKTICKETCREATE = "OnZendeskTicketCreate"
    ONZENDESKTICKETSTATUSUPDATE = "OnZendeskTicketStatusUpdate"
    ONSALESFORCECASECREATE = "OnSalesforceCaseCreate"
    ONCONTACTEVALUATIONSUBMIT = "OnContactEvaluationSubmit"
    ONMETRICDATAUPDATE = "OnMetricDataUpdate"
    ONCASECREATE = "OnCaseCreate"
    ONCASEUPDATE = "OnCaseUpdate"
    ONSLABREACH = "OnSlaBreach"


class FailureReasonCode:
    INVALID_ATTRIBUTE_KEY = "INVALID_ATTRIBUTE_KEY"
    INVALID_CUSTOMER_ENDPOINT = "INVALID_CUSTOMER_ENDPOINT"
    INVALID_SYSTEM_ENDPOINT = "INVALID_SYSTEM_ENDPOINT"
    INVALID_QUEUE = "INVALID_QUEUE"
    INVALID_OUTBOUND_STRATEGY = "INVALID_OUTBOUND_STRATEGY"
    MISSING_CAMPAIGN = "MISSING_CAMPAIGN"
    MISSING_CUSTOMER_ENDPOINT = "MISSING_CUSTOMER_ENDPOINT"
    MISSING_QUEUE_ID_AND_SYSTEM_ENDPOINT = "MISSING_QUEUE_ID_AND_SYSTEM_ENDPOINT"
    REQUEST_THROTTLED = "REQUEST_THROTTLED"
    IDEMPOTENCY_EXCEPTION = "IDEMPOTENCY_EXCEPTION"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class FileStatusType:
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"


class FileUseCaseType:
    EMAIL_MESSAGE = "EMAIL_MESSAGE"
    ATTACHMENT = "ATTACHMENT"


class FilterV2StringConditionComparisonOperator:
    NOT_EXISTS = "NOT_EXISTS"


class FlowAssociationResourceType:
    SMS_PHONE_NUMBER = "SMS_PHONE_NUMBER"
    INBOUND_EMAIL = "INBOUND_EMAIL"
    OUTBOUND_EMAIL = "OUTBOUND_EMAIL"
    ANALYTICS_CONNECTOR = "ANALYTICS_CONNECTOR"
    WHATSAPP_MESSAGING_PHONE_NUMBER = "WHATSAPP_MESSAGING_PHONE_NUMBER"


class FlowModuleType:
    MCP = "MCP"


class Grouping:
    QUEUE = "QUEUE"
    CHANNEL = "CHANNEL"
    ROUTING_PROFILE = "ROUTING_PROFILE"
    ROUTING_STEP_EXPRESSION = "ROUTING_STEP_EXPRESSION"
    AGENT_STATUS = "AGENT_STATUS"
    SUBTYPE = "SUBTYPE"
    VALIDATION_TEST_TYPE = "VALIDATION_TEST_TYPE"


class HierarchyGroupMatchType:
    EXACT = "EXACT"
    WITH_CHILD_GROUPS = "WITH_CHILD_GROUPS"


class HistoricalMetricName:
    CONTACTS_QUEUED = "CONTACTS_QUEUED"
    CONTACTS_HANDLED = "CONTACTS_HANDLED"
    CONTACTS_ABANDONED = "CONTACTS_ABANDONED"
    CONTACTS_CONSULTED = "CONTACTS_CONSULTED"
    CONTACTS_AGENT_HUNG_UP_FIRST = "CONTACTS_AGENT_HUNG_UP_FIRST"
    CONTACTS_HANDLED_INCOMING = "CONTACTS_HANDLED_INCOMING"
    CONTACTS_HANDLED_OUTBOUND = "CONTACTS_HANDLED_OUTBOUND"
    CONTACTS_HOLD_ABANDONS = "CONTACTS_HOLD_ABANDONS"
    CONTACTS_TRANSFERRED_IN = "CONTACTS_TRANSFERRED_IN"
    CONTACTS_TRANSFERRED_OUT = "CONTACTS_TRANSFERRED_OUT"
    CONTACTS_TRANSFERRED_IN_FROM_QUEUE = "CONTACTS_TRANSFERRED_IN_FROM_QUEUE"
    CONTACTS_TRANSFERRED_OUT_FROM_QUEUE = "CONTACTS_TRANSFERRED_OUT_FROM_QUEUE"
    CONTACTS_MISSED = "CONTACTS_MISSED"
    CALLBACK_CONTACTS_HANDLED = "CALLBACK_CONTACTS_HANDLED"
    API_CONTACTS_HANDLED = "API_CONTACTS_HANDLED"
    OCCUPANCY = "OCCUPANCY"
    HANDLE_TIME = "HANDLE_TIME"
    AFTER_CONTACT_WORK_TIME = "AFTER_CONTACT_WORK_TIME"
    QUEUED_TIME = "QUEUED_TIME"
    ABANDON_TIME = "ABANDON_TIME"
    QUEUE_ANSWER_TIME = "QUEUE_ANSWER_TIME"
    HOLD_TIME = "HOLD_TIME"
    INTERACTION_TIME = "INTERACTION_TIME"
    INTERACTION_AND_HOLD_TIME = "INTERACTION_AND_HOLD_TIME"
    SERVICE_LEVEL = "SERVICE_LEVEL"


class HoursOfOperationDays:
    SUNDAY = "SUNDAY"
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"


class InboundMessageSourceType:
    RAW = "RAW"


class InitiateAs:
    CONNECTED_TO_USER = "CONNECTED_TO_USER"
    COMPLETED = "COMPLETED"


class InstanceAttributeType:
    INBOUND_CALLS = "INBOUND_CALLS"
    OUTBOUND_CALLS = "OUTBOUND_CALLS"
    CONTACTFLOW_LOGS = "CONTACTFLOW_LOGS"
    CONTACT_LENS = "CONTACT_LENS"
    AUTO_RESOLVE_BEST_VOICES = "AUTO_RESOLVE_BEST_VOICES"
    USE_CUSTOM_TTS_VOICES = "USE_CUSTOM_TTS_VOICES"
    EARLY_MEDIA = "EARLY_MEDIA"
    MULTI_PARTY_CONFERENCE = "MULTI_PARTY_CONFERENCE"
    HIGH_VOLUME_OUTBOUND = "HIGH_VOLUME_OUTBOUND"
    ENHANCED_CONTACT_MONITORING = "ENHANCED_CONTACT_MONITORING"
    ENHANCED_CHAT_MONITORING = "ENHANCED_CHAT_MONITORING"
    MULTI_PARTY_CHAT_CONFERENCE = "MULTI_PARTY_CHAT_CONFERENCE"
    MESSAGE_STREAMING = "MESSAGE_STREAMING"


class InstanceReplicationStatus:
    INSTANCE_REPLICATION_COMPLETE = "INSTANCE_REPLICATION_COMPLETE"
    INSTANCE_REPLICATION_IN_PROGRESS = "INSTANCE_REPLICATION_IN_PROGRESS"
    INSTANCE_REPLICATION_FAILED = "INSTANCE_REPLICATION_FAILED"
    INSTANCE_REPLICA_DELETING = "INSTANCE_REPLICA_DELETING"
    INSTANCE_REPLICATION_DELETION_FAILED = "INSTANCE_REPLICATION_DELETION_FAILED"
    RESOURCE_REPLICATION_NOT_STARTED = "RESOURCE_REPLICATION_NOT_STARTED"


class InstanceStatus:
    CREATION_IN_PROGRESS = "CREATION_IN_PROGRESS"
    ACTIVE = "ACTIVE"
    CREATION_FAILED = "CREATION_FAILED"


class InstanceStorageResourceType:
    CHAT_TRANSCRIPTS = "CHAT_TRANSCRIPTS"
    CALL_RECORDINGS = "CALL_RECORDINGS"
    SCHEDULED_REPORTS = "SCHEDULED_REPORTS"
    MEDIA_STREAMS = "MEDIA_STREAMS"
    CONTACT_TRACE_RECORDS = "CONTACT_TRACE_RECORDS"
    AGENT_EVENTS = "AGENT_EVENTS"
    REAL_TIME_CONTACT_ANALYSIS_SEGMENTS = "REAL_TIME_CONTACT_ANALYSIS_SEGMENTS"
    ATTACHMENTS = "ATTACHMENTS"
    CONTACT_EVALUATIONS = "CONTACT_EVALUATIONS"
    SCREEN_RECORDINGS = "SCREEN_RECORDINGS"
    REAL_TIME_CONTACT_ANALYSIS_CHAT_SEGMENTS = (
        "REAL_TIME_CONTACT_ANALYSIS_CHAT_SEGMENTS"
    )
    REAL_TIME_CONTACT_ANALYSIS_VOICE_SEGMENTS = (
        "REAL_TIME_CONTACT_ANALYSIS_VOICE_SEGMENTS"
    )
    EMAIL_MESSAGES = "EMAIL_MESSAGES"


class IntegrationType:
    EVENT = "EVENT"
    VOICE_ID = "VOICE_ID"
    PINPOINT_APP = "PINPOINT_APP"
    WISDOM_ASSISTANT = "WISDOM_ASSISTANT"
    WISDOM_KNOWLEDGE_BASE = "WISDOM_KNOWLEDGE_BASE"
    WISDOM_QUICK_RESPONSES = "WISDOM_QUICK_RESPONSES"
    Q_MESSAGE_TEMPLATES = "Q_MESSAGE_TEMPLATES"
    CASES_DOMAIN = "CASES_DOMAIN"
    APPLICATION = "APPLICATION"
    FILE_SCANNER = "FILE_SCANNER"
    SES_IDENTITY = "SES_IDENTITY"
    ANALYTICS_CONNECTOR = "ANALYTICS_CONNECTOR"
    CALL_TRANSFER_CONNECTOR = "CALL_TRANSFER_CONNECTOR"
    COGNITO_USER_POOL = "COGNITO_USER_POOL"
    MESSAGE_PROCESSOR = "MESSAGE_PROCESSOR"


class IntervalPeriod:
    FIFTEEN_MIN = "FIFTEEN_MIN"
    THIRTY_MIN = "THIRTY_MIN"
    HOUR = "HOUR"
    DAY = "DAY"
    WEEK = "WEEK"
    TOTAL = "TOTAL"


class IvrRecordingTrack:
    ALL = "ALL"


class LexVersion:
    V1 = "V1"
    V2 = "V2"


class ListFlowAssociationResourceType:
    WHATSAPP_MESSAGING_PHONE_NUMBER = "WHATSAPP_MESSAGING_PHONE_NUMBER"
    VOICE_PHONE_NUMBER = "VOICE_PHONE_NUMBER"
    INBOUND_EMAIL = "INBOUND_EMAIL"
    OUTBOUND_EMAIL = "OUTBOUND_EMAIL"
    ANALYTICS_CONNECTOR = "ANALYTICS_CONNECTOR"


class MediaStreamType:
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"


class MediaType:
    IMAGE_LOGO_LIGHT_FAVICON = "IMAGE_LOGO_LIGHT_FAVICON"
    IMAGE_LOGO_DARK_FAVICON = "IMAGE_LOGO_DARK_FAVICON"
    IMAGE_LOGO_LIGHT_HORIZONTAL = "IMAGE_LOGO_LIGHT_HORIZONTAL"
    IMAGE_LOGO_DARK_HORIZONTAL = "IMAGE_LOGO_DARK_HORIZONTAL"


class MeetingFeatureStatus:
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class MonitorCapability:
    SILENT_MONITOR = "SILENT_MONITOR"
    BARGE = "BARGE"


class MultiSelectQuestionRuleCategoryAutomationCondition:
    PRESENT = "PRESENT"
    NOT_PRESENT = "NOT_PRESENT"


class NextContactType:
    QUICK_CONNECT = "QUICK_CONNECT"


class NotificationContentType:
    PLAIN_TEXT = "PLAIN_TEXT"


class NotificationDeliveryType:
    EMAIL = "EMAIL"


class NumberComparisonType:
    GREATER_OR_EQUAL = "GREATER_OR_EQUAL"
    GREATER = "GREATER"
    LESSER_OR_EQUAL = "LESSER_OR_EQUAL"
    LESSER = "LESSER"
    EQUAL = "EQUAL"
    NOT_EQUAL = "NOT_EQUAL"
    RANGE = "RANGE"


class NumericQuestionPropertyAutomationLabel:
    OVERALL_CUSTOMER_SENTIMENT_SCORE = "OVERALL_CUSTOMER_SENTIMENT_SCORE"
    OVERALL_AGENT_SENTIMENT_SCORE = "OVERALL_AGENT_SENTIMENT_SCORE"
    CUSTOMER_SENTIMENT_SCORE_WITHOUT_AGENT = "CUSTOMER_SENTIMENT_SCORE_WITHOUT_AGENT"
    CUSTOMER_SENTIMENT_SCORE_WITH_AGENT = "CUSTOMER_SENTIMENT_SCORE_WITH_AGENT"
    NON_TALK_TIME = "NON_TALK_TIME"
    NON_TALK_TIME_PERCENTAGE = "NON_TALK_TIME_PERCENTAGE"
    NUMBER_OF_INTERRUPTIONS = "NUMBER_OF_INTERRUPTIONS"
    CONTACT_DURATION = "CONTACT_DURATION"
    AGENT_INTERACTION_DURATION = "AGENT_INTERACTION_DURATION"
    CUSTOMER_HOLD_TIME = "CUSTOMER_HOLD_TIME"
    LONGEST_HOLD_DURATION = "LONGEST_HOLD_DURATION"
    NUMBER_OF_HOLDS = "NUMBER_OF_HOLDS"
    AGENT_INTERACTION_AND_HOLD_DURATION = "AGENT_INTERACTION_AND_HOLD_DURATION"


class OutboundMessageSourceType:
    TEMPLATE = "TEMPLATE"
    RAW = "RAW"


class OutboundStrategyType:
    AGENT_FIRST = "AGENT_FIRST"


class OverrideDays:
    SUNDAY = "SUNDAY"
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"


class ParticipantRole:
    AGENT = "AGENT"
    CUSTOMER = "CUSTOMER"
    SYSTEM = "SYSTEM"
    CUSTOM_BOT = "CUSTOM_BOT"
    SUPERVISOR = "SUPERVISOR"


class ParticipantState:
    INITIAL = "INITIAL"
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    MISSED = "MISSED"


class ParticipantTimerAction:
    UNSET = "Unset"


class ParticipantTimerType:
    IDLE = "IDLE"
    DISCONNECT_NONCUSTOMER = "DISCONNECT_NONCUSTOMER"


class ParticipantType:
    ALL = "ALL"
    MANAGER = "MANAGER"
    AGENT = "AGENT"
    CUSTOMER = "CUSTOMER"
    THIRDPARTY = "THIRDPARTY"


class PhoneNumberType:
    TOLL_FREE = "TOLL_FREE"
    DID = "DID"
    UIFN = "UIFN"
    SHARED = "SHARED"
    THIRD_PARTY_TF = "THIRD_PARTY_TF"
    THIRD_PARTY_DID = "THIRD_PARTY_DID"
    SHORT_CODE = "SHORT_CODE"


class PhoneNumberWorkflowStatus:
    CLAIMED = "CLAIMED"
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"


class PhoneType:
    SOFT_PHONE = "SOFT_PHONE"
    DESK_PHONE = "DESK_PHONE"


class PropertyValidationExceptionReason:
    INVALID_FORMAT = "INVALID_FORMAT"
    UNIQUE_CONSTRAINT_VIOLATED = "UNIQUE_CONSTRAINT_VIOLATED"
    REFERENCED_RESOURCE_NOT_FOUND = "REFERENCED_RESOURCE_NOT_FOUND"
    RESOURCE_NAME_ALREADY_EXISTS = "RESOURCE_NAME_ALREADY_EXISTS"
    REQUIRED_PROPERTY_MISSING = "REQUIRED_PROPERTY_MISSING"
    NOT_SUPPORTED = "NOT_SUPPORTED"


class QuestionRuleCategoryAutomationCondition:
    PRESENT = "PRESENT"
    NOT_PRESENT = "NOT_PRESENT"


class QueueStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class QueueType:
    STANDARD = "STANDARD"
    AGENT = "AGENT"


class QuickConnectType:
    USER = "USER"
    QUEUE = "QUEUE"
    PHONE_NUMBER = "PHONE_NUMBER"
    FLOW = "FLOW"


class RealTimeContactAnalysisOutputType:
    RAW = "Raw"
    REDACTED = "Redacted"


class RealTimeContactAnalysisPostContactSummaryFailureCode:
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    INSUFFICIENT_CONVERSATION_CONTENT = "INSUFFICIENT_CONVERSATION_CONTENT"
    FAILED_SAFETY_GUIDELINES = "FAILED_SAFETY_GUIDELINES"
    INVALID_ANALYSIS_CONFIGURATION = "INVALID_ANALYSIS_CONFIGURATION"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class RealTimeContactAnalysisPostContactSummaryStatus:
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class RealTimeContactAnalysisSegmentType:
    TRANSCRIPT = "Transcript"
    CATEGORIES = "Categories"
    ISSUES = "Issues"
    EVENT = "Event"
    ATTACHMENTS = "Attachments"
    POSTCONTACTSUMMARY = "PostContactSummary"


class RealTimeContactAnalysisSentimentLabel:
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"


class RealTimeContactAnalysisStatus:
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class RealTimeContactAnalysisSupportedChannel:
    VOICE = "VOICE"
    CHAT = "CHAT"


class RecordingStatus:
    AVAILABLE = "AVAILABLE"
    DELETED = "DELETED"


class ReferenceStatus:
    AVAILABLE = "AVAILABLE"
    DELETED = "DELETED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"


class ReferenceType:
    URL = "URL"
    ATTACHMENT = "ATTACHMENT"
    CONTACT_ANALYSIS = "CONTACT_ANALYSIS"
    NUMBER = "NUMBER"
    STRING = "STRING"
    DATE = "DATE"
    EMAIL = "EMAIL"
    EMAIL_MESSAGE = "EMAIL_MESSAGE"
    EMAIL_MESSAGE_PLAIN_TEXT = "EMAIL_MESSAGE_PLAIN_TEXT"


class RehydrationType:
    ENTIRE_PAST_SESSION = "ENTIRE_PAST_SESSION"
    FROM_SEGMENT = "FROM_SEGMENT"


class ResourceType:
    CONTACT = "CONTACT"
    CONTACT_FLOW = "CONTACT_FLOW"
    INSTANCE = "INSTANCE"
    PARTICIPANT = "PARTICIPANT"
    HIERARCHY_LEVEL = "HIERARCHY_LEVEL"
    HIERARCHY_GROUP = "HIERARCHY_GROUP"
    USER = "USER"
    PHONE_NUMBER = "PHONE_NUMBER"


class ResponseMode:
    INCREMENTAL = "INCREMENTAL"
    COMPLETE = "COMPLETE"


class RoutingCriteriaStepStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    JOINED = "JOINED"
    EXPIRED = "EXPIRED"


class RulePublishStatus:
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"


class ScreenShareCapability:
    SEND = "SEND"


class SearchContactsMatchType:
    MATCH_ALL = "MATCH_ALL"
    MATCH_ANY = "MATCH_ANY"
    MATCH_EXACT = "MATCH_EXACT"
    MATCH_NONE = "MATCH_NONE"


class SearchContactsTimeRangeConditionType:
    NOT_EXISTS = "NOT_EXISTS"


class SearchContactsTimeRangeType:
    INITIATION_TIMESTAMP = "INITIATION_TIMESTAMP"
    SCHEDULED_TIMESTAMP = "SCHEDULED_TIMESTAMP"
    CONNECTED_TO_AGENT_TIMESTAMP = "CONNECTED_TO_AGENT_TIMESTAMP"
    DISCONNECT_TIMESTAMP = "DISCONNECT_TIMESTAMP"
    ENQUEUE_TIMESTAMP = "ENQUEUE_TIMESTAMP"


class SearchableQueueType:
    STANDARD = "STANDARD"


class SingleSelectQuestionRuleCategoryAutomationCondition:
    PRESENT = "PRESENT"
    NOT_PRESENT = "NOT_PRESENT"


class SlaAssignmentType:
    CASES = "CASES"


class SlaType:
    CASEFIELD = "CaseField"


class SortOrder:
    ASCENDING = "ASCENDING"
    DESCENDING = "DESCENDING"


class SortableFieldName:
    INITIATION_TIMESTAMP = "INITIATION_TIMESTAMP"
    SCHEDULED_TIMESTAMP = "SCHEDULED_TIMESTAMP"
    CONNECTED_TO_AGENT_TIMESTAMP = "CONNECTED_TO_AGENT_TIMESTAMP"
    DISCONNECT_TIMESTAMP = "DISCONNECT_TIMESTAMP"
    INITIATION_METHOD = "INITIATION_METHOD"
    CHANNEL = "CHANNEL"
    EXPIRY_TIMESTAMP = "EXPIRY_TIMESTAMP"


class SourceType:
    SALESFORCE = "SALESFORCE"
    ZENDESK = "ZENDESK"
    CASES = "CASES"


class Statistic:
    SUM = "SUM"
    MAX = "MAX"
    AVG = "AVG"


class Status:
    COMPLETE = "COMPLETE"
    IN_PROGRESS = "IN_PROGRESS"
    DELETED = "DELETED"


class StorageType:
    S3 = "S3"
    KINESIS_VIDEO_STREAM = "KINESIS_VIDEO_STREAM"
    KINESIS_STREAM = "KINESIS_STREAM"
    KINESIS_FIREHOSE = "KINESIS_FIREHOSE"


class StringComparisonType:
    STARTS_WITH = "STARTS_WITH"
    CONTAINS = "CONTAINS"
    EXACT = "EXACT"


class TargetListType:
    PROFICIENCIES = "PROFICIENCIES"


class TaskTemplateFieldType:
    NAME = "NAME"
    DESCRIPTION = "DESCRIPTION"
    SCHEDULED_TIME = "SCHEDULED_TIME"
    QUICK_CONNECT = "QUICK_CONNECT"
    URL = "URL"
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    TEXT_AREA = "TEXT_AREA"
    DATE_TIME = "DATE_TIME"
    BOOLEAN = "BOOLEAN"
    SINGLE_SELECT = "SINGLE_SELECT"
    EMAIL = "EMAIL"
    SELF_ASSIGN = "SELF_ASSIGN"
    EXPIRY_DURATION = "EXPIRY_DURATION"


class TaskTemplateStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class TimerEligibleParticipantRoles:
    CUSTOMER = "CUSTOMER"
    AGENT = "AGENT"


class TrafficDistributionGroupStatus:
    CREATION_IN_PROGRESS = "CREATION_IN_PROGRESS"
    ACTIVE = "ACTIVE"
    CREATION_FAILED = "CREATION_FAILED"
    PENDING_DELETION = "PENDING_DELETION"
    DELETION_FAILED = "DELETION_FAILED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"


class TrafficType:
    GENERAL = "GENERAL"
    CAMPAIGN = "CAMPAIGN"


class Unit:
    SECONDS = "SECONDS"
    COUNT = "COUNT"
    PERCENT = "PERCENT"


class UseCaseType:
    RULES_EVALUATION = "RULES_EVALUATION"
    CONNECT_CAMPAIGNS = "CONNECT_CAMPAIGNS"


class VideoCapability:
    SEND = "SEND"


class ViewStatus:
    PUBLISHED = "PUBLISHED"
    SAVED = "SAVED"


class ViewType:
    CUSTOMER_MANAGED = "CUSTOMER_MANAGED"
    AWS_MANAGED = "AWS_MANAGED"


class Visibility:
    ALL = "ALL"
    ASSIGNED = "ASSIGNED"
    NONE = "NONE"


class VocabularyLanguageCode:
    AR_AE = "ar-AE"
    DE_CH = "de-CH"
    DE_DE = "de-DE"
    EN_AB = "en-AB"
    EN_AU = "en-AU"
    EN_GB = "en-GB"
    EN_IE = "en-IE"
    EN_IN = "en-IN"
    EN_US = "en-US"
    EN_WL = "en-WL"
    ES_ES = "es-ES"
    ES_US = "es-US"
    FR_CA = "fr-CA"
    FR_FR = "fr-FR"
    HI_IN = "hi-IN"
    IT_IT = "it-IT"
    JA_JP = "ja-JP"
    KO_KR = "ko-KR"
    PT_BR = "pt-BR"
    PT_PT = "pt-PT"
    ZH_CN = "zh-CN"
    EN_NZ = "en-NZ"
    EN_ZA = "en-ZA"
    CA_ES = "ca-ES"
    DA_DK = "da-DK"
    FI_FI = "fi-FI"
    ID_ID = "id-ID"
    MS_MY = "ms-MY"
    NL_NL = "nl-NL"
    NO_NO = "no-NO"
    PL_PL = "pl-PL"
    SV_SE = "sv-SE"
    TL_PH = "tl-PH"


class VocabularyState:
    CREATION_IN_PROGRESS = "CREATION_IN_PROGRESS"
    ACTIVE = "ACTIVE"
    CREATION_FAILED = "CREATION_FAILED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"


class VoiceRecordingTrack:
    FROM_AGENT = "FROM_AGENT"
    TO_AGENT = "TO_AGENT"
    ALL = "ALL"


class WorkspaceFontFamily:
    ARIAL = "Arial"
    COURIERNEW = "Courier New"
    GEORGIA = "Georgia"
    TIMESNEWROMAN = "Times New Roman"
    TREBUCHET = "Trebuchet"
    VERDANA = "Verdana"


# PropertyType submodules
from . import ContactFlowModule as _ContactFlowModule
from . import DataTable as _DataTable
from . import DataTableAttribute as _DataTableAttribute
from . import DataTableRecord as _DataTableRecord
from . import EmailAddress as _EmailAddress
from . import EvaluationForm as _EvaluationForm
from . import HoursOfOperation as _HoursOfOperation
from . import Instance as _Instance
from . import InstanceStorageConfig as _InstanceStorageConfig
from . import PredefinedAttribute as _PredefinedAttribute
from . import Queue as _Queue
from . import QuickConnect as _QuickConnect
from . import RoutingProfile as _RoutingProfile
from . import Rule as _Rule
from . import SecurityProfile as _SecurityProfile
from . import TaskTemplate as _TaskTemplate
from . import User as _User
from . import UserHierarchyStructure as _UserHierarchyStructure
from . import Workspace as _Workspace


# Resources
# ============================================================


@dataclass
class AgentStatus(CloudFormationResource):
    """AgentStatus resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-agentstatus.html

    CloudFormation type: AWS::Connect::AgentStatus
    """

    _resource_type: ClassVar[str] = "AWS::Connect::AgentStatus"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    state: DslValue[str] | None = None
    description: DslValue[str] | None = None
    display_order: DslValue[int] | None = None
    reset_order_number: DslValue[bool] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    type_: DslValue[str] | None = None

    # GetAtt attributes
    AGENTSTATUSARN: ClassVar[str] = "AgentStatusArn"
    LASTMODIFIEDTIME: ClassVar[str] = "LastModifiedTime"
    LASTMODIFIEDREGION: ClassVar[str] = "LastModifiedRegion"


@dataclass
class ApprovedOrigin(CloudFormationResource):
    """ApprovedOrigin resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-approvedorigin.html

    CloudFormation type: AWS::Connect::ApprovedOrigin
    """

    _resource_type: ClassVar[str] = "AWS::Connect::ApprovedOrigin"

    instance_id: DslValue[str] | None = None
    origin: DslValue[str] | None = None


@dataclass
class ContactFlow(CloudFormationResource):
    """ContactFlow resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-contactflow.html

    CloudFormation type: AWS::Connect::ContactFlow
    """

    _resource_type: ClassVar[str] = "AWS::Connect::ContactFlow"

    content: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    type_: DslValue[str] | None = None
    description: DslValue[str] | None = None
    state: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CONTACTFLOWARN: ClassVar[str] = "ContactFlowArn"


@dataclass
class ContactFlowModule(CloudFormationResource):
    """ContactFlowModule resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-contactflowmodule.html

    CloudFormation type: AWS::Connect::ContactFlowModule
    """

    _resource_type: ClassVar[str] = "AWS::Connect::ContactFlowModule"

    content: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    description: DslValue[str] | None = None
    external_invocation_configuration: (
        DslValue[_ContactFlowModule.ExternalInvocationConfiguration] | None
    ) = None
    settings: DslValue[str] | None = None
    state: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CONTACTFLOWMODULEARN: ClassVar[str] = "ContactFlowModuleArn"
    STATUS: ClassVar[str] = "Status"

    # PropertyType descriptors for nested GetAtt support
    ExternalInvocationConfiguration = PropertyTypeDescriptor(
        _ContactFlowModule.ExternalInvocationConfiguration,
        "ExternalInvocationConfiguration",
    )


@dataclass
class ContactFlowVersion(CloudFormationResource):
    """ContactFlowVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-contactflowversion.html

    CloudFormation type: AWS::Connect::ContactFlowVersion
    """

    _resource_type: ClassVar[str] = "AWS::Connect::ContactFlowVersion"

    contact_flow_id: DslValue[str] | None = None
    description: DslValue[str] | None = None

    # GetAtt attributes
    FLOWCONTENTSHA256: ClassVar[str] = "FlowContentSha256"
    CONTACTFLOWVERSIONARN: ClassVar[str] = "ContactFlowVersionARN"
    VERSION: ClassVar[str] = "Version"


@dataclass
class DataTable(CloudFormationResource):
    """DataTable resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-datatable.html

    CloudFormation type: AWS::Connect::DataTable
    """

    _resource_type: ClassVar[str] = "AWS::Connect::DataTable"

    description: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    status: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    time_zone: DslValue[str] | None = None
    value_lock_level: DslValue[str] | None = None

    # GetAtt attributes
    LOCKVERSION: ClassVar[str] = "LockVersion"
    CREATEDTIME: ClassVar[str] = "CreatedTime"
    LOCKVERSION_DATATABLE: ClassVar[str] = "LockVersion.DataTable"
    LASTMODIFIEDTIME: ClassVar[str] = "LastModifiedTime"
    ARN: ClassVar[str] = "Arn"
    LASTMODIFIEDREGION: ClassVar[str] = "LastModifiedRegion"

    # PropertyType descriptors for nested GetAtt support
    LockVersion = PropertyTypeDescriptor(_DataTable.LockVersion, "LockVersion")


@dataclass
class DataTableAttribute(CloudFormationResource):
    """DataTableAttribute resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-datatableattribute.html

    CloudFormation type: AWS::Connect::DataTableAttribute
    """

    _resource_type: ClassVar[str] = "AWS::Connect::DataTableAttribute"

    data_table_arn: DslValue[str] | None = None
    description: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    primary: DslValue[bool] | None = None
    validation: DslValue[_DataTableAttribute.Validation] | None = None
    value_type: DslValue[str] | None = None

    # GetAtt attributes
    LOCKVERSION_ATTRIBUTE: ClassVar[str] = "LockVersion.Attribute"
    LOCKVERSION: ClassVar[str] = "LockVersion"
    LOCKVERSION_DATATABLE: ClassVar[str] = "LockVersion.DataTable"
    ATTRIBUTEID: ClassVar[str] = "AttributeId"
    LASTMODIFIEDTIME: ClassVar[str] = "LastModifiedTime"
    LASTMODIFIEDREGION: ClassVar[str] = "LastModifiedRegion"

    # PropertyType descriptors for nested GetAtt support
    Enum = PropertyTypeDescriptor(_DataTableAttribute.Enum, "Enum")
    LockVersion = PropertyTypeDescriptor(_DataTableAttribute.LockVersion, "LockVersion")
    Validation = PropertyTypeDescriptor(_DataTableAttribute.Validation, "Validation")


@dataclass
class DataTableRecord(CloudFormationResource):
    """DataTableRecord resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-datatablerecord.html

    CloudFormation type: AWS::Connect::DataTableRecord
    """

    _resource_type: ClassVar[str] = "AWS::Connect::DataTableRecord"

    data_table_arn: DslValue[str] | None = None
    data_table_record: DslValue[_DataTableRecord.DataTableRecord] | None = None
    instance_arn: DslValue[str] | None = None

    # GetAtt attributes
    RECORDID: ClassVar[str] = "RecordId"

    # PropertyType descriptors for nested GetAtt support
    DataTableRecord = PropertyTypeDescriptor(
        _DataTableRecord.DataTableRecord, "DataTableRecord"
    )
    Value = PropertyTypeDescriptor(_DataTableRecord.Value, "Value")


@dataclass
class EmailAddress(CloudFormationResource):
    """EmailAddress resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-emailaddress.html

    CloudFormation type: AWS::Connect::EmailAddress
    """

    _resource_type: ClassVar[str] = "AWS::Connect::EmailAddress"

    email_address: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    alias_configurations: list[DslValue[_EmailAddress.AliasConfiguration]] = field(
        default_factory=list
    )
    description: DslValue[str] | None = None
    display_name: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    EMAILADDRESSARN: ClassVar[str] = "EmailAddressArn"

    # PropertyType descriptors for nested GetAtt support
    AliasConfiguration = PropertyTypeDescriptor(
        _EmailAddress.AliasConfiguration, "AliasConfiguration"
    )


@dataclass
class EvaluationForm(CloudFormationResource):
    """EvaluationForm resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-evaluationform.html

    CloudFormation type: AWS::Connect::EvaluationForm
    """

    _resource_type: ClassVar[str] = "AWS::Connect::EvaluationForm"

    instance_arn: DslValue[str] | None = None
    items: list[DslValue[_EvaluationForm.EvaluationFormBaseItem]] = field(
        default_factory=list
    )
    status: DslValue[str] | None = None
    title: DslValue[str] | None = None
    auto_evaluation_configuration: (
        DslValue[_EvaluationForm.AutoEvaluationConfiguration] | None
    ) = None
    description: DslValue[str] | None = None
    language_configuration: (
        DslValue[_EvaluationForm.EvaluationFormLanguageConfiguration] | None
    ) = None
    scoring_strategy: DslValue[_EvaluationForm.ScoringStrategy] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    target_configuration: (
        DslValue[_EvaluationForm.EvaluationFormTargetConfiguration] | None
    ) = None

    # GetAtt attributes
    EVALUATIONFORMARN: ClassVar[str] = "EvaluationFormArn"

    # PropertyType descriptors for nested GetAtt support
    AutoEvaluationConfiguration = PropertyTypeDescriptor(
        _EvaluationForm.AutoEvaluationConfiguration, "AutoEvaluationConfiguration"
    )
    AutomaticFailConfiguration = PropertyTypeDescriptor(
        _EvaluationForm.AutomaticFailConfiguration, "AutomaticFailConfiguration"
    )
    EvaluationFormBaseItem = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormBaseItem, "EvaluationFormBaseItem"
    )
    EvaluationFormItem = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItem, "EvaluationFormItem"
    )
    EvaluationFormItemEnablementCondition = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementCondition,
        "EvaluationFormItemEnablementCondition",
    )
    EvaluationFormItemEnablementConditionOperand = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementConditionOperand,
        "EvaluationFormItemEnablementConditionOperand",
    )
    EvaluationFormItemEnablementConfiguration = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementConfiguration,
        "EvaluationFormItemEnablementConfiguration",
    )
    EvaluationFormItemEnablementExpression = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementExpression,
        "EvaluationFormItemEnablementExpression",
    )
    EvaluationFormItemEnablementSource = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementSource,
        "EvaluationFormItemEnablementSource",
    )
    EvaluationFormItemEnablementSourceValue = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormItemEnablementSourceValue,
        "EvaluationFormItemEnablementSourceValue",
    )
    EvaluationFormLanguageConfiguration = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormLanguageConfiguration,
        "EvaluationFormLanguageConfiguration",
    )
    EvaluationFormMultiSelectQuestionAutomation = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormMultiSelectQuestionAutomation,
        "EvaluationFormMultiSelectQuestionAutomation",
    )
    EvaluationFormMultiSelectQuestionAutomationOption = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormMultiSelectQuestionAutomationOption,
        "EvaluationFormMultiSelectQuestionAutomationOption",
    )
    EvaluationFormMultiSelectQuestionOption = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormMultiSelectQuestionOption,
        "EvaluationFormMultiSelectQuestionOption",
    )
    EvaluationFormMultiSelectQuestionProperties = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormMultiSelectQuestionProperties,
        "EvaluationFormMultiSelectQuestionProperties",
    )
    EvaluationFormNumericQuestionAutomation = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormNumericQuestionAutomation,
        "EvaluationFormNumericQuestionAutomation",
    )
    EvaluationFormNumericQuestionOption = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormNumericQuestionOption,
        "EvaluationFormNumericQuestionOption",
    )
    EvaluationFormNumericQuestionProperties = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormNumericQuestionProperties,
        "EvaluationFormNumericQuestionProperties",
    )
    EvaluationFormQuestion = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormQuestion, "EvaluationFormQuestion"
    )
    EvaluationFormQuestionAutomationAnswerSource = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormQuestionAutomationAnswerSource,
        "EvaluationFormQuestionAutomationAnswerSource",
    )
    EvaluationFormQuestionTypeProperties = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormQuestionTypeProperties,
        "EvaluationFormQuestionTypeProperties",
    )
    EvaluationFormSection = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormSection, "EvaluationFormSection"
    )
    EvaluationFormSingleSelectQuestionAutomation = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormSingleSelectQuestionAutomation,
        "EvaluationFormSingleSelectQuestionAutomation",
    )
    EvaluationFormSingleSelectQuestionAutomationOption = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormSingleSelectQuestionAutomationOption,
        "EvaluationFormSingleSelectQuestionAutomationOption",
    )
    EvaluationFormSingleSelectQuestionOption = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormSingleSelectQuestionOption,
        "EvaluationFormSingleSelectQuestionOption",
    )
    EvaluationFormSingleSelectQuestionProperties = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormSingleSelectQuestionProperties,
        "EvaluationFormSingleSelectQuestionProperties",
    )
    EvaluationFormTargetConfiguration = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormTargetConfiguration,
        "EvaluationFormTargetConfiguration",
    )
    EvaluationFormTextQuestionAutomation = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormTextQuestionAutomation,
        "EvaluationFormTextQuestionAutomation",
    )
    EvaluationFormTextQuestionProperties = PropertyTypeDescriptor(
        _EvaluationForm.EvaluationFormTextQuestionProperties,
        "EvaluationFormTextQuestionProperties",
    )
    MultiSelectQuestionRuleCategoryAutomation = PropertyTypeDescriptor(
        _EvaluationForm.MultiSelectQuestionRuleCategoryAutomation,
        "MultiSelectQuestionRuleCategoryAutomation",
    )
    NumericQuestionPropertyValueAutomation = PropertyTypeDescriptor(
        _EvaluationForm.NumericQuestionPropertyValueAutomation,
        "NumericQuestionPropertyValueAutomation",
    )
    ScoringStrategy = PropertyTypeDescriptor(
        _EvaluationForm.ScoringStrategy, "ScoringStrategy"
    )
    SingleSelectQuestionRuleCategoryAutomation = PropertyTypeDescriptor(
        _EvaluationForm.SingleSelectQuestionRuleCategoryAutomation,
        "SingleSelectQuestionRuleCategoryAutomation",
    )


@dataclass
class HoursOfOperation(CloudFormationResource):
    """HoursOfOperation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-hoursofoperation.html

    CloudFormation type: AWS::Connect::HoursOfOperation
    """

    _resource_type: ClassVar[str] = "AWS::Connect::HoursOfOperation"

    config: list[DslValue[_HoursOfOperation.HoursOfOperationConfig]] = field(
        default_factory=list
    )
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    time_zone: DslValue[str] | None = None
    child_hours_of_operations: list[
        DslValue[_HoursOfOperation.HoursOfOperationsIdentifier]
    ] = field(default_factory=list)
    description: DslValue[str] | None = None
    hours_of_operation_overrides: list[
        DslValue[_HoursOfOperation.HoursOfOperationOverride]
    ] = field(default_factory=list)
    parent_hours_of_operations: list[
        DslValue[_HoursOfOperation.HoursOfOperationsIdentifier]
    ] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    HOURSOFOPERATIONARN: ClassVar[str] = "HoursOfOperationArn"

    # PropertyType descriptors for nested GetAtt support
    HoursOfOperationConfig = PropertyTypeDescriptor(
        _HoursOfOperation.HoursOfOperationConfig, "HoursOfOperationConfig"
    )
    HoursOfOperationOverride = PropertyTypeDescriptor(
        _HoursOfOperation.HoursOfOperationOverride, "HoursOfOperationOverride"
    )
    HoursOfOperationOverrideConfig = PropertyTypeDescriptor(
        _HoursOfOperation.HoursOfOperationOverrideConfig,
        "HoursOfOperationOverrideConfig",
    )
    HoursOfOperationTimeSlice = PropertyTypeDescriptor(
        _HoursOfOperation.HoursOfOperationTimeSlice, "HoursOfOperationTimeSlice"
    )
    HoursOfOperationsIdentifier = PropertyTypeDescriptor(
        _HoursOfOperation.HoursOfOperationsIdentifier, "HoursOfOperationsIdentifier"
    )
    OverrideTimeSlice = PropertyTypeDescriptor(
        _HoursOfOperation.OverrideTimeSlice, "OverrideTimeSlice"
    )
    RecurrenceConfig = PropertyTypeDescriptor(
        _HoursOfOperation.RecurrenceConfig, "RecurrenceConfig"
    )
    RecurrencePattern = PropertyTypeDescriptor(
        _HoursOfOperation.RecurrencePattern, "RecurrencePattern"
    )


@dataclass
class Instance(CloudFormationResource):
    """Instance resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-instance.html

    CloudFormation type: AWS::Connect::Instance
    """

    _resource_type: ClassVar[str] = "AWS::Connect::Instance"

    attributes: DslValue[_Instance.Attributes] | None = None
    identity_management_type: DslValue[str] | None = None
    directory_id: DslValue[str] | None = None
    instance_alias: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CREATEDTIME: ClassVar[str] = "CreatedTime"
    SERVICEROLE: ClassVar[str] = "ServiceRole"
    INSTANCESTATUS: ClassVar[str] = "InstanceStatus"
    ID: ClassVar[str] = "Id"
    ARN: ClassVar[str] = "Arn"

    # PropertyType descriptors for nested GetAtt support
    Attributes = PropertyTypeDescriptor(_Instance.Attributes, "Attributes")


@dataclass
class InstanceStorageConfig(CloudFormationResource):
    """InstanceStorageConfig resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-instancestorageconfig.html

    CloudFormation type: AWS::Connect::InstanceStorageConfig
    """

    _resource_type: ClassVar[str] = "AWS::Connect::InstanceStorageConfig"

    instance_arn: DslValue[str] | None = None
    resource_type: DslValue[str] | None = None
    storage_type: DslValue[str] | None = None
    kinesis_firehose_config: (
        DslValue[_InstanceStorageConfig.KinesisFirehoseConfig] | None
    ) = None
    kinesis_stream_config: (
        DslValue[_InstanceStorageConfig.KinesisStreamConfig] | None
    ) = None
    kinesis_video_stream_config: (
        DslValue[_InstanceStorageConfig.KinesisVideoStreamConfig] | None
    ) = None
    s3_config: DslValue[_InstanceStorageConfig.S3Config] | None = None

    # GetAtt attributes
    ASSOCIATIONID: ClassVar[str] = "AssociationId"

    # PropertyType descriptors for nested GetAtt support
    EncryptionConfig = PropertyTypeDescriptor(
        _InstanceStorageConfig.EncryptionConfig, "EncryptionConfig"
    )
    KinesisFirehoseConfig = PropertyTypeDescriptor(
        _InstanceStorageConfig.KinesisFirehoseConfig, "KinesisFirehoseConfig"
    )
    KinesisStreamConfig = PropertyTypeDescriptor(
        _InstanceStorageConfig.KinesisStreamConfig, "KinesisStreamConfig"
    )
    KinesisVideoStreamConfig = PropertyTypeDescriptor(
        _InstanceStorageConfig.KinesisVideoStreamConfig, "KinesisVideoStreamConfig"
    )
    S3Config = PropertyTypeDescriptor(_InstanceStorageConfig.S3Config, "S3Config")


@dataclass
class IntegrationAssociation(CloudFormationResource):
    """IntegrationAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-integrationassociation.html

    CloudFormation type: AWS::Connect::IntegrationAssociation
    """

    _resource_type: ClassVar[str] = "AWS::Connect::IntegrationAssociation"

    instance_id: DslValue[str] | None = None
    integration_arn: DslValue[str] | None = None
    integration_type: DslValue[str] | None = None

    # GetAtt attributes
    INTEGRATIONASSOCIATIONID: ClassVar[str] = "IntegrationAssociationId"


@dataclass
class PhoneNumber(CloudFormationResource):
    """PhoneNumber resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-phonenumber.html

    CloudFormation type: AWS::Connect::PhoneNumber
    """

    _resource_type: ClassVar[str] = "AWS::Connect::PhoneNumber"

    target_arn: DslValue[str] | None = None
    country_code: DslValue[str] | None = None
    description: DslValue[str] | None = None
    prefix: DslValue[str] | None = None
    source_phone_number_arn: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    type_: DslValue[str] | None = None

    # GetAtt attributes
    ADDRESS: ClassVar[str] = "Address"
    PHONENUMBERARN: ClassVar[str] = "PhoneNumberArn"


@dataclass
class PredefinedAttribute(CloudFormationResource):
    """PredefinedAttribute resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-predefinedattribute.html

    CloudFormation type: AWS::Connect::PredefinedAttribute
    """

    _resource_type: ClassVar[str] = "AWS::Connect::PredefinedAttribute"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    attribute_configuration: (
        DslValue[_PredefinedAttribute.AttributeConfiguration] | None
    ) = None
    purposes: list[DslValue[str]] = field(default_factory=list)
    values: DslValue[_PredefinedAttribute.Values] | None = None

    # GetAtt attributes
    LASTMODIFIEDTIME: ClassVar[str] = "LastModifiedTime"
    LASTMODIFIEDREGION: ClassVar[str] = "LastModifiedRegion"

    # PropertyType descriptors for nested GetAtt support
    AttributeConfiguration = PropertyTypeDescriptor(
        _PredefinedAttribute.AttributeConfiguration, "AttributeConfiguration"
    )
    Values = PropertyTypeDescriptor(_PredefinedAttribute.Values, "Values")


@dataclass
class Prompt(CloudFormationResource):
    """Prompt resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-prompt.html

    CloudFormation type: AWS::Connect::Prompt
    """

    _resource_type: ClassVar[str] = "AWS::Connect::Prompt"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    description: DslValue[str] | None = None
    s3_uri: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    PROMPTARN: ClassVar[str] = "PromptArn"


@dataclass
class Queue(CloudFormationResource):
    """Queue resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-queue.html

    CloudFormation type: AWS::Connect::Queue
    """

    _resource_type: ClassVar[str] = "AWS::Connect::Queue"

    hours_of_operation_arn: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    description: DslValue[str] | None = None
    max_contacts: DslValue[int] | None = None
    outbound_caller_config: DslValue[_Queue.OutboundCallerConfig] | None = None
    outbound_email_config: DslValue[_Queue.OutboundEmailConfig] | None = None
    quick_connect_arns: list[DslValue[str]] = field(default_factory=list)
    status: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    TYPE: ClassVar[str] = "Type"
    QUEUEARN: ClassVar[str] = "QueueArn"

    # PropertyType descriptors for nested GetAtt support
    OutboundCallerConfig = PropertyTypeDescriptor(
        _Queue.OutboundCallerConfig, "OutboundCallerConfig"
    )
    OutboundEmailConfig = PropertyTypeDescriptor(
        _Queue.OutboundEmailConfig, "OutboundEmailConfig"
    )


@dataclass
class QuickConnect(CloudFormationResource):
    """QuickConnect resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-quickconnect.html

    CloudFormation type: AWS::Connect::QuickConnect
    """

    _resource_type: ClassVar[str] = "AWS::Connect::QuickConnect"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    quick_connect_config: DslValue[_QuickConnect.QuickConnectConfig] | None = None
    description: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    QUICKCONNECTARN: ClassVar[str] = "QuickConnectArn"
    QUICKCONNECTTYPE: ClassVar[str] = "QuickConnectType"

    # PropertyType descriptors for nested GetAtt support
    PhoneNumberQuickConnectConfig = PropertyTypeDescriptor(
        _QuickConnect.PhoneNumberQuickConnectConfig, "PhoneNumberQuickConnectConfig"
    )
    QueueQuickConnectConfig = PropertyTypeDescriptor(
        _QuickConnect.QueueQuickConnectConfig, "QueueQuickConnectConfig"
    )
    QuickConnectConfig = PropertyTypeDescriptor(
        _QuickConnect.QuickConnectConfig, "QuickConnectConfig"
    )
    UserQuickConnectConfig = PropertyTypeDescriptor(
        _QuickConnect.UserQuickConnectConfig, "UserQuickConnectConfig"
    )


@dataclass
class RoutingProfile(CloudFormationResource):
    """RoutingProfile resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-routingprofile.html

    CloudFormation type: AWS::Connect::RoutingProfile
    """

    _resource_type: ClassVar[str] = "AWS::Connect::RoutingProfile"

    default_outbound_queue_arn: DslValue[str] | None = None
    description: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    media_concurrencies: list[DslValue[_RoutingProfile.MediaConcurrency]] = field(
        default_factory=list
    )
    name: DslValue[str] | None = None
    agent_availability_timer: DslValue[str] | None = None
    manual_assignment_queue_configs: list[
        DslValue[_RoutingProfile.RoutingProfileManualAssignmentQueueConfig]
    ] = field(default_factory=list)
    queue_configs: list[DslValue[_RoutingProfile.RoutingProfileQueueConfig]] = field(
        default_factory=list
    )
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ROUTINGPROFILEARN: ClassVar[str] = "RoutingProfileArn"

    # PropertyType descriptors for nested GetAtt support
    CrossChannelBehavior = PropertyTypeDescriptor(
        _RoutingProfile.CrossChannelBehavior, "CrossChannelBehavior"
    )
    MediaConcurrency = PropertyTypeDescriptor(
        _RoutingProfile.MediaConcurrency, "MediaConcurrency"
    )
    RoutingProfileManualAssignmentQueueConfig = PropertyTypeDescriptor(
        _RoutingProfile.RoutingProfileManualAssignmentQueueConfig,
        "RoutingProfileManualAssignmentQueueConfig",
    )
    RoutingProfileQueueConfig = PropertyTypeDescriptor(
        _RoutingProfile.RoutingProfileQueueConfig, "RoutingProfileQueueConfig"
    )
    RoutingProfileQueueReference = PropertyTypeDescriptor(
        _RoutingProfile.RoutingProfileQueueReference, "RoutingProfileQueueReference"
    )


@dataclass
class Rule(CloudFormationResource):
    """Rule resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-rule.html

    CloudFormation type: AWS::Connect::Rule
    """

    _resource_type: ClassVar[str] = "AWS::Connect::Rule"

    actions: DslValue[_Rule.Actions] | None = None
    function: DslValue[str] | None = None
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    publish_status: DslValue[str] | None = None
    trigger_event_source: DslValue[_Rule.RuleTriggerEventSource] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    RULEARN: ClassVar[str] = "RuleArn"

    # PropertyType descriptors for nested GetAtt support
    Actions = PropertyTypeDescriptor(_Rule.Actions, "Actions")
    CreateCaseAction = PropertyTypeDescriptor(
        _Rule.CreateCaseAction, "CreateCaseAction"
    )
    EventBridgeAction = PropertyTypeDescriptor(
        _Rule.EventBridgeAction, "EventBridgeAction"
    )
    Field = PropertyTypeDescriptor(_Rule.Field, "Field")
    FieldValue = PropertyTypeDescriptor(_Rule.FieldValue, "FieldValue")
    NotificationRecipientType = PropertyTypeDescriptor(
        _Rule.NotificationRecipientType, "NotificationRecipientType"
    )
    Reference = PropertyTypeDescriptor(_Rule.Reference, "Reference")
    RuleTriggerEventSource = PropertyTypeDescriptor(
        _Rule.RuleTriggerEventSource, "RuleTriggerEventSource"
    )
    SendNotificationAction = PropertyTypeDescriptor(
        _Rule.SendNotificationAction, "SendNotificationAction"
    )
    SubmitAutoEvaluationAction = PropertyTypeDescriptor(
        _Rule.SubmitAutoEvaluationAction, "SubmitAutoEvaluationAction"
    )
    TaskAction = PropertyTypeDescriptor(_Rule.TaskAction, "TaskAction")
    UpdateCaseAction = PropertyTypeDescriptor(
        _Rule.UpdateCaseAction, "UpdateCaseAction"
    )


@dataclass
class SecurityKey(CloudFormationResource):
    """SecurityKey resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-securitykey.html

    CloudFormation type: AWS::Connect::SecurityKey
    """

    _resource_type: ClassVar[str] = "AWS::Connect::SecurityKey"

    instance_id: DslValue[str] | None = None
    key: DslValue[str] | None = None

    # GetAtt attributes
    ASSOCIATIONID: ClassVar[str] = "AssociationId"


@dataclass
class SecurityProfile(CloudFormationResource):
    """SecurityProfile resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-securityprofile.html

    CloudFormation type: AWS::Connect::SecurityProfile
    """

    _resource_type: ClassVar[str] = "AWS::Connect::SecurityProfile"

    instance_arn: DslValue[str] | None = None
    security_profile_name: DslValue[str] | None = None
    allowed_access_control_hierarchy_group_id: DslValue[str] | None = None
    allowed_access_control_tags: list[DslValue[Tag]] = field(default_factory=list)
    applications: list[DslValue[_SecurityProfile.Application]] = field(
        default_factory=list
    )
    description: DslValue[str] | None = None
    granular_access_control_configuration: (
        DslValue[_SecurityProfile.GranularAccessControlConfiguration] | None
    ) = None
    hierarchy_restricted_resources: list[DslValue[str]] = field(default_factory=list)
    permissions: list[DslValue[str]] = field(default_factory=list)
    tag_restricted_resources: list[DslValue[str]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    SECURITYPROFILEARN: ClassVar[str] = "SecurityProfileArn"
    LASTMODIFIEDTIME: ClassVar[str] = "LastModifiedTime"
    LASTMODIFIEDREGION: ClassVar[str] = "LastModifiedRegion"

    # PropertyType descriptors for nested GetAtt support
    Application = PropertyTypeDescriptor(_SecurityProfile.Application, "Application")
    DataTableAccessControlConfiguration = PropertyTypeDescriptor(
        _SecurityProfile.DataTableAccessControlConfiguration,
        "DataTableAccessControlConfiguration",
    )
    GranularAccessControlConfiguration = PropertyTypeDescriptor(
        _SecurityProfile.GranularAccessControlConfiguration,
        "GranularAccessControlConfiguration",
    )
    PrimaryAttributeAccessControlConfigurationItem = PropertyTypeDescriptor(
        _SecurityProfile.PrimaryAttributeAccessControlConfigurationItem,
        "PrimaryAttributeAccessControlConfigurationItem",
    )
    PrimaryAttributeValue = PropertyTypeDescriptor(
        _SecurityProfile.PrimaryAttributeValue, "PrimaryAttributeValue"
    )


@dataclass
class TaskTemplate(CloudFormationResource):
    """TaskTemplate resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-tasktemplate.html

    CloudFormation type: AWS::Connect::TaskTemplate
    """

    _resource_type: ClassVar[str] = "AWS::Connect::TaskTemplate"

    instance_arn: DslValue[str] | None = None
    client_token: DslValue[str] | None = None
    constraints: DslValue[_TaskTemplate.Constraints] | None = None
    contact_flow_arn: DslValue[str] | None = None
    defaults: list[DslValue[_TaskTemplate.DefaultFieldValue]] = field(
        default_factory=list
    )
    description: DslValue[str] | None = None
    fields: list[DslValue[_TaskTemplate.Field]] = field(default_factory=list)
    name: DslValue[str] | None = None
    self_assign_contact_flow_arn: DslValue[str] | None = None
    status: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"

    # PropertyType descriptors for nested GetAtt support
    Constraints = PropertyTypeDescriptor(_TaskTemplate.Constraints, "Constraints")
    DefaultFieldValue = PropertyTypeDescriptor(
        _TaskTemplate.DefaultFieldValue, "DefaultFieldValue"
    )
    Field = PropertyTypeDescriptor(_TaskTemplate.Field, "Field")
    FieldIdentifier = PropertyTypeDescriptor(
        _TaskTemplate.FieldIdentifier, "FieldIdentifier"
    )
    InvisibleFieldInfo = PropertyTypeDescriptor(
        _TaskTemplate.InvisibleFieldInfo, "InvisibleFieldInfo"
    )
    ReadOnlyFieldInfo = PropertyTypeDescriptor(
        _TaskTemplate.ReadOnlyFieldInfo, "ReadOnlyFieldInfo"
    )
    RequiredFieldInfo = PropertyTypeDescriptor(
        _TaskTemplate.RequiredFieldInfo, "RequiredFieldInfo"
    )


@dataclass
class TrafficDistributionGroup(CloudFormationResource):
    """TrafficDistributionGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-trafficdistributiongroup.html

    CloudFormation type: AWS::Connect::TrafficDistributionGroup
    """

    _resource_type: ClassVar[str] = "AWS::Connect::TrafficDistributionGroup"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    description: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    ISDEFAULT: ClassVar[str] = "IsDefault"
    TRAFFICDISTRIBUTIONGROUPARN: ClassVar[str] = "TrafficDistributionGroupArn"


@dataclass
class User(CloudFormationResource):
    """User resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-user.html

    CloudFormation type: AWS::Connect::User
    """

    _resource_type: ClassVar[str] = "AWS::Connect::User"

    instance_arn: DslValue[str] | None = None
    phone_config: DslValue[_User.UserPhoneConfig] | None = None
    routing_profile_arn: DslValue[str] | None = None
    security_profile_arns: list[DslValue[str]] = field(default_factory=list)
    username: DslValue[str] | None = None
    directory_user_id: DslValue[str] | None = None
    hierarchy_group_arn: DslValue[str] | None = None
    identity_info: DslValue[_User.UserIdentityInfo] | None = None
    password: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    user_proficiencies: list[DslValue[_User.UserProficiency]] = field(
        default_factory=list
    )

    # GetAtt attributes
    USERARN: ClassVar[str] = "UserArn"

    # PropertyType descriptors for nested GetAtt support
    UserIdentityInfo = PropertyTypeDescriptor(
        _User.UserIdentityInfo, "UserIdentityInfo"
    )
    UserPhoneConfig = PropertyTypeDescriptor(_User.UserPhoneConfig, "UserPhoneConfig")
    UserProficiency = PropertyTypeDescriptor(_User.UserProficiency, "UserProficiency")


@dataclass
class UserHierarchyGroup(CloudFormationResource):
    """UserHierarchyGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-userhierarchygroup.html

    CloudFormation type: AWS::Connect::UserHierarchyGroup
    """

    _resource_type: ClassVar[str] = "AWS::Connect::UserHierarchyGroup"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    parent_group_arn: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    USERHIERARCHYGROUPARN: ClassVar[str] = "UserHierarchyGroupArn"


@dataclass
class UserHierarchyStructure(CloudFormationResource):
    """UserHierarchyStructure resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-userhierarchystructure.html

    CloudFormation type: AWS::Connect::UserHierarchyStructure
    """

    _resource_type: ClassVar[str] = "AWS::Connect::UserHierarchyStructure"

    instance_arn: DslValue[str] | None = None
    user_hierarchy_structure: (
        DslValue[_UserHierarchyStructure.UserHierarchyStructure] | None
    ) = None

    # GetAtt attributes
    USERHIERARCHYSTRUCTUREARN: ClassVar[str] = "UserHierarchyStructureArn"

    # PropertyType descriptors for nested GetAtt support
    LevelFive = PropertyTypeDescriptor(_UserHierarchyStructure.LevelFive, "LevelFive")
    LevelFour = PropertyTypeDescriptor(_UserHierarchyStructure.LevelFour, "LevelFour")
    LevelOne = PropertyTypeDescriptor(_UserHierarchyStructure.LevelOne, "LevelOne")
    LevelThree = PropertyTypeDescriptor(
        _UserHierarchyStructure.LevelThree, "LevelThree"
    )
    LevelTwo = PropertyTypeDescriptor(_UserHierarchyStructure.LevelTwo, "LevelTwo")
    UserHierarchyStructure = PropertyTypeDescriptor(
        _UserHierarchyStructure.UserHierarchyStructure, "UserHierarchyStructure"
    )


@dataclass
class View(CloudFormationResource):
    """View resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-view.html

    CloudFormation type: AWS::Connect::View
    """

    _resource_type: ClassVar[str] = "AWS::Connect::View"

    actions: list[DslValue[str]] = field(default_factory=list)
    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    template: DslValue[dict[str, Any]] | None = None
    description: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    VIEWARN: ClassVar[str] = "ViewArn"
    VIEWCONTENTSHA256: ClassVar[str] = "ViewContentSha256"
    VIEWID: ClassVar[str] = "ViewId"


@dataclass
class ViewVersion(CloudFormationResource):
    """ViewVersion resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-viewversion.html

    CloudFormation type: AWS::Connect::ViewVersion
    """

    _resource_type: ClassVar[str] = "AWS::Connect::ViewVersion"

    view_arn: DslValue[str] | None = None
    version_description: DslValue[str] | None = None
    view_content_sha256: DslValue[str] | None = None

    # GetAtt attributes
    VIEWVERSIONARN: ClassVar[str] = "ViewVersionArn"
    VERSION: ClassVar[str] = "Version"


@dataclass
class Workspace(CloudFormationResource):
    """Workspace resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connect-workspace.html

    CloudFormation type: AWS::Connect::Workspace
    """

    _resource_type: ClassVar[str] = "AWS::Connect::Workspace"

    instance_arn: DslValue[str] | None = None
    name: DslValue[str] | None = None
    associations: list[DslValue[str]] = field(default_factory=list)
    description: DslValue[str] | None = None
    media: list[DslValue[_Workspace.MediaItem]] = field(default_factory=list)
    pages: list[DslValue[_Workspace.WorkspacePage]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)
    theme: DslValue[_Workspace.WorkspaceTheme] | None = None
    title: DslValue[str] | None = None
    visibility: DslValue[str] | None = None

    # GetAtt attributes
    ID: ClassVar[str] = "Id"
    ARN: ClassVar[str] = "Arn"

    # PropertyType descriptors for nested GetAtt support
    FontFamily = PropertyTypeDescriptor(_Workspace.FontFamily, "FontFamily")
    MediaItem = PropertyTypeDescriptor(_Workspace.MediaItem, "MediaItem")
    PaletteCanvas = PropertyTypeDescriptor(_Workspace.PaletteCanvas, "PaletteCanvas")
    PaletteHeader = PropertyTypeDescriptor(_Workspace.PaletteHeader, "PaletteHeader")
    PaletteNavigation = PropertyTypeDescriptor(
        _Workspace.PaletteNavigation, "PaletteNavigation"
    )
    PalettePrimary = PropertyTypeDescriptor(_Workspace.PalettePrimary, "PalettePrimary")
    WorkspacePage = PropertyTypeDescriptor(_Workspace.WorkspacePage, "WorkspacePage")
    WorkspaceTheme = PropertyTypeDescriptor(_Workspace.WorkspaceTheme, "WorkspaceTheme")
    WorkspaceThemeConfig = PropertyTypeDescriptor(
        _Workspace.WorkspaceThemeConfig, "WorkspaceThemeConfig"
    )
    WorkspaceThemePalette = PropertyTypeDescriptor(
        _Workspace.WorkspaceThemePalette, "WorkspaceThemePalette"
    )
    WorkspaceThemeTypography = PropertyTypeDescriptor(
        _Workspace.WorkspaceThemeTypography, "WorkspaceThemeTypography"
    )
