"""
AWS-specific stub configuration for dataclass_dsl.

Provides AWS_STUB_CONFIG for generating .pyi stub files that work
with wetwire-aws imports. The stub generator uses this to expand
star imports for core types.

Note: Service modules (s3, ec2, lambda_, etc.) are NOT included in
the static stub config. They are dynamically detected based on actual
usage in each package.
"""

from dataclass_dsl import StubConfig

# All names exported from wetwire_aws that should be available
# via `from . import *` in resource packages.
# This includes only core types - NOT the 264 service modules.
AWS_CORE_EXPORTS = [
    # Decorator
    "wetwire_aws",
    # Base classes
    "CloudFormationResource",
    "PropertyType",
    "Tag",
    # Policy helpers
    "PolicyStatement",
    "DenyStatement",
    "PolicyDocument",
    # Template and components
    "CloudFormationTemplate",
    "Parameter",
    "Output",
    "Mapping",
    "TemplateCondition",
    # Reference types from dataclass-dsl
    "Ref",
    "Attr",
    "RefList",
    "RefDict",
    # Reference helpers
    "ref",
    "get_att",
    "ARN",
    # Intrinsic functions (CF intrinsics)
    "RefIntrinsic",
    "GetAtt",
    "Sub",
    "Join",
    "Select",
    "Split",
    "If",
    "Equals",
    "And",
    "Or",
    "Not",
    "Base64",
    "GetAZs",
    "ImportValue",
    "FindInMap",
    "Transform",
    "Cidr",
    "Condition",
    # Parameter type constants
    "STRING",
    "NUMBER",
    "LIST_NUMBER",
    "COMMA_DELIMITED_LIST",
    "SSM_PARAMETER_STRING",
    "SSM_PARAMETER_STRING_LIST",
    "AVAILABILITY_ZONE",
    "LIST_AVAILABILITY_ZONE",
    "AMI_ID",
    "INSTANCE_ID",
    "KEY_PAIR",
    "SECURITY_GROUP_ID",
    "LIST_SECURITY_GROUP_ID",
    "SUBNET_ID",
    "LIST_SUBNET_ID",
    "VPC_ID",
    "VOLUME_ID",
    "HOSTED_ZONE_ID",
    # Pseudo-parameters
    "AWS_ACCOUNT_ID",
    "AWS_NOTIFICATION_ARNS",
    "AWS_NO_VALUE",
    "AWS_PARTITION",
    "AWS_REGION",
    "AWS_STACK_ID",
    "AWS_STACK_NAME",
    "AWS_URL_SUFFIX",
    # Condition operator constants
    "BOOL",
    "STRING_EQUALS",
    "STRING_NOT_EQUALS",
    "STRING_EQUALS_IGNORE_CASE",
    "STRING_NOT_EQUALS_IGNORE_CASE",
    "STRING_LIKE",
    "STRING_NOT_LIKE",
    "NUMERIC_EQUALS",
    "NUMERIC_NOT_EQUALS",
    "NUMERIC_LESS_THAN",
    "NUMERIC_LESS_THAN_EQUALS",
    "NUMERIC_GREATER_THAN",
    "NUMERIC_GREATER_THAN_EQUALS",
    "DATE_EQUALS",
    "DATE_NOT_EQUALS",
    "DATE_LESS_THAN",
    "DATE_LESS_THAN_EQUALS",
    "DATE_GREATER_THAN",
    "DATE_GREATER_THAN_EQUALS",
    "IP_ADDRESS",
    "NOT_IP_ADDRESS",
    "ARN_EQUALS",
    "ARN_NOT_EQUALS",
    "ARN_LIKE",
    "ARN_NOT_LIKE",
    "NULL",
]

# Build extra header lines for core wetwire_aws imports only
# These are needed because setup_params() and setup_resources() inject
# names dynamically, but the IDE can't see that from static analysis.
#
# Note: We do NOT import all 264 service modules here. That would bloat
# every stub file with 500+ lines. Instead, the stub generator will
# add imports for only the service modules actually used by each package.
_CORE_IMPORT_LINES = [
    "# Core exports injected by setup_params() and setup_resources()",
    "from wetwire_aws import (",
    "    # Decorator",
    "    wetwire_aws,",
    "    # Base classes",
    "    CloudFormationResource,",
    "    PropertyType,",
    "    Tag,",
    "    # Policy helpers",
    "    PolicyStatement,",
    "    DenyStatement,",
    "    PolicyDocument,",
    "    # Template components",
    "    CloudFormationTemplate,",
    "    Parameter,",
    "    Output,",
    "    Mapping,",
    "    TemplateCondition,",
    "    # Reference types (from dataclass-dsl)",
    "    Ref,",
    "    Attr,",
    "    RefList,",
    "    RefDict,",
    "    # Reference helpers",
    "    ref,",
    "    get_att,",
    "    ARN,",
    "    # Intrinsic functions",
    "    RefIntrinsic,",
    "    GetAtt,",
    "    Sub,",
    "    Join,",
    "    Select,",
    "    Split,",
    "    If,",
    "    Equals,",
    "    And,",
    "    Or,",
    "    Not,",
    "    Base64,",
    "    GetAZs,",
    "    ImportValue,",
    "    FindInMap,",
    "    Transform,",
    "    Cidr,",
    "    Condition,",
    "    # Parameter type constants",
    "    STRING,",
    "    NUMBER,",
    "    LIST_NUMBER,",
    "    COMMA_DELIMITED_LIST,",
    "    SSM_PARAMETER_STRING,",
    "    SSM_PARAMETER_STRING_LIST,",
    "    # AWS-specific parameter types",
    "    AVAILABILITY_ZONE,",
    "    LIST_AVAILABILITY_ZONE,",
    "    AMI_ID,",
    "    INSTANCE_ID,",
    "    KEY_PAIR,",
    "    SECURITY_GROUP_ID,",
    "    LIST_SECURITY_GROUP_ID,",
    "    SUBNET_ID,",
    "    LIST_SUBNET_ID,",
    "    VPC_ID,",
    "    VOLUME_ID,",
    "    HOSTED_ZONE_ID,",
    "    # Pseudo-parameters",
    "    AWS_ACCOUNT_ID,",
    "    AWS_NOTIFICATION_ARNS,",
    "    AWS_NO_VALUE,",
    "    AWS_PARTITION,",
    "    AWS_REGION,",
    "    AWS_STACK_ID,",
    "    AWS_STACK_NAME,",
    "    AWS_URL_SUFFIX,",
    "    # Condition operator constants",
    "    BOOL,",
    "    STRING_EQUALS,",
    "    STRING_NOT_EQUALS,",
    "    STRING_EQUALS_IGNORE_CASE,",
    "    STRING_NOT_EQUALS_IGNORE_CASE,",
    "    STRING_LIKE,",
    "    STRING_NOT_LIKE,",
    "    NUMERIC_EQUALS,",
    "    NUMERIC_NOT_EQUALS,",
    "    NUMERIC_LESS_THAN,",
    "    NUMERIC_LESS_THAN_EQUALS,",
    "    NUMERIC_GREATER_THAN,",
    "    NUMERIC_GREATER_THAN_EQUALS,",
    "    DATE_EQUALS,",
    "    DATE_NOT_EQUALS,",
    "    DATE_LESS_THAN,",
    "    DATE_LESS_THAN_EQUALS,",
    "    DATE_GREATER_THAN,",
    "    DATE_GREATER_THAN_EQUALS,",
    "    IP_ADDRESS,",
    "    NOT_IP_ADDRESS,",
    "    ARN_EQUALS,",
    "    ARN_NOT_EQUALS,",
    "    ARN_LIKE,",
    "    ARN_NOT_LIKE,",
    "    NULL,",
    ")",
]

AWS_STUB_CONFIG = StubConfig(
    package_name="wetwire_aws",
    core_imports=AWS_CORE_EXPORTS,
    expand_star_imports={
        "wetwire_aws": AWS_CORE_EXPORTS,
    },
    extra_header_lines=_CORE_IMPORT_LINES,
)
