"""
AWS NEPTUNEGRAPH CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:23Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# PropertyType submodules
from . import Graph as _Graph


# Resources
# ============================================================


@dataclass
class Graph(CloudFormationResource):
    """Graph resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptunegraph-graph.html

    CloudFormation type: AWS::NeptuneGraph::Graph
    """

    _resource_type: ClassVar[str] = "AWS::NeptuneGraph::Graph"

    provisioned_memory: DslValue[int] | None = None
    deletion_protection: DslValue[bool] | None = None
    graph_name: DslValue[str] | None = None
    public_connectivity: DslValue[bool] | None = None
    replica_count: DslValue[int] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    vector_search_configuration: DslValue[_Graph.VectorSearchConfiguration] | None = (
        None
    )

    # GetAtt attributes
    ENDPOINT: ClassVar[str] = "Endpoint"
    GRAPHARN: ClassVar[str] = "GraphArn"
    GRAPHID: ClassVar[str] = "GraphId"

    # PropertyType descriptors for nested GetAtt support
    VectorSearchConfiguration = PropertyTypeDescriptor(
        _Graph.VectorSearchConfiguration, "VectorSearchConfiguration"
    )


@dataclass
class PrivateGraphEndpoint(CloudFormationResource):
    """PrivateGraphEndpoint resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptunegraph-privategraphendpoint.html

    CloudFormation type: AWS::NeptuneGraph::PrivateGraphEndpoint
    """

    _resource_type: ClassVar[str] = "AWS::NeptuneGraph::PrivateGraphEndpoint"

    graph_identifier: DslValue[str] | None = None
    vpc_id: DslValue[str] | None = None
    security_group_ids: list[DslValue[str]] = field(default_factory=list)
    subnet_ids: list[DslValue[str]] = field(default_factory=list)

    # GetAtt attributes
    VPCENDPOINTID: ClassVar[str] = "VpcEndpointId"
    PRIVATEGRAPHENDPOINTIDENTIFIER: ClassVar[str] = "PrivateGraphEndpointIdentifier"
