"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .messaging import TestQ as TestQ
from .params import AppName as AppName
from .security import StorageReplicationPolicy as StorageReplicationPolicy
from .security import StorageReplicationPolicyAllowStatement0 as StorageReplicationPolicyAllowStatement0
from .security import StorageReplicationPolicyAllowStatement1 as StorageReplicationPolicyAllowStatement1
from .security import StorageReplicationPolicyAllowStatement2 as StorageReplicationPolicyAllowStatement2
from .security import StorageReplicationPolicyPolicyDocument as StorageReplicationPolicyPolicyDocument
from .security import StorageReplicationRole as StorageReplicationRole
from .security import StorageReplicationRoleAllowStatement0 as StorageReplicationRoleAllowStatement0
from .security import StorageReplicationRoleAssumeRolePolicyDocument as StorageReplicationRoleAssumeRolePolicyDocument
from .storage import StorageBucket as StorageBucket
from .storage import StorageBucketBucketEncryption as StorageBucketBucketEncryption
from .storage import StorageBucketDeleteMarkerReplication as StorageBucketDeleteMarkerReplication
from .storage import StorageBucketLoggingConfiguration as StorageBucketLoggingConfiguration
from .storage import StorageBucketMetadataTableEncryptionConfiguration as StorageBucketMetadataTableEncryptionConfiguration
from .storage import StorageBucketPolicyPolicy as StorageBucketPolicyPolicy
from .storage import StorageBucketPolicyPolicyAllowStatement1 as StorageBucketPolicyPolicyAllowStatement1
from .storage import StorageBucketPolicyPolicyDenyStatement0 as StorageBucketPolicyPolicyDenyStatement0
from .storage import StorageBucketPolicyPolicyPolicyDocument as StorageBucketPolicyPolicyPolicyDocument
from .storage import StorageBucketPublicAccessBlockConfiguration as StorageBucketPublicAccessBlockConfiguration
from .storage import StorageBucketReplicationConfiguration as StorageBucketReplicationConfiguration
from .storage import StorageBucketReplicationDestination as StorageBucketReplicationDestination
from .storage import StorageBucketReplicationRule as StorageBucketReplicationRule
from .storage import StorageBucketServerSideEncryptionRule as StorageBucketServerSideEncryptionRule
from .storage import StorageLogBucket as StorageLogBucket
from .storage import StorageLogBucketBucketEncryption as StorageLogBucketBucketEncryption
from .storage import StorageLogBucketDefaultRetention as StorageLogBucketDefaultRetention
from .storage import StorageLogBucketDeleteMarkerReplication as StorageLogBucketDeleteMarkerReplication
from .storage import StorageLogBucketMetadataTableEncryptionConfiguration as StorageLogBucketMetadataTableEncryptionConfiguration
from .storage import StorageLogBucketObjectLockConfiguration as StorageLogBucketObjectLockConfiguration
from .storage import StorageLogBucketObjectLockRule as StorageLogBucketObjectLockRule
from .storage import StorageLogBucketPolicyPolicy as StorageLogBucketPolicyPolicy
from .storage import StorageLogBucketPolicyPolicyAllowStatement1 as StorageLogBucketPolicyPolicyAllowStatement1
from .storage import StorageLogBucketPolicyPolicyDenyStatement0 as StorageLogBucketPolicyPolicyDenyStatement0
from .storage import StorageLogBucketPolicyPolicyPolicyDocument as StorageLogBucketPolicyPolicyPolicyDocument
from .storage import StorageLogBucketPublicAccessBlockConfiguration as StorageLogBucketPublicAccessBlockConfiguration
from .storage import StorageLogBucketServerSideEncryptionRule as StorageLogBucketServerSideEncryptionRule
from .storage import StorageReplicaBucket as StorageReplicaBucket
from .storage import StorageReplicaBucketBucketEncryption as StorageReplicaBucketBucketEncryption
from .storage import StorageReplicaBucketDeleteMarkerReplication as StorageReplicaBucketDeleteMarkerReplication
from .storage import StorageReplicaBucketMetadataTableEncryptionConfiguration as StorageReplicaBucketMetadataTableEncryptionConfiguration
from .storage import StorageReplicaBucketPolicyPolicy as StorageReplicaBucketPolicyPolicy
from .storage import StorageReplicaBucketPolicyPolicyAllowStatement1 as StorageReplicaBucketPolicyPolicyAllowStatement1
from .storage import StorageReplicaBucketPolicyPolicyDenyStatement0 as StorageReplicaBucketPolicyPolicyDenyStatement0
from .storage import StorageReplicaBucketPolicyPolicyPolicyDocument as StorageReplicaBucketPolicyPolicyPolicyDocument
from .storage import StorageReplicaBucketPublicAccessBlockConfiguration as StorageReplicaBucketPublicAccessBlockConfiguration
from .storage import StorageReplicaBucketServerSideEncryptionRule as StorageReplicaBucketServerSideEncryptionRule

__all__: list[str] = ['AMI_ID', 'ARN', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'AppName', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'DenyStatement', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'If', 'ImportValue', 'Join', 'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NUMBER', 'Not', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType', 'Ref', 'RefDict', 'RefList', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'SUBNET_ID', 'Select', 'Split', 'StorageBucket', 'StorageBucketBucketEncryption', 'StorageBucketDeleteMarkerReplication', 'StorageBucketLoggingConfiguration', 'StorageBucketMetadataTableEncryptionConfiguration', 'StorageBucketPolicyPolicy', 'StorageBucketPolicyPolicyAllowStatement1', 'StorageBucketPolicyPolicyDenyStatement0', 'StorageBucketPolicyPolicyPolicyDocument', 'StorageBucketPublicAccessBlockConfiguration', 'StorageBucketReplicationConfiguration', 'StorageBucketReplicationDestination', 'StorageBucketReplicationRule', 'StorageBucketServerSideEncryptionRule', 'StorageLogBucket', 'StorageLogBucketBucketEncryption', 'StorageLogBucketDefaultRetention', 'StorageLogBucketDeleteMarkerReplication', 'StorageLogBucketMetadataTableEncryptionConfiguration', 'StorageLogBucketObjectLockConfiguration', 'StorageLogBucketObjectLockRule', 'StorageLogBucketPolicyPolicy', 'StorageLogBucketPolicyPolicyAllowStatement1', 'StorageLogBucketPolicyPolicyDenyStatement0', 'StorageLogBucketPolicyPolicyPolicyDocument', 'StorageLogBucketPublicAccessBlockConfiguration', 'StorageLogBucketServerSideEncryptionRule', 'StorageReplicaBucket', 'StorageReplicaBucketBucketEncryption', 'StorageReplicaBucketDeleteMarkerReplication', 'StorageReplicaBucketMetadataTableEncryptionConfiguration', 'StorageReplicaBucketPolicyPolicy', 'StorageReplicaBucketPolicyPolicyAllowStatement1', 'StorageReplicaBucketPolicyPolicyDenyStatement0', 'StorageReplicaBucketPolicyPolicyPolicyDocument', 'StorageReplicaBucketPublicAccessBlockConfiguration', 'StorageReplicaBucketServerSideEncryptionRule', 'StorageReplicationPolicy', 'StorageReplicationPolicyAllowStatement0', 'StorageReplicationPolicyAllowStatement1', 'StorageReplicationPolicyAllowStatement2', 'StorageReplicationPolicyPolicyDocument', 'StorageReplicationRole', 'StorageReplicationRoleAllowStatement0', 'StorageReplicationRoleAssumeRolePolicyDocument', 'Sub', 'TemplateCondition', 'TestQ', 'Transform', 'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
