"""
AWS MEDIAPACKAGEV2 CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:22Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# Constants
# ============================================================


class AdMarkerDash:
    BINARY = "BINARY"
    XML = "XML"


class AdMarkerHls:
    DATERANGE = "DATERANGE"
    SCTE35_ENHANCED = "SCTE35_ENHANCED"


class CmafEncryptionMethod:
    CENC = "CENC"
    CBCS = "CBCS"


class ConflictExceptionType:
    RESOURCE_IN_USE = "RESOURCE_IN_USE"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    IDEMPOTENT_PARAMETER_MISMATCH = "IDEMPOTENT_PARAMETER_MISMATCH"
    CONFLICTING_OPERATION = "CONFLICTING_OPERATION"


class ContainerType:
    TS = "TS"
    CMAF = "CMAF"
    ISM = "ISM"


class DashCompactness:
    STANDARD = "STANDARD"
    NONE = "NONE"


class DashDrmSignaling:
    INDIVIDUAL = "INDIVIDUAL"
    REFERENCED = "REFERENCED"


class DashPeriodTrigger:
    AVAILS = "AVAILS"
    DRM_KEY_ROTATION = "DRM_KEY_ROTATION"
    SOURCE_CHANGES = "SOURCE_CHANGES"
    SOURCE_DISRUPTIONS = "SOURCE_DISRUPTIONS"
    NONE = "NONE"


class DashProfile:
    DVB_DASH = "DVB_DASH"


class DashSegmentTemplateFormat:
    NUMBER_WITH_TIMELINE = "NUMBER_WITH_TIMELINE"


class DashTtmlProfile:
    IMSC_1 = "IMSC_1"
    EBU_TT_D_101 = "EBU_TT_D_101"


class DashUtcTimingMode:
    HTTP_HEAD = "HTTP_HEAD"
    HTTP_ISO = "HTTP_ISO"
    HTTP_XSDATE = "HTTP_XSDATE"
    UTC_DIRECT = "UTC_DIRECT"


class DrmSystem:
    CLEAR_KEY_AES_128 = "CLEAR_KEY_AES_128"
    FAIRPLAY = "FAIRPLAY"
    PLAYREADY = "PLAYREADY"
    WIDEVINE = "WIDEVINE"
    IRDETO = "IRDETO"


class EndpointErrorCondition:
    STALE_MANIFEST = "STALE_MANIFEST"
    INCOMPLETE_MANIFEST = "INCOMPLETE_MANIFEST"
    MISSING_DRM_KEY = "MISSING_DRM_KEY"
    SLATE_INPUT = "SLATE_INPUT"


class HarvestJobStatus:
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class InputType:
    HLS = "HLS"
    CMAF = "CMAF"


class IsmEncryptionMethod:
    CENC = "CENC"


class MssManifestLayout:
    FULL = "FULL"
    COMPACT = "COMPACT"


class PresetSpeke20Audio:
    PRESET_AUDIO_1 = "PRESET_AUDIO_1"
    PRESET_AUDIO_2 = "PRESET_AUDIO_2"
    PRESET_AUDIO_3 = "PRESET_AUDIO_3"
    SHARED = "SHARED"
    UNENCRYPTED = "UNENCRYPTED"


class PresetSpeke20Video:
    PRESET_VIDEO_1 = "PRESET_VIDEO_1"
    PRESET_VIDEO_2 = "PRESET_VIDEO_2"
    PRESET_VIDEO_3 = "PRESET_VIDEO_3"
    PRESET_VIDEO_4 = "PRESET_VIDEO_4"
    PRESET_VIDEO_5 = "PRESET_VIDEO_5"
    PRESET_VIDEO_6 = "PRESET_VIDEO_6"
    PRESET_VIDEO_7 = "PRESET_VIDEO_7"
    PRESET_VIDEO_8 = "PRESET_VIDEO_8"
    SHARED = "SHARED"
    UNENCRYPTED = "UNENCRYPTED"


class ResourceTypeNotFound:
    CHANNEL_GROUP = "CHANNEL_GROUP"
    CHANNEL = "CHANNEL"
    ORIGIN_ENDPOINT = "ORIGIN_ENDPOINT"
    HARVEST_JOB = "HARVEST_JOB"


class ScteFilter:
    SPLICE_INSERT = "SPLICE_INSERT"
    BREAK = "BREAK"
    PROVIDER_ADVERTISEMENT = "PROVIDER_ADVERTISEMENT"
    DISTRIBUTOR_ADVERTISEMENT = "DISTRIBUTOR_ADVERTISEMENT"
    PROVIDER_PLACEMENT_OPPORTUNITY = "PROVIDER_PLACEMENT_OPPORTUNITY"
    DISTRIBUTOR_PLACEMENT_OPPORTUNITY = "DISTRIBUTOR_PLACEMENT_OPPORTUNITY"
    PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY = "PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY"
    DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY = (
        "DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY"
    )
    PROGRAM = "PROGRAM"


class ScteInSegments:
    NONE = "NONE"
    ALL = "ALL"


class TsEncryptionMethod:
    AES_128 = "AES_128"
    SAMPLE_AES = "SAMPLE_AES"


class ValidationExceptionType:
    CONTAINER_TYPE_IMMUTABLE = "CONTAINER_TYPE_IMMUTABLE"
    INVALID_PAGINATION_TOKEN = "INVALID_PAGINATION_TOKEN"
    INVALID_PAGINATION_MAX_RESULTS = "INVALID_PAGINATION_MAX_RESULTS"
    INVALID_POLICY = "INVALID_POLICY"
    INVALID_ROLE_ARN = "INVALID_ROLE_ARN"
    MANIFEST_NAME_COLLISION = "MANIFEST_NAME_COLLISION"
    ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH = (
        "ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH"
    )
    CENC_IV_INCOMPATIBLE = "CENC_IV_INCOMPATIBLE"
    ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE = (
        "ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE"
    )
    ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE = (
        "ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE"
    )
    ENCRYPTION_CONTRACT_UNENCRYPTED = "ENCRYPTION_CONTRACT_UNENCRYPTED"
    ENCRYPTION_CONTRACT_SHARED = "ENCRYPTION_CONTRACT_SHARED"
    NUM_MANIFESTS_LOW = "NUM_MANIFESTS_LOW"
    NUM_MANIFESTS_HIGH = "NUM_MANIFESTS_HIGH"
    MANIFEST_DRM_SYSTEMS_INCOMPATIBLE = "MANIFEST_DRM_SYSTEMS_INCOMPATIBLE"
    DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE = (
        "DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE"
    )
    ROLE_ARN_NOT_ASSUMABLE = "ROLE_ARN_NOT_ASSUMABLE"
    ROLE_ARN_LENGTH_OUT_OF_RANGE = "ROLE_ARN_LENGTH_OUT_OF_RANGE"
    ROLE_ARN_INVALID_FORMAT = "ROLE_ARN_INVALID_FORMAT"
    URL_INVALID = "URL_INVALID"
    URL_SCHEME = "URL_SCHEME"
    URL_USER_INFO = "URL_USER_INFO"
    URL_PORT = "URL_PORT"
    URL_UNKNOWN_HOST = "URL_UNKNOWN_HOST"
    URL_LOCAL_ADDRESS = "URL_LOCAL_ADDRESS"
    URL_LOOPBACK_ADDRESS = "URL_LOOPBACK_ADDRESS"
    URL_LINK_LOCAL_ADDRESS = "URL_LINK_LOCAL_ADDRESS"
    URL_MULTICAST_ADDRESS = "URL_MULTICAST_ADDRESS"
    MEMBER_INVALID = "MEMBER_INVALID"
    MEMBER_MISSING = "MEMBER_MISSING"
    MEMBER_MIN_VALUE = "MEMBER_MIN_VALUE"
    MEMBER_MAX_VALUE = "MEMBER_MAX_VALUE"
    MEMBER_MIN_LENGTH = "MEMBER_MIN_LENGTH"
    MEMBER_MAX_LENGTH = "MEMBER_MAX_LENGTH"
    MEMBER_INVALID_ENUM_VALUE = "MEMBER_INVALID_ENUM_VALUE"
    MEMBER_DOES_NOT_MATCH_PATTERN = "MEMBER_DOES_NOT_MATCH_PATTERN"
    INVALID_MANIFEST_FILTER = "INVALID_MANIFEST_FILTER"
    INVALID_DRM_SETTINGS = "INVALID_DRM_SETTINGS"
    INVALID_TIME_DELAY_SECONDS = "INVALID_TIME_DELAY_SECONDS"
    END_TIME_EARLIER_THAN_START_TIME = "END_TIME_EARLIER_THAN_START_TIME"
    TS_CONTAINER_TYPE_WITH_DASH_MANIFEST = "TS_CONTAINER_TYPE_WITH_DASH_MANIFEST"
    DIRECT_MODE_WITH_TIMING_SOURCE = "DIRECT_MODE_WITH_TIMING_SOURCE"
    NONE_MODE_WITH_TIMING_SOURCE = "NONE_MODE_WITH_TIMING_SOURCE"
    TIMING_SOURCE_MISSING = "TIMING_SOURCE_MISSING"
    UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION = (
        "UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION"
    )
    PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES = (
        "PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES"
    )
    DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS = (
        "DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS"
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION = (
        "ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION"
    )
    SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY = "SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY"
    HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION = (
        "HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION"
    )
    HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT = (
        "HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT"
    )
    TOO_MANY_IN_PROGRESS_HARVEST_JOBS = "TOO_MANY_IN_PROGRESS_HARVEST_JOBS"
    HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION = "HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION"
    INVALID_HARVEST_JOB_DURATION = "INVALID_HARVEST_JOB_DURATION"
    HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE = (
        "HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE"
    )
    HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION = (
        "HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION"
    )
    HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED = (
        "HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED"
    )
    CLIP_START_TIME_WITH_START_OR_END = "CLIP_START_TIME_WITH_START_OR_END"
    START_TAG_TIME_OFFSET_INVALID = "START_TAG_TIME_OFFSET_INVALID"
    INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION = (
        "INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION"
    )
    DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE = (
        "DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE"
    )
    INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION = (
        "INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION"
    )
    INCOMPATIBLE_XML_ENCODING = "INCOMPATIBLE_XML_ENCODING"
    CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE = (
        "CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE"
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING = (
        "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING"
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION = (
        "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION"
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION = (
        "ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION"
    )
    TS_CONTAINER_TYPE_WITH_MSS_MANIFEST = "TS_CONTAINER_TYPE_WITH_MSS_MANIFEST"
    CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST = "CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST"
    ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST = "ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST"
    ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST = "ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST"
    ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST = "ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST"
    ISM_CONTAINER_TYPE_WITH_SCTE = "ISM_CONTAINER_TYPE_WITH_SCTE"
    ISM_CONTAINER_WITH_KEY_ROTATION = "ISM_CONTAINER_WITH_KEY_ROTATION"
    BATCH_GET_SECRET_VALUE_DENIED = "BATCH_GET_SECRET_VALUE_DENIED"
    GET_SECRET_VALUE_DENIED = "GET_SECRET_VALUE_DENIED"
    DESCRIBE_SECRET_DENIED = "DESCRIBE_SECRET_DENIED"
    INVALID_SECRET_FORMAT = "INVALID_SECRET_FORMAT"
    SECRET_IS_NOT_ONE_KEY_VALUE_PAIR = "SECRET_IS_NOT_ONE_KEY_VALUE_PAIR"
    INVALID_SECRET_KEY = "INVALID_SECRET_KEY"
    INVALID_SECRET_VALUE = "INVALID_SECRET_VALUE"
    SECRET_ARN_RESOURCE_NOT_FOUND = "SECRET_ARN_RESOURCE_NOT_FOUND"
    DECRYPT_SECRET_FAILED = "DECRYPT_SECRET_FAILED"
    TOO_MANY_SECRETS = "TOO_MANY_SECRETS"
    DUPLICATED_SECRET = "DUPLICATED_SECRET"
    MALFORMED_SECRET_ARN = "MALFORMED_SECRET_ARN"
    SECRET_FROM_DIFFERENT_ACCOUNT = "SECRET_FROM_DIFFERENT_ACCOUNT"
    SECRET_FROM_DIFFERENT_REGION = "SECRET_FROM_DIFFERENT_REGION"
    INVALID_SECRET = "INVALID_SECRET"
    RESOURCE_NOT_IN_SAME_REGION = "RESOURCE_NOT_IN_SAME_REGION"
    CERTIFICATE_RESOURCE_NOT_FOUND = "CERTIFICATE_RESOURCE_NOT_FOUND"
    CERTIFICATE_ACCESS_DENIED = "CERTIFICATE_ACCESS_DENIED"
    DESCRIBE_CERTIFICATE_FAILED = "DESCRIBE_CERTIFICATE_FAILED"
    INVALID_CERTIFICATE_STATUS = "INVALID_CERTIFICATE_STATUS"
    INVALID_CERTIFICATE_KEY_ALGORITHM = "INVALID_CERTIFICATE_KEY_ALGORITHM"
    INVALID_CERTIFICATE_SIGNATURE_ALGORITHM = "INVALID_CERTIFICATE_SIGNATURE_ALGORITHM"
    MISSING_CERTIFICATE_DOMAIN_NAME = "MISSING_CERTIFICATE_DOMAIN_NAME"
    INVALID_ARN = "INVALID_ARN"


# PropertyType submodules
from . import Channel as _Channel
from . import OriginEndpoint as _OriginEndpoint
from . import OriginEndpointPolicy as _OriginEndpointPolicy


# Resources
# ============================================================


@dataclass
class Channel(CloudFormationResource):
    """Channel resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-channel.html

    CloudFormation type: AWS::MediaPackageV2::Channel
    """

    _resource_type: ClassVar[str] = "AWS::MediaPackageV2::Channel"

    channel_group_name: str | None = None
    channel_name: str | None = None
    description: str | None = None
    input_switch_configuration: _Channel.InputSwitchConfiguration | None = None
    input_type: str | None = None
    output_header_configuration: _Channel.OutputHeaderConfiguration | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    MODIFIEDAT: ClassVar[str] = "ModifiedAt"
    INGESTENDPOINTS: ClassVar[str] = "IngestEndpoints"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    ARN: ClassVar[str] = "Arn"
    INGESTENDPOINTURLS: ClassVar[str] = "IngestEndpointUrls"


@dataclass
class ChannelGroup(CloudFormationResource):
    """ChannelGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-channelgroup.html

    CloudFormation type: AWS::MediaPackageV2::ChannelGroup
    """

    _resource_type: ClassVar[str] = "AWS::MediaPackageV2::ChannelGroup"

    channel_group_name: str | None = None
    description: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    MODIFIEDAT: ClassVar[str] = "ModifiedAt"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    ARN: ClassVar[str] = "Arn"
    EGRESSDOMAIN: ClassVar[str] = "EgressDomain"


@dataclass
class ChannelPolicy(CloudFormationResource):
    """ChannelPolicy resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-channelpolicy.html

    CloudFormation type: AWS::MediaPackageV2::ChannelPolicy
    """

    _resource_type: ClassVar[str] = "AWS::MediaPackageV2::ChannelPolicy"

    channel_group_name: str | None = None
    channel_name: str | None = None
    policy: dict[str, Any] | None = None


@dataclass
class OriginEndpoint(CloudFormationResource):
    """OriginEndpoint resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-originendpoint.html

    CloudFormation type: AWS::MediaPackageV2::OriginEndpoint
    """

    _resource_type: ClassVar[str] = "AWS::MediaPackageV2::OriginEndpoint"

    channel_group_name: str | None = None
    channel_name: str | None = None
    container_type: str | None = None
    origin_endpoint_name: str | None = None
    dash_manifests: list[_OriginEndpoint.DashManifestConfiguration] = field(
        default_factory=list
    )
    description: str | None = None
    force_endpoint_error_configuration: (
        _OriginEndpoint.ForceEndpointErrorConfiguration | None
    ) = None
    hls_manifests: list[_OriginEndpoint.HlsManifestConfiguration] = field(
        default_factory=list
    )
    low_latency_hls_manifests: list[
        _OriginEndpoint.LowLatencyHlsManifestConfiguration
    ] = field(default_factory=list)
    mss_manifests: list[_OriginEndpoint.MssManifestConfiguration] = field(
        default_factory=list
    )
    segment: _OriginEndpoint.Segment | None = None
    startover_window_seconds: int | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    MODIFIEDAT: ClassVar[str] = "ModifiedAt"
    LOWLATENCYHLSMANIFESTURLS: ClassVar[str] = "LowLatencyHlsManifestUrls"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    MSSMANIFESTURLS: ClassVar[str] = "MssManifestUrls"
    ARN: ClassVar[str] = "Arn"
    HLSMANIFESTURLS: ClassVar[str] = "HlsManifestUrls"
    DASHMANIFESTURLS: ClassVar[str] = "DashManifestUrls"


@dataclass
class OriginEndpointPolicy(CloudFormationResource):
    """OriginEndpointPolicy resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-originendpointpolicy.html

    CloudFormation type: AWS::MediaPackageV2::OriginEndpointPolicy
    """

    _resource_type: ClassVar[str] = "AWS::MediaPackageV2::OriginEndpointPolicy"

    channel_group_name: str | None = None
    channel_name: str | None = None
    origin_endpoint_name: str | None = None
    policy: dict[str, Any] | None = None
    cdn_auth_configuration: _OriginEndpointPolicy.CdnAuthConfiguration | None = None


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Channel.IngestEndpoint = _Channel.IngestEndpoint
Channel.InputSwitchConfiguration = _Channel.InputSwitchConfiguration
Channel.OutputHeaderConfiguration = _Channel.OutputHeaderConfiguration
OriginEndpoint.DashBaseUrl = _OriginEndpoint.DashBaseUrl
OriginEndpoint.DashDvbFontDownload = _OriginEndpoint.DashDvbFontDownload
OriginEndpoint.DashDvbMetricsReporting = _OriginEndpoint.DashDvbMetricsReporting
OriginEndpoint.DashDvbSettings = _OriginEndpoint.DashDvbSettings
OriginEndpoint.DashManifestConfiguration = _OriginEndpoint.DashManifestConfiguration
OriginEndpoint.DashProgramInformation = _OriginEndpoint.DashProgramInformation
OriginEndpoint.DashSubtitleConfiguration = _OriginEndpoint.DashSubtitleConfiguration
OriginEndpoint.DashTtmlConfiguration = _OriginEndpoint.DashTtmlConfiguration
OriginEndpoint.DashUtcTiming = _OriginEndpoint.DashUtcTiming
OriginEndpoint.Encryption = _OriginEndpoint.Encryption
OriginEndpoint.EncryptionContractConfiguration = (
    _OriginEndpoint.EncryptionContractConfiguration
)
OriginEndpoint.EncryptionMethod = _OriginEndpoint.EncryptionMethod
OriginEndpoint.FilterConfiguration = _OriginEndpoint.FilterConfiguration
OriginEndpoint.ForceEndpointErrorConfiguration = (
    _OriginEndpoint.ForceEndpointErrorConfiguration
)
OriginEndpoint.HlsManifestConfiguration = _OriginEndpoint.HlsManifestConfiguration
OriginEndpoint.LowLatencyHlsManifestConfiguration = (
    _OriginEndpoint.LowLatencyHlsManifestConfiguration
)
OriginEndpoint.MssManifestConfiguration = _OriginEndpoint.MssManifestConfiguration
OriginEndpoint.Scte = _OriginEndpoint.Scte
OriginEndpoint.ScteDash = _OriginEndpoint.ScteDash
OriginEndpoint.ScteHls = _OriginEndpoint.ScteHls
OriginEndpoint.Segment = _OriginEndpoint.Segment
OriginEndpoint.SpekeKeyProvider = _OriginEndpoint.SpekeKeyProvider
OriginEndpoint.StartTag = _OriginEndpoint.StartTag
OriginEndpointPolicy.CdnAuthConfiguration = _OriginEndpointPolicy.CdnAuthConfiguration
