"""
AWS CODEGURUPROFILER CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class ActionGroup:
    AGENTPERMISSIONS = "agentPermissions"


class AgentParameterField:
    SAMPLINGINTERVALINMILLISECONDS = "SamplingIntervalInMilliseconds"
    REPORTINGINTERVALINMILLISECONDS = "ReportingIntervalInMilliseconds"
    MINIMUMTIMEFORREPORTINGINMILLISECONDS = "MinimumTimeForReportingInMilliseconds"
    MEMORYUSAGELIMITPERCENT = "MemoryUsageLimitPercent"
    MAXSTACKDEPTH = "MaxStackDepth"


class AggregationPeriod:
    PT5M = "PT5M"
    PT1H = "PT1H"
    P1D = "P1D"


class ComputePlatform:
    DEFAULT = "Default"
    AWSLAMBDA = "AWSLambda"


class EventPublisher:
    ANOMALYDETECTION = "AnomalyDetection"


class FeedbackType:
    POSITIVE = "Positive"
    NEGATIVE = "Negative"


class MetadataField:
    COMPUTEPLATFORM = "ComputePlatform"
    AGENTID = "AgentId"
    AWSREQUESTID = "AwsRequestId"
    EXECUTIONENVIRONMENT = "ExecutionEnvironment"
    LAMBDAFUNCTIONARN = "LambdaFunctionArn"
    LAMBDAMEMORYLIMITINMB = "LambdaMemoryLimitInMB"
    LAMBDAREMAININGTIMEINMILLISECONDS = "LambdaRemainingTimeInMilliseconds"
    LAMBDATIMEGAPBETWEENINVOKESINMILLISECONDS = (
        "LambdaTimeGapBetweenInvokesInMilliseconds"
    )
    LAMBDAPREVIOUSEXECUTIONTIMEINMILLISECONDS = (
        "LambdaPreviousExecutionTimeInMilliseconds"
    )


class MetricType:
    AGGREGATEDRELATIVETOTALTIME = "AggregatedRelativeTotalTime"


class OrderBy:
    TIMESTAMPDESCENDING = "TimestampDescending"
    TIMESTAMPASCENDING = "TimestampAscending"


# PropertyType submodules
from . import ProfilingGroup as _ProfilingGroup


# Resources
# ============================================================


@dataclass
class ProfilingGroup(CloudFormationResource):
    """ProfilingGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeguruprofiler-profilinggroup.html

    CloudFormation type: AWS::CodeGuruProfiler::ProfilingGroup
    """

    _resource_type: ClassVar[str] = "AWS::CodeGuruProfiler::ProfilingGroup"

    profiling_group_name: str | None = None
    agent_permissions: _ProfilingGroup.AgentPermissions | None = None
    anomaly_detection_notification_configuration: list[_ProfilingGroup.Channel] = field(
        default_factory=list
    )
    compute_platform: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
ProfilingGroup.AgentPermissions = PropertyTypeDescriptor(
    _ProfilingGroup.AgentPermissions, "AgentPermissions"
)
ProfilingGroup.Channel = PropertyTypeDescriptor(_ProfilingGroup.Channel, "Channel")
