"""
AWS ELASTICLOADBALANCINGV2 CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:21Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class ActionTypeEnum:
    FORWARD = "forward"
    AUTHENTICATE_OIDC = "authenticate-oidc"
    AUTHENTICATE_COGNITO = "authenticate-cognito"
    REDIRECT = "redirect"
    FIXED_RESPONSE = "fixed-response"
    JWT_VALIDATION = "jwt-validation"


class AdvertiseTrustStoreCaNamesEnum:
    ON = "on"
    OFF = "off"


class AnomalyResultEnum:
    ANOMALOUS = "anomalous"
    NORMAL = "normal"


class AuthenticateCognitoActionConditionalBehaviorEnum:
    DENY = "deny"
    ALLOW = "allow"
    AUTHENTICATE = "authenticate"


class AuthenticateOidcActionConditionalBehaviorEnum:
    DENY = "deny"
    ALLOW = "allow"
    AUTHENTICATE = "authenticate"


class CapacityReservationStateEnum:
    PROVISIONED = "provisioned"
    PENDING = "pending"
    REBALANCING = "rebalancing"
    FAILED = "failed"


class DescribeTargetHealthInputIncludeEnum:
    ANOMALYDETECTION = "AnomalyDetection"
    ALL = "All"


class EnablePrefixForIpv6SourceNatEnum:
    ON = "on"
    OFF = "off"


class EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum:
    ON = "on"
    OFF = "off"


class IpAddressType:
    IPV4 = "ipv4"
    DUALSTACK = "dualstack"
    DUALSTACK_WITHOUT_PUBLIC_IPV4 = "dualstack-without-public-ipv4"


class JwtValidationActionAdditionalClaimFormatEnum:
    SINGLE_STRING = "single-string"
    STRING_ARRAY = "string-array"
    SPACE_SEPARATED_VALUES = "space-separated-values"


class LoadBalancerSchemeEnum:
    INTERNET_FACING = "internet-facing"
    INTERNAL = "internal"


class LoadBalancerStateEnum:
    ACTIVE = "active"
    PROVISIONING = "provisioning"
    ACTIVE_IMPAIRED = "active_impaired"
    FAILED = "failed"


class LoadBalancerTypeEnum:
    APPLICATION = "application"
    NETWORK = "network"
    GATEWAY = "gateway"


class MitigationInEffectEnum:
    YES = "yes"
    NO = "no"


class ProtocolEnum:
    HTTP = "HTTP"
    HTTPS = "HTTPS"
    TCP = "TCP"
    TLS = "TLS"
    UDP = "UDP"
    TCP_UDP = "TCP_UDP"
    GENEVE = "GENEVE"
    QUIC = "QUIC"
    TCP_QUIC = "TCP_QUIC"


class RedirectActionStatusCodeEnum:
    HTTP_301 = "HTTP_301"
    HTTP_302 = "HTTP_302"


class RemoveIpamPoolEnum:
    IPV4 = "ipv4"


class RevocationType:
    CRL = "CRL"


class TargetAdministrativeOverrideReasonEnum:
    ADMINISTRATIVEOVERRIDE_UNKNOWN = "AdministrativeOverride.Unknown"
    ADMINISTRATIVEOVERRIDE_NOOVERRIDE = "AdministrativeOverride.NoOverride"
    ADMINISTRATIVEOVERRIDE_ZONALSHIFTACTIVE = "AdministrativeOverride.ZonalShiftActive"
    ADMINISTRATIVEOVERRIDE_ZONALSHIFTDELEGATEDTODNS = (
        "AdministrativeOverride.ZonalShiftDelegatedToDns"
    )


class TargetAdministrativeOverrideStateEnum:
    UNKNOWN = "unknown"
    NO_OVERRIDE = "no_override"
    ZONAL_SHIFT_ACTIVE = "zonal_shift_active"
    ZONAL_SHIFT_DELEGATED_TO_DNS = "zonal_shift_delegated_to_dns"


class TargetGroupIpAddressTypeEnum:
    IPV4 = "ipv4"
    IPV6 = "ipv6"


class TargetHealthReasonEnum:
    ELB_REGISTRATIONINPROGRESS = "Elb.RegistrationInProgress"
    ELB_INITIALHEALTHCHECKING = "Elb.InitialHealthChecking"
    TARGET_RESPONSECODEMISMATCH = "Target.ResponseCodeMismatch"
    TARGET_TIMEOUT = "Target.Timeout"
    TARGET_FAILEDHEALTHCHECKS = "Target.FailedHealthChecks"
    TARGET_NOTREGISTERED = "Target.NotRegistered"
    TARGET_NOTINUSE = "Target.NotInUse"
    TARGET_DEREGISTRATIONINPROGRESS = "Target.DeregistrationInProgress"
    TARGET_INVALIDSTATE = "Target.InvalidState"
    TARGET_IPUNUSABLE = "Target.IpUnusable"
    TARGET_HEALTHCHECKDISABLED = "Target.HealthCheckDisabled"
    ELB_INTERNALERROR = "Elb.InternalError"


class TargetHealthStateEnum:
    INITIAL = "initial"
    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    UNHEALTHY_DRAINING = "unhealthy.draining"
    UNUSED = "unused"
    DRAINING = "draining"
    UNAVAILABLE = "unavailable"


class TargetTypeEnum:
    INSTANCE = "instance"
    IP = "ip"
    LAMBDA = "lambda"
    ALB = "alb"


class TransformTypeEnum:
    HOST_HEADER_REWRITE = "host-header-rewrite"
    URL_REWRITE = "url-rewrite"


class TrustStoreAssociationStatusEnum:
    ACTIVE = "active"
    REMOVED = "removed"


class TrustStoreStatus:
    ACTIVE = "ACTIVE"
    CREATING = "CREATING"


# PropertyType submodules
from . import Listener as _Listener
from . import ListenerCertificate as _ListenerCertificate
from . import ListenerRule as _ListenerRule
from . import LoadBalancer as _LoadBalancer
from . import TargetGroup as _TargetGroup
from . import TrustStoreRevocation as _TrustStoreRevocation


# Resources
# ============================================================


@dataclass
class Listener(CloudFormationResource):
    """Listener resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::Listener
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::Listener"

    default_actions: list[DslValue[_Listener.Action]] = field(default_factory=list)
    load_balancer_arn: DslValue[str] | None = None
    alpn_policy: list[DslValue[str]] = field(default_factory=list)
    certificates: list[DslValue[_Listener.Certificate]] = field(default_factory=list)
    listener_attributes: list[DslValue[_Listener.ListenerAttribute]] = field(
        default_factory=list
    )
    mutual_authentication: DslValue[_Listener.MutualAuthentication] | None = None
    port: DslValue[int] | None = None
    protocol: DslValue[str] | None = None
    ssl_policy: DslValue[str] | None = None

    # GetAtt attributes
    LISTENERARN: ClassVar[str] = "ListenerArn"

    # PropertyType descriptors for nested GetAtt support
    Action = PropertyTypeDescriptor(_Listener.Action, "Action")
    AuthenticateCognitoConfig = PropertyTypeDescriptor(
        _Listener.AuthenticateCognitoConfig, "AuthenticateCognitoConfig"
    )
    AuthenticateOidcConfig = PropertyTypeDescriptor(
        _Listener.AuthenticateOidcConfig, "AuthenticateOidcConfig"
    )
    Certificate = PropertyTypeDescriptor(_Listener.Certificate, "Certificate")
    FixedResponseConfig = PropertyTypeDescriptor(
        _Listener.FixedResponseConfig, "FixedResponseConfig"
    )
    ForwardConfig = PropertyTypeDescriptor(_Listener.ForwardConfig, "ForwardConfig")
    JwtValidationActionAdditionalClaim = PropertyTypeDescriptor(
        _Listener.JwtValidationActionAdditionalClaim,
        "JwtValidationActionAdditionalClaim",
    )
    JwtValidationConfig = PropertyTypeDescriptor(
        _Listener.JwtValidationConfig, "JwtValidationConfig"
    )
    ListenerAttribute = PropertyTypeDescriptor(
        _Listener.ListenerAttribute, "ListenerAttribute"
    )
    MutualAuthentication = PropertyTypeDescriptor(
        _Listener.MutualAuthentication, "MutualAuthentication"
    )
    RedirectConfig = PropertyTypeDescriptor(_Listener.RedirectConfig, "RedirectConfig")
    TargetGroupStickinessConfig = PropertyTypeDescriptor(
        _Listener.TargetGroupStickinessConfig, "TargetGroupStickinessConfig"
    )
    TargetGroupTuple = PropertyTypeDescriptor(
        _Listener.TargetGroupTuple, "TargetGroupTuple"
    )


@dataclass
class ListenerCertificate(CloudFormationResource):
    """ListenerCertificate resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listenercertificate.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::ListenerCertificate"

    certificates: list[DslValue[_ListenerCertificate.Certificate]] = field(
        default_factory=list
    )
    listener_arn: DslValue[str] | None = None

    # PropertyType descriptors for nested GetAtt support
    Certificate = PropertyTypeDescriptor(
        _ListenerCertificate.Certificate, "Certificate"
    )


@dataclass
class ListenerRule(CloudFormationResource):
    """ListenerRule resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listenerrule.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::ListenerRule
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::ListenerRule"

    actions: list[DslValue[_ListenerRule.Action]] = field(default_factory=list)
    conditions: list[DslValue[_ListenerRule.RuleCondition]] = field(
        default_factory=list
    )
    priority: DslValue[int] | None = None
    listener_arn: DslValue[str] | None = None
    transforms: list[DslValue[_ListenerRule.Transform]] = field(default_factory=list)

    # GetAtt attributes
    ISDEFAULT: ClassVar[str] = "IsDefault"
    RULEARN: ClassVar[str] = "RuleArn"

    # PropertyType descriptors for nested GetAtt support
    Action = PropertyTypeDescriptor(_ListenerRule.Action, "Action")
    AuthenticateCognitoConfig = PropertyTypeDescriptor(
        _ListenerRule.AuthenticateCognitoConfig, "AuthenticateCognitoConfig"
    )
    AuthenticateOidcConfig = PropertyTypeDescriptor(
        _ListenerRule.AuthenticateOidcConfig, "AuthenticateOidcConfig"
    )
    FixedResponseConfig = PropertyTypeDescriptor(
        _ListenerRule.FixedResponseConfig, "FixedResponseConfig"
    )
    ForwardConfig = PropertyTypeDescriptor(_ListenerRule.ForwardConfig, "ForwardConfig")
    HostHeaderConfig = PropertyTypeDescriptor(
        _ListenerRule.HostHeaderConfig, "HostHeaderConfig"
    )
    HttpHeaderConfig = PropertyTypeDescriptor(
        _ListenerRule.HttpHeaderConfig, "HttpHeaderConfig"
    )
    HttpRequestMethodConfig = PropertyTypeDescriptor(
        _ListenerRule.HttpRequestMethodConfig, "HttpRequestMethodConfig"
    )
    JwtValidationActionAdditionalClaim = PropertyTypeDescriptor(
        _ListenerRule.JwtValidationActionAdditionalClaim,
        "JwtValidationActionAdditionalClaim",
    )
    JwtValidationConfig = PropertyTypeDescriptor(
        _ListenerRule.JwtValidationConfig, "JwtValidationConfig"
    )
    PathPatternConfig = PropertyTypeDescriptor(
        _ListenerRule.PathPatternConfig, "PathPatternConfig"
    )
    QueryStringConfig = PropertyTypeDescriptor(
        _ListenerRule.QueryStringConfig, "QueryStringConfig"
    )
    QueryStringKeyValue = PropertyTypeDescriptor(
        _ListenerRule.QueryStringKeyValue, "QueryStringKeyValue"
    )
    RedirectConfig = PropertyTypeDescriptor(
        _ListenerRule.RedirectConfig, "RedirectConfig"
    )
    RewriteConfig = PropertyTypeDescriptor(_ListenerRule.RewriteConfig, "RewriteConfig")
    RewriteConfigObject = PropertyTypeDescriptor(
        _ListenerRule.RewriteConfigObject, "RewriteConfigObject"
    )
    RuleCondition = PropertyTypeDescriptor(_ListenerRule.RuleCondition, "RuleCondition")
    SourceIpConfig = PropertyTypeDescriptor(
        _ListenerRule.SourceIpConfig, "SourceIpConfig"
    )
    TargetGroupStickinessConfig = PropertyTypeDescriptor(
        _ListenerRule.TargetGroupStickinessConfig, "TargetGroupStickinessConfig"
    )
    TargetGroupTuple = PropertyTypeDescriptor(
        _ListenerRule.TargetGroupTuple, "TargetGroupTuple"
    )
    Transform = PropertyTypeDescriptor(_ListenerRule.Transform, "Transform")


@dataclass
class LoadBalancer(CloudFormationResource):
    """LoadBalancer resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::LoadBalancer
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::LoadBalancer"

    enable_capacity_reservation_provision_stabilize: DslValue[bool] | None = None
    enable_prefix_for_ipv6_source_nat: DslValue[str] | None = None
    enforce_security_group_inbound_rules_on_private_link_traffic: (
        DslValue[str] | None
    ) = None
    ip_address_type: DslValue[str] | None = None
    ipv4_ipam_pool_id: DslValue[str] | None = None
    load_balancer_attributes: list[DslValue[_LoadBalancer.LoadBalancerAttribute]] = (
        field(default_factory=list)
    )
    minimum_load_balancer_capacity: (
        DslValue[_LoadBalancer.MinimumLoadBalancerCapacity] | None
    ) = None
    name: DslValue[str] | None = None
    scheme: DslValue[str] | None = None
    security_groups: list[DslValue[str]] = field(default_factory=list)
    subnet_mappings: list[DslValue[_LoadBalancer.SubnetMapping]] = field(
        default_factory=list
    )
    subnets: list[DslValue[str]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)
    type_: DslValue[str] | None = None

    # GetAtt attributes
    SECURITYGROUPS: ClassVar[str] = "SecurityGroups"
    LOADBALANCERNAME: ClassVar[str] = "LoadBalancerName"
    CANONICALHOSTEDZONEID: ClassVar[str] = "CanonicalHostedZoneID"
    LOADBALANCERARN: ClassVar[str] = "LoadBalancerArn"
    DNSNAME: ClassVar[str] = "DNSName"
    LOADBALANCERFULLNAME: ClassVar[str] = "LoadBalancerFullName"

    # PropertyType descriptors for nested GetAtt support
    LoadBalancerAttribute = PropertyTypeDescriptor(
        _LoadBalancer.LoadBalancerAttribute, "LoadBalancerAttribute"
    )
    MinimumLoadBalancerCapacity = PropertyTypeDescriptor(
        _LoadBalancer.MinimumLoadBalancerCapacity, "MinimumLoadBalancerCapacity"
    )
    SubnetMapping = PropertyTypeDescriptor(_LoadBalancer.SubnetMapping, "SubnetMapping")


@dataclass
class TargetGroup(CloudFormationResource):
    """TargetGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::TargetGroup
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::TargetGroup"

    health_check_enabled: DslValue[bool] | None = None
    health_check_interval_seconds: DslValue[int] | None = None
    health_check_path: DslValue[str] | None = None
    health_check_port: DslValue[str] | None = None
    health_check_protocol: DslValue[str] | None = None
    health_check_timeout_seconds: DslValue[int] | None = None
    healthy_threshold_count: DslValue[int] | None = None
    ip_address_type: DslValue[str] | None = None
    matcher: DslValue[_TargetGroup.Matcher] | None = None
    name: DslValue[str] | None = None
    port: DslValue[int] | None = None
    protocol: DslValue[str] | None = None
    protocol_version: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    target_control_port: DslValue[int] | None = None
    target_group_attributes: list[DslValue[_TargetGroup.TargetGroupAttribute]] = field(
        default_factory=list
    )
    target_type: DslValue[str] | None = None
    targets: list[DslValue[_TargetGroup.TargetDescription]] = field(
        default_factory=list
    )
    unhealthy_threshold_count: DslValue[int] | None = None
    vpc_id: DslValue[str] | None = None

    # GetAtt attributes
    TARGETGROUPARN: ClassVar[str] = "TargetGroupArn"
    LOADBALANCERARNS: ClassVar[str] = "LoadBalancerArns"
    TARGETGROUPFULLNAME: ClassVar[str] = "TargetGroupFullName"
    TARGETGROUPNAME: ClassVar[str] = "TargetGroupName"

    # PropertyType descriptors for nested GetAtt support
    Matcher = PropertyTypeDescriptor(_TargetGroup.Matcher, "Matcher")
    TargetDescription = PropertyTypeDescriptor(
        _TargetGroup.TargetDescription, "TargetDescription"
    )
    TargetGroupAttribute = PropertyTypeDescriptor(
        _TargetGroup.TargetGroupAttribute, "TargetGroupAttribute"
    )


@dataclass
class TrustStore(CloudFormationResource):
    """TrustStore resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-truststore.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::TrustStore
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::TrustStore"

    ca_certificates_bundle_s3_bucket: DslValue[str] | None = None
    ca_certificates_bundle_s3_key: DslValue[str] | None = None
    ca_certificates_bundle_s3_object_version: DslValue[str] | None = None
    name: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    TRUSTSTOREARN: ClassVar[str] = "TrustStoreArn"
    NUMBEROFCACERTIFICATES: ClassVar[str] = "NumberOfCaCertificates"


@dataclass
class TrustStoreRevocation(CloudFormationResource):
    """TrustStoreRevocation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-truststorerevocation.html

    CloudFormation type: AWS::ElasticLoadBalancingV2::TrustStoreRevocation
    """

    _resource_type: ClassVar[str] = "AWS::ElasticLoadBalancingV2::TrustStoreRevocation"

    revocation_contents: list[DslValue[_TrustStoreRevocation.RevocationContent]] = (
        field(default_factory=list)
    )
    trust_store_arn: DslValue[str] | None = None

    # GetAtt attributes
    TRUSTSTOREREVOCATIONS: ClassVar[str] = "TrustStoreRevocations"
    REVOCATIONID: ClassVar[str] = "RevocationId"

    # PropertyType descriptors for nested GetAtt support
    RevocationContent = PropertyTypeDescriptor(
        _TrustStoreRevocation.RevocationContent, "RevocationContent"
    )
    TrustStoreRevocation = PropertyTypeDescriptor(
        _TrustStoreRevocation.TrustStoreRevocation, "TrustStoreRevocation"
    )
