"""
AWS GUARDDUTY CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# Constants
# ============================================================


class AdminStatus:
    ENABLED = "ENABLED"
    DISABLE_IN_PROGRESS = "DISABLE_IN_PROGRESS"


class AutoEnableMembers:
    NEW = "NEW"
    ALL = "ALL"
    NONE = "NONE"


class ClusterStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"
    PENDING = "PENDING"


class CoverageFilterCriterionKey:
    ACCOUNT_ID = "ACCOUNT_ID"
    CLUSTER_NAME = "CLUSTER_NAME"
    RESOURCE_TYPE = "RESOURCE_TYPE"
    COVERAGE_STATUS = "COVERAGE_STATUS"
    ADDON_VERSION = "ADDON_VERSION"
    MANAGEMENT_TYPE = "MANAGEMENT_TYPE"
    EKS_CLUSTER_NAME = "EKS_CLUSTER_NAME"
    ECS_CLUSTER_NAME = "ECS_CLUSTER_NAME"
    AGENT_VERSION = "AGENT_VERSION"
    INSTANCE_ID = "INSTANCE_ID"
    CLUSTER_ARN = "CLUSTER_ARN"


class CoverageSortKey:
    ACCOUNT_ID = "ACCOUNT_ID"
    CLUSTER_NAME = "CLUSTER_NAME"
    COVERAGE_STATUS = "COVERAGE_STATUS"
    ISSUE = "ISSUE"
    ADDON_VERSION = "ADDON_VERSION"
    UPDATED_AT = "UPDATED_AT"
    EKS_CLUSTER_NAME = "EKS_CLUSTER_NAME"
    ECS_CLUSTER_NAME = "ECS_CLUSTER_NAME"
    INSTANCE_ID = "INSTANCE_ID"


class CoverageStatisticsType:
    COUNT_BY_RESOURCE_TYPE = "COUNT_BY_RESOURCE_TYPE"
    COUNT_BY_COVERAGE_STATUS = "COUNT_BY_COVERAGE_STATUS"


class CoverageStatus:
    HEALTHY = "HEALTHY"
    UNHEALTHY = "UNHEALTHY"


class CriterionKey:
    EC2_INSTANCE_ARN = "EC2_INSTANCE_ARN"
    SCAN_ID = "SCAN_ID"
    ACCOUNT_ID = "ACCOUNT_ID"
    GUARDDUTY_FINDING_ID = "GUARDDUTY_FINDING_ID"
    SCAN_START_TIME = "SCAN_START_TIME"
    SCAN_STATUS = "SCAN_STATUS"
    SCAN_TYPE = "SCAN_TYPE"


class DataSource:
    FLOW_LOGS = "FLOW_LOGS"
    CLOUD_TRAIL = "CLOUD_TRAIL"
    DNS_LOGS = "DNS_LOGS"
    S3_LOGS = "S3_LOGS"
    KUBERNETES_AUDIT_LOGS = "KUBERNETES_AUDIT_LOGS"
    EC2_MALWARE_SCAN = "EC2_MALWARE_SCAN"


class DataSourceStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class DestinationType:
    S3 = "S3"


class DetectionSource:
    AMAZON = "AMAZON"
    BITDEFENDER = "BITDEFENDER"


class DetectorFeature:
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    EBS_MALWARE_PROTECTION = "EBS_MALWARE_PROTECTION"
    RDS_LOGIN_EVENTS = "RDS_LOGIN_EVENTS"
    EKS_RUNTIME_MONITORING = "EKS_RUNTIME_MONITORING"
    LAMBDA_NETWORK_LOGS = "LAMBDA_NETWORK_LOGS"
    RUNTIME_MONITORING = "RUNTIME_MONITORING"


class DetectorFeatureResult:
    FLOW_LOGS = "FLOW_LOGS"
    CLOUD_TRAIL = "CLOUD_TRAIL"
    DNS_LOGS = "DNS_LOGS"
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    EBS_MALWARE_PROTECTION = "EBS_MALWARE_PROTECTION"
    RDS_LOGIN_EVENTS = "RDS_LOGIN_EVENTS"
    EKS_RUNTIME_MONITORING = "EKS_RUNTIME_MONITORING"
    LAMBDA_NETWORK_LOGS = "LAMBDA_NETWORK_LOGS"
    RUNTIME_MONITORING = "RUNTIME_MONITORING"


class DetectorStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class EbsSnapshotPreservation:
    NO_RETENTION = "NO_RETENTION"
    RETENTION_WITH_FINDING = "RETENTION_WITH_FINDING"


class EcsClusterStatus:
    ACTIVE = "ACTIVE"
    PROVISIONING = "PROVISIONING"
    DEPROVISIONING = "DEPROVISIONING"
    FAILED = "FAILED"
    INACTIVE = "INACTIVE"


class EcsLaunchType:
    FARGATE = "FARGATE"
    EC2 = "EC2"


class FeatureAdditionalConfiguration:
    EKS_ADDON_MANAGEMENT = "EKS_ADDON_MANAGEMENT"
    ECS_FARGATE_AGENT_MANAGEMENT = "ECS_FARGATE_AGENT_MANAGEMENT"
    EC2_AGENT_MANAGEMENT = "EC2_AGENT_MANAGEMENT"


class FeatureStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class Feedback:
    USEFUL = "USEFUL"
    NOT_USEFUL = "NOT_USEFUL"


class FilterAction:
    NOOP = "NOOP"
    ARCHIVE = "ARCHIVE"


class FindingPublishingFrequency:
    FIFTEEN_MINUTES = "FIFTEEN_MINUTES"
    ONE_HOUR = "ONE_HOUR"
    SIX_HOURS = "SIX_HOURS"


class FindingResourceType:
    EC2_INSTANCE = "EC2_INSTANCE"
    EC2_NETWORK_INTERFACE = "EC2_NETWORK_INTERFACE"
    S3_BUCKET = "S3_BUCKET"
    S3_OBJECT = "S3_OBJECT"
    ACCESS_KEY = "ACCESS_KEY"
    EKS_CLUSTER = "EKS_CLUSTER"
    KUBERNETES_WORKLOAD = "KUBERNETES_WORKLOAD"
    CONTAINER = "CONTAINER"
    ECS_CLUSTER = "ECS_CLUSTER"
    ECS_TASK = "ECS_TASK"
    AUTOSCALING_AUTO_SCALING_GROUP = "AUTOSCALING_AUTO_SCALING_GROUP"
    IAM_INSTANCE_PROFILE = "IAM_INSTANCE_PROFILE"
    CLOUDFORMATION_STACK = "CLOUDFORMATION_STACK"
    EC2_LAUNCH_TEMPLATE = "EC2_LAUNCH_TEMPLATE"
    EC2_VPC = "EC2_VPC"
    EC2_IMAGE = "EC2_IMAGE"


class FindingStatisticType:
    COUNT_BY_SEVERITY = "COUNT_BY_SEVERITY"


class FreeTrialFeatureResult:
    FLOW_LOGS = "FLOW_LOGS"
    CLOUD_TRAIL = "CLOUD_TRAIL"
    DNS_LOGS = "DNS_LOGS"
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    EBS_MALWARE_PROTECTION = "EBS_MALWARE_PROTECTION"
    RDS_LOGIN_EVENTS = "RDS_LOGIN_EVENTS"
    EKS_RUNTIME_MONITORING = "EKS_RUNTIME_MONITORING"
    LAMBDA_NETWORK_LOGS = "LAMBDA_NETWORK_LOGS"
    FARGATE_RUNTIME_MONITORING = "FARGATE_RUNTIME_MONITORING"
    EC2_RUNTIME_MONITORING = "EC2_RUNTIME_MONITORING"


class GroupByType:
    ACCOUNT = "ACCOUNT"
    DATE = "DATE"
    FINDING_TYPE = "FINDING_TYPE"
    RESOURCE = "RESOURCE"
    SEVERITY = "SEVERITY"


class IndicatorType:
    SUSPICIOUS_USER_AGENT = "SUSPICIOUS_USER_AGENT"
    SUSPICIOUS_NETWORK = "SUSPICIOUS_NETWORK"
    MALICIOUS_IP = "MALICIOUS_IP"
    TOR_IP = "TOR_IP"
    ATTACK_TACTIC = "ATTACK_TACTIC"
    HIGH_RISK_API = "HIGH_RISK_API"
    ATTACK_TECHNIQUE = "ATTACK_TECHNIQUE"
    UNUSUAL_API_FOR_ACCOUNT = "UNUSUAL_API_FOR_ACCOUNT"
    UNUSUAL_ASN_FOR_ACCOUNT = "UNUSUAL_ASN_FOR_ACCOUNT"
    UNUSUAL_ASN_FOR_USER = "UNUSUAL_ASN_FOR_USER"
    SUSPICIOUS_PROCESS = "SUSPICIOUS_PROCESS"
    MALICIOUS_DOMAIN = "MALICIOUS_DOMAIN"
    MALICIOUS_PROCESS = "MALICIOUS_PROCESS"
    CRYPTOMINING_IP = "CRYPTOMINING_IP"
    CRYPTOMINING_DOMAIN = "CRYPTOMINING_DOMAIN"
    CRYPTOMINING_PROCESS = "CRYPTOMINING_PROCESS"


class IpSetFormat:
    TXT = "TXT"
    STIX = "STIX"
    OTX_CSV = "OTX_CSV"
    ALIEN_VAULT = "ALIEN_VAULT"
    PROOF_POINT = "PROOF_POINT"
    FIRE_EYE = "FIRE_EYE"


class IpSetStatus:
    INACTIVE = "INACTIVE"
    ACTIVATING = "ACTIVATING"
    ACTIVE = "ACTIVE"
    DEACTIVATING = "DEACTIVATING"
    ERROR = "ERROR"
    DELETE_PENDING = "DELETE_PENDING"
    DELETED = "DELETED"


class KubernetesResourcesTypes:
    PODS = "PODS"
    JOBS = "JOBS"
    CRONJOBS = "CRONJOBS"
    DEPLOYMENTS = "DEPLOYMENTS"
    DAEMONSETS = "DAEMONSETS"
    STATEFULSETS = "STATEFULSETS"
    REPLICASETS = "REPLICASETS"
    REPLICATIONCONTROLLERS = "REPLICATIONCONTROLLERS"


class ListMalwareScansCriterionKey:
    RESOURCE_ARN = "RESOURCE_ARN"
    SCAN_ID = "SCAN_ID"
    ACCOUNT_ID = "ACCOUNT_ID"
    GUARDDUTY_FINDING_ID = "GUARDDUTY_FINDING_ID"
    RESOURCE_TYPE = "RESOURCE_TYPE"
    SCAN_START_TIME = "SCAN_START_TIME"
    SCAN_STATUS = "SCAN_STATUS"
    SCAN_TYPE = "SCAN_TYPE"


class MalwareProtectionPlanStatus:
    ACTIVE = "ACTIVE"
    WARNING = "WARNING"
    ERROR = "ERROR"


class MalwareProtectionPlanTaggingActionStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class MalwareProtectionResourceType:
    EBS_RECOVERY_POINT = "EBS_RECOVERY_POINT"
    EBS_SNAPSHOT = "EBS_SNAPSHOT"
    EBS_VOLUME = "EBS_VOLUME"
    EC2_AMI = "EC2_AMI"
    EC2_INSTANCE = "EC2_INSTANCE"
    EC2_RECOVERY_POINT = "EC2_RECOVERY_POINT"
    S3_RECOVERY_POINT = "S3_RECOVERY_POINT"
    S3_BUCKET = "S3_BUCKET"


class MalwareProtectionScanStatus:
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ISSUES = "COMPLETED_WITH_ISSUES"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class MalwareProtectionScanType:
    BACKUP_INITIATED = "BACKUP_INITIATED"
    ON_DEMAND = "ON_DEMAND"
    GUARDDUTY_INITIATED = "GUARDDUTY_INITIATED"


class ManagementType:
    AUTO_MANAGED = "AUTO_MANAGED"
    MANUAL = "MANUAL"
    DISABLED = "DISABLED"


class MfaStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class NetworkDirection:
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"


class OrderBy:
    ASC = "ASC"
    DESC = "DESC"


class OrgFeature:
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    EBS_MALWARE_PROTECTION = "EBS_MALWARE_PROTECTION"
    RDS_LOGIN_EVENTS = "RDS_LOGIN_EVENTS"
    EKS_RUNTIME_MONITORING = "EKS_RUNTIME_MONITORING"
    LAMBDA_NETWORK_LOGS = "LAMBDA_NETWORK_LOGS"
    RUNTIME_MONITORING = "RUNTIME_MONITORING"


class OrgFeatureAdditionalConfiguration:
    EKS_ADDON_MANAGEMENT = "EKS_ADDON_MANAGEMENT"
    ECS_FARGATE_AGENT_MANAGEMENT = "ECS_FARGATE_AGENT_MANAGEMENT"
    EC2_AGENT_MANAGEMENT = "EC2_AGENT_MANAGEMENT"


class OrgFeatureStatus:
    NEW = "NEW"
    NONE = "NONE"
    ALL = "ALL"


class ProfileSubtype:
    FREQUENT = "FREQUENT"
    INFREQUENT = "INFREQUENT"
    UNSEEN = "UNSEEN"
    RARE = "RARE"


class ProfileType:
    FREQUENCY = "FREQUENCY"


class PublicAccessStatus:
    BLOCKED = "BLOCKED"
    ALLOWED = "ALLOWED"


class PublicAclIgnoreBehavior:
    IGNORED = "IGNORED"
    NOT_IGNORED = "NOT_IGNORED"


class PublicBucketRestrictBehavior:
    RESTRICTED = "RESTRICTED"
    NOT_RESTRICTED = "NOT_RESTRICTED"


class PublishingStatus:
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    PUBLISHING = "PUBLISHING"
    UNABLE_TO_PUBLISH_FIX_DESTINATION_PROPERTY = (
        "UNABLE_TO_PUBLISH_FIX_DESTINATION_PROPERTY"
    )
    STOPPED = "STOPPED"


class ResourceType:
    EKS = "EKS"
    ECS = "ECS"
    EC2 = "EC2"


class ScanCategory:
    FULL_SCAN = "FULL_SCAN"
    INCREMENTAL_SCAN = "INCREMENTAL_SCAN"


class ScanCriterionKey:
    EC2_INSTANCE_TAG = "EC2_INSTANCE_TAG"


class ScanResult:
    CLEAN = "CLEAN"
    INFECTED = "INFECTED"


class ScanResultStatus:
    NO_THREATS_FOUND = "NO_THREATS_FOUND"
    THREATS_FOUND = "THREATS_FOUND"


class ScanStatus:
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ScanStatusReason:
    ACCESS_DENIED = "ACCESS_DENIED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    SNAPSHOT_SIZE_LIMIT_EXCEEDED = "SNAPSHOT_SIZE_LIMIT_EXCEEDED"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"
    INCONSISTENT_SOURCE = "INCONSISTENT_SOURCE"
    INCREMENTAL_NO_DIFFERENCE = "INCREMENTAL_NO_DIFFERENCE"
    NO_EBS_VOLUMES_FOUND = "NO_EBS_VOLUMES_FOUND"
    UNSUPPORTED_PRODUCT_CODE_TYPE = "UNSUPPORTED_PRODUCT_CODE_TYPE"
    AMI_SNAPSHOT_LIMIT_EXCEEDED = "AMI_SNAPSHOT_LIMIT_EXCEEDED"
    UNRELATED_RESOURCES = "UNRELATED_RESOURCES"
    BASE_RESOURCE_NOT_SCANNED = "BASE_RESOURCE_NOT_SCANNED"
    BASE_CREATED_AFTER_TARGET = "BASE_CREATED_AFTER_TARGET"
    UNSUPPORTED_FOR_INCREMENTAL = "UNSUPPORTED_FOR_INCREMENTAL"
    UNSUPPORTED_AMI = "UNSUPPORTED_AMI"
    UNSUPPORTED_SNAPSHOT = "UNSUPPORTED_SNAPSHOT"
    UNSUPPORTED_COMPOSITE_RECOVERY_POINT = "UNSUPPORTED_COMPOSITE_RECOVERY_POINT"


class ScanType:
    GUARDDUTY_INITIATED = "GUARDDUTY_INITIATED"
    ON_DEMAND = "ON_DEMAND"


class SignalType:
    FINDING = "FINDING"
    CLOUD_TRAIL = "CLOUD_TRAIL"
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    FLOW_LOGS = "FLOW_LOGS"
    DNS_LOGS = "DNS_LOGS"
    RUNTIME_MONITORING = "RUNTIME_MONITORING"


class ThreatEntitySetFormat:
    TXT = "TXT"
    STIX = "STIX"
    OTX_CSV = "OTX_CSV"
    ALIEN_VAULT = "ALIEN_VAULT"
    PROOF_POINT = "PROOF_POINT"
    FIRE_EYE = "FIRE_EYE"


class ThreatEntitySetStatus:
    INACTIVE = "INACTIVE"
    ACTIVATING = "ACTIVATING"
    ACTIVE = "ACTIVE"
    DEACTIVATING = "DEACTIVATING"
    ERROR = "ERROR"
    DELETE_PENDING = "DELETE_PENDING"
    DELETED = "DELETED"


class ThreatIntelSetFormat:
    TXT = "TXT"
    STIX = "STIX"
    OTX_CSV = "OTX_CSV"
    ALIEN_VAULT = "ALIEN_VAULT"
    PROOF_POINT = "PROOF_POINT"
    FIRE_EYE = "FIRE_EYE"


class ThreatIntelSetStatus:
    INACTIVE = "INACTIVE"
    ACTIVATING = "ACTIVATING"
    ACTIVE = "ACTIVE"
    DEACTIVATING = "DEACTIVATING"
    ERROR = "ERROR"
    DELETE_PENDING = "DELETE_PENDING"
    DELETED = "DELETED"


class TriggerType:
    BACKUP = "BACKUP"
    GUARDDUTY = "GUARDDUTY"


class TrustedEntitySetFormat:
    TXT = "TXT"
    STIX = "STIX"
    OTX_CSV = "OTX_CSV"
    ALIEN_VAULT = "ALIEN_VAULT"
    PROOF_POINT = "PROOF_POINT"
    FIRE_EYE = "FIRE_EYE"


class TrustedEntitySetStatus:
    INACTIVE = "INACTIVE"
    ACTIVATING = "ACTIVATING"
    ACTIVE = "ACTIVE"
    DEACTIVATING = "DEACTIVATING"
    ERROR = "ERROR"
    DELETE_PENDING = "DELETE_PENDING"
    DELETED = "DELETED"


class UsageFeature:
    FLOW_LOGS = "FLOW_LOGS"
    CLOUD_TRAIL = "CLOUD_TRAIL"
    DNS_LOGS = "DNS_LOGS"
    S3_DATA_EVENTS = "S3_DATA_EVENTS"
    EKS_AUDIT_LOGS = "EKS_AUDIT_LOGS"
    EBS_MALWARE_PROTECTION = "EBS_MALWARE_PROTECTION"
    RDS_LOGIN_EVENTS = "RDS_LOGIN_EVENTS"
    LAMBDA_NETWORK_LOGS = "LAMBDA_NETWORK_LOGS"
    EKS_RUNTIME_MONITORING = "EKS_RUNTIME_MONITORING"
    FARGATE_RUNTIME_MONITORING = "FARGATE_RUNTIME_MONITORING"
    EC2_RUNTIME_MONITORING = "EC2_RUNTIME_MONITORING"
    RDS_DBI_PROTECTION_PROVISIONED = "RDS_DBI_PROTECTION_PROVISIONED"
    RDS_DBI_PROTECTION_SERVERLESS = "RDS_DBI_PROTECTION_SERVERLESS"


class UsageStatisticType:
    SUM_BY_ACCOUNT = "SUM_BY_ACCOUNT"
    SUM_BY_DATA_SOURCE = "SUM_BY_DATA_SOURCE"
    SUM_BY_RESOURCE = "SUM_BY_RESOURCE"
    TOP_RESOURCES = "TOP_RESOURCES"
    SUM_BY_FEATURES = "SUM_BY_FEATURES"
    TOP_ACCOUNTS_BY_FEATURE = "TOP_ACCOUNTS_BY_FEATURE"


# PropertyType submodules
from . import Detector as _Detector
from . import Filter as _Filter
from . import IPSet as _IPSet
from . import MalwareProtectionPlan as _MalwareProtectionPlan
from . import PublishingDestination as _PublishingDestination
from . import ThreatEntitySet as _ThreatEntitySet
from . import ThreatIntelSet as _ThreatIntelSet
from . import TrustedEntitySet as _TrustedEntitySet


# Resources
# ============================================================


@dataclass
class Detector(CloudFormationResource):
    """Detector resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html

    CloudFormation type: AWS::GuardDuty::Detector
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::Detector"

    enable: bool | None = None
    data_sources: _Detector.CFNDataSourceConfigurations | None = None
    features: list[_Detector.CFNFeatureConfiguration] = field(default_factory=list)
    finding_publishing_frequency: str | None = None
    tags: list[_Detector.TagItem] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class Filter(CloudFormationResource):
    """Filter resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-filter.html

    CloudFormation type: AWS::GuardDuty::Filter
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::Filter"

    detector_id: str | None = None
    finding_criteria: _Filter.FindingCriteria | None = None
    name: str | None = None
    action: str | None = None
    description: str | None = None
    rank: int | None = None
    tags: list[_Filter.TagItem] = field(default_factory=list)


@dataclass
class IPSet(CloudFormationResource):
    """IPSet resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-ipset.html

    CloudFormation type: AWS::GuardDuty::IPSet
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::IPSet"

    format: str | None = None
    location: str | None = None
    activate: bool | None = None
    detector_id: str | None = None
    expected_bucket_owner: str | None = None
    name: str | None = None
    tags: list[_IPSet.TagItem] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class MalwareProtectionPlan(CloudFormationResource):
    """MalwareProtectionPlan resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-malwareprotectionplan.html

    CloudFormation type: AWS::GuardDuty::MalwareProtectionPlan
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::MalwareProtectionPlan"

    protected_resource: _MalwareProtectionPlan.CFNProtectedResource | None = None
    role: str | None = None
    actions: _MalwareProtectionPlan.CFNActions | None = None
    tags: list[_MalwareProtectionPlan.TagItem] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    STATUSREASONS: ClassVar[str] = "StatusReasons"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    MALWAREPROTECTIONPLANID: ClassVar[str] = "MalwareProtectionPlanId"
    ARN: ClassVar[str] = "Arn"


@dataclass
class Master(CloudFormationResource):
    """Master resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-master.html

    CloudFormation type: AWS::GuardDuty::Master
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::Master"

    detector_id: str | None = None
    master_id: str | None = None
    invitation_id: str | None = None


@dataclass
class Member(CloudFormationResource):
    """Member resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-member.html

    CloudFormation type: AWS::GuardDuty::Member
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::Member"

    email: str | None = None
    detector_id: str | None = None
    disable_email_notification: bool | None = None
    member_id: str | None = None
    message: str | None = None
    status: str | None = None


@dataclass
class PublishingDestination(CloudFormationResource):
    """PublishingDestination resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-publishingdestination.html

    CloudFormation type: AWS::GuardDuty::PublishingDestination
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::PublishingDestination"

    destination_properties: _PublishingDestination.CFNDestinationProperties | None = (
        None
    )
    destination_type: str | None = None
    detector_id: str | None = None
    tags: list[_PublishingDestination.TagItem] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    PUBLISHINGFAILURESTARTTIMESTAMP: ClassVar[str] = "PublishingFailureStartTimestamp"
    ID: ClassVar[str] = "Id"


@dataclass
class ThreatEntitySet(CloudFormationResource):
    """ThreatEntitySet resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-threatentityset.html

    CloudFormation type: AWS::GuardDuty::ThreatEntitySet
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::ThreatEntitySet"

    format: str | None = None
    location: str | None = None
    activate: bool | None = None
    detector_id: str | None = None
    expected_bucket_owner: str | None = None
    name: str | None = None
    tags: list[_ThreatEntitySet.TagItem] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    ID: ClassVar[str] = "Id"
    ERRORDETAILS: ClassVar[str] = "ErrorDetails"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


@dataclass
class ThreatIntelSet(CloudFormationResource):
    """ThreatIntelSet resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-threatintelset.html

    CloudFormation type: AWS::GuardDuty::ThreatIntelSet
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::ThreatIntelSet"

    format: str | None = None
    location: str | None = None
    activate: bool | None = None
    detector_id: str | None = None
    expected_bucket_owner: str | None = None
    name: str | None = None
    tags: list[_ThreatIntelSet.TagItem] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"


@dataclass
class TrustedEntitySet(CloudFormationResource):
    """TrustedEntitySet resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-trustedentityset.html

    CloudFormation type: AWS::GuardDuty::TrustedEntitySet
    """

    _resource_type: ClassVar[str] = "AWS::GuardDuty::TrustedEntitySet"

    format: str | None = None
    location: str | None = None
    activate: bool | None = None
    detector_id: str | None = None
    expected_bucket_owner: str | None = None
    name: str | None = None
    tags: list[_TrustedEntitySet.TagItem] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    ID: ClassVar[str] = "Id"
    ERRORDETAILS: ClassVar[str] = "ErrorDetails"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Detector.CFNDataSourceConfigurations = _Detector.CFNDataSourceConfigurations
Detector.CFNFeatureAdditionalConfiguration = _Detector.CFNFeatureAdditionalConfiguration
Detector.CFNFeatureConfiguration = _Detector.CFNFeatureConfiguration
Detector.CFNKubernetesAuditLogsConfiguration = (
    _Detector.CFNKubernetesAuditLogsConfiguration
)
Detector.CFNKubernetesConfiguration = _Detector.CFNKubernetesConfiguration
Detector.CFNMalwareProtectionConfiguration = _Detector.CFNMalwareProtectionConfiguration
Detector.CFNS3LogsConfiguration = _Detector.CFNS3LogsConfiguration
Detector.CFNScanEc2InstanceWithFindingsConfiguration = (
    _Detector.CFNScanEc2InstanceWithFindingsConfiguration
)
Detector.TagItem = _Detector.TagItem
Filter.Condition = _Filter.Condition
Filter.FindingCriteria = _Filter.FindingCriteria
Filter.TagItem = _Filter.TagItem
IPSet.TagItem = _IPSet.TagItem
MalwareProtectionPlan.CFNActions = _MalwareProtectionPlan.CFNActions
MalwareProtectionPlan.CFNProtectedResource = _MalwareProtectionPlan.CFNProtectedResource
MalwareProtectionPlan.CFNStatusReasons = _MalwareProtectionPlan.CFNStatusReasons
MalwareProtectionPlan.CFNTagging = _MalwareProtectionPlan.CFNTagging
MalwareProtectionPlan.S3Bucket = _MalwareProtectionPlan.S3Bucket
MalwareProtectionPlan.TagItem = _MalwareProtectionPlan.TagItem
PublishingDestination.CFNDestinationProperties = (
    _PublishingDestination.CFNDestinationProperties
)
PublishingDestination.TagItem = _PublishingDestination.TagItem
ThreatEntitySet.TagItem = _ThreatEntitySet.TagItem
ThreatIntelSet.TagItem = _ThreatIntelSet.TagItem
TrustedEntitySet.TagItem = _TrustedEntitySet.TagItem
