"""
AWS CODECOMMIT CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class ApprovalState:
    APPROVE = "APPROVE"
    REVOKE = "REVOKE"


class BatchGetRepositoriesErrorCodeEnum:
    ENCRYPTIONINTEGRITYCHECKSFAILEDEXCEPTION = (
        "EncryptionIntegrityChecksFailedException"
    )
    ENCRYPTIONKEYACCESSDENIEDEXCEPTION = "EncryptionKeyAccessDeniedException"
    ENCRYPTIONKEYDISABLEDEXCEPTION = "EncryptionKeyDisabledException"
    ENCRYPTIONKEYNOTFOUNDEXCEPTION = "EncryptionKeyNotFoundException"
    ENCRYPTIONKEYUNAVAILABLEEXCEPTION = "EncryptionKeyUnavailableException"
    REPOSITORYDOESNOTEXISTEXCEPTION = "RepositoryDoesNotExistException"


class ChangeTypeEnum:
    A = "A"
    M = "M"
    D = "D"


class ConflictDetailLevelTypeEnum:
    FILE_LEVEL = "FILE_LEVEL"
    LINE_LEVEL = "LINE_LEVEL"


class ConflictResolutionStrategyTypeEnum:
    NONE = "NONE"
    ACCEPT_SOURCE = "ACCEPT_SOURCE"
    ACCEPT_DESTINATION = "ACCEPT_DESTINATION"
    AUTOMERGE = "AUTOMERGE"


class FileModeTypeEnum:
    EXECUTABLE = "EXECUTABLE"
    NORMAL = "NORMAL"
    SYMLINK = "SYMLINK"


class MergeOptionTypeEnum:
    FAST_FORWARD_MERGE = "FAST_FORWARD_MERGE"
    SQUASH_MERGE = "SQUASH_MERGE"
    THREE_WAY_MERGE = "THREE_WAY_MERGE"


class ObjectTypeEnum:
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"
    GIT_LINK = "GIT_LINK"
    SYMBOLIC_LINK = "SYMBOLIC_LINK"


class OrderEnum:
    ASCENDING = "ascending"
    DESCENDING = "descending"


class OverrideStatus:
    OVERRIDE = "OVERRIDE"
    REVOKE = "REVOKE"


class PullRequestEventType:
    PULL_REQUEST_CREATED = "PULL_REQUEST_CREATED"
    PULL_REQUEST_STATUS_CHANGED = "PULL_REQUEST_STATUS_CHANGED"
    PULL_REQUEST_SOURCE_REFERENCE_UPDATED = "PULL_REQUEST_SOURCE_REFERENCE_UPDATED"
    PULL_REQUEST_MERGE_STATE_CHANGED = "PULL_REQUEST_MERGE_STATE_CHANGED"
    PULL_REQUEST_APPROVAL_RULE_CREATED = "PULL_REQUEST_APPROVAL_RULE_CREATED"
    PULL_REQUEST_APPROVAL_RULE_UPDATED = "PULL_REQUEST_APPROVAL_RULE_UPDATED"
    PULL_REQUEST_APPROVAL_RULE_DELETED = "PULL_REQUEST_APPROVAL_RULE_DELETED"
    PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN = "PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN"
    PULL_REQUEST_APPROVAL_STATE_CHANGED = "PULL_REQUEST_APPROVAL_STATE_CHANGED"


class PullRequestStatusEnum:
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class RelativeFileVersionEnum:
    BEFORE = "BEFORE"
    AFTER = "AFTER"


class ReplacementTypeEnum:
    KEEP_BASE = "KEEP_BASE"
    KEEP_SOURCE = "KEEP_SOURCE"
    KEEP_DESTINATION = "KEEP_DESTINATION"
    USE_NEW_CONTENT = "USE_NEW_CONTENT"


class RepositoryTriggerEventEnum:
    ALL = "all"
    UPDATEREFERENCE = "updateReference"
    CREATEREFERENCE = "createReference"
    DELETEREFERENCE = "deleteReference"


class SortByEnum:
    REPOSITORYNAME = "repositoryName"
    LASTMODIFIEDDATE = "lastModifiedDate"


# PropertyType submodules
from . import Repository as _Repository


# Resources
# ============================================================


@dataclass
class Repository(CloudFormationResource):
    """Repository resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codecommit-repository.html

    CloudFormation type: AWS::CodeCommit::Repository
    """

    _resource_type: ClassVar[str] = "AWS::CodeCommit::Repository"

    repository_name: DslValue[str] | None = None
    code: DslValue[_Repository.Code] | None = None
    kms_key_id: DslValue[str] | None = None
    repository_description: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    triggers: list[DslValue[_Repository.RepositoryTrigger]] = field(
        default_factory=list
    )

    # GetAtt attributes
    CLONEURLHTTP: ClassVar[str] = "CloneUrlHttp"
    KMSKEYID: ClassVar[str] = "KmsKeyId"
    CLONEURLSSH: ClassVar[str] = "CloneUrlSsh"
    ARN: ClassVar[str] = "Arn"
    NAME: ClassVar[str] = "Name"

    # PropertyType descriptors for nested GetAtt support
    Code = PropertyTypeDescriptor(_Repository.Code, "Code")
    RepositoryTrigger = PropertyTypeDescriptor(
        _Repository.RepositoryTrigger, "RepositoryTrigger"
    )
    S3 = PropertyTypeDescriptor(_Repository.S3, "S3")
