"""
AWS SDB CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:26Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Resources
# ============================================================


@dataclass
class Domain(CloudFormationResource):
    """Domain resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-simpledb.html

    CloudFormation type: AWS::SDB::Domain
    """

    _resource_type: ClassVar[str] = "AWS::SDB::Domain"

    description: str | None = None
