"""
AWS IVS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:22Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class ChannelLatencyMode:
    NORMAL = "NORMAL"
    LOW = "LOW"


class ChannelType:
    BASIC = "BASIC"
    STANDARD = "STANDARD"
    ADVANCED_SD = "ADVANCED_SD"
    ADVANCED_HD = "ADVANCED_HD"


class ContainerFormat:
    TS = "TS"
    FRAGMENTED_MP4 = "FRAGMENTED_MP4"


class MultitrackMaximumResolution:
    SD = "SD"
    HD = "HD"
    FULL_HD = "FULL_HD"


class MultitrackPolicy:
    ALLOW = "ALLOW"
    REQUIRE = "REQUIRE"


class RecordingConfigurationState:
    CREATING = "CREATING"
    CREATE_FAILED = "CREATE_FAILED"
    ACTIVE = "ACTIVE"


class RecordingMode:
    DISABLED = "DISABLED"
    INTERVAL = "INTERVAL"


class RenditionConfigurationRendition:
    SD = "SD"
    HD = "HD"
    FULL_HD = "FULL_HD"
    LOWEST_RESOLUTION = "LOWEST_RESOLUTION"


class RenditionConfigurationRenditionSelection:
    ALL = "ALL"
    NONE = "NONE"
    CUSTOM = "CUSTOM"


class StreamHealth:
    HEALTHY = "HEALTHY"
    STARVING = "STARVING"
    UNKNOWN = "UNKNOWN"


class StreamState:
    LIVE = "LIVE"
    OFFLINE = "OFFLINE"


class ThumbnailConfigurationResolution:
    SD = "SD"
    HD = "HD"
    FULL_HD = "FULL_HD"
    LOWEST_RESOLUTION = "LOWEST_RESOLUTION"


class ThumbnailConfigurationStorage:
    SEQUENTIAL = "SEQUENTIAL"
    LATEST = "LATEST"


class TranscodePreset:
    HIGHER_BANDWIDTH_DELIVERY = "HIGHER_BANDWIDTH_DELIVERY"
    CONSTRAINED_BANDWIDTH_DELIVERY = "CONSTRAINED_BANDWIDTH_DELIVERY"


# PropertyType submodules
from . import Channel as _Channel
from . import EncoderConfiguration as _EncoderConfiguration
from . import RecordingConfiguration as _RecordingConfiguration
from . import Stage as _Stage
from . import StorageConfiguration as _StorageConfiguration


# Resources
# ============================================================


@dataclass
class Channel(CloudFormationResource):
    """Channel resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-channel.html

    CloudFormation type: AWS::IVS::Channel
    """

    _resource_type: ClassVar[str] = "AWS::IVS::Channel"

    authorized: bool | None = None
    container_format: str | None = None
    insecure_ingest: bool | None = None
    latency_mode: str | None = None
    multitrack_input_configuration: _Channel.MultitrackInputConfiguration | None = None
    name: str | None = None
    preset: str | None = None
    recording_configuration_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)
    type_: str | None = None

    # GetAtt attributes
    PLAYBACKURL: ClassVar[str] = "PlaybackUrl"
    INGESTENDPOINT: ClassVar[str] = "IngestEndpoint"
    ARN: ClassVar[str] = "Arn"


@dataclass
class EncoderConfiguration(CloudFormationResource):
    """EncoderConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-encoderconfiguration.html

    CloudFormation type: AWS::IVS::EncoderConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::IVS::EncoderConfiguration"

    name: str | None = None
    tags: list[Tag] = field(default_factory=list)
    video: _EncoderConfiguration.Video | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class IngestConfiguration(CloudFormationResource):
    """IngestConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-ingestconfiguration.html

    CloudFormation type: AWS::IVS::IngestConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::IVS::IngestConfiguration"

    ingest_protocol: str | None = None
    insecure_ingest: bool | None = None
    name: str | None = None
    stage_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)
    user_id: str | None = None

    # GetAtt attributes
    PARTICIPANTID: ClassVar[str] = "ParticipantId"
    STATE: ClassVar[str] = "State"
    ARN: ClassVar[str] = "Arn"
    STREAMKEY: ClassVar[str] = "StreamKey"


@dataclass
class PlaybackKeyPair(CloudFormationResource):
    """PlaybackKeyPair resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-playbackkeypair.html

    CloudFormation type: AWS::IVS::PlaybackKeyPair
    """

    _resource_type: ClassVar[str] = "AWS::IVS::PlaybackKeyPair"

    name: str | None = None
    public_key_material: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    FINGERPRINT: ClassVar[str] = "Fingerprint"
    ARN: ClassVar[str] = "Arn"


@dataclass
class PlaybackRestrictionPolicy(CloudFormationResource):
    """PlaybackRestrictionPolicy resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-playbackrestrictionpolicy.html

    CloudFormation type: AWS::IVS::PlaybackRestrictionPolicy
    """

    _resource_type: ClassVar[str] = "AWS::IVS::PlaybackRestrictionPolicy"

    allowed_countries: list[String] = field(default_factory=list)
    allowed_origins: list[String] = field(default_factory=list)
    enable_strict_origin_enforcement: bool | None = None
    name: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class PublicKey(CloudFormationResource):
    """PublicKey resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-publickey.html

    CloudFormation type: AWS::IVS::PublicKey
    """

    _resource_type: ClassVar[str] = "AWS::IVS::PublicKey"

    name: str | None = None
    public_key_material: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    FINGERPRINT: ClassVar[str] = "Fingerprint"
    ARN: ClassVar[str] = "Arn"


@dataclass
class RecordingConfiguration(CloudFormationResource):
    """RecordingConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-recordingconfiguration.html

    CloudFormation type: AWS::IVS::RecordingConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::IVS::RecordingConfiguration"

    destination_configuration: (
        _RecordingConfiguration.DestinationConfiguration | None
    ) = None
    name: str | None = None
    recording_reconnect_window_seconds: int | None = None
    rendition_configuration: _RecordingConfiguration.RenditionConfiguration | None = (
        None
    )
    tags: list[Tag] = field(default_factory=list)
    thumbnail_configuration: _RecordingConfiguration.ThumbnailConfiguration | None = (
        None
    )

    # GetAtt attributes
    STATE: ClassVar[str] = "State"
    ARN: ClassVar[str] = "Arn"


@dataclass
class Stage(CloudFormationResource):
    """Stage resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-stage.html

    CloudFormation type: AWS::IVS::Stage
    """

    _resource_type: ClassVar[str] = "AWS::IVS::Stage"

    auto_participant_recording_configuration: (
        _Stage.AutoParticipantRecordingConfiguration | None
    ) = None
    name: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"
    ACTIVESESSIONID: ClassVar[str] = "ActiveSessionId"


@dataclass
class StorageConfiguration(CloudFormationResource):
    """StorageConfiguration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-storageconfiguration.html

    CloudFormation type: AWS::IVS::StorageConfiguration
    """

    _resource_type: ClassVar[str] = "AWS::IVS::StorageConfiguration"

    s3: _StorageConfiguration.S3StorageConfiguration | None = None
    name: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class StreamKey(CloudFormationResource):
    """StreamKey resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-streamkey.html

    CloudFormation type: AWS::IVS::StreamKey
    """

    _resource_type: ClassVar[str] = "AWS::IVS::StreamKey"

    channel_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    VALUE: ClassVar[str] = "Value"
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Channel.MultitrackInputConfiguration = PropertyTypeDescriptor(
    _Channel.MultitrackInputConfiguration, "MultitrackInputConfiguration"
)
EncoderConfiguration.Video = PropertyTypeDescriptor(
    _EncoderConfiguration.Video, "Video"
)
RecordingConfiguration.DestinationConfiguration = PropertyTypeDescriptor(
    _RecordingConfiguration.DestinationConfiguration, "DestinationConfiguration"
)
RecordingConfiguration.RenditionConfiguration = PropertyTypeDescriptor(
    _RecordingConfiguration.RenditionConfiguration, "RenditionConfiguration"
)
RecordingConfiguration.S3DestinationConfiguration = PropertyTypeDescriptor(
    _RecordingConfiguration.S3DestinationConfiguration, "S3DestinationConfiguration"
)
RecordingConfiguration.ThumbnailConfiguration = PropertyTypeDescriptor(
    _RecordingConfiguration.ThumbnailConfiguration, "ThumbnailConfiguration"
)
Stage.AutoParticipantRecordingConfiguration = PropertyTypeDescriptor(
    _Stage.AutoParticipantRecordingConfiguration,
    "AutoParticipantRecordingConfiguration",
)
Stage.HlsConfiguration = PropertyTypeDescriptor(
    _Stage.HlsConfiguration, "HlsConfiguration"
)
Stage.ParticipantRecordingHlsConfiguration = PropertyTypeDescriptor(
    _Stage.ParticipantRecordingHlsConfiguration, "ParticipantRecordingHlsConfiguration"
)
Stage.ParticipantThumbnailConfiguration = PropertyTypeDescriptor(
    _Stage.ParticipantThumbnailConfiguration, "ParticipantThumbnailConfiguration"
)
Stage.ThumbnailConfiguration = PropertyTypeDescriptor(
    _Stage.ThumbnailConfiguration, "ThumbnailConfiguration"
)
StorageConfiguration.S3StorageConfiguration = PropertyTypeDescriptor(
    _StorageConfiguration.S3StorageConfiguration, "S3StorageConfiguration"
)
