"""
AWS SCHEDULER CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:26Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class ActionAfterCompletion:
    NONE = "NONE"
    DELETE = "DELETE"


class AssignPublicIp:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class FlexibleTimeWindowMode:
    OFF = "OFF"
    FLEXIBLE = "FLEXIBLE"


class LaunchType:
    EC2 = "EC2"
    FARGATE = "FARGATE"
    EXTERNAL = "EXTERNAL"


class PlacementConstraintType:
    DISTINCTINSTANCE = "distinctInstance"
    MEMBEROF = "memberOf"


class PlacementStrategyType:
    RANDOM = "random"
    SPREAD = "spread"
    BINPACK = "binpack"


class PropagateTags:
    TASK_DEFINITION = "TASK_DEFINITION"


class ScheduleGroupState:
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"


class ScheduleState:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


# PropertyType submodules
from . import Schedule as _Schedule


# Resources
# ============================================================


@dataclass
class Schedule(CloudFormationResource):
    """Schedule resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html

    CloudFormation type: AWS::Scheduler::Schedule
    """

    _resource_type: ClassVar[str] = "AWS::Scheduler::Schedule"

    flexible_time_window: _Schedule.FlexibleTimeWindow | None = None
    schedule_expression: str | None = None
    target: _Schedule.Target | None = None
    description: str | None = None
    end_date: str | None = None
    group_name: str | None = None
    kms_key_arn: str | None = None
    name: str | None = None
    schedule_expression_timezone: str | None = None
    start_date: str | None = None
    state: str | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class ScheduleGroup(CloudFormationResource):
    """ScheduleGroup resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedulegroup.html

    CloudFormation type: AWS::Scheduler::ScheduleGroup
    """

    _resource_type: ClassVar[str] = "AWS::Scheduler::ScheduleGroup"

    name: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    CREATIONDATE: ClassVar[str] = "CreationDate"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONDATE: ClassVar[str] = "LastModificationDate"
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Schedule.AwsVpcConfiguration = PropertyTypeDescriptor(
    _Schedule.AwsVpcConfiguration, "AwsVpcConfiguration"
)
Schedule.CapacityProviderStrategyItem = PropertyTypeDescriptor(
    _Schedule.CapacityProviderStrategyItem, "CapacityProviderStrategyItem"
)
Schedule.DeadLetterConfig = PropertyTypeDescriptor(
    _Schedule.DeadLetterConfig, "DeadLetterConfig"
)
Schedule.EcsParameters = PropertyTypeDescriptor(
    _Schedule.EcsParameters, "EcsParameters"
)
Schedule.EventBridgeParameters = PropertyTypeDescriptor(
    _Schedule.EventBridgeParameters, "EventBridgeParameters"
)
Schedule.FlexibleTimeWindow = PropertyTypeDescriptor(
    _Schedule.FlexibleTimeWindow, "FlexibleTimeWindow"
)
Schedule.KinesisParameters = PropertyTypeDescriptor(
    _Schedule.KinesisParameters, "KinesisParameters"
)
Schedule.NetworkConfiguration = PropertyTypeDescriptor(
    _Schedule.NetworkConfiguration, "NetworkConfiguration"
)
Schedule.PlacementConstraint = PropertyTypeDescriptor(
    _Schedule.PlacementConstraint, "PlacementConstraint"
)
Schedule.PlacementStrategy = PropertyTypeDescriptor(
    _Schedule.PlacementStrategy, "PlacementStrategy"
)
Schedule.RetryPolicy = PropertyTypeDescriptor(_Schedule.RetryPolicy, "RetryPolicy")
Schedule.SageMakerPipelineParameter = PropertyTypeDescriptor(
    _Schedule.SageMakerPipelineParameter, "SageMakerPipelineParameter"
)
Schedule.SageMakerPipelineParameters = PropertyTypeDescriptor(
    _Schedule.SageMakerPipelineParameters, "SageMakerPipelineParameters"
)
Schedule.SqsParameters = PropertyTypeDescriptor(
    _Schedule.SqsParameters, "SqsParameters"
)
Schedule.Target = PropertyTypeDescriptor(_Schedule.Target, "Target")
