"""
AWS PAYMENTCRYPTOGRAPHY CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:23Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# PropertyType submodules
from . import Key as _Key


# Resources
# ============================================================


@dataclass
class Alias(CloudFormationResource):
    """Alias resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-paymentcryptography-alias.html

    CloudFormation type: AWS::PaymentCryptography::Alias
    """

    _resource_type: ClassVar[str] = "AWS::PaymentCryptography::Alias"

    alias_name: DslValue[str] | None = None
    key_arn: DslValue[str] | None = None


@dataclass
class Key(CloudFormationResource):
    """Key resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-paymentcryptography-key.html

    CloudFormation type: AWS::PaymentCryptography::Key
    """

    _resource_type: ClassVar[str] = "AWS::PaymentCryptography::Key"

    exportable: DslValue[bool] | None = None
    key_attributes: DslValue[_Key.KeyAttributes] | None = None
    derive_key_usage: DslValue[str] | None = None
    enabled: DslValue[bool] | None = None
    key_check_value_algorithm: DslValue[str] | None = None
    replication_regions: list[DslValue[str]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    KEYIDENTIFIER: ClassVar[str] = "KeyIdentifier"
    REPLICATIONSTATUS: ClassVar[str] = "ReplicationStatus"
    KEYSTATE: ClassVar[str] = "KeyState"
    KEYORIGIN: ClassVar[str] = "KeyOrigin"

    # PropertyType descriptors for nested GetAtt support
    KeyAttributes = PropertyTypeDescriptor(_Key.KeyAttributes, "KeyAttributes")
    KeyModesOfUse = PropertyTypeDescriptor(_Key.KeyModesOfUse, "KeyModesOfUse")
    ReplicationStatusType = PropertyTypeDescriptor(
        _Key.ReplicationStatusType, "ReplicationStatusType"
    )
