"""
AWS PCACONNECTORAD CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:24Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# PropertyType submodules
from . import Connector as _Connector
from . import Template as _Template
from . import TemplateGroupAccessControlEntry as _TemplateGroupAccessControlEntry


# Resources
# ============================================================


@dataclass
class Connector(CloudFormationResource):
    """Connector resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorad-connector.html

    CloudFormation type: AWS::PCAConnectorAD::Connector
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorAD::Connector"

    certificate_authority_arn: str | None = None
    directory_id: str | None = None
    vpc_information: _Connector.VpcInformation | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    CONNECTORARN: ClassVar[str] = "ConnectorArn"


@dataclass
class DirectoryRegistration(CloudFormationResource):
    """DirectoryRegistration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorad-directoryregistration.html

    CloudFormation type: AWS::PCAConnectorAD::DirectoryRegistration
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorAD::DirectoryRegistration"

    directory_id: str | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    DIRECTORYREGISTRATIONARN: ClassVar[str] = "DirectoryRegistrationArn"


@dataclass
class ServicePrincipalName(CloudFormationResource):
    """ServicePrincipalName resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorad-serviceprincipalname.html

    CloudFormation type: AWS::PCAConnectorAD::ServicePrincipalName
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorAD::ServicePrincipalName"

    connector_arn: str | None = None
    directory_registration_arn: str | None = None


@dataclass
class Template(CloudFormationResource):
    """Template resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorad-template.html

    CloudFormation type: AWS::PCAConnectorAD::Template
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorAD::Template"

    connector_arn: str | None = None
    definition: _Template.TemplateDefinition | None = None
    name: str | None = None
    reenroll_all_certificate_holders: bool | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    TEMPLATEARN: ClassVar[str] = "TemplateArn"


@dataclass
class TemplateGroupAccessControlEntry(CloudFormationResource):
    """TemplateGroupAccessControlEntry resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorad-templategroupaccesscontrolentry.html

    CloudFormation type: AWS::PCAConnectorAD::TemplateGroupAccessControlEntry
    """

    _resource_type: ClassVar[str] = (
        "AWS::PCAConnectorAD::TemplateGroupAccessControlEntry"
    )

    access_rights: _TemplateGroupAccessControlEntry.AccessRights | None = None
    group_display_name: str | None = None
    group_security_identifier: str | None = None
    template_arn: str | None = None


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Connector.VpcInformation = PropertyTypeDescriptor(
    _Connector.VpcInformation, "VpcInformation"
)
Template.ApplicationPolicies = PropertyTypeDescriptor(
    _Template.ApplicationPolicies, "ApplicationPolicies"
)
Template.ApplicationPolicy = PropertyTypeDescriptor(
    _Template.ApplicationPolicy, "ApplicationPolicy"
)
Template.CertificateValidity = PropertyTypeDescriptor(
    _Template.CertificateValidity, "CertificateValidity"
)
Template.EnrollmentFlagsV2 = PropertyTypeDescriptor(
    _Template.EnrollmentFlagsV2, "EnrollmentFlagsV2"
)
Template.EnrollmentFlagsV3 = PropertyTypeDescriptor(
    _Template.EnrollmentFlagsV3, "EnrollmentFlagsV3"
)
Template.EnrollmentFlagsV4 = PropertyTypeDescriptor(
    _Template.EnrollmentFlagsV4, "EnrollmentFlagsV4"
)
Template.ExtensionsV2 = PropertyTypeDescriptor(_Template.ExtensionsV2, "ExtensionsV2")
Template.ExtensionsV3 = PropertyTypeDescriptor(_Template.ExtensionsV3, "ExtensionsV3")
Template.ExtensionsV4 = PropertyTypeDescriptor(_Template.ExtensionsV4, "ExtensionsV4")
Template.GeneralFlagsV2 = PropertyTypeDescriptor(
    _Template.GeneralFlagsV2, "GeneralFlagsV2"
)
Template.GeneralFlagsV3 = PropertyTypeDescriptor(
    _Template.GeneralFlagsV3, "GeneralFlagsV3"
)
Template.GeneralFlagsV4 = PropertyTypeDescriptor(
    _Template.GeneralFlagsV4, "GeneralFlagsV4"
)
Template.KeyUsage = PropertyTypeDescriptor(_Template.KeyUsage, "KeyUsage")
Template.KeyUsageFlags = PropertyTypeDescriptor(
    _Template.KeyUsageFlags, "KeyUsageFlags"
)
Template.KeyUsageProperty = PropertyTypeDescriptor(
    _Template.KeyUsageProperty, "KeyUsageProperty"
)
Template.KeyUsagePropertyFlags = PropertyTypeDescriptor(
    _Template.KeyUsagePropertyFlags, "KeyUsagePropertyFlags"
)
Template.PrivateKeyAttributesV2 = PropertyTypeDescriptor(
    _Template.PrivateKeyAttributesV2, "PrivateKeyAttributesV2"
)
Template.PrivateKeyAttributesV3 = PropertyTypeDescriptor(
    _Template.PrivateKeyAttributesV3, "PrivateKeyAttributesV3"
)
Template.PrivateKeyAttributesV4 = PropertyTypeDescriptor(
    _Template.PrivateKeyAttributesV4, "PrivateKeyAttributesV4"
)
Template.PrivateKeyFlagsV2 = PropertyTypeDescriptor(
    _Template.PrivateKeyFlagsV2, "PrivateKeyFlagsV2"
)
Template.PrivateKeyFlagsV3 = PropertyTypeDescriptor(
    _Template.PrivateKeyFlagsV3, "PrivateKeyFlagsV3"
)
Template.PrivateKeyFlagsV4 = PropertyTypeDescriptor(
    _Template.PrivateKeyFlagsV4, "PrivateKeyFlagsV4"
)
Template.SubjectNameFlagsV2 = PropertyTypeDescriptor(
    _Template.SubjectNameFlagsV2, "SubjectNameFlagsV2"
)
Template.SubjectNameFlagsV3 = PropertyTypeDescriptor(
    _Template.SubjectNameFlagsV3, "SubjectNameFlagsV3"
)
Template.SubjectNameFlagsV4 = PropertyTypeDescriptor(
    _Template.SubjectNameFlagsV4, "SubjectNameFlagsV4"
)
Template.TemplateDefinition = PropertyTypeDescriptor(
    _Template.TemplateDefinition, "TemplateDefinition"
)
Template.TemplateV2 = PropertyTypeDescriptor(_Template.TemplateV2, "TemplateV2")
Template.TemplateV3 = PropertyTypeDescriptor(_Template.TemplateV3, "TemplateV3")
Template.TemplateV4 = PropertyTypeDescriptor(_Template.TemplateV4, "TemplateV4")
Template.ValidityPeriod = PropertyTypeDescriptor(
    _Template.ValidityPeriod, "ValidityPeriod"
)
TemplateGroupAccessControlEntry.AccessRights = PropertyTypeDescriptor(
    _TemplateGroupAccessControlEntry.AccessRights, "AccessRights"
)
