"""This template accomplishes the following tasks: (1) creates a VPC peering connection. (2) updates the specified route tables and security groups to allow communications via the VPC peering connecti...

Generated by wetwire-aws import."""

from wetwire_aws.loader import setup_params, setup_resources

setup_params(globals())

from .params import *  # noqa: F403, F401

setup_resources(__file__, __name__, globals())

