"""
AWS QBUSINESS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:24Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# Constants
# ============================================================


class APISchemaType:
    OPEN_API_V3 = "OPEN_API_V3"


class ActionPayloadFieldType:
    STRING = "STRING"
    NUMBER = "NUMBER"
    ARRAY = "ARRAY"
    BOOLEAN = "BOOLEAN"


class ApplicationStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class AttachmentStatus:
    FAILED = "FAILED"
    SUCCESS = "SUCCESS"


class AttachmentsControlMode:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AttributeType:
    STRING = "STRING"
    STRING_LIST = "STRING_LIST"
    NUMBER = "NUMBER"
    DATE = "DATE"


class AttributeValueOperator:
    DELETE = "DELETE"


class AudioExtractionStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class AudioExtractionType:
    TRANSCRIPT = "TRANSCRIPT"
    SUMMARY = "SUMMARY"


class AutoSubscriptionStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class BrowserExtension:
    FIREFOX = "FIREFOX"
    CHROME = "CHROME"


class ChatMode:
    RETRIEVAL_MODE = "RETRIEVAL_MODE"
    CREATOR_MODE = "CREATOR_MODE"
    PLUGIN_MODE = "PLUGIN_MODE"


class ChatResponseConfigurationStatus:
    CREATING = "CREATING"
    UPDATING = "UPDATING"
    FAILED = "FAILED"
    ACTIVE = "ACTIVE"


class ContentType:
    PDF = "PDF"
    HTML = "HTML"
    MS_WORD = "MS_WORD"
    PLAIN_TEXT = "PLAIN_TEXT"
    PPT = "PPT"
    RTF = "RTF"
    XML = "XML"
    XSLT = "XSLT"
    MS_EXCEL = "MS_EXCEL"
    CSV = "CSV"
    JSON = "JSON"
    MD = "MD"


class CreatorModeControl:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class DataAccessorAuthenticationType:
    AWS_IAM_IDC_TTI = "AWS_IAM_IDC_TTI"
    AWS_IAM_IDC_AUTH_CODE = "AWS_IAM_IDC_AUTH_CODE"


class DataSourceStatus:
    PENDING_CREATION = "PENDING_CREATION"
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class DataSourceSyncJobStatus:
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    SYNCING = "SYNCING"
    INCOMPLETE = "INCOMPLETE"
    STOPPING = "STOPPING"
    ABORTED = "ABORTED"
    SYNCING_INDEXING = "SYNCING_INDEXING"


class DocumentAttributeBoostingLevel:
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    ONE = "ONE"
    TWO = "TWO"


class DocumentContentOperator:
    DELETE = "DELETE"


class DocumentEnrichmentConditionOperator:
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUALS = "GREATER_THAN_OR_EQUALS"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUALS = "LESS_THAN_OR_EQUALS"
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    CONTAINS = "CONTAINS"
    NOT_CONTAINS = "NOT_CONTAINS"
    EXISTS = "EXISTS"
    NOT_EXISTS = "NOT_EXISTS"
    BEGINS_WITH = "BEGINS_WITH"


class DocumentStatus:
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    INDEXED = "INDEXED"
    UPDATED = "UPDATED"
    FAILED = "FAILED"
    DELETING = "DELETING"
    DELETED = "DELETED"
    DOCUMENT_FAILED_TO_INDEX = "DOCUMENT_FAILED_TO_INDEX"


class ErrorCode:
    INTERNALERROR = "InternalError"
    INVALIDREQUEST = "InvalidRequest"
    RESOURCEINACTIVE = "ResourceInactive"
    RESOURCENOTFOUND = "ResourceNotFound"


class GroupStatus:
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    PROCESSING = "PROCESSING"
    DELETING = "DELETING"
    DELETED = "DELETED"


class HallucinationReductionControl:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IdentityType:
    AWS_IAM_IDP_SAML = "AWS_IAM_IDP_SAML"
    AWS_IAM_IDP_OIDC = "AWS_IAM_IDP_OIDC"
    AWS_IAM_IDC = "AWS_IAM_IDC"
    AWS_QUICKSIGHT_IDP = "AWS_QUICKSIGHT_IDP"
    ANONYMOUS = "ANONYMOUS"


class ImageExtractionStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IndexStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    UPDATING = "UPDATING"


class IndexType:
    ENTERPRISE = "ENTERPRISE"
    STARTER = "STARTER"


class MemberRelation:
    AND = "AND"
    OR = "OR"


class MembershipType:
    INDEX = "INDEX"
    DATASOURCE = "DATASOURCE"


class MessageType:
    USER = "USER"
    SYSTEM = "SYSTEM"


class MessageUsefulness:
    USEFUL = "USEFUL"
    NOT_USEFUL = "NOT_USEFUL"


class MessageUsefulnessReason:
    NOT_FACTUALLY_CORRECT = "NOT_FACTUALLY_CORRECT"
    HARMFUL_OR_UNSAFE = "HARMFUL_OR_UNSAFE"
    INCORRECT_OR_MISSING_SOURCES = "INCORRECT_OR_MISSING_SOURCES"
    NOT_HELPFUL = "NOT_HELPFUL"
    FACTUALLY_CORRECT = "FACTUALLY_CORRECT"
    COMPLETE = "COMPLETE"
    RELEVANT_SOURCES = "RELEVANT_SOURCES"
    HELPFUL = "HELPFUL"
    NOT_BASED_ON_DOCUMENTS = "NOT_BASED_ON_DOCUMENTS"
    NOT_COMPLETE = "NOT_COMPLETE"
    NOT_CONCISE = "NOT_CONCISE"
    OTHER = "OTHER"


class NumberAttributeBoostingType:
    PRIORITIZE_LARGER_VALUES = "PRIORITIZE_LARGER_VALUES"
    PRIORITIZE_SMALLER_VALUES = "PRIORITIZE_SMALLER_VALUES"


class OrchestrationControl:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class OutputFormat:
    RAW = "RAW"
    EXTRACTED = "EXTRACTED"


class PermissionConditionOperator:
    STRINGEQUALS = "StringEquals"


class PersonalizationControlMode:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class PluginBuildStatus:
    READY = "READY"
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    CREATE_FAILED = "CREATE_FAILED"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    UPDATE_FAILED = "UPDATE_FAILED"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"


class PluginState:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class PluginType:
    SERVICE_NOW = "SERVICE_NOW"
    SALESFORCE = "SALESFORCE"
    JIRA = "JIRA"
    ZENDESK = "ZENDESK"
    CUSTOM = "CUSTOM"
    QUICKSIGHT = "QUICKSIGHT"
    SERVICENOW_NOW_PLATFORM = "SERVICENOW_NOW_PLATFORM"
    JIRA_CLOUD = "JIRA_CLOUD"
    SALESFORCE_CRM = "SALESFORCE_CRM"
    ZENDESK_SUITE = "ZENDESK_SUITE"
    ATLASSIAN_CONFLUENCE = "ATLASSIAN_CONFLUENCE"
    GOOGLE_CALENDAR = "GOOGLE_CALENDAR"
    MICROSOFT_TEAMS = "MICROSOFT_TEAMS"
    MICROSOFT_EXCHANGE = "MICROSOFT_EXCHANGE"
    PAGERDUTY_ADVANCE = "PAGERDUTY_ADVANCE"
    SMARTSHEET = "SMARTSHEET"
    ASANA = "ASANA"


class PluginTypeCategory:
    CUSTOMERRELATIONSHIPMANAGEMENTCRM = "Customer relationship management (CRM)"
    PROJECTMANAGEMENT = "Project management"
    COMMUNICATION = "Communication"
    PRODUCTIVITY = "Productivity"
    TICKETINGANDINCIDENTMANAGEMENT = "Ticketing and incident management"


class QAppsControlMode:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class ReadAccessType:
    ALLOW = "ALLOW"
    DENY = "DENY"


class ResponseConfigurationType:
    ALL = "ALL"


class ResponseScope:
    ENTERPRISE_CONTENT_ONLY = "ENTERPRISE_CONTENT_ONLY"
    EXTENDED_KNOWLEDGE_ENABLED = "EXTENDED_KNOWLEDGE_ENABLED"


class RetrieverStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"


class RetrieverType:
    NATIVE_INDEX = "NATIVE_INDEX"
    KENDRA_INDEX = "KENDRA_INDEX"


class RuleType:
    CONTENT_BLOCKER_RULE = "CONTENT_BLOCKER_RULE"
    CONTENT_RETRIEVAL_RULE = "CONTENT_RETRIEVAL_RULE"


class ScoreConfidence:
    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class Status:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class StringAttributeValueBoostingLevel:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    ONE = "ONE"
    TWO = "TWO"
    THREE = "THREE"
    FOUR = "FOUR"
    FIVE = "FIVE"


class SubscriptionType:
    Q_LITE = "Q_LITE"
    Q_BUSINESS = "Q_BUSINESS"


class SystemMessageType:
    RESPONSE = "RESPONSE"
    GROUNDED_RESPONSE = "GROUNDED_RESPONSE"


class ValidationExceptionReason:
    CANNOT_PARSE = "CANNOT_PARSE"
    FIELD_VALIDATION_FAILED = "FIELD_VALIDATION_FAILED"
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION"


class VideoExtractionStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class VideoExtractionType:
    TRANSCRIPT = "TRANSCRIPT"
    SUMMARY = "SUMMARY"


class WebExperienceSamplePromptsControlMode:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class WebExperienceStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    FAILED = "FAILED"
    PENDING_AUTH_CONFIG = "PENDING_AUTH_CONFIG"


# PropertyType submodules
from . import Application as _Application
from . import DataAccessor as _DataAccessor
from . import DataSource as _DataSource
from . import Index as _Index
from . import Permission as _Permission
from . import Plugin as _Plugin
from . import Retriever as _Retriever
from . import WebExperience as _WebExperience


# Resources
# ============================================================


@dataclass
class Application(CloudFormationResource):
    """Application resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-application.html

    CloudFormation type: AWS::QBusiness::Application
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::Application"
    _property_mappings: ClassVar[dict[str, str]] = {
        "client_ids_for_oidc": "ClientIdsForOIDC",
    }

    display_name: str | None = None
    attachments_configuration: _Application.AttachmentsConfiguration | None = None
    auto_subscription_configuration: (
        _Application.AutoSubscriptionConfiguration | None
    ) = None
    client_ids_for_oidc: list[String] = field(default_factory=list)
    description: str | None = None
    encryption_configuration: _Application.EncryptionConfiguration | None = None
    iam_identity_provider_arn: str | None = None
    identity_center_instance_arn: str | None = None
    identity_type: str | None = None
    personalization_configuration: _Application.PersonalizationConfiguration | None = (
        None
    )
    q_apps_configuration: _Application.QAppsConfiguration | None = None
    quick_sight_configuration: _Application.QuickSightConfiguration | None = None
    role_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    IDENTITYCENTERAPPLICATIONARN: ClassVar[str] = "IdentityCenterApplicationArn"
    APPLICATIONARN: ClassVar[str] = "ApplicationArn"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    APPLICATIONID: ClassVar[str] = "ApplicationId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


@dataclass
class DataAccessor(CloudFormationResource):
    """DataAccessor resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-dataaccessor.html

    CloudFormation type: AWS::QBusiness::DataAccessor
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::DataAccessor"

    action_configurations: list[_DataAccessor.ActionConfiguration] = field(
        default_factory=list
    )
    application_id: str | None = None
    display_name: str | None = None
    principal: str | None = None
    authentication_detail: _DataAccessor.DataAccessorAuthenticationDetail | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    IDCAPPLICATIONARN: ClassVar[str] = "IdcApplicationArn"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    DATAACCESSORARN: ClassVar[str] = "DataAccessorArn"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    DATAACCESSORID: ClassVar[str] = "DataAccessorId"


@dataclass
class DataSource(CloudFormationResource):
    """DataSource resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-datasource.html

    CloudFormation type: AWS::QBusiness::DataSource
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::DataSource"

    application_id: str | None = None
    configuration: dict[str, Any] | None = None
    display_name: str | None = None
    index_id: str | None = None
    description: str | None = None
    document_enrichment_configuration: (
        _DataSource.DocumentEnrichmentConfiguration | None
    ) = None
    media_extraction_configuration: _DataSource.MediaExtractionConfiguration | None = (
        None
    )
    role_arn: str | None = None
    sync_schedule: str | None = None
    tags: list[Tag] = field(default_factory=list)
    vpc_configuration: _DataSource.DataSourceVpcConfiguration | None = None

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    DATASOURCEARN: ClassVar[str] = "DataSourceArn"
    TYPE: ClassVar[str] = "Type"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    DATASOURCEID: ClassVar[str] = "DataSourceId"


@dataclass
class Index(CloudFormationResource):
    """Index resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-index.html

    CloudFormation type: AWS::QBusiness::Index
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::Index"

    application_id: str | None = None
    display_name: str | None = None
    capacity_configuration: _Index.IndexCapacityConfiguration | None = None
    description: str | None = None
    document_attribute_configurations: list[_Index.DocumentAttributeConfiguration] = (
        field(default_factory=list)
    )
    tags: list[Tag] = field(default_factory=list)
    type_: str | None = None

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    INDEXSTATISTICS: ClassVar[str] = "IndexStatistics"
    INDEXSTATISTICS_TEXTDOCUMENTSTATISTICS_INDEXEDTEXTDOCUMENTCOUNT: ClassVar[str] = (
        "IndexStatistics.TextDocumentStatistics.IndexedTextDocumentCount"
    )
    INDEXID: ClassVar[str] = "IndexId"
    INDEXARN: ClassVar[str] = "IndexArn"
    INDEXSTATISTICS_TEXTDOCUMENTSTATISTICS: ClassVar[str] = (
        "IndexStatistics.TextDocumentStatistics"
    )
    CREATEDAT: ClassVar[str] = "CreatedAt"
    INDEXSTATISTICS_TEXTDOCUMENTSTATISTICS_INDEXEDTEXTBYTES: ClassVar[str] = (
        "IndexStatistics.TextDocumentStatistics.IndexedTextBytes"
    )
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


@dataclass
class Permission(CloudFormationResource):
    """Permission resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-permission.html

    CloudFormation type: AWS::QBusiness::Permission
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::Permission"

    actions: list[String] = field(default_factory=list)
    application_id: str | None = None
    principal: str | None = None
    statement_id: str | None = None
    conditions: list[_Permission.Condition] = field(default_factory=list)


@dataclass
class Plugin(CloudFormationResource):
    """Plugin resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-plugin.html

    CloudFormation type: AWS::QBusiness::Plugin
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::Plugin"

    auth_configuration: _Plugin.PluginAuthConfiguration | None = None
    display_name: str | None = None
    type_: str | None = None
    application_id: str | None = None
    custom_plugin_configuration: _Plugin.CustomPluginConfiguration | None = None
    server_url: str | None = None
    state: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    PLUGINARN: ClassVar[str] = "PluginArn"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    BUILDSTATUS: ClassVar[str] = "BuildStatus"
    PLUGINID: ClassVar[str] = "PluginId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


@dataclass
class Retriever(CloudFormationResource):
    """Retriever resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-retriever.html

    CloudFormation type: AWS::QBusiness::Retriever
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::Retriever"

    application_id: str | None = None
    configuration: _Retriever.RetrieverConfiguration | None = None
    display_name: str | None = None
    type_: str | None = None
    role_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    RETRIEVERARN: ClassVar[str] = "RetrieverArn"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    RETRIEVERID: ClassVar[str] = "RetrieverId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


@dataclass
class WebExperience(CloudFormationResource):
    """WebExperience resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qbusiness-webexperience.html

    CloudFormation type: AWS::QBusiness::WebExperience
    """

    _resource_type: ClassVar[str] = "AWS::QBusiness::WebExperience"

    application_id: str | None = None
    browser_extension_configuration: (
        _WebExperience.BrowserExtensionConfiguration | None
    ) = None
    customization_configuration: _WebExperience.CustomizationConfiguration | None = None
    identity_provider_configuration: (
        _WebExperience.IdentityProviderConfiguration | None
    ) = None
    origins: list[String] = field(default_factory=list)
    role_arn: str | None = None
    sample_prompts_control_mode: str | None = None
    subtitle: str | None = None
    tags: list[Tag] = field(default_factory=list)
    title: str | None = None
    welcome_message: str | None = None

    # GetAtt attributes
    STATUS: ClassVar[str] = "Status"
    WEBEXPERIENCEID: ClassVar[str] = "WebExperienceId"
    DEFAULTENDPOINT: ClassVar[str] = "DefaultEndpoint"
    WEBEXPERIENCEARN: ClassVar[str] = "WebExperienceArn"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Application.AttachmentsConfiguration = _Application.AttachmentsConfiguration
Application.AutoSubscriptionConfiguration = _Application.AutoSubscriptionConfiguration
Application.EncryptionConfiguration = _Application.EncryptionConfiguration
Application.PersonalizationConfiguration = _Application.PersonalizationConfiguration
Application.QAppsConfiguration = _Application.QAppsConfiguration
Application.QuickSightConfiguration = _Application.QuickSightConfiguration
DataAccessor.ActionConfiguration = _DataAccessor.ActionConfiguration
DataAccessor.ActionFilterConfiguration = _DataAccessor.ActionFilterConfiguration
DataAccessor.AttributeFilter = _DataAccessor.AttributeFilter
DataAccessor.DataAccessorAuthenticationConfiguration = (
    _DataAccessor.DataAccessorAuthenticationConfiguration
)
DataAccessor.DataAccessorAuthenticationDetail = (
    _DataAccessor.DataAccessorAuthenticationDetail
)
DataAccessor.DataAccessorIdcTrustedTokenIssuerConfiguration = (
    _DataAccessor.DataAccessorIdcTrustedTokenIssuerConfiguration
)
DataAccessor.DocumentAttribute = _DataAccessor.DocumentAttribute
DataAccessor.DocumentAttributeValue = _DataAccessor.DocumentAttributeValue
DataSource.AudioExtractionConfiguration = _DataSource.AudioExtractionConfiguration
DataSource.DataSourceVpcConfiguration = _DataSource.DataSourceVpcConfiguration
DataSource.DocumentAttributeCondition = _DataSource.DocumentAttributeCondition
DataSource.DocumentAttributeTarget = _DataSource.DocumentAttributeTarget
DataSource.DocumentAttributeValue = _DataSource.DocumentAttributeValue
DataSource.DocumentEnrichmentConfiguration = _DataSource.DocumentEnrichmentConfiguration
DataSource.HookConfiguration = _DataSource.HookConfiguration
DataSource.ImageExtractionConfiguration = _DataSource.ImageExtractionConfiguration
DataSource.InlineDocumentEnrichmentConfiguration = (
    _DataSource.InlineDocumentEnrichmentConfiguration
)
DataSource.MediaExtractionConfiguration = _DataSource.MediaExtractionConfiguration
DataSource.VideoExtractionConfiguration = _DataSource.VideoExtractionConfiguration
Index.DocumentAttributeConfiguration = _Index.DocumentAttributeConfiguration
Index.IndexCapacityConfiguration = _Index.IndexCapacityConfiguration
Index.IndexStatistics = _Index.IndexStatistics
Index.TextDocumentStatistics = _Index.TextDocumentStatistics
Permission.Condition = _Permission.Condition
Plugin.APISchema = _Plugin.APISchema
Plugin.BasicAuthConfiguration = _Plugin.BasicAuthConfiguration
Plugin.CustomPluginConfiguration = _Plugin.CustomPluginConfiguration
Plugin.OAuth2ClientCredentialConfiguration = _Plugin.OAuth2ClientCredentialConfiguration
Plugin.PluginAuthConfiguration = _Plugin.PluginAuthConfiguration
Plugin.S3 = _Plugin.S3
Retriever.KendraIndexConfiguration = _Retriever.KendraIndexConfiguration
Retriever.NativeIndexConfiguration = _Retriever.NativeIndexConfiguration
Retriever.RetrieverConfiguration = _Retriever.RetrieverConfiguration
WebExperience.BrowserExtensionConfiguration = (
    _WebExperience.BrowserExtensionConfiguration
)
WebExperience.CustomizationConfiguration = _WebExperience.CustomizationConfiguration
WebExperience.IdentityProviderConfiguration = (
    _WebExperience.IdentityProviderConfiguration
)
WebExperience.OpenIDConnectProviderConfiguration = (
    _WebExperience.OpenIDConnectProviderConfiguration
)
WebExperience.SamlProviderConfiguration = _WebExperience.SamlProviderConfiguration
