"""
AWS NETWORKMANAGER CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:23Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class AttachmentErrorCode:
    VPC_NOT_FOUND = "VPC_NOT_FOUND"
    SUBNET_NOT_FOUND = "SUBNET_NOT_FOUND"
    SUBNET_DUPLICATED_IN_AVAILABILITY_ZONE = "SUBNET_DUPLICATED_IN_AVAILABILITY_ZONE"
    SUBNET_NO_FREE_ADDRESSES = "SUBNET_NO_FREE_ADDRESSES"
    SUBNET_UNSUPPORTED_AVAILABILITY_ZONE = "SUBNET_UNSUPPORTED_AVAILABILITY_ZONE"
    SUBNET_NO_IPV6_CIDRS = "SUBNET_NO_IPV6_CIDRS"
    VPN_CONNECTION_NOT_FOUND = "VPN_CONNECTION_NOT_FOUND"
    MAXIMUM_NO_ENCAP_LIMIT_EXCEEDED = "MAXIMUM_NO_ENCAP_LIMIT_EXCEEDED"
    DIRECT_CONNECT_GATEWAY_NOT_FOUND = "DIRECT_CONNECT_GATEWAY_NOT_FOUND"
    DIRECT_CONNECT_GATEWAY_EXISTING_ATTACHMENTS = (
        "DIRECT_CONNECT_GATEWAY_EXISTING_ATTACHMENTS"
    )
    DIRECT_CONNECT_GATEWAY_NO_PRIVATE_VIF = "DIRECT_CONNECT_GATEWAY_NO_PRIVATE_VIF"
    VPN_EXISTING_ASSOCIATIONS = "VPN_EXISTING_ASSOCIATIONS"
    VPC_UNSUPPORTED_FEATURES = "VPC_UNSUPPORTED_FEATURES"


class AttachmentState:
    REJECTED = "REJECTED"
    PENDING_ATTACHMENT_ACCEPTANCE = "PENDING_ATTACHMENT_ACCEPTANCE"
    CREATING = "CREATING"
    FAILED = "FAILED"
    AVAILABLE = "AVAILABLE"
    UPDATING = "UPDATING"
    PENDING_NETWORK_UPDATE = "PENDING_NETWORK_UPDATE"
    PENDING_TAG_ACCEPTANCE = "PENDING_TAG_ACCEPTANCE"
    DELETING = "DELETING"


class AttachmentType:
    CONNECT = "CONNECT"
    SITE_TO_SITE_VPN = "SITE_TO_SITE_VPN"
    VPC = "VPC"
    DIRECT_CONNECT_GATEWAY = "DIRECT_CONNECT_GATEWAY"
    TRANSIT_GATEWAY_ROUTE_TABLE = "TRANSIT_GATEWAY_ROUTE_TABLE"


class ChangeAction:
    ADD = "ADD"
    MODIFY = "MODIFY"
    REMOVE = "REMOVE"


class ChangeSetState:
    PENDING_GENERATION = "PENDING_GENERATION"
    FAILED_GENERATION = "FAILED_GENERATION"
    READY_TO_EXECUTE = "READY_TO_EXECUTE"
    EXECUTING = "EXECUTING"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    OUT_OF_DATE = "OUT_OF_DATE"


class ChangeStatus:
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class ChangeType:
    CORE_NETWORK_SEGMENT = "CORE_NETWORK_SEGMENT"
    NETWORK_FUNCTION_GROUP = "NETWORK_FUNCTION_GROUP"
    CORE_NETWORK_EDGE = "CORE_NETWORK_EDGE"
    ATTACHMENT_MAPPING = "ATTACHMENT_MAPPING"
    ATTACHMENT_ROUTE_PROPAGATION = "ATTACHMENT_ROUTE_PROPAGATION"
    ATTACHMENT_ROUTE_STATIC = "ATTACHMENT_ROUTE_STATIC"
    ROUTING_POLICY = "ROUTING_POLICY"
    ROUTING_POLICY_SEGMENT_ASSOCIATION = "ROUTING_POLICY_SEGMENT_ASSOCIATION"
    ROUTING_POLICY_EDGE_ASSOCIATION = "ROUTING_POLICY_EDGE_ASSOCIATION"
    ROUTING_POLICY_ATTACHMENT_ASSOCIATION = "ROUTING_POLICY_ATTACHMENT_ASSOCIATION"
    CORE_NETWORK_CONFIGURATION = "CORE_NETWORK_CONFIGURATION"
    SEGMENTS_CONFIGURATION = "SEGMENTS_CONFIGURATION"
    SEGMENT_ACTIONS_CONFIGURATION = "SEGMENT_ACTIONS_CONFIGURATION"
    ATTACHMENT_POLICIES_CONFIGURATION = "ATTACHMENT_POLICIES_CONFIGURATION"


class ConnectPeerAssociationState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    DELETED = "DELETED"


class ConnectPeerErrorCode:
    EDGE_LOCATION_NO_FREE_IPS = "EDGE_LOCATION_NO_FREE_IPS"
    EDGE_LOCATION_PEER_DUPLICATE = "EDGE_LOCATION_PEER_DUPLICATE"
    SUBNET_NOT_FOUND = "SUBNET_NOT_FOUND"
    IP_OUTSIDE_SUBNET_CIDR_RANGE = "IP_OUTSIDE_SUBNET_CIDR_RANGE"
    INVALID_INSIDE_CIDR_BLOCK = "INVALID_INSIDE_CIDR_BLOCK"
    NO_ASSOCIATED_CIDR_BLOCK = "NO_ASSOCIATED_CIDR_BLOCK"


class ConnectPeerState:
    CREATING = "CREATING"
    FAILED = "FAILED"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"


class ConnectionState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    UPDATING = "UPDATING"


class ConnectionStatus:
    UP = "UP"
    DOWN = "DOWN"


class ConnectionType:
    BGP = "BGP"
    IPSEC = "IPSEC"


class CoreNetworkPolicyAlias:
    LIVE = "LIVE"
    LATEST = "LATEST"


class CoreNetworkState:
    CREATING = "CREATING"
    UPDATING = "UPDATING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"


class CustomerGatewayAssociationState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    DELETED = "DELETED"


class DeviceState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    UPDATING = "UPDATING"


class GlobalNetworkState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    UPDATING = "UPDATING"


class LinkAssociationState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    DELETED = "DELETED"


class LinkState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    UPDATING = "UPDATING"


class PeeringErrorCode:
    TRANSIT_GATEWAY_NOT_FOUND = "TRANSIT_GATEWAY_NOT_FOUND"
    TRANSIT_GATEWAY_PEERS_LIMIT_EXCEEDED = "TRANSIT_GATEWAY_PEERS_LIMIT_EXCEEDED"
    MISSING_PERMISSIONS = "MISSING_PERMISSIONS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    EDGE_LOCATION_PEER_DUPLICATE = "EDGE_LOCATION_PEER_DUPLICATE"
    INVALID_TRANSIT_GATEWAY_STATE = "INVALID_TRANSIT_GATEWAY_STATE"


class PeeringState:
    CREATING = "CREATING"
    FAILED = "FAILED"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"


class PeeringType:
    TRANSIT_GATEWAY = "TRANSIT_GATEWAY"


class RouteAnalysisCompletionReasonCode:
    TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND = "TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND"
    TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY = (
        "TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY"
    )
    CYCLIC_PATH_DETECTED = "CYCLIC_PATH_DETECTED"
    TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND = (
        "TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND"
    )
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND = "BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND"
    INACTIVE_ROUTE_FOR_DESTINATION_FOUND = "INACTIVE_ROUTE_FOR_DESTINATION_FOUND"
    TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH = (
        "TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH"
    )
    MAX_HOPS_EXCEEDED = "MAX_HOPS_EXCEEDED"
    POSSIBLE_MIDDLEBOX = "POSSIBLE_MIDDLEBOX"
    NO_DESTINATION_ARN_PROVIDED = "NO_DESTINATION_ARN_PROVIDED"


class RouteAnalysisCompletionResultCode:
    CONNECTED = "CONNECTED"
    NOT_CONNECTED = "NOT_CONNECTED"


class RouteAnalysisStatus:
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RouteState:
    ACTIVE = "ACTIVE"
    BLACKHOLE = "BLACKHOLE"


class RouteTableType:
    TRANSIT_GATEWAY_ROUTE_TABLE = "TRANSIT_GATEWAY_ROUTE_TABLE"
    CORE_NETWORK_SEGMENT = "CORE_NETWORK_SEGMENT"
    NETWORK_FUNCTION_GROUP = "NETWORK_FUNCTION_GROUP"


class RouteType:
    PROPAGATED = "PROPAGATED"
    STATIC = "STATIC"


class RoutingPolicyDirection:
    INBOUND = "inbound"
    OUTBOUND = "outbound"


class SegmentActionServiceInsertion:
    SEND_VIA = "send-via"
    SEND_TO = "send-to"


class SendViaMode:
    DUAL_HOP = "dual-hop"
    SINGLE_HOP = "single-hop"


class SiteState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    UPDATING = "UPDATING"


class TransitGatewayConnectPeerAssociationState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    DELETED = "DELETED"


class TransitGatewayRegistrationState:
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELETING = "DELETING"
    DELETED = "DELETED"
    FAILED = "FAILED"


class TunnelProtocol:
    GRE = "GRE"
    NO_ENCAP = "NO_ENCAP"


class ValidationExceptionReason:
    UNKNOWNOPERATION = "UnknownOperation"
    CANNOTPARSE = "CannotParse"
    FIELDVALIDATIONFAILED = "FieldValidationFailed"
    OTHER = "Other"


# PropertyType submodules
from . import ConnectAttachment as _ConnectAttachment
from . import ConnectPeer as _ConnectPeer
from . import CoreNetwork as _CoreNetwork
from . import Device as _Device
from . import DirectConnectGatewayAttachment as _DirectConnectGatewayAttachment
from . import Link as _Link
from . import Site as _Site
from . import SiteToSiteVpnAttachment as _SiteToSiteVpnAttachment
from . import TransitGatewayRouteTableAttachment as _TransitGatewayRouteTableAttachment
from . import VpcAttachment as _VpcAttachment


# Resources
# ============================================================


@dataclass
class ConnectAttachment(CloudFormationResource):
    """ConnectAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-connectattachment.html

    CloudFormation type: AWS::NetworkManager::ConnectAttachment
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::ConnectAttachment"

    core_network_id: DslValue[str] | None = None
    edge_location: DslValue[str] | None = None
    options: DslValue[_ConnectAttachment.ConnectAttachmentOptions] | None = None
    transport_attachment_id: DslValue[str] | None = None
    network_function_group_name: DslValue[str] | None = None
    proposed_network_function_group_change: (
        DslValue[_ConnectAttachment.ProposedNetworkFunctionGroupChange] | None
    ) = None
    proposed_segment_change: (
        DslValue[_ConnectAttachment.ProposedSegmentChange] | None
    ) = None
    routing_policy_label: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    ATTACHMENTTYPE: ClassVar[str] = "AttachmentType"
    SEGMENTNAME: ClassVar[str] = "SegmentName"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    ATTACHMENTID: ClassVar[str] = "AttachmentId"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    ATTACHMENTPOLICYRULENUMBER: ClassVar[str] = "AttachmentPolicyRuleNumber"

    # PropertyType descriptors for nested GetAtt support
    ConnectAttachmentOptions = PropertyTypeDescriptor(
        _ConnectAttachment.ConnectAttachmentOptions, "ConnectAttachmentOptions"
    )
    ProposedNetworkFunctionGroupChange = PropertyTypeDescriptor(
        _ConnectAttachment.ProposedNetworkFunctionGroupChange,
        "ProposedNetworkFunctionGroupChange",
    )
    ProposedSegmentChange = PropertyTypeDescriptor(
        _ConnectAttachment.ProposedSegmentChange, "ProposedSegmentChange"
    )


@dataclass
class ConnectPeer(CloudFormationResource):
    """ConnectPeer resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-connectpeer.html

    CloudFormation type: AWS::NetworkManager::ConnectPeer
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::ConnectPeer"

    connect_attachment_id: DslValue[str] | None = None
    peer_address: DslValue[str] | None = None
    bgp_options: DslValue[_ConnectPeer.BgpOptions] | None = None
    core_network_address: DslValue[str] | None = None
    inside_cidr_blocks: list[DslValue[str]] = field(default_factory=list)
    subnet_arn: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CONFIGURATION_BGPCONFIGURATIONS: ClassVar[str] = "Configuration.BgpConfigurations"
    CORENETWORKID: ClassVar[str] = "CoreNetworkId"
    CONFIGURATION_INSIDECIDRBLOCKS: ClassVar[str] = "Configuration.InsideCidrBlocks"
    CONFIGURATION: ClassVar[str] = "Configuration"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    CONNECTPEERID: ClassVar[str] = "ConnectPeerId"
    CONFIGURATION_CORENETWORKADDRESS: ClassVar[str] = "Configuration.CoreNetworkAddress"
    CONFIGURATION_PROTOCOL: ClassVar[str] = "Configuration.Protocol"
    CONFIGURATION_PEERADDRESS: ClassVar[str] = "Configuration.PeerAddress"
    EDGELOCATION: ClassVar[str] = "EdgeLocation"

    # PropertyType descriptors for nested GetAtt support
    BgpOptions = PropertyTypeDescriptor(_ConnectPeer.BgpOptions, "BgpOptions")
    ConnectPeerBgpConfiguration = PropertyTypeDescriptor(
        _ConnectPeer.ConnectPeerBgpConfiguration, "ConnectPeerBgpConfiguration"
    )
    ConnectPeerConfiguration = PropertyTypeDescriptor(
        _ConnectPeer.ConnectPeerConfiguration, "ConnectPeerConfiguration"
    )


@dataclass
class CoreNetwork(CloudFormationResource):
    """CoreNetwork resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-corenetwork.html

    CloudFormation type: AWS::NetworkManager::CoreNetwork
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::CoreNetwork"

    global_network_id: DslValue[str] | None = None
    description: DslValue[str] | None = None
    policy_document: DslValue[dict[str, Any]] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CORENETWORKID: ClassVar[str] = "CoreNetworkId"
    STATE: ClassVar[str] = "State"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    SEGMENTS: ClassVar[str] = "Segments"
    NETWORKFUNCTIONGROUPS: ClassVar[str] = "NetworkFunctionGroups"
    OWNERACCOUNT: ClassVar[str] = "OwnerAccount"
    EDGES: ClassVar[str] = "Edges"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"

    # PropertyType descriptors for nested GetAtt support
    CoreNetworkEdge = PropertyTypeDescriptor(
        _CoreNetwork.CoreNetworkEdge, "CoreNetworkEdge"
    )
    CoreNetworkNetworkFunctionGroup = PropertyTypeDescriptor(
        _CoreNetwork.CoreNetworkNetworkFunctionGroup, "CoreNetworkNetworkFunctionGroup"
    )
    CoreNetworkSegment = PropertyTypeDescriptor(
        _CoreNetwork.CoreNetworkSegment, "CoreNetworkSegment"
    )
    Segments = PropertyTypeDescriptor(_CoreNetwork.Segments, "Segments")


@dataclass
class CoreNetworkPrefixListAssociation(CloudFormationResource):
    """CoreNetworkPrefixListAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-corenetworkprefixlistassociation.html

    CloudFormation type: AWS::NetworkManager::CoreNetworkPrefixListAssociation
    """

    _resource_type: ClassVar[str] = (
        "AWS::NetworkManager::CoreNetworkPrefixListAssociation"
    )

    core_network_id: DslValue[str] | None = None
    prefix_list_alias: DslValue[str] | None = None
    prefix_list_arn: DslValue[str] | None = None


@dataclass
class CustomerGatewayAssociation(CloudFormationResource):
    """CustomerGatewayAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-customergatewayassociation.html

    CloudFormation type: AWS::NetworkManager::CustomerGatewayAssociation
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::CustomerGatewayAssociation"

    customer_gateway_arn: DslValue[str] | None = None
    device_id: DslValue[str] | None = None
    global_network_id: DslValue[str] | None = None
    link_id: DslValue[str] | None = None


@dataclass
class Device(CloudFormationResource):
    """Device resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-device.html

    CloudFormation type: AWS::NetworkManager::Device
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::Device"
    _property_mappings: ClassVar[dict[str, str]] = {
        "aws_location": "AWSLocation",
    }

    global_network_id: DslValue[str] | None = None
    aws_location: DslValue[_Device.AWSLocation] | None = None
    description: DslValue[str] | None = None
    location: DslValue[_Device.Location] | None = None
    model: DslValue[str] | None = None
    serial_number: DslValue[str] | None = None
    site_id: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    type_: DslValue[str] | None = None
    vendor: DslValue[str] | None = None

    # GetAtt attributes
    DEVICEARN: ClassVar[str] = "DeviceArn"
    DEVICEID: ClassVar[str] = "DeviceId"
    STATE: ClassVar[str] = "State"
    CREATEDAT: ClassVar[str] = "CreatedAt"

    # PropertyType descriptors for nested GetAtt support
    AWSLocation = PropertyTypeDescriptor(_Device.AWSLocation, "AWSLocation")
    Location = PropertyTypeDescriptor(_Device.Location, "Location")


@dataclass
class DirectConnectGatewayAttachment(CloudFormationResource):
    """DirectConnectGatewayAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-directconnectgatewayattachment.html

    CloudFormation type: AWS::NetworkManager::DirectConnectGatewayAttachment
    """

    _resource_type: ClassVar[str] = (
        "AWS::NetworkManager::DirectConnectGatewayAttachment"
    )

    core_network_id: DslValue[str] | None = None
    direct_connect_gateway_arn: DslValue[str] | None = None
    edge_locations: list[DslValue[str]] = field(default_factory=list)
    proposed_network_function_group_change: (
        DslValue[_DirectConnectGatewayAttachment.ProposedNetworkFunctionGroupChange]
        | None
    ) = None
    proposed_segment_change: (
        DslValue[_DirectConnectGatewayAttachment.ProposedSegmentChange] | None
    ) = None
    routing_policy_label: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    ATTACHMENTTYPE: ClassVar[str] = "AttachmentType"
    SEGMENTNAME: ClassVar[str] = "SegmentName"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    ATTACHMENTID: ClassVar[str] = "AttachmentId"
    NETWORKFUNCTIONGROUPNAME: ClassVar[str] = "NetworkFunctionGroupName"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    ATTACHMENTPOLICYRULENUMBER: ClassVar[str] = "AttachmentPolicyRuleNumber"

    # PropertyType descriptors for nested GetAtt support
    ProposedNetworkFunctionGroupChange = PropertyTypeDescriptor(
        _DirectConnectGatewayAttachment.ProposedNetworkFunctionGroupChange,
        "ProposedNetworkFunctionGroupChange",
    )
    ProposedSegmentChange = PropertyTypeDescriptor(
        _DirectConnectGatewayAttachment.ProposedSegmentChange, "ProposedSegmentChange"
    )


@dataclass
class GlobalNetwork(CloudFormationResource):
    """GlobalNetwork resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-globalnetwork.html

    CloudFormation type: AWS::NetworkManager::GlobalNetwork
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::GlobalNetwork"

    created_at: DslValue[str] | None = None
    description: DslValue[str] | None = None
    state: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ID: ClassVar[str] = "Id"
    ARN: ClassVar[str] = "Arn"


@dataclass
class Link(CloudFormationResource):
    """Link resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-link.html

    CloudFormation type: AWS::NetworkManager::Link
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::Link"

    bandwidth: DslValue[_Link.Bandwidth] | None = None
    global_network_id: DslValue[str] | None = None
    site_id: DslValue[str] | None = None
    description: DslValue[str] | None = None
    provider: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    type_: DslValue[str] | None = None

    # GetAtt attributes
    LINKARN: ClassVar[str] = "LinkArn"
    STATE: ClassVar[str] = "State"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    LINKID: ClassVar[str] = "LinkId"

    # PropertyType descriptors for nested GetAtt support
    Bandwidth = PropertyTypeDescriptor(_Link.Bandwidth, "Bandwidth")


@dataclass
class LinkAssociation(CloudFormationResource):
    """LinkAssociation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-linkassociation.html

    CloudFormation type: AWS::NetworkManager::LinkAssociation
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::LinkAssociation"

    device_id: DslValue[str] | None = None
    global_network_id: DslValue[str] | None = None
    link_id: DslValue[str] | None = None


@dataclass
class Site(CloudFormationResource):
    """Site resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-site.html

    CloudFormation type: AWS::NetworkManager::Site
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::Site"

    global_network_id: DslValue[str] | None = None
    description: DslValue[str] | None = None
    location: DslValue[_Site.Location] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    SITEID: ClassVar[str] = "SiteId"
    SITEARN: ClassVar[str] = "SiteArn"
    STATE: ClassVar[str] = "State"
    CREATEDAT: ClassVar[str] = "CreatedAt"

    # PropertyType descriptors for nested GetAtt support
    Location = PropertyTypeDescriptor(_Site.Location, "Location")


@dataclass
class SiteToSiteVpnAttachment(CloudFormationResource):
    """SiteToSiteVpnAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-sitetositevpnattachment.html

    CloudFormation type: AWS::NetworkManager::SiteToSiteVpnAttachment
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::SiteToSiteVpnAttachment"

    core_network_id: DslValue[str] | None = None
    vpn_connection_arn: DslValue[str] | None = None
    network_function_group_name: DslValue[str] | None = None
    proposed_network_function_group_change: (
        DslValue[_SiteToSiteVpnAttachment.ProposedNetworkFunctionGroupChange] | None
    ) = None
    proposed_segment_change: (
        DslValue[_SiteToSiteVpnAttachment.ProposedSegmentChange] | None
    ) = None
    routing_policy_label: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    ATTACHMENTTYPE: ClassVar[str] = "AttachmentType"
    SEGMENTNAME: ClassVar[str] = "SegmentName"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    ATTACHMENTID: ClassVar[str] = "AttachmentId"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    EDGELOCATION: ClassVar[str] = "EdgeLocation"
    ATTACHMENTPOLICYRULENUMBER: ClassVar[str] = "AttachmentPolicyRuleNumber"

    # PropertyType descriptors for nested GetAtt support
    ProposedNetworkFunctionGroupChange = PropertyTypeDescriptor(
        _SiteToSiteVpnAttachment.ProposedNetworkFunctionGroupChange,
        "ProposedNetworkFunctionGroupChange",
    )
    ProposedSegmentChange = PropertyTypeDescriptor(
        _SiteToSiteVpnAttachment.ProposedSegmentChange, "ProposedSegmentChange"
    )


@dataclass
class TransitGatewayPeering(CloudFormationResource):
    """TransitGatewayPeering resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-transitgatewaypeering.html

    CloudFormation type: AWS::NetworkManager::TransitGatewayPeering
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::TransitGatewayPeering"

    core_network_id: DslValue[str] | None = None
    transit_gateway_arn: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    PEERINGTYPE: ClassVar[str] = "PeeringType"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    PEERINGID: ClassVar[str] = "PeeringId"
    TRANSITGATEWAYPEERINGATTACHMENTID: ClassVar[str] = (
        "TransitGatewayPeeringAttachmentId"
    )
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    EDGELOCATION: ClassVar[str] = "EdgeLocation"


@dataclass
class TransitGatewayRegistration(CloudFormationResource):
    """TransitGatewayRegistration resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-transitgatewayregistration.html

    CloudFormation type: AWS::NetworkManager::TransitGatewayRegistration
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::TransitGatewayRegistration"

    global_network_id: DslValue[str] | None = None
    transit_gateway_arn: DslValue[str] | None = None


@dataclass
class TransitGatewayRouteTableAttachment(CloudFormationResource):
    """TransitGatewayRouteTableAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-transitgatewayroutetableattachment.html

    CloudFormation type: AWS::NetworkManager::TransitGatewayRouteTableAttachment
    """

    _resource_type: ClassVar[str] = (
        "AWS::NetworkManager::TransitGatewayRouteTableAttachment"
    )

    peering_id: DslValue[str] | None = None
    transit_gateway_route_table_arn: DslValue[str] | None = None
    network_function_group_name: DslValue[str] | None = None
    proposed_network_function_group_change: (
        DslValue[_TransitGatewayRouteTableAttachment.ProposedNetworkFunctionGroupChange]
        | None
    ) = None
    proposed_segment_change: (
        DslValue[_TransitGatewayRouteTableAttachment.ProposedSegmentChange] | None
    ) = None
    routing_policy_label: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CORENETWORKID: ClassVar[str] = "CoreNetworkId"
    ATTACHMENTTYPE: ClassVar[str] = "AttachmentType"
    SEGMENTNAME: ClassVar[str] = "SegmentName"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    ATTACHMENTID: ClassVar[str] = "AttachmentId"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    EDGELOCATION: ClassVar[str] = "EdgeLocation"
    ATTACHMENTPOLICYRULENUMBER: ClassVar[str] = "AttachmentPolicyRuleNumber"

    # PropertyType descriptors for nested GetAtt support
    ProposedNetworkFunctionGroupChange = PropertyTypeDescriptor(
        _TransitGatewayRouteTableAttachment.ProposedNetworkFunctionGroupChange,
        "ProposedNetworkFunctionGroupChange",
    )
    ProposedSegmentChange = PropertyTypeDescriptor(
        _TransitGatewayRouteTableAttachment.ProposedSegmentChange,
        "ProposedSegmentChange",
    )


@dataclass
class VpcAttachment(CloudFormationResource):
    """VpcAttachment resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkmanager-vpcattachment.html

    CloudFormation type: AWS::NetworkManager::VpcAttachment
    """

    _resource_type: ClassVar[str] = "AWS::NetworkManager::VpcAttachment"

    core_network_id: DslValue[str] | None = None
    subnet_arns: list[DslValue[str]] = field(default_factory=list)
    vpc_arn: DslValue[str] | None = None
    options: DslValue[_VpcAttachment.VpcOptions] | None = None
    proposed_network_function_group_change: (
        DslValue[_VpcAttachment.ProposedNetworkFunctionGroupChange] | None
    ) = None
    proposed_segment_change: DslValue[_VpcAttachment.ProposedSegmentChange] | None = (
        None
    )
    routing_policy_label: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ATTACHMENTTYPE: ClassVar[str] = "AttachmentType"
    SEGMENTNAME: ClassVar[str] = "SegmentName"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    UPDATEDAT: ClassVar[str] = "UpdatedAt"
    ATTACHMENTID: ClassVar[str] = "AttachmentId"
    NETWORKFUNCTIONGROUPNAME: ClassVar[str] = "NetworkFunctionGroupName"
    CORENETWORKARN: ClassVar[str] = "CoreNetworkArn"
    RESOURCEARN: ClassVar[str] = "ResourceArn"
    STATE: ClassVar[str] = "State"
    LASTMODIFICATIONERRORS: ClassVar[str] = "LastModificationErrors"
    OWNERACCOUNTID: ClassVar[str] = "OwnerAccountId"
    EDGELOCATION: ClassVar[str] = "EdgeLocation"
    ATTACHMENTPOLICYRULENUMBER: ClassVar[str] = "AttachmentPolicyRuleNumber"

    # PropertyType descriptors for nested GetAtt support
    ProposedNetworkFunctionGroupChange = PropertyTypeDescriptor(
        _VpcAttachment.ProposedNetworkFunctionGroupChange,
        "ProposedNetworkFunctionGroupChange",
    )
    ProposedSegmentChange = PropertyTypeDescriptor(
        _VpcAttachment.ProposedSegmentChange, "ProposedSegmentChange"
    )
    VpcOptions = PropertyTypeDescriptor(_VpcAttachment.VpcOptions, "VpcOptions")
