"""
AWS DOCDBELASTIC CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:21Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Resources
# ============================================================


@dataclass
class Cluster(CloudFormationResource):
    """Cluster resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdbelastic-cluster.html

    CloudFormation type: AWS::DocDBElastic::Cluster
    """

    _resource_type: ClassVar[str] = "AWS::DocDBElastic::Cluster"

    admin_user_name: DslValue[str] | None = None
    auth_type: DslValue[str] | None = None
    cluster_name: DslValue[str] | None = None
    shard_capacity: DslValue[int] | None = None
    shard_count: DslValue[int] | None = None
    admin_user_password: DslValue[str] | None = None
    backup_retention_period: DslValue[int] | None = None
    kms_key_id: DslValue[str] | None = None
    preferred_backup_window: DslValue[str] | None = None
    preferred_maintenance_window: DslValue[str] | None = None
    shard_instance_count: DslValue[int] | None = None
    subnet_ids: list[DslValue[str]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)
    vpc_security_group_ids: list[DslValue[str]] = field(default_factory=list)

    # GetAtt attributes
    CLUSTERARN: ClassVar[str] = "ClusterArn"
    CLUSTERENDPOINT: ClassVar[str] = "ClusterEndpoint"
