"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    # Decorator
    wetwire_aws,
    # Base classes
    CloudFormationResource,
    PropertyType,
    # Policy helpers
    PolicyStatement,
    DenyStatement,
    PolicyDocument,
    # Template components
    CloudFormationTemplate,
    Parameter,
    Output,
    Mapping,
    TemplateCondition,
    # Reference types (from dataclass-dsl)
    Ref,
    RefList,
    RefDict,
    # Reference helpers
    ref,
    get_att,
    ARN,
    # Intrinsic functions
    GetAtt,
    Sub,
    Join,
    Select,
    Split,
    If,
    Equals,
    And,
    Or,
    Not,
    Base64,
    GetAZs,
    ImportValue,
    FindInMap,
    Transform,
    Cidr,
    Condition,
    # Parameter type constants
    STRING,
    NUMBER,
    LIST_NUMBER,
    COMMA_DELIMITED_LIST,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    LIST_AVAILABILITY_ZONE,
    AMI_ID,
    INSTANCE_ID,
    KEY_PAIR,
    SECURITY_GROUP_ID,
    LIST_SECURITY_GROUP_ID,
    SUBNET_ID,
    LIST_SUBNET_ID,
    VPC_ID,
    VOLUME_ID,
    HOSTED_ZONE_ID,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NOTIFICATION_ARNS,
    AWS_NO_VALUE,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from wetwire_aws.loader import setup_params, setup_resources

from .main import DynamoDBInputS3OutputHive as DynamoDBInputS3OutputHive
from .main import DynamoDBInputS3OutputHiveField as DynamoDBInputS3OutputHiveField
from .main import DynamoDBInputS3OutputHiveField1 as DynamoDBInputS3OutputHiveField1
from .main import DynamoDBInputS3OutputHiveField2 as DynamoDBInputS3OutputHiveField2
from .main import DynamoDBInputS3OutputHiveField3 as DynamoDBInputS3OutputHiveField3
from .main import DynamoDBInputS3OutputHiveParameterAttribute as DynamoDBInputS3OutputHiveParameterAttribute
from .main import DynamoDBInputS3OutputHiveParameterAttribute1 as DynamoDBInputS3OutputHiveParameterAttribute1
from .main import DynamoDBInputS3OutputHiveParameterAttribute10 as DynamoDBInputS3OutputHiveParameterAttribute10
from .main import DynamoDBInputS3OutputHiveParameterAttribute11 as DynamoDBInputS3OutputHiveParameterAttribute11
from .main import DynamoDBInputS3OutputHiveParameterAttribute12 as DynamoDBInputS3OutputHiveParameterAttribute12
from .main import DynamoDBInputS3OutputHiveParameterAttribute13 as DynamoDBInputS3OutputHiveParameterAttribute13
from .main import DynamoDBInputS3OutputHiveParameterAttribute14 as DynamoDBInputS3OutputHiveParameterAttribute14
from .main import DynamoDBInputS3OutputHiveParameterAttribute15 as DynamoDBInputS3OutputHiveParameterAttribute15
from .main import DynamoDBInputS3OutputHiveParameterAttribute16 as DynamoDBInputS3OutputHiveParameterAttribute16
from .main import DynamoDBInputS3OutputHiveParameterAttribute17 as DynamoDBInputS3OutputHiveParameterAttribute17
from .main import DynamoDBInputS3OutputHiveParameterAttribute18 as DynamoDBInputS3OutputHiveParameterAttribute18
from .main import DynamoDBInputS3OutputHiveParameterAttribute19 as DynamoDBInputS3OutputHiveParameterAttribute19
from .main import DynamoDBInputS3OutputHiveParameterAttribute2 as DynamoDBInputS3OutputHiveParameterAttribute2
from .main import DynamoDBInputS3OutputHiveParameterAttribute20 as DynamoDBInputS3OutputHiveParameterAttribute20
from .main import DynamoDBInputS3OutputHiveParameterAttribute3 as DynamoDBInputS3OutputHiveParameterAttribute3
from .main import DynamoDBInputS3OutputHiveParameterAttribute4 as DynamoDBInputS3OutputHiveParameterAttribute4
from .main import DynamoDBInputS3OutputHiveParameterAttribute5 as DynamoDBInputS3OutputHiveParameterAttribute5
from .main import DynamoDBInputS3OutputHiveParameterAttribute6 as DynamoDBInputS3OutputHiveParameterAttribute6
from .main import DynamoDBInputS3OutputHiveParameterAttribute7 as DynamoDBInputS3OutputHiveParameterAttribute7
from .main import DynamoDBInputS3OutputHiveParameterAttribute8 as DynamoDBInputS3OutputHiveParameterAttribute8
from .main import DynamoDBInputS3OutputHiveParameterAttribute9 as DynamoDBInputS3OutputHiveParameterAttribute9
from .main import DynamoDBInputS3OutputHivePipelineObject as DynamoDBInputS3OutputHivePipelineObject
from .main import DynamoDBInputS3OutputHivePipelineObject1 as DynamoDBInputS3OutputHivePipelineObject1
from .main import DynamoDBInputS3OutputHivePipelineObject2 as DynamoDBInputS3OutputHivePipelineObject2
from .main import DynamoDBInputS3OutputHivePipelineObject3 as DynamoDBInputS3OutputHivePipelineObject3
from .main import DynamoDBInputS3OutputHivePipelineObject4 as DynamoDBInputS3OutputHivePipelineObject4
from .main import DynamoDBInputS3OutputHivePipelineObject5 as DynamoDBInputS3OutputHivePipelineObject5

__all__: list[str] = ['AMI_ID', 'ARN', 'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE', 'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX', 'And', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr', 'CloudFormationResource', 'CloudFormationTemplate', 'Condition', 'DenyStatement', 'DynamoDBInputS3OutputHive', 'DynamoDBInputS3OutputHiveField', 'DynamoDBInputS3OutputHiveField1', 'DynamoDBInputS3OutputHiveField2', 'DynamoDBInputS3OutputHiveField3', 'DynamoDBInputS3OutputHiveParameterAttribute', 'DynamoDBInputS3OutputHiveParameterAttribute1', 'DynamoDBInputS3OutputHiveParameterAttribute10', 'DynamoDBInputS3OutputHiveParameterAttribute11', 'DynamoDBInputS3OutputHiveParameterAttribute12', 'DynamoDBInputS3OutputHiveParameterAttribute13', 'DynamoDBInputS3OutputHiveParameterAttribute14', 'DynamoDBInputS3OutputHiveParameterAttribute15', 'DynamoDBInputS3OutputHiveParameterAttribute16', 'DynamoDBInputS3OutputHiveParameterAttribute17', 'DynamoDBInputS3OutputHiveParameterAttribute18', 'DynamoDBInputS3OutputHiveParameterAttribute19', 'DynamoDBInputS3OutputHiveParameterAttribute2', 'DynamoDBInputS3OutputHiveParameterAttribute20', 'DynamoDBInputS3OutputHiveParameterAttribute3', 'DynamoDBInputS3OutputHiveParameterAttribute4', 'DynamoDBInputS3OutputHiveParameterAttribute5', 'DynamoDBInputS3OutputHiveParameterAttribute6', 'DynamoDBInputS3OutputHiveParameterAttribute7', 'DynamoDBInputS3OutputHiveParameterAttribute8', 'DynamoDBInputS3OutputHiveParameterAttribute9', 'DynamoDBInputS3OutputHivePipelineObject', 'DynamoDBInputS3OutputHivePipelineObject1', 'DynamoDBInputS3OutputHivePipelineObject2', 'DynamoDBInputS3OutputHivePipelineObject3', 'DynamoDBInputS3OutputHivePipelineObject4', 'DynamoDBInputS3OutputHivePipelineObject5', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt', 'HOSTED_ZONE_ID', 'INSTANCE_ID', 'If', 'ImportValue', 'Join', 'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID', 'LIST_SUBNET_ID', 'Mapping', 'NUMBER', 'Not', 'Or', 'Output', 'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType', 'Ref', 'RefDict', 'RefList', 'SECURITY_GROUP_ID', 'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING', 'SUBNET_ID', 'Select', 'Split', 'Sub', 'TemplateCondition', 'Transform', 'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq', 'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig', 'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights', 'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest', 'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager', 'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch', 'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor', 'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot', 'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront', 'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit', 'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer', 'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications', 'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns', 'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew', 'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective', 'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb', 'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks', 'elasticache', 'elasticbeanstalk', 'elasticloadbalancing', 'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers', 'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently', 'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift', 'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2', 'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam', 'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor', 'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents', 'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless', 'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis', 'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo', 'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager', 'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2', 'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive', 'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb', 'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall', 'networkmanager', 'notifications', 'notificationscontacts', 'oam', 'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice', 'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography', 'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint', 'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram', 'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces', 'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups', 'robomaker', 'rolesanywhere', 'route53', 'route53profiles', 'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver', 'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts', 's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager', 'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry', 'servicediscovery', 'ses', 'setup_params', 'setup_resources', 'shield', 'signer', 'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect', 'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp', 'synthetics', 'systemsmanagersap', 'timestream', 'transfer', 'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2', 'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances', 'workspacesthinclient', 'workspacesweb', 'xray']
