"""
AWS CLOUDWATCH CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class ActionsSuppressedBy:
    WAITPERIOD = "WaitPeriod"
    EXTENSIONPERIOD = "ExtensionPeriod"
    ALARM = "Alarm"


class AlarmType:
    COMPOSITEALARM = "CompositeAlarm"
    METRICALARM = "MetricAlarm"


class AnomalyDetectorStateValue:
    PENDING_TRAINING = "PENDING_TRAINING"
    TRAINED_INSUFFICIENT_DATA = "TRAINED_INSUFFICIENT_DATA"
    TRAINED = "TRAINED"


class AnomalyDetectorType:
    SINGLE_METRIC = "SINGLE_METRIC"
    METRIC_MATH = "METRIC_MATH"


class ComparisonOperator:
    GREATERTHANOREQUALTOTHRESHOLD = "GreaterThanOrEqualToThreshold"
    GREATERTHANTHRESHOLD = "GreaterThanThreshold"
    LESSTHANTHRESHOLD = "LessThanThreshold"
    LESSTHANOREQUALTOTHRESHOLD = "LessThanOrEqualToThreshold"
    LESSTHANLOWERORGREATERTHANUPPERTHRESHOLD = (
        "LessThanLowerOrGreaterThanUpperThreshold"
    )
    LESSTHANLOWERTHRESHOLD = "LessThanLowerThreshold"
    GREATERTHANUPPERTHRESHOLD = "GreaterThanUpperThreshold"


class EvaluationState:
    PARTIAL_DATA = "PARTIAL_DATA"


class HistoryItemType:
    CONFIGURATIONUPDATE = "ConfigurationUpdate"
    STATEUPDATE = "StateUpdate"
    ACTION = "Action"
    ALARMCONTRIBUTORSTATEUPDATE = "AlarmContributorStateUpdate"
    ALARMCONTRIBUTORACTION = "AlarmContributorAction"


class MetricStreamOutputFormat:
    JSON = "json"
    OPENTELEMETRY0_7 = "opentelemetry0.7"
    OPENTELEMETRY1_0 = "opentelemetry1.0"


class RecentlyActive:
    PT3H = "PT3H"


class ScanBy:
    TIMESTAMPDESCENDING = "TimestampDescending"
    TIMESTAMPASCENDING = "TimestampAscending"


class StandardUnit:
    SECONDS = "Seconds"
    MICROSECONDS = "Microseconds"
    MILLISECONDS = "Milliseconds"
    BYTES = "Bytes"
    KILOBYTES = "Kilobytes"
    MEGABYTES = "Megabytes"
    GIGABYTES = "Gigabytes"
    TERABYTES = "Terabytes"
    BITS = "Bits"
    KILOBITS = "Kilobits"
    MEGABITS = "Megabits"
    GIGABITS = "Gigabits"
    TERABITS = "Terabits"
    PERCENT = "Percent"
    COUNT = "Count"
    BYTESSECOND = "Bytes/Second"
    KILOBYTESSECOND = "Kilobytes/Second"
    MEGABYTESSECOND = "Megabytes/Second"
    GIGABYTESSECOND = "Gigabytes/Second"
    TERABYTESSECOND = "Terabytes/Second"
    BITSSECOND = "Bits/Second"
    KILOBITSSECOND = "Kilobits/Second"
    MEGABITSSECOND = "Megabits/Second"
    GIGABITSSECOND = "Gigabits/Second"
    TERABITSSECOND = "Terabits/Second"
    COUNTSECOND = "Count/Second"
    NONE = "None"


class StateValue:
    OK = "OK"
    ALARM = "ALARM"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class Statistic:
    SAMPLECOUNT = "SampleCount"
    AVERAGE = "Average"
    SUM = "Sum"
    MINIMUM = "Minimum"
    MAXIMUM = "Maximum"


class StatusCode:
    COMPLETE = "Complete"
    INTERNALERROR = "InternalError"
    PARTIALDATA = "PartialData"
    FORBIDDEN = "Forbidden"


# PropertyType submodules
from . import Alarm as _Alarm
from . import AnomalyDetector as _AnomalyDetector
from . import InsightRule as _InsightRule
from . import MetricStream as _MetricStream


# Resources
# ============================================================


@dataclass
class Alarm(CloudFormationResource):
    """Alarm resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html

    CloudFormation type: AWS::CloudWatch::Alarm
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::Alarm"
    _property_mappings: ClassVar[dict[str, str]] = {
        "ok_actions": "OKActions",
    }

    comparison_operator: DslValue[str] | None = None
    evaluation_periods: DslValue[int] | None = None
    actions_enabled: DslValue[bool] | None = None
    alarm_actions: list[DslValue[str]] = field(default_factory=list)
    alarm_description: DslValue[str] | None = None
    alarm_name: DslValue[str] | None = None
    datapoints_to_alarm: DslValue[int] | None = None
    dimensions: list[DslValue[_Alarm.Dimension]] = field(default_factory=list)
    evaluate_low_sample_count_percentile: DslValue[str] | None = None
    extended_statistic: DslValue[str] | None = None
    insufficient_data_actions: list[DslValue[str]] = field(default_factory=list)
    metric_name: DslValue[str] | None = None
    metrics: list[DslValue[_Alarm.MetricDataQuery]] = field(default_factory=list)
    namespace: DslValue[str] | None = None
    ok_actions: list[DslValue[str]] = field(default_factory=list)
    period: DslValue[int] | None = None
    statistic: DslValue[str] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)
    threshold: DslValue[float] | None = None
    threshold_metric_id: DslValue[str] | None = None
    treat_missing_data: DslValue[str] | None = None
    unit: DslValue[str] | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"

    # PropertyType descriptors for nested GetAtt support
    Dimension = PropertyTypeDescriptor(_Alarm.Dimension, "Dimension")
    Metric = PropertyTypeDescriptor(_Alarm.Metric, "Metric")
    MetricDataQuery = PropertyTypeDescriptor(_Alarm.MetricDataQuery, "MetricDataQuery")
    MetricStat = PropertyTypeDescriptor(_Alarm.MetricStat, "MetricStat")


@dataclass
class AnomalyDetector(CloudFormationResource):
    """AnomalyDetector resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html

    CloudFormation type: AWS::CloudWatch::AnomalyDetector
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::AnomalyDetector"

    configuration: DslValue[_AnomalyDetector.Configuration] | None = None
    dimensions: list[DslValue[_AnomalyDetector.Dimension]] = field(default_factory=list)
    metric_characteristics: DslValue[_AnomalyDetector.MetricCharacteristics] | None = (
        None
    )
    metric_math_anomaly_detector: (
        DslValue[_AnomalyDetector.MetricMathAnomalyDetector] | None
    ) = None
    metric_name: DslValue[str] | None = None
    namespace: DslValue[str] | None = None
    single_metric_anomaly_detector: (
        DslValue[_AnomalyDetector.SingleMetricAnomalyDetector] | None
    ) = None
    stat: DslValue[str] | None = None

    # PropertyType descriptors for nested GetAtt support
    Configuration = PropertyTypeDescriptor(
        _AnomalyDetector.Configuration, "Configuration"
    )
    Dimension = PropertyTypeDescriptor(_AnomalyDetector.Dimension, "Dimension")
    Metric = PropertyTypeDescriptor(_AnomalyDetector.Metric, "Metric")
    MetricCharacteristics = PropertyTypeDescriptor(
        _AnomalyDetector.MetricCharacteristics, "MetricCharacteristics"
    )
    MetricDataQueries = PropertyTypeDescriptor(
        _AnomalyDetector.MetricDataQueries, "MetricDataQueries"
    )
    MetricDataQuery = PropertyTypeDescriptor(
        _AnomalyDetector.MetricDataQuery, "MetricDataQuery"
    )
    MetricMathAnomalyDetector = PropertyTypeDescriptor(
        _AnomalyDetector.MetricMathAnomalyDetector, "MetricMathAnomalyDetector"
    )
    MetricStat = PropertyTypeDescriptor(_AnomalyDetector.MetricStat, "MetricStat")
    Range = PropertyTypeDescriptor(_AnomalyDetector.Range, "Range")
    SingleMetricAnomalyDetector = PropertyTypeDescriptor(
        _AnomalyDetector.SingleMetricAnomalyDetector, "SingleMetricAnomalyDetector"
    )


@dataclass
class CompositeAlarm(CloudFormationResource):
    """CompositeAlarm resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-compositealarm.html

    CloudFormation type: AWS::CloudWatch::CompositeAlarm
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::CompositeAlarm"
    _property_mappings: ClassVar[dict[str, str]] = {
        "ok_actions": "OKActions",
    }

    alarm_rule: DslValue[str] | None = None
    actions_enabled: DslValue[bool] | None = None
    actions_suppressor: DslValue[str] | None = None
    actions_suppressor_extension_period: DslValue[int] | None = None
    actions_suppressor_wait_period: DslValue[int] | None = None
    alarm_actions: list[DslValue[str]] = field(default_factory=list)
    alarm_description: DslValue[str] | None = None
    alarm_name: DslValue[str] | None = None
    insufficient_data_actions: list[DslValue[str]] = field(default_factory=list)
    ok_actions: list[DslValue[str]] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


@dataclass
class Dashboard(CloudFormationResource):
    """Dashboard resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html

    CloudFormation type: AWS::CloudWatch::Dashboard
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::Dashboard"

    dashboard_body: DslValue[str] | None = None
    dashboard_name: DslValue[str] | None = None


@dataclass
class InsightRule(CloudFormationResource):
    """InsightRule resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-insightrule.html

    CloudFormation type: AWS::CloudWatch::InsightRule
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::InsightRule"

    rule_body: DslValue[str] | None = None
    rule_name: DslValue[str] | None = None
    rule_state: DslValue[str] | None = None
    apply_on_transformed_logs: DslValue[bool] | None = None
    tags: DslValue[_InsightRule.Tags] | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"
    RULENAME: ClassVar[str] = "RuleName"

    # PropertyType descriptors for nested GetAtt support
    Tags = PropertyTypeDescriptor(_InsightRule.Tags, "Tags")


@dataclass
class MetricStream(CloudFormationResource):
    """MetricStream resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html

    CloudFormation type: AWS::CloudWatch::MetricStream
    """

    _resource_type: ClassVar[str] = "AWS::CloudWatch::MetricStream"

    firehose_arn: DslValue[str] | None = None
    output_format: DslValue[str] | None = None
    role_arn: DslValue[str] | None = None
    exclude_filters: list[DslValue[_MetricStream.MetricStreamFilter]] = field(
        default_factory=list
    )
    include_filters: list[DslValue[_MetricStream.MetricStreamFilter]] = field(
        default_factory=list
    )
    include_linked_accounts_metrics: DslValue[bool] | None = None
    name: DslValue[str] | None = None
    statistics_configurations: list[
        DslValue[_MetricStream.MetricStreamStatisticsConfiguration]
    ] = field(default_factory=list)
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    CREATIONDATE: ClassVar[str] = "CreationDate"
    STATE: ClassVar[str] = "State"
    ARN: ClassVar[str] = "Arn"
    LASTUPDATEDATE: ClassVar[str] = "LastUpdateDate"

    # PropertyType descriptors for nested GetAtt support
    MetricStreamFilter = PropertyTypeDescriptor(
        _MetricStream.MetricStreamFilter, "MetricStreamFilter"
    )
    MetricStreamStatisticsConfiguration = PropertyTypeDescriptor(
        _MetricStream.MetricStreamStatisticsConfiguration,
        "MetricStreamStatisticsConfiguration",
    )
    MetricStreamStatisticsMetric = PropertyTypeDescriptor(
        _MetricStream.MetricStreamStatisticsMetric, "MetricStreamStatisticsMetric"
    )
