"""
AWS KINESIS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:21Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# Constants
# ============================================================


class ConsumerStatus:
    CREATING = "CREATING"
    DELETING = "DELETING"
    ACTIVE = "ACTIVE"


class EncryptionType:
    NONE = "NONE"
    KMS = "KMS"


class MetricsName:
    INCOMINGBYTES = "IncomingBytes"
    INCOMINGRECORDS = "IncomingRecords"
    OUTGOINGBYTES = "OutgoingBytes"
    OUTGOINGRECORDS = "OutgoingRecords"
    WRITEPROVISIONEDTHROUGHPUTEXCEEDED = "WriteProvisionedThroughputExceeded"
    READPROVISIONEDTHROUGHPUTEXCEEDED = "ReadProvisionedThroughputExceeded"
    ITERATORAGEMILLISECONDS = "IteratorAgeMilliseconds"
    ALL = "ALL"


class MinimumThroughputBillingCommitmentInputStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class MinimumThroughputBillingCommitmentOutputStatus:
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    ENABLED_UNTIL_EARLIEST_ALLOWED_END = "ENABLED_UNTIL_EARLIEST_ALLOWED_END"


class ScalingType:
    UNIFORM_SCALING = "UNIFORM_SCALING"


class ShardFilterType:
    AFTER_SHARD_ID = "AFTER_SHARD_ID"
    AT_TRIM_HORIZON = "AT_TRIM_HORIZON"
    FROM_TRIM_HORIZON = "FROM_TRIM_HORIZON"
    AT_LATEST = "AT_LATEST"
    AT_TIMESTAMP = "AT_TIMESTAMP"
    FROM_TIMESTAMP = "FROM_TIMESTAMP"


class ShardIteratorType:
    AT_SEQUENCE_NUMBER = "AT_SEQUENCE_NUMBER"
    AFTER_SEQUENCE_NUMBER = "AFTER_SEQUENCE_NUMBER"
    TRIM_HORIZON = "TRIM_HORIZON"
    LATEST = "LATEST"
    AT_TIMESTAMP = "AT_TIMESTAMP"


class StreamMode:
    PROVISIONED = "PROVISIONED"
    ON_DEMAND = "ON_DEMAND"


class StreamStatus:
    CREATING = "CREATING"
    DELETING = "DELETING"
    ACTIVE = "ACTIVE"
    UPDATING = "UPDATING"


# PropertyType submodules
from . import Stream as _Stream


# Resources
# ============================================================


@dataclass
class ResourcePolicy(CloudFormationResource):
    """ResourcePolicy resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-resourcepolicy.html

    CloudFormation type: AWS::Kinesis::ResourcePolicy
    """

    _resource_type: ClassVar[str] = "AWS::Kinesis::ResourcePolicy"

    resource_arn: str | None = None
    resource_policy: dict[str, Any] | None = None


@dataclass
class Stream(CloudFormationResource):
    """Stream resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html

    CloudFormation type: AWS::Kinesis::Stream
    """

    _resource_type: ClassVar[str] = "AWS::Kinesis::Stream"

    desired_shard_level_metrics: list[String] = field(default_factory=list)
    max_record_size_in_ki_b: int | None = None
    name: str | None = None
    retention_period_hours: int | None = None
    shard_count: int | None = None
    stream_encryption: _Stream.StreamEncryption | None = None
    stream_mode_details: _Stream.StreamModeDetails | None = None
    tags: list[Tag] = field(default_factory=list)
    warm_throughput_mi_bps: int | None = None

    # GetAtt attributes
    WARMTHROUGHPUTOBJECT_CURRENTMIBPS: ClassVar[str] = (
        "WarmThroughputObject.CurrentMiBps"
    )
    WARMTHROUGHPUTOBJECT_TARGETMIBPS: ClassVar[str] = "WarmThroughputObject.TargetMiBps"
    WARMTHROUGHPUTOBJECT: ClassVar[str] = "WarmThroughputObject"
    ARN: ClassVar[str] = "Arn"


@dataclass
class StreamConsumer(CloudFormationResource):
    """StreamConsumer resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-streamconsumer.html

    CloudFormation type: AWS::Kinesis::StreamConsumer
    """

    _resource_type: ClassVar[str] = "AWS::Kinesis::StreamConsumer"
    _property_mappings: ClassVar[dict[str, str]] = {
        "stream_arn": "StreamARN",
    }

    consumer_name: str | None = None
    stream_arn: str | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    CONSUMERCREATIONTIMESTAMP: ClassVar[str] = "ConsumerCreationTimestamp"
    CONSUMERNAME: ClassVar[str] = "ConsumerName"
    CONSUMERARN: ClassVar[str] = "ConsumerARN"
    CONSUMERSTATUS: ClassVar[str] = "ConsumerStatus"
    STREAMARN: ClassVar[str] = "StreamARN"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Stream.StreamEncryption = _Stream.StreamEncryption
Stream.StreamModeDetails = _Stream.StreamModeDetails
Stream.WarmThroughputObject = _Stream.WarmThroughputObject
