"""
AWS ACMPCA CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:15Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# PropertyType submodules
from . import Certificate as _Certificate
from . import CertificateAuthority as _CertificateAuthority


# Resources
# ============================================================


@dataclass
class Certificate(CloudFormationResource):
    """Certificate resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificate.html

    CloudFormation type: AWS::ACMPCA::Certificate
    """

    _resource_type: ClassVar[str] = "AWS::ACMPCA::Certificate"

    certificate_authority_arn: str | None = None
    certificate_signing_request: str | None = None
    signing_algorithm: str | None = None
    validity: _Certificate.Validity | None = None
    api_passthrough: _Certificate.ApiPassthrough | None = None
    template_arn: str | None = None
    validity_not_before: _Certificate.Validity | None = None

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"
    CERTIFICATE: ClassVar[str] = "Certificate"


@dataclass
class CertificateAuthority(CloudFormationResource):
    """CertificateAuthority resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html

    CloudFormation type: AWS::ACMPCA::CertificateAuthority
    """

    _resource_type: ClassVar[str] = "AWS::ACMPCA::CertificateAuthority"

    key_algorithm: str | None = None
    signing_algorithm: str | None = None
    subject: _CertificateAuthority.Subject | None = None
    type_: str | None = None
    csr_extensions: _CertificateAuthority.CsrExtensions | None = None
    key_storage_security_standard: str | None = None
    revocation_configuration: _CertificateAuthority.RevocationConfiguration | None = (
        None
    )
    tags: list[Tag] = field(default_factory=list)
    usage_mode: str | None = None

    # GetAtt attributes
    CERTIFICATESIGNINGREQUEST: ClassVar[str] = "CertificateSigningRequest"
    ARN: ClassVar[str] = "Arn"


@dataclass
class CertificateAuthorityActivation(CloudFormationResource):
    """CertificateAuthorityActivation resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthorityactivation.html

    CloudFormation type: AWS::ACMPCA::CertificateAuthorityActivation
    """

    _resource_type: ClassVar[str] = "AWS::ACMPCA::CertificateAuthorityActivation"

    certificate: str | None = None
    certificate_authority_arn: str | None = None
    certificate_chain: str | None = None
    status: str | None = None

    # GetAtt attributes
    COMPLETECERTIFICATECHAIN: ClassVar[str] = "CompleteCertificateChain"


@dataclass
class Permission(CloudFormationResource):
    """Permission resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-permission.html

    CloudFormation type: AWS::ACMPCA::Permission
    """

    _resource_type: ClassVar[str] = "AWS::ACMPCA::Permission"

    actions: list[String] = field(default_factory=list)
    certificate_authority_arn: str | None = None
    principal: str | None = None
    source_account: str | None = None


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Certificate.ApiPassthrough = _Certificate.ApiPassthrough
Certificate.CustomAttribute = _Certificate.CustomAttribute
Certificate.CustomExtension = _Certificate.CustomExtension
Certificate.EdiPartyName = _Certificate.EdiPartyName
Certificate.ExtendedKeyUsage = _Certificate.ExtendedKeyUsage
Certificate.Extensions = _Certificate.Extensions
Certificate.GeneralName = _Certificate.GeneralName
Certificate.KeyUsage = _Certificate.KeyUsage
Certificate.OtherName = _Certificate.OtherName
Certificate.PolicyInformation = _Certificate.PolicyInformation
Certificate.PolicyQualifierInfo = _Certificate.PolicyQualifierInfo
Certificate.Qualifier = _Certificate.Qualifier
Certificate.Subject = _Certificate.Subject
Certificate.Validity = _Certificate.Validity
CertificateAuthority.AccessDescription = _CertificateAuthority.AccessDescription
CertificateAuthority.AccessMethod = _CertificateAuthority.AccessMethod
CertificateAuthority.CrlConfiguration = _CertificateAuthority.CrlConfiguration
CertificateAuthority.CrlDistributionPointExtensionConfiguration = (
    _CertificateAuthority.CrlDistributionPointExtensionConfiguration
)
CertificateAuthority.CsrExtensions = _CertificateAuthority.CsrExtensions
CertificateAuthority.CustomAttribute = _CertificateAuthority.CustomAttribute
CertificateAuthority.EdiPartyName = _CertificateAuthority.EdiPartyName
CertificateAuthority.GeneralName = _CertificateAuthority.GeneralName
CertificateAuthority.KeyUsage = _CertificateAuthority.KeyUsage
CertificateAuthority.OcspConfiguration = _CertificateAuthority.OcspConfiguration
CertificateAuthority.OtherName = _CertificateAuthority.OtherName
CertificateAuthority.RevocationConfiguration = (
    _CertificateAuthority.RevocationConfiguration
)
CertificateAuthority.Subject = _CertificateAuthority.Subject
