"""
AWS CONNECTCAMPAIGNS CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-05T22:51:20Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)


# Constants
# ============================================================


class CampaignState:
    INITIALIZED = "Initialized"
    RUNNING = "Running"
    PAUSED = "Paused"
    STOPPED = "Stopped"
    FAILED = "Failed"


class EncryptionType:
    KMS = "KMS"


class FailureCode:
    INVALIDINPUT = "InvalidInput"
    REQUESTTHROTTLED = "RequestThrottled"
    UNKNOWNERROR = "UnknownError"


class GetCampaignStateBatchFailureCode:
    RESOURCENOTFOUND = "ResourceNotFound"
    UNKNOWNERROR = "UnknownError"


class InstanceIdFilterOperator:
    EQ = "Eq"


class InstanceOnboardingJobFailureCode:
    EVENT_BRIDGE_ACCESS_DENIED = "EVENT_BRIDGE_ACCESS_DENIED"
    EVENT_BRIDGE_MANAGED_RULE_LIMIT_EXCEEDED = (
        "EVENT_BRIDGE_MANAGED_RULE_LIMIT_EXCEEDED"
    )
    IAM_ACCESS_DENIED = "IAM_ACCESS_DENIED"
    KMS_ACCESS_DENIED = "KMS_ACCESS_DENIED"
    KMS_KEY_NOT_FOUND = "KMS_KEY_NOT_FOUND"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"


class InstanceOnboardingJobStatusCode:
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


# PropertyType submodules
from . import Campaign as _Campaign


# Resources
# ============================================================


@dataclass
class Campaign(CloudFormationResource):
    """Campaign resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-connectcampaigns-campaign.html

    CloudFormation type: AWS::ConnectCampaigns::Campaign
    """

    _resource_type: ClassVar[str] = "AWS::ConnectCampaigns::Campaign"

    connect_instance_arn: str | None = None
    dialer_config: _Campaign.DialerConfig | None = None
    name: str | None = None
    outbound_call_config: _Campaign.OutboundCallConfig | None = None
    tags: list[Tag] = field(default_factory=list)

    # GetAtt attributes
    ARN: ClassVar[str] = "Arn"


# Attach PropertyTypes to resource classes via descriptors for nested GetAtt support
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
# Using PropertyTypeDescriptor enables MyDB.Endpoint.Address syntax
Campaign.AgentlessDialerConfig = PropertyTypeDescriptor(
    _Campaign.AgentlessDialerConfig, "AgentlessDialerConfig"
)
Campaign.AnswerMachineDetectionConfig = PropertyTypeDescriptor(
    _Campaign.AnswerMachineDetectionConfig, "AnswerMachineDetectionConfig"
)
Campaign.DialerConfig = PropertyTypeDescriptor(_Campaign.DialerConfig, "DialerConfig")
Campaign.OutboundCallConfig = PropertyTypeDescriptor(
    _Campaign.OutboundCallConfig, "OutboundCallConfig"
)
Campaign.PredictiveDialerConfig = PropertyTypeDescriptor(
    _Campaign.PredictiveDialerConfig, "PredictiveDialerConfig"
)
Campaign.ProgressiveDialerConfig = PropertyTypeDescriptor(
    _Campaign.ProgressiveDialerConfig, "ProgressiveDialerConfig"
)
