"""
AWS HEALTHLAKE CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2026.01.02
  Generator: 1.0.0
  Date: 2026-01-07T05:29:22Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import (
    CloudFormationResource,
    PropertyType,
    PropertyTypeDescriptor,
    Tag,
)
from wetwire_aws.typing import DslValue


# Constants
# ============================================================


class AuthorizationStrategy:
    SMART_ON_FHIR_V1 = "SMART_ON_FHIR_V1"
    SMART_ON_FHIR = "SMART_ON_FHIR"
    AWS_AUTH = "AWS_AUTH"


class CmkType:
    CUSTOMER_MANAGED_KMS_KEY = "CUSTOMER_MANAGED_KMS_KEY"
    AWS_OWNED_KMS_KEY = "AWS_OWNED_KMS_KEY"


class DatastoreStatus:
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    DELETED = "DELETED"
    CREATE_FAILED = "CREATE_FAILED"


class ErrorCategory:
    RETRYABLE_ERROR = "RETRYABLE_ERROR"
    NON_RETRYABLE_ERROR = "NON_RETRYABLE_ERROR"


class FHIRVersion:
    R4 = "R4"


class JobStatus:
    SUBMITTED = "SUBMITTED"
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCEL_SUBMITTED = "CANCEL_SUBMITTED"
    CANCEL_IN_PROGRESS = "CANCEL_IN_PROGRESS"
    CANCEL_COMPLETED = "CANCEL_COMPLETED"
    CANCEL_FAILED = "CANCEL_FAILED"


class PreloadDataType:
    SYNTHEA = "SYNTHEA"


class ValidationLevel:
    STRICT = "strict"
    STRUCTURE_ONLY = "structure-only"
    MINIMAL = "minimal"


# PropertyType submodules
from . import FHIRDatastore as _FHIRDatastore


# Resources
# ============================================================


@dataclass
class FHIRDatastore(CloudFormationResource):
    """FHIRDatastore resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-healthlake-fhirdatastore.html

    CloudFormation type: AWS::HealthLake::FHIRDatastore
    """

    _resource_type: ClassVar[str] = "AWS::HealthLake::FHIRDatastore"

    datastore_type_version: DslValue[str] | None = None
    datastore_name: DslValue[str] | None = None
    identity_provider_configuration: (
        DslValue[_FHIRDatastore.IdentityProviderConfiguration] | None
    ) = None
    preload_data_config: DslValue[_FHIRDatastore.PreloadDataConfig] | None = None
    sse_configuration: DslValue[_FHIRDatastore.SseConfiguration] | None = None
    tags: list[DslValue[Tag]] = field(default_factory=list)

    # GetAtt attributes
    DATASTOREARN: ClassVar[str] = "DatastoreArn"
    CREATEDAT_NANOS: ClassVar[str] = "CreatedAt.Nanos"
    DATASTOREID: ClassVar[str] = "DatastoreId"
    CREATEDAT: ClassVar[str] = "CreatedAt"
    DATASTORESTATUS: ClassVar[str] = "DatastoreStatus"
    DATASTOREENDPOINT: ClassVar[str] = "DatastoreEndpoint"
    CREATEDAT_SECONDS: ClassVar[str] = "CreatedAt.Seconds"

    # PropertyType descriptors for nested GetAtt support
    CreatedAt = PropertyTypeDescriptor(_FHIRDatastore.CreatedAt, "CreatedAt")
    IdentityProviderConfiguration = PropertyTypeDescriptor(
        _FHIRDatastore.IdentityProviderConfiguration, "IdentityProviderConfiguration"
    )
    KmsEncryptionConfig = PropertyTypeDescriptor(
        _FHIRDatastore.KmsEncryptionConfig, "KmsEncryptionConfig"
    )
    PreloadDataConfig = PropertyTypeDescriptor(
        _FHIRDatastore.PreloadDataConfig, "PreloadDataConfig"
    )
    SseConfiguration = PropertyTypeDescriptor(
        _FHIRDatastore.SseConfiguration, "SseConfiguration"
    )
