"""
AWS PCACONNECTORSCEP CloudFormation resources.

Generated:
  Source: CloudFormation Spec 2025.12.18
  Generator: 1.0.0
  Date: 2026-01-01T08:07:23Z

DO NOT EDIT - This file is generated by wetwire-aws codegen.
To regenerate: python -m wetwire_aws.codegen.generate
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from wetwire_aws.base import CloudFormationResource, PropertyType, Tag


# PropertyType submodules
from . import Connector as _Connector


# Resources
# ============================================================


@dataclass
class Challenge(CloudFormationResource):
    """Challenge resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorscep-challenge.html

    CloudFormation type: AWS::PCAConnectorSCEP::Challenge
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorSCEP::Challenge"

    connector_arn: str | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    CHALLENGEARN: ClassVar[str] = "ChallengeArn"


@dataclass
class Connector(CloudFormationResource):
    """Connector resource.

    http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaconnectorscep-connector.html

    CloudFormation type: AWS::PCAConnectorSCEP::Connector
    """

    _resource_type: ClassVar[str] = "AWS::PCAConnectorSCEP::Connector"

    certificate_authority_arn: str | None = None
    mobile_device_management: _Connector.MobileDeviceManagement | None = None
    tags: dict[str, String] = field(default_factory=dict)

    # GetAtt attributes
    CONNECTORARN: ClassVar[str] = "ConnectorArn"
    OPENIDCONFIGURATION_AUDIENCE: ClassVar[str] = "OpenIdConfiguration.Audience"
    TYPE: ClassVar[str] = "Type"
    OPENIDCONFIGURATION_ISSUER: ClassVar[str] = "OpenIdConfiguration.Issuer"
    ENDPOINT: ClassVar[str] = "Endpoint"
    OPENIDCONFIGURATION: ClassVar[str] = "OpenIdConfiguration"
    OPENIDCONFIGURATION_SUBJECT: ClassVar[str] = "OpenIdConfiguration.Subject"


# Attach PropertyTypes to resource classes for convenient access
# e.g., s3.Bucket.BucketEncryption instead of s3._Bucket.BucketEncryption
Connector.IntuneConfiguration = _Connector.IntuneConfiguration
Connector.MobileDeviceManagement = _Connector.MobileDeviceManagement
Connector.OpenIdConfiguration = _Connector.OpenIdConfiguration
